import { PRODUCT_IMAGE_FALLBACK } from "@/lib/media/product-image";

const CATEGORY_ICON_PATHS: Record<string, string> = {
  vehicles: "/icons/categories/vehicles.svg",
  property: "/icons/categories/property.svg",
  electronics: "/icons/categories/electronics.svg",
  fashion: "/icons/categories/womens-fashion.svg",
  "home-garden": "/icons/categories/home-garden.svg",
  diy: "/icons/categories/diy.svg",
  tools: "/icons/categories/tools.svg",
  sports: "/icons/categories/sports.svg",
  health: "/icons/categories/health.svg",
  beauty: "/icons/categories/beauty.svg",
  pets: "/icons/categories/pets.svg",
  "baby-kids": "/icons/categories/kids-fashion.svg",
  toys: "/icons/categories/kids-fashion.svg",
  books: "/icons/categories/electronics.svg",
  music: "/icons/categories/electronics.svg",
  movies: "/icons/categories/electronics.svg",
  gaming: "/icons/categories/gaming.svg",
  collectibles: "/icons/categories/jewellery.svg",
  business: "/icons/categories/services.svg",
  jobs: "/icons/categories/services.svg",
  services: "/icons/categories/services.svg",
  tickets: "/icons/categories/services.svg",
  food: "/icons/categories/home-garden.svg",
  office: "/icons/categories/computers.svg",
  industrial: "/icons/categories/tools.svg",
  agriculture: "/icons/categories/home-garden.svg",
  travel: "/icons/categories/services.svg",
  events: "/icons/categories/services.svg",
  "free-stuff": "/icons/categories/home-garden.svg",
  "everything-else": "/icons/categories/electronics.svg",
  phones: "/icons/categories/phones.svg",
  computers: "/icons/categories/computers.svg",
  autoparts: "/icons/categories/autoparts.svg",
  jewellery: "/icons/categories/jewellery.svg",
  shoes: "/icons/categories/shoes.svg",
};

export function getCategoryImageUrl(slug: string): string {
  return CATEGORY_ICON_PATHS[slug] ?? PRODUCT_IMAGE_FALLBACK;
}

export function getCategoryIcon(slug: string): string {
  const icons: Record<string, string> = {
    vehicles: "🚗",
    property: "🏠",
    electronics: "📱",
    fashion: "👗",
    "home-garden": "🌿",
    diy: "🔨",
    tools: "🛠️",
    sports: "⚽",
    health: "💊",
    beauty: "💄",
    pets: "🐾",
    "baby-kids": "👶",
    toys: "🧸",
    books: "📚",
    music: "🎵",
    movies: "🎬",
    gaming: "🎮",
    collectibles: "🏆",
    business: "💼",
    jobs: "💼",
    services: "🤝",
    tickets: "🎫",
    food: "🍽️",
    office: "🖇️",
    industrial: "🏭",
    agriculture: "🌾",
    travel: "✈️",
    events: "🎉",
    "free-stuff": "🎁",
    "everything-else": "📦",
  };
  return icons[slug] ?? "🏷️";
}
