/**
 * Canonical marketplace country of origin database — SSOT for listing attributes.
 */

export const MARKETPLACE_COUNTRIES_OF_ORIGIN = [
  "United Kingdom",
  "England",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "Ireland",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Portugal",
  "Netherlands",
  "Belgium",
  "Sweden",
  "Denmark",
  "Norway",
  "Finland",
  "Poland",
  "Czech Republic",
  "Austria",
  "Switzerland",
  "Turkey",
  "China",
  "Japan",
  "South Korea",
  "Taiwan",
  "India",
  "Vietnam",
  "Thailand",
  "Indonesia",
  "Malaysia",
  "Philippines",
  "United States",
  "Canada",
  "Mexico",
  "Brazil",
  "Australia",
  "New Zealand",
  "South Africa",
  "Morocco",
  "Egypt",
  "Israel",
  "UAE",
  "Unknown",
] as const;

export const MARKETPLACE_COUNTRIES_BY_VERTICAL = {
  default: MARKETPLACE_COUNTRIES_OF_ORIGIN,
} as const;
