/**
 * Canonical marketplace feature database — SSOT for category-scoped listing attributes.
 */

export const PILLOW_FEATURES = [
  "Cooling",
  "Hypoallergenic",
  "Adjustable",
  "Anti-Allergy",
  "Anti-Snore",
  "Orthopaedic",
  "Breathable",
  "Washable Cover",
  "Removable Cover",
  "Temperature Regulating",
  "Dust Mite Resistant",
  "Cervical Support",
  "Side Sleeper",
  "Back Sleeper",
  "Stomach Sleeper",
  "Pressure Relief",
  "Gel Infused",
  "Shredded Fill",
  "Contoured",
  "Travel Compact",
  "Inflatable",
  "Foldable",
  "Hotel Quality",
  "Vegan",
  "Organic",
  "Eco-Friendly",
  "Noise Reducing",
  "Waterproof",
  "Aromatherapy",
  "Weighted",
] as const;

export const BEDDING_FEATURES = [
  ...PILLOW_FEATURES,
  "Anti-Bacterial",
  "Moisture Wicking",
  "Tog Rated",
  "All Season",
  "Winter Weight",
  "Summer Weight",
  "Zippered",
  "Deep Fitted",
  "Easy Care",
  "Wrinkle Resistant",
  "Fade Resistant",
  "Pillow Protector Compatible",
] as const;

export const ELECTRONICS_FEATURES = [
  "5G",
  "Wi-Fi 6",
  "Bluetooth",
  "NFC",
  "Water Resistant",
  "Dust Resistant",
  "Fast Charging",
  "Wireless Charging",
  "Face ID",
  "Fingerprint",
  "Dual SIM",
  "eSIM",
  "OLED Display",
  "HDR",
  "120Hz",
  "Noise Cancelling",
  "Spatial Audio",
  "USB-C",
  "Thunderbolt",
  "Backlit Keyboard",
  "Touchscreen",
  "Stylus Support",
  "Expandable Storage",
  "Smart Home Compatible",
] as const;

export const FASHION_FEATURES = [
  "Waterproof",
  "Windproof",
  "Breathable",
  "Stretch",
  "Lined",
  "Hooded",
  "Pockets",
  "Zip Closure",
  "Button Closure",
  "Machine Washable",
  "Dry Clean Only",
  "UV Protection",
  "Reflective",
  "Insulated",
  "Packable",
] as const;

export const VEHICLE_FEATURES = [
  "Air Conditioning",
  "Climate Control",
  "Cruise Control",
  "Parking Sensors",
  "Reversing Camera",
  "Sat Nav",
  "Bluetooth",
  "Apple CarPlay",
  "Android Auto",
  "Leather Seats",
  "Heated Seats",
  "Sunroof",
  "Panoramic Roof",
  "Alloy Wheels",
  "Tow Bar",
  "Keyless Entry",
  "Start/Stop",
  "Lane Assist",
  "Adaptive Cruise",
  "Electric Windows",
] as const;

export const MARKETPLACE_FEATURES_BY_SCOPE = {
  default: [] as readonly string[],
  pillows: PILLOW_FEATURES,
  bedding: BEDDING_FEATURES,
  electronics: ELECTRONICS_FEATURES,
  fashion: FASHION_FEATURES,
  vehicles: VEHICLE_FEATURES,
} as const;
