/**
 * ROVEXO v1.0 — PRODUCT PAGE / VIEW ITEM OWNER FREEZE CERTIFICATE
 *
 * STATUS: PRODUCTION UI LOCK ACTIVE
 * CANONICAL VERSION: view-item-v2.0-final
 * Route: /listing/[slug]
 * UI: features/product-detail/ProductDetailPage.tsx
 * Freeze: lib/product-detail/view-item-ui-ux-freeze-v1.ts
 *
 * Absolute: Less is more. Premium > complexity. If it looks premium, do not touch it.
 * Delivery on View Item: REMOVED (Checkout / Order Tracking only).
 * Post-freeze: bug · security · a11y · performance · browser only.
 * NO COMMIT / PUSH / DEPLOY until Owner unfreeze approval.
 */

export const PRODUCT_PAGE_CANONICAL_FREEZE_V1 = {
  version: "cod-sange-v3.1",
  status: "PRODUCTION_UI_LOCK_ACTIVE",
  freezeStatus: "FROZEN",
  viewItemVersion: "2.0",
  canonicalVersion: "view-item-v2.0-final",
  ownerCertified: true,
  ownerVerified: true,
  freezeLocked: true,
  productionReady: true,
  viewItemUiUxFreeze: "lib/product-detail/view-item-ui-ux-freeze-v1.ts",
  viewItemFinalUiLock: "lib/product-detail/view-item-final-ui-lock-v1.ts",
  officialLocal: "http://localhost:3000/listing/[slug]",
  extension: "lib/product-detail/view-item-bundle-multi-stock-v1.ts",
  implementationPass: [
    "DELETE Add To Cart",
    "DELETE Platform Fee text",
    "Report Seller only in buyer ••• menu (Canonical Edit Listing Engine)",
    "DELETE Shipping calculated at checkout",
    "DELETE Delivery section from View Item",
    "DELETE Old Header",
    "Overlay chrome ← / ♥ / •••",
    "Views right-aligned with price",
    "£incl. green under price",
    "Stock line below seller (green dot)",
    "Seller Card before Description",
    "Quantity only when stock > 1",
    "Dynamic Product Information field map",
    "Document scroll clears sticky actions",
    "Make Offer solid green · Buy Now solid purple",
  ] as const,
  deliveryRemovedFromViewItem: true,
  lockedLayoutOrder: [
    "Gallery",
    "Header / Favourite / Share",
    "Title",
    "Price",
    "Stock Status",
    "Total incl.",
    "View Counter",
    "Seller Card",
    "Description",
    "Product Information (populated only)",
    "Quantity (stock > 1)",
    "Buy Now",
    "Make Offer",
  ] as const,
  locked: [
    "Image Gallery",
    "Header",
    "Favourite",
    "Share",
    "Price Section",
    "Stock Status",
    "Seller Card",
    "Description",
    "Product Information Table",
    "Quantity Selector",
    "Buy Now",
    "Make Offer",
    "Bottom Action Bar",
    "Full Page Scroll",
  ] as const,
  actions: {
    buyNow: true,
    makeOffer: true,
    addToBundle: true,
    addToCart: false,
  } as const,
  removedForever: [
    "Add to Cart",
    "Platform Fee text on product page",
    "Report Seller on page body / seller card",
    "Shipping calculated at checkout",
    "Delivery on View Item",
    "White header title bar",
    "Header product title",
    "Duplicated Stock in specification table",
    "Similar Items on View Item body",
  ] as const,
  forbiddenPostFreeze: [
    "redesign",
    "ui-redesign",
    "ux-redesign",
    "experiments",
    "add-to-cart",
    "delivery-on-view-item",
    "move-sections",
    "change-spacing",
    "change-buttons",
    "change-typography",
    "change-colours",
    "unnecessary text",
    "colour redesign",
  ] as const,
  changeControl: {
    commit: "FORBIDDEN_UNTIL_OWNER_UNFREEZE",
    push: "FORBIDDEN_UNTIL_OWNER_UNFREEZE",
    deploy: "FORBIDDEN_UNTIL_OWNER_UNFREEZE",
  } as const,
  productionGatesBeforeCommit: [
    "TypeScript",
    "ESLint",
    "Build",
    "Related tests",
    "Responsive QA",
    "Mobile QA",
    "Desktop QA",
    "Regression Testing",
    "Owner Approval",
    "Owner Unfreeze Approval",
  ] as const,
  ssot: {
    freeze: "lib/product-detail/product-page-canonical-freeze-v1.ts",
    viewItemUiUxFreeze: "lib/product-detail/view-item-ui-ux-freeze-v1.ts",
    viewItemUiLock: "lib/product-detail/view-item-final-ui-lock-v1.ts",
    fieldMap: "lib/product-detail/product-information-field-map-v1.ts",
    page: "features/product-detail/ProductDetailPage.tsx",
    chrome: "features/product-detail/ProductPageChrome.tsx",
    viewItemBundle: "lib/product-detail/view-item-bundle-multi-stock-v1.ts",
    actionBar: "lib/transaction-hub/product-action-bar.ts",
  } as const,
} as const;
