export const LAUNCH_READINESS_ROUTES = [
  { id: "dashboard", label: "Launch Board", href: "/super-admin/launch-readiness" },
  { id: "infrastructure", label: "Infrastructure", href: "/super-admin/launch-readiness/infrastructure" },
  { id: "email", label: "Email", href: "/super-admin/launch-readiness/email" },
  { id: "cron", label: "Cron Jobs", href: "/super-admin/launch-readiness/cron" },
  { id: "queue", label: "Queue", href: "/super-admin/launch-readiness/queue" },
  { id: "pwa", label: "PWA", href: "/super-admin/launch-readiness/pwa" },
  { id: "push", label: "Push", href: "/super-admin/launch-readiness/push" },
  { id: "health", label: "Health", href: "/super-admin/launch-readiness/health" },
  { id: "performance", label: "Performance", href: "/super-admin/launch-readiness/performance" },
  { id: "security", label: "Security", href: "/super-admin/launch-readiness/security" },
  { id: "deployment", label: "Deployment", href: "/super-admin/launch-readiness/deployment" },
  { id: "marketplace", label: "Marketplace", href: "/super-admin/launch-readiness/marketplace" },
  { id: "launch-gate", label: "Launch Gate", href: "/super-admin/launch-readiness/launch-gate" },
  { id: "reports", label: "Reports", href: "/super-admin/launch-readiness/reports" },
] as const;

export const EXECUTION_TRIGGERS = [
  "pre-release",
  "release-candidate",
  "production-build",
  "deployment",
  "full-scan",
  "enterprise-qa",
  "enterprise-certification",
  "launch-validation",
  "scheduled",
] as const;

export const EMAIL_CHECKS = [
  "smtp",
  "transactional-emails",
  "email-queue",
  "email-templates",
  "password-reset",
  "email-verification",
  "order-emails",
  "shipping-emails",
  "marketplace-notifications",
  "support-emails",
  "bounce-detection",
  "retry-queue",
  "delivery-status",
  "rate-limits",
  "spf",
  "dkim",
  "dmarc",
  "mailbox-health",
] as const;

export const CRON_CHECKS = [
  "scheduler",
  "cron-jobs",
  "recurring-jobs",
  "queue-workers",
  "retry-queue",
  "cleanup-jobs",
  "email-jobs",
  "search-index-jobs",
  "analytics-jobs",
  "notification-jobs",
  "backup-jobs",
  "health-jobs",
  "certification-jobs",
  "deployment-jobs",
  "failed-jobs",
  "stuck-jobs",
  "long-running-jobs",
  "missing-jobs",
  "duplicate-jobs",
] as const;

export const QUEUE_CHECKS = [
  "redis-queue",
  "background-workers",
  "priority-queue",
  "retry-queue",
  "delayed-queue",
  "dead-letter-queue",
  "worker-health",
  "queue-latency",
  "queue-throughput",
] as const;

export const PWA_CHECKS = [
  "manifest",
  "service-worker",
  "offline-mode",
  "install-prompt",
  "app-icons",
  "splash-screen",
  "background-sync",
  "update-strategy",
  "offline-cache",
  "version-upgrade",
  "app-shortcuts",
  "display-mode",
  "standalone-mode",
] as const;

export const PUSH_CHECKS = [
  "firebase-cloud-messaging",
  "apple-push-notifications",
  "web-push",
  "device-registration",
  "device-removal",
  "token-refresh",
  "badge-count",
  "silent-push",
  "notification-queue",
  "retry-logic",
  "delivery-success",
  "delivery-failure",
] as const;

export const HEALTH_CHECKS = [
  "frontend",
  "backend",
  "api",
  "database",
  "redis",
  "storage",
  "authentication",
  "authorization",
  "search",
  "ai-services",
  "payments",
  "orders",
  "wallet",
  "shipping",
  "messaging",
  "notifications",
  "webhooks",
  "cron",
  "workers",
] as const;

export const PERFORMANCE_CHECKS = [
  "core-web-vitals",
  "largest-contentful-paint",
  "interaction-to-next-paint",
  "cumulative-layout-shift",
  "bundle-size",
  "tree-shaking",
  "lazy-loading",
  "image-optimisation",
  "render-time",
  "cpu-usage",
  "memory-usage",
  "api-latency",
  "database-latency",
] as const;

export const CACHING_CHECKS = [
  "browser-cache",
  "server-cache",
  "redis-cache",
  "api-cache",
  "image-cache",
  "cdn-cache",
  "search-cache",
  "cache-invalidation",
  "cache-warm-up",
  "cache-expiration",
] as const;

export const DATABASE_CHECKS = [
  "missing-indexes",
  "duplicate-indexes",
  "unused-indexes",
  "foreign-keys",
  "constraints",
  "slow-queries",
  "full-table-scans",
  "migration-integrity",
  "referential-integrity",
  "connection-pool",
] as const;

export const SEARCH_INDEX_CHECKS = [
  "search-index",
  "missing-indexes",
  "reindex-queue",
  "search-accuracy",
  "search-latency",
  "category-index",
  "listing-index",
  "marketplace-index",
] as const;

export const SEO_CHECKS = [
  "meta-titles",
  "meta-descriptions",
  "canonical-urls",
  "robots",
  "xml-sitemap",
  "structured-data",
  "schema-org",
  "open-graph",
  "twitter-cards",
  "internal-links",
  "broken-links",
  "redirect-chains",
  "duplicate-metadata",
  "indexability",
] as const;

export const SECURITY_CHECKS = [
  "authentication",
  "authorization",
  "rbac",
  "mfa-readiness",
  "rate-limiting",
  "cors",
  "csp",
  "csrf",
  "xss",
  "sql-injection-protection",
  "secrets",
  "environment-variables",
  "cookie-security",
  "session-security",
  "encryption",
] as const;

export const STORAGE_CHECKS = [
  "image-storage",
  "file-storage",
  "orphan-files",
  "duplicate-files",
  "storage-usage",
  "compression",
  "backup-integrity",
  "restore-capability",
] as const;

export const DEPLOYMENT_CHECKS = [
  "environment-variables",
  "production-config",
  "feature-flags",
  "release-notes",
  "rollback-strategy",
  "database-migrations",
  "asset-versioning",
  "cdn",
  "production-build",
] as const;

export const MONITORING_CHECKS = [
  "application-logs",
  "audit-logs",
  "error-logs",
  "performance-metrics",
  "tracing",
  "alerts",
  "incident-detection",
  "health-reports",
] as const;

export const OMEGA_GLOBAL_SCANS = [
  "architecture-scan",
  "infrastructure-scan",
  "email-scan",
  "cron-scan",
  "queue-scan",
  "pwa-scan",
  "push-scan",
  "health-scan",
  "performance-scan",
  "caching-scan",
  "database-scan",
  "search-scan",
  "seo-scan",
  "security-scan",
  "storage-scan",
  "deployment-scan",
  "marketplace-scan",
  "buyer-scan",
  "seller-scan",
  "company-scan",
  "super-admin-scan",
  "homepage-scan",
  "category-scan",
  "search-validation",
  "listing-validation",
  "end-to-end-validation",
] as const;

export const LAUNCH_READINESS_SCORES = [
  "infrastructure",
  "performance",
  "security",
  "seo",
  "database",
  "email",
  "cron",
  "queue",
  "pwa",
  "push",
  "marketplace",
  "homepage",
  "category",
  "search",
  "listing",
  "buyer",
  "seller",
  "company",
  "enterprise",
] as const;

export const LAUNCH_PRODUCTION_GATES = [
  "typecheck",
  "unit-tests",
  "integration-tests",
  "enterprise-tests",
  "infrastructure-validation",
  "email-validation",
  "cron-validation",
  "queue-validation",
  "pwa-validation",
  "push-validation",
  "performance-validation",
  "caching-validation",
  "database-validation",
  "search-validation",
  "seo-validation",
  "security-validation",
  "accessibility-validation",
  "qa-validation",
  "governance-validation",
  "e2e-validation",
  "enterprise-certification",
] as const;

export const LAUNCH_BLOCKERS = [
  "critical-infrastructure-failures",
  "critical-security-findings",
  "critical-performance-regressions",
  "failed-cron-jobs",
  "failed-queue-workers",
  "email-failures",
  "push-failures",
  "missing-indexes",
  "database-integrity-issues",
  "broken-search-indexes",
  "broken-homepage",
  "broken-categories",
  "broken-search",
  "broken-listing-workflow",
  "critical-accessibility-failures",
  "critical-seo-failures",
  "critical-business-workflow-failures",
] as const;

export const REPORT_TYPES = ["launch-readiness", "infrastructure", "operations", "marketplace", "security", "performance", "certification"] as const;
export const EXPORT_FORMATS = ["pdf", "excel", "csv", "json"] as const;

export const LAUNCH_READINESS_API = {
  snapshot: "/api/super-admin/launch-readiness",
  action: "/api/super-admin/launch-readiness/action",
  validate: "/api/super-admin/launch-readiness/validate",
  repair: "/api/super-admin/launch-readiness/repair",
  certify: "/api/super-admin/launch-readiness/certify",
  export: "/api/super-admin/launch-readiness/export",
  v1Snapshot: "/api/v1/super-admin/launch-readiness",
} as const;

export const SOURCE_FILES = {
  emailService: "lib/email/service.ts",
  emailConstants: "lib/email/constants.ts",
  pwaProvider: "components/pwa/PwaProvider.tsx",
  serviceWorker: "public/sw.js",
  pushClient: "lib/push/client-subscribe.ts",
  rateLimit: "lib/api/rate-limit.ts",
  middleware: "middleware.ts",
  authMiddleware: "lib/supabase/middleware.ts",
  healthRoute: "app/api/health/route.ts",
  searchRoute: "app/api/search/route.ts",
  sitemap: "app/sitemap.ts",
  robots: "app/robots.ts",
  homePage: "app/page.tsx",
  categoriesPage: "app/categories/page.tsx",
  cronMaintenance: "app/api/cron/maintenance/route.ts",
  nextConfig: "next.config.ts",
  layout: "app/layout.tsx",
} as const;
