/**
 * ROVEXO PWA — GLOBAL PLATFORM EMOJI ICON SYSTEM
 * ONE map for Account · Home · Sell · Search · Inbox · Orders · Shipping ·
 * Wallet · Store · Settings · Business · Analytics.
 * Ordinary functional icons = emoji text. Brand/photos remain images.
 */

export const PLATFORM_EMOJI_SYSTEM = "GLOBAL_PLATFORM_ICON_SYSTEM" as const;
export const PLATFORM_EMOJI_VERSION = "1.0" as const;

/** Canonical emoji glyphs — semantic keys only. */
export const PLATFORM_EMOJI = {
  home: "🏠",
  dashboard: "🏠",
  search: "🔎",
  browse: "🗂️",
  filter: "🔍",
  add: "➕",
  plus: "➕",
  sell: "📤",
  inbox: "💬",
  messages: "💬",
  chat: "💬",
  notifications: "🔔",
  bell: "🔔",
  account: "👤",
  profile: "👤",
  user: "👤",
  favourites: "❤️",
  saved: "❤️",
  heart: "❤️",
  heartEmpty: "🤍",
  heartOutline: "♡",
  orders: "🛍️",
  businessOrders: "🧳",
  bag: "🛍️",
  listings: "📦",
  inventory: "📦",
  product: "📦",
  shipping: "🚚",
  truck: "🚚",
  tracking: "🚚",
  address: "📍",
  location: "📍",
  wallet: "💳",
  payment: "💳",
  creditCard: "💳",
  balance: "💰",
  pound: "💷",
  gbp: "💷",
  analytics: "📊",
  reviews: "⭐",
  star: "⭐",
  businessReviews: "❤️",
  store: "🏪",
  stores: "🏪",
  settings: "⚙️",
  manage: "⚙️",
  help: "❓",
  privacy: "🔒",
  lock: "🔒",
  security: "🔐",
  legal: "📜",
  document: "📄",
  refresh: "🔄",
  switch: "🔄",
  processing: "🔄",
  edit: "✏️",
  compose: "✏️",
  delete: "🗑️",
  confirm: "✓",
  check: "✓",
  verified: "✓",
  doubleCheck: "✓✓",
  remove: "❌",
  close: "❌",
  back: "⬅️",
  continue: "➡️",
  chevron: "›",
  dropdown: "🔽",
  expand: "🔼",
  sort: "↕️",
  date: "📅",
  camera: "📷",
  image: "🖼️",
  gallery: "🖼️",
  attachment: "📎",
  share: "↗️",
  link: "🔗",
  copy: "📋",
  qr: "🔳",
  warning: "⚠️",
  info: "ℹ️",
  support: "🛟",
  headset: "🛟",
  resolution: "🛟",
  offer: "🎁",
  tag: "🏷️",
  price: "🏷️",
  categories: "🗂️",
  cart: "🛒",
  checkout: "🛒",
  send: "➤",
  more: "⋯",
  menu: "☰",
  eye: "👁️",
  clock: "⏳",
  pending: "⏳",
  recent: "🕒",
  paid: "✅",
  outOfStock: "📭",
  lowStock: "⚠️",
  vat: "🧾",
  directory: "🏢",
  business: "💼",
  ideas: "💡",
  promotions: "📣",
  megaphone: "📣",
  holiday: "🌴",
  theme: "🌙",
  moon: "🌙",
  logout: "🚪",
  following: "👥",
  people: "👥",
  import: "📥",
  returns: "↩️",
  refunds: "💷",
  disputes: "⚖️",
  language: "🌐",
  globe: "🌐",
  accessibility: "♿",
  verification: "🛡️",
  trust: "🛡️",
  shield: "🛡️",
  mail: "✉️",
  phone: "📞",
  bank: "🏦",
  ban: "🚫",
  available: "📦",
  totalInventory: "📦",
  unitsSold: "🧳",
  passwordShow: "👁️",
  passwordHide: "🙈",
} as const;

export type PlatformEmojiKey = keyof typeof PLATFORM_EMOJI;

export const ACCOUNT_ICON_EMOJI = {
  profile: PLATFORM_EMOJI.profile,
  orders: PLATFORM_EMOJI.orders,
  saved: PLATFORM_EMOJI.saved,
  listings: PLATFORM_EMOJI.listings,
  messages: PLATFORM_EMOJI.messages,
  wallet: PLATFORM_EMOJI.wallet,
  business: PLATFORM_EMOJI.business,
  settings: PLATFORM_EMOJI.settings,
  help: PLATFORM_EMOJI.help,
  reviews: PLATFORM_EMOJI.reviews,
  import: PLATFORM_EMOJI.import,
  shipping: PLATFORM_EMOJI.shipping,
  returns: PLATFORM_EMOJI.returns,
  notifications: PLATFORM_EMOJI.notifications,
  security: PLATFORM_EMOJI.security,
  following: PLATFORM_EMOJI.following,
  payment: PLATFORM_EMOJI.payment,
  support: PLATFORM_EMOJI.support,
  cart: PLATFORM_EMOJI.cart,
  verification: PLATFORM_EMOJI.verification,
  ideas: PLATFORM_EMOJI.ideas,
  promotions: PLATFORM_EMOJI.promotions,
  search: PLATFORM_EMOJI.search,
  sell: PLATFORM_EMOJI.sell,
  categories: PLATFORM_EMOJI.categories,
  product: PLATFORM_EMOJI.product,
  checkout: PLATFORM_EMOJI.checkout,
  tracking: PLATFORM_EMOJI.tracking,
  disputes: PLATFORM_EMOJI.disputes,
  refunds: PLATFORM_EMOJI.refunds,
  directory: PLATFORM_EMOJI.directory,
  stores: PLATFORM_EMOJI.stores,
  legal: PLATFORM_EMOJI.legal,
  trust: PLATFORM_EMOJI.trust,
  analytics: PLATFORM_EMOJI.analytics,
  inventory: PLATFORM_EMOJI.inventory,
  vat: PLATFORM_EMOJI.vat,
  recent: PLATFORM_EMOJI.recent,
  address: PLATFORM_EMOJI.address,
  language: PLATFORM_EMOJI.language,
  accessibility: PLATFORM_EMOJI.accessibility,
  inbox: PLATFORM_EMOJI.inbox,
} as const;

export type AccountIconName = keyof typeof ACCOUNT_ICON_EMOJI;

export const PROFILE_ICON_EMOJI = {
  favourites: PLATFORM_EMOJI.favourites,
  settings: PLATFORM_EMOJI.settings,
  ideas: PLATFORM_EMOJI.ideas,
  legal: PLATFORM_EMOJI.legal,
  help: PLATFORM_EMOJI.help,
  promote: PLATFORM_EMOJI.promotions,
  "holiday-mode": PLATFORM_EMOJI.holiday,
  balance: PLATFORM_EMOJI.balance,
  "my-orders": PLATFORM_EMOJI.orders,
  logout: PLATFORM_EMOJI.logout,
  theme: PLATFORM_EMOJI.theme,
} as const;

export const LINE_ICON_EMOJI = {
  SearchLineIcon: PLATFORM_EMOJI.search,
  BrowseCategoriesLineIcon: PLATFORM_EMOJI.browse,
  BellLineIcon: PLATFORM_EMOJI.bell,
  CartLineIcon: PLATFORM_EMOJI.cart,
  ComposeLineIcon: PLATFORM_EMOJI.compose,
  CameraLineIcon: PLATFORM_EMOJI.camera,
  BackLineIcon: PLATFORM_EMOJI.back,
  MoreLineIcon: PLATFORM_EMOJI.more,
  GalleryLineIcon: PLATFORM_EMOJI.gallery,
  SendLineIcon: PLATFORM_EMOJI.send,
  ChevronRightLineIcon: PLATFORM_EMOJI.chevron,
  DoubleCheckLineIcon: PLATFORM_EMOJI.doubleCheck,
  CheckLineIcon: PLATFORM_EMOJI.check,
  HeartLineIcon: PLATFORM_EMOJI.heart,
  ChatLineIcon: PLATFORM_EMOJI.chat,
  BagLineIcon: PLATFORM_EMOJI.bag,
  TruckLineIcon: PLATFORM_EMOJI.truck,
  StarLineIcon: PLATFORM_EMOJI.star,
  TagLineIcon: PLATFORM_EMOJI.tag,
  PeopleLineIcon: PLATFORM_EMOJI.people,
  CreditCardLineIcon: PLATFORM_EMOJI.creditCard,
  ShieldLineIcon: PLATFORM_EMOJI.shield,
  MegaphoneLineIcon: PLATFORM_EMOJI.megaphone,
  InfoLineIcon: PLATFORM_EMOJI.info,
  UserLineIcon: PLATFORM_EMOJI.user,
  WalletLineIcon: PLATFORM_EMOJI.wallet,
  SettingsLineIcon: PLATFORM_EMOJI.settings,
  LogoutLineIcon: PLATFORM_EMOJI.logout,
  MailLineIcon: PLATFORM_EMOJI.mail,
  LockLineIcon: PLATFORM_EMOJI.lock,
  PhoneLineIcon: PLATFORM_EMOJI.phone,
  EditLineIcon: PLATFORM_EMOJI.edit,
  BankLineIcon: PLATFORM_EMOJI.bank,
  GlobeLineIcon: PLATFORM_EMOJI.globe,
  PoundLineIcon: PLATFORM_EMOJI.pound,
  MoonLineIcon: PLATFORM_EMOJI.moon,
  DocumentLineIcon: PLATFORM_EMOJI.document,
  HeadsetLineIcon: PLATFORM_EMOJI.headset,
  EyeLineIcon: PLATFORM_EMOJI.eye,
  LocationLineIcon: PLATFORM_EMOJI.location,
  BanLineIcon: PLATFORM_EMOJI.ban,
  ShareNodesLineIcon: PLATFORM_EMOJI.share,
} as const;

const NAME_EMOJI: Record<string, string> = {
  home: PLATFORM_EMOJI.home,
  search: PLATFORM_EMOJI.search,
  sell: PLATFORM_EMOJI.sell,
  saved: PLATFORM_EMOJI.saved,
  account: PLATFORM_EMOJI.account,
  heart: PLATFORM_EMOJI.heart,
  wishlist: PLATFORM_EMOJI.saved,
  messages: PLATFORM_EMOJI.messages,
  bell: PLATFORM_EMOJI.bell,
  user: PLATFORM_EMOJI.user,
  eye: PLATFORM_EMOJI.eye,
  star: PLATFORM_EMOJI.star,
  "arrow-right": PLATFORM_EMOJI.continue,
  plus: PLATFORM_EMOJI.plus,
  verified: PLATFORM_EMOJI.verified,
  "badge-check": PLATFORM_EMOJI.verified,
  settings: PLATFORM_EMOJI.settings,
  shield: PLATFORM_EMOJI.shield,
  logout: PLATFORM_EMOJI.logout,
  orders: PLATFORM_EMOJI.orders,
  cart: PLATFORM_EMOJI.cart,
  payment: PLATFORM_EMOJI.payment,
  shipping: PLATFORM_EMOJI.shipping,
  business: PLATFORM_EMOJI.business,
  listings: PLATFORM_EMOJI.listings,
  wallet: PLATFORM_EMOJI.wallet,
  analytics: PLATFORM_EMOJI.analytics,
  trust: PLATFORM_EMOJI.trust,
  help: PLATFORM_EMOJI.help,
  support: PLATFORM_EMOJI.support,
  inventory: PLATFORM_EMOJI.inventory,
  wholesale: PLATFORM_EMOJI.inventory,
  plans: PLATFORM_EMOJI.document,
  addresses: PLATFORM_EMOJI.address,
  auctions: PLATFORM_EMOJI.tag,
  resolution: PLATFORM_EMOJI.resolution,
  categories: PLATFORM_EMOJI.categories,
  tax: PLATFORM_EMOJI.vat,
  admin: PLATFORM_EMOJI.settings,
  notifications: PLATFORM_EMOJI.notifications,
  "buy-hub": PLATFORM_EMOJI.bag,
  "sell-hub": PLATFORM_EMOJI.sell,
  "business-hub": PLATFORM_EMOJI.business,
  "support-hub": PLATFORM_EMOJI.support,
};

export function platformEmoji(key: string): string {
  if (key in PLATFORM_EMOJI) return PLATFORM_EMOJI[key as PlatformEmojiKey];
  if (key in ACCOUNT_ICON_EMOJI) return ACCOUNT_ICON_EMOJI[key as AccountIconName];
  if (key in NAME_EMOJI) return NAME_EMOJI[key];
  return PLATFORM_EMOJI.info;
}

export function accountIconEmoji(name: AccountIconName): string {
  return ACCOUNT_ICON_EMOJI[name];
}

/** Semantic category glyphs (functional tiles, not photographic heroes). */
export const CATEGORY_TYPE_EMOJI: Record<string, string> = {
  vehicles: "🛞",
  property: "🏠",
  phones: "📱",
  computers: "💻",
  electronics: "💻",
  gaming: "🎮",
  fashion: "👗",
  furniture: "🪑",
  "home-garden": "🏡",
  garden: "🏡",
  sports: "⚽",
  pets: "🐾",
  jobs: "💼",
  services: "🔧",
  autoparts: "🛞",
  wholesale: "📦",
  auctions: "🏷️",
  beauty: "💄",
  health: "❤️",
  baby: "🧸",
  jewellery: "💎",
  diy: "🛠️",
  tools: "🛠️",
  kids: "🧸",
  "kids-fashion": "🧸",
  "womens-fashion": "👗",
  "mens-fashion": "👔",
  shoes: "👟",
  cycling: "🚲",
  business: "💼",
  luxury: "💎",
  collectibles: "🪙",
  handmade: "🧵",
  books: "📚",
  more: "⋯",
  designer: "💎",
};

export function categoryTypeEmoji(type: string): string {
  return CATEGORY_TYPE_EMOJI[type] ?? PLATFORM_EMOJI.categories;
}

export function rovexoIconRefEmoji(folder: string, name: string): string {
  if (folder === "categories") return categoryTypeEmoji(name);
  return platformEmoji(name);
}
