/**
 * ROVEXO Catalog Master — UK Brand pools (content SSOT for product-type Brand DBs).
 * COD SÂNGE Brand Database Expansion — data only. Filtering / UI / architecture unchanged.
 * Sell freeze: pools feed dedicated path DBs. No Brand + Other applied at order layer.
 */

export const BRAND_OTHER = "Other" as const;

/** Women's clothing / fashion (UK high-street + premium). */
export const UK_WOMENS_CLOTHING_BRANDS = [
  "Zara",
  "H&M",
  "Next",
  "River Island",
  "Mango",
  "New Look",
  "Boohoo",
  "ASOS",
  "Missguided",
  "Karen Millen",
  "Phase Eight",
  "PrettyLittleThing",
  "Topshop",
  "Oasis",
  "Warehouse",
  "Reiss",
  "Whistles",
  "Hobbs",
  "Coast",
  "Monsoon",
  "Ted Baker",
  "French Connection",
  "Superdry",
  "Uniqlo",
  "Primark",
  "Matalan",
  "Marks & Spencer",
  "Gap",
  "Levi's",
  "Calvin Klein",
  "Tommy Hilfiger",
  "Ralph Lauren",
  "& Other Stories",
  "Cos",
  "Arket",
  "Massimo Dutti",
  "Stradivarius",
  "Pull&Bear",
  "Bershka",
  "Forever 21",
  "Dorothy Perkins",
  "Wallis",
  "Evans",
  "Simply Be",
  "Quiet",
  "Nobody's Child",
  "Never Fully Dressed",
  "Ghost",
  "LK Bennett",
  "Jigsaw",
  "Anthropologie",
  "Free People",
  "AllSaints",
  "Whistles Petite",
  "Me+Em",
  "Sézane",
  "Reformation",
  "Ganni",
  "Sandro",
  "Maje",
  "Ba&sh",
  "Rouje",
  "Boden",
  "FatFace",
  "White Stuff",
  "Seasalt Cornwall",
  "Toast",
  "People Tree",
  "Thought",
  "Finery London",
  "Kitri",
  "Rixo",
  "Self-Portrait",
  "Ted Baker London",
  "Joseph",
  "Theory",
  "Max Mara",
  "Diane von Furstenberg",
] as const;

export const UK_MENS_CLOTHING_BRANDS = [
  "Nike",
  "Adidas",
  "Levi's",
  "Tommy Hilfiger",
  "Superdry",
  "Fred Perry",
  "Puma",
  "Jack & Jones",
  "Next",
  "H&M",
  "Zara",
  "Uniqlo",
  "ASOS",
  "River Island",
  "Primark",
  "Matalan",
  "Marks & Spencer",
  "Gap",
  "Calvin Klein",
  "Ralph Lauren",
  "Hugo Boss",
  "Ted Baker",
  "Reiss",
  "Cos",
  "Arket",
  "Massimo Dutti",
  "Pull&Bear",
  "Bershka",
  "The North Face",
  "Under Armour",
  "Reebok",
  "Lacoste",
  "Hollister",
  "Abercrombie & Fitch",
  "AllSaints",
  "FatFace",
  "Joules",
  "Crew Clothing",
  "Charles Tyrwhitt",
  "TM Lewin",
  "Hawes & Curtis",
  "Ben Sherman",
  "Lyle & Scott",
  "Pretty Green",
  "Farah",
  "Gant",
  "Scotch & Soda",
  "Selected Homme",
  "Hackett",
  "Paul Smith",
  "Aquascutum",
  "Barbour",
  "Belstaff",
  "Stone Island",
  "CP Company",
  "Napapijri",
  "Columbia",
  "Patagonia",
  "Carhartt WIP",
  "Dickies",
  "Wrangler",
  "Lee",
  "Dockers",
  "Boss Orange",
  "Armani Exchange",
  "Emporio Armani",
  "Diesel",
  "Guess",
  "Edwin",
  "Nudie Jeans",
  "Weekend Offender",
  "Merc London",
  "Oxford Shirt Company",
  "Hawes and Curtis",
] as const;

export const UK_SHOE_BRANDS = [
  "Nike",
  "Adidas",
  "New Balance",
  "Dr. Martens",
  "Converse",
  "Clarks",
  "Vans",
  "Timberland",
  "Skechers",
  "Puma",
  "Jordan",
  "UGG",
  "Birkenstock",
  "Crocs",
  "ASICS",
  "Salomon",
  "Merrell",
  "Caterpillar",
  "Kickers",
  "Office",
  "Schuh",
  "Kurt Geiger",
  "Aldo",
  "Steve Madden",
  "Hotter",
  "Hush Puppies",
  "Geox",
  "Ecco",
  "Sperry",
  "Toms",
  "Reef",
  "Teva",
  "Hunter",
  "Blundstone",
  "Red Wing",
  "Palladium",
  "Fila",
  "Diadora",
  "On Running",
  "Hoka",
  "Brooks",
  "Saucony",
  "Reebok",
  "Under Armour",
  "Lacoste",
  "Gola",
  "K-Swiss",
  "Saucony Originals",
  "Veja",
  "Common Projects",
  "Axel Arigato",
  "Filling Pieces",
  "Clarks Originals",
  "Loake",
  "Church's",
  "Grenson",
  "Tricker's",
  "Solovair",
  "Kickers Original",
  "Barratts",
  "Jones Bootmaker",
  "Ravel",
  "Carvela",
  "KG Kurt Geiger",
  "FitFlop",
  "Crocs Classic",
  "Keen",
  "Columbia",
  "The North Face",
] as const;

export const UK_WOMENS_SHOE_EXTRA = [
  "Jimmy Choo",
  "Christian Louboutin",
  "Stuart Weitzman",
  "Sam Edelman",
  "Dune",
  "Faith",
  "New Look Shoes",
  "River Island Shoes",
  "Manolo Blahnik",
  "Jimmy Choo London",
  "Charlotte Olympia",
  "Aquazzura",
  "Roger Vivier",
  "Russell & Bromley",
  "LK Bennett Shoes",
  "Phase Eight Shoes",
  "Office London",
  "Schuh Women",
  "PrettyBallerinas",
  "French Sole",
] as const;

export const UK_BAG_BRANDS = [
  "Michael Kors",
  "Kate Spade",
  "Coach",
  "Furla",
  "Radley",
  "Kipling",
  "Samsonite",
  "Eastpak",
  "Herschel",
  "Fjällräven",
  "Longchamp",
  "Tory Burch",
  "Guess",
  "DKNY",
  "Ted Baker",
  "Kurt Geiger",
  "The North Face",
  "Osprey",
  "Antler",
  "Briggs & Riley",
  "Rimowa",
  "Away",
  "Tumi",
  "Delsey",
  "American Tourister",
  "Cabin Max",
  "Travelpro",
  "Victorinox",
  "Horizn Studios",
  "Monos",
  "July",
  "Lipault",
  "Hedgren",
  "Pacsafe",
  "Eagle Creek",
  "Cotopaxi",
  "Patagonia",
  "Deuter",
  "Thule",
  "Ortlieb",
  "Mulberry",
  "Aspinal of London",
  "Smythson",
  "Anya Hindmarch",
  "Cambridge Satchel",
  "Radley London",
  "Fossil",
  "Marc Jacobs",
  "Rebecca Minkoff",
  "Vera Bradley",
] as const;

export const UK_TRAVEL_PILLOW_BRANDS = [
  "Cabeau",
  "BCOZZY",
  "Trtl",
  "Samsonite",
  "Tempur",
  "Go Travel",
  "Travelrest",
  "Ostrichpillow",
  "Travel Blue",
  "Lifeventure",
  "Sea to Summit",
  "Aeris",
  "Dot & Dot",
  "Huzi",
  "J-Pillow",
  "Knirps",
  "Eagle Creek",
  "Pacsafe",
  "Design Go",
  "Cocoon",
  "MLVOC",
  "TripPal",
  "Curl",
  "Pluto Pod",
  "Bucky",
  "Cloudz",
  "Lewis N. Clark",
  "Therm-a-Rest",
  "Exped",
  "Mulisoft",
  "Elviros",
  "Jinxia",
  "Napfun",
  "Everlasting Comfort",
  "Cushion Lab",
  "Nekteck",
  "ComfiLife",
  "Restor",
  "AirComfy",
  "G4Free",
  "Trekology",
  "Veken",
  "Coneke",
  "HomeTop",
  "NEMO",
  "Big Agnes",
  "Quechua",
  "Decathlon",
  "CabinMax",
  "BlitzWolf",
  "Baseus",
  "EPABO",
  "Snuggle-Pedic",
  "Pharmedoc",
  "Purple",
  "REI Co-op",
  "Osprey",
  "Deuter",
] as const;

export const UK_MEMORY_FOAM_PILLOW_BRANDS = [
  "Tempur",
  "Emma",
  "Simba",
  "Silentnight",
  "Dreams",
  "Eve Sleep",
  "Hypnos",
  "Slumberdown",
  "Dunlopillo",
  "Casper",
  "Brooklyn Bedding",
  "Purple",
  "Becket",
  "Mammoth",
  "Orthocare",
  "Putnams",
  "Sleepeezee",
  "Harrison Spinks",
  "Otty",
  "Nectar",
  "Leesa",
  "Brook + Wilde",
  "Puffy",
  "Layla",
  "Nest Bedding",
  "Dormeo",
  "Vispring",
  "Savon",
  "Woolroom",
  "John Lewis",
  "Dunelm",
  "IKEA",
  "Mulisoft",
  "Elviros",
  "Jinxia",
  "Napfun",
  "Panda London",
  "Coop Home Goods",
  "Beckham Hotel Collection",
  "EPABO",
  "Snuggle-Pedic",
  "Eli & Elm",
  "Linenspa",
  "Zinus",
  "Lucid",
  "Milliard",
  "Sleep Innovations",
  "ComfiLife",
  "Cushion Lab",
  "Everlasting Comfort",
  "Pharmedoc",
  "Sealy",
  "Serta",
  "Beautyrest",
  "Stearns & Foster",
  "Tempur-Pedic",
] as const;

export const UK_BEDDING_BRANDS = [
  "Dunelm",
  "John Lewis",
  "IKEA",
  "Habitat",
  "The White Company",
  "Christy",
  "Sheridan",
  "Emma Bridgewater",
  "Joules",
  "Cath Kidston",
  "Silentnight",
  "Slumberdown",
  "Dreams",
  "Tempur",
  "Emma",
  "Simba",
  "Marks & Spencer",
  "Next Home",
  "Made.com",
  "Wayfair",
  "Brook + Wilde",
  "Otty",
  "Nectar",
  "Eve Sleep",
  "Hypnos",
  "Vispring",
  "Savon",
  "Woolroom",
  "Secret Linen Store",
  "Piglet in Bed",
  "Soak&Sleep",
  "Bedeck",
  "Yves Delorme",
  "Frette",
  "Dorma",
  "Panda London",
  "Dormeo",
  "Casper",
  "Purple",
  "Sleepeezee",
  "Harrison Spinks",
  "Dunlopillo",
  "Fogarty",
  "Scooms",
  "And So To Bed",
  "The Fine Cotton Company",
  "Brooklinen",
  "Parachute",
  "Boll & Branch",
  "Coyuchi",
  "Snowe",
  "Buffy",
  "Designers Guild",
  "Sanderson",
  "Liberty",
  "Orla Kiely",
  "Laura Ashley",
  "Catherine Lansfield",
  "Zara Home",
  "H&M Home",
] as const;

export const UK_HOME_BRANDS = [
  "IKEA",
  "Dunelm",
  "John Lewis",
  "Habitat",
  "Muji",
  "Dyson",
  "Philips",
  "Bosch",
  "Black+Decker",
  "Russell Hobbs",
  "Morphy Richards",
  "Kenwood",
  "KitchenAid",
  "Le Creuset",
  "Joseph Joseph",
  "Lakeland",
  "Next Home",
  "Made.com",
  "Wayfair",
  "Argos",
  "B&Q",
  "Screwfix",
  "Wilko",
  "The Range",
  "Laura Ashley",
  "Sophie Allport",
  "Roberts Radio",
  "Smeg",
  "Nespresso",
  "De'Longhi",
  "Dualit",
  "Sage",
  "Breville",
  "Magimix",
  "Tefal",
  "Pyrex",
  "Stellar",
  "Judge",
  "ProCook",
  "Denby",
  "Portmeirion",
  "Wedgwood",
  "Royal Doulton",
  "Villeroy & Boch",
  "Staub",
  "Zwilling",
  "Wüsthof",
  "Global Knives",
  "Alessi",
  "Simplehuman",
  "Brabantia",
  "Addis",
  "OXO",
] as const;

export const UK_FURNITURE_BRANDS = [
  "IKEA",
  "DFS",
  "Sofology",
  "Furniture Village",
  "Dunelm",
  "John Lewis",
  "Habitat",
  "Made.com",
  "Wayfair",
  "Oak Furnitureland",
  "Harveys",
  "Dreams",
  "Silentnight",
  "Emma",
  "Simba",
  "Next Home",
  "La-Z-Boy",
  "Sharps",
  "Hammonds",
  "Wren",
  "Sofa Club",
  "Love Your Home",
  "Loaf",
  "Heal's",
  "The Conran Shop",
  "Nest",
  "Furniture123",
  "Furniture Choice",
  "ScS",
  "Bensons for Beds",
  "Mattressman",
  "Mattress Online",
  "Julian Bowen",
  "Birlea",
  "Core Products",
  "Happy Beds",
  "Sleepy People",
  "Noah Grey",
  "French Connection Home",
  "West Elm",
  "Pottery Barn",
  "Crate & Barrel",
  "Sofas & Stuff",
  "Sofa.com",
  "Swyft",
  "Snug",
  "Made",
  "Swoon",
  "Habitat Loves",
  "Argos Home",
  "B&Q",
  "The Range",
  "Maisons du Monde",
  "La Redoute",
  "Cox & Cox",
  "Graham & Green",
  "Oliver Bonas",
  "Amara",
  "Anthropologie",
  "H&M Home",
  "Zara Home",
  "Muji",
  "BoConcept",
  "Habitat Revive",
  "Ercol",
  "GPlan",
  "Parker Knoll",
  "Duresta",
  "Baker",
  "Natuzzi",
  "Roche Bobois",
  "Ligne Roset",
  "Kartell",
  "Vitra",
  "Herman Miller",
  "Hay",
  "Muuto",
  "String",
  "USM",
  "Cassina",
  "Poliform",
  "B&B Italia",
  "Flexform",
  "Molteni&C",
] as const;

export const UK_TABLET_BRANDS = [
  "Apple",
  "Samsung",
  "Amazon",
  "Microsoft",
  "Lenovo",
  "Huawei",
  "Xiaomi",
  "Google",
  "Honor",
  "OPPO",
  "realme",
  "OnePlus",
  "Nokia",
  "Alcatel",
  "TCL",
  "Asus",
  "Acer",
  "Dell",
  "HP",
  "LG",
  "Sony",
  "Blackview",
  "Doogee",
  "Oukitel",
  "Teclast",
  "Chuwi",
  "ALLDOCUBE",
  "BMAX",
  "Prestigio",
  "Archos",
  "Medion",
  "Fusion5",
  "Dragon Touch",
  "Vankyo",
  "Pritom",
  "Modio",
  "Yuntab",
  "iGet",
  "Kruger&Matz",
  "Overmax",
  "Navitel",
  "Hannspree",
  "Toshiba",
  "Sharp",
  "Panasonic",
  "Wacom",
  "XP-Pen",
  "Huion",
  "Remarkable",
  "BOOX",
  "Supernote",
  "Fujitsu",
  "Vaio",
  "Surface",
] as const;

export const UK_EREADER_BRANDS = [
  "Amazon",
  "Kobo",
  "Remarkable",
  "BOOX",
  "PocketBook",
  "Tolino",
  "Supernote",
  "Kindle",
  "Barnes & Noble",
  "Nook",
  "Sony",
  "Likebook",
  "Meebook",
  "Bigme",
  "iReader",
  "Huawei",
  "Xiaomi",
  "Onyx",
  "Dasung",
  "Boox Palma",
  "Kobo Libra",
  "Kobo Clara",
  "Kobo Sage",
  "Kobo Elipsa",
  "PocketBook InkPad",
  "PocketBook Verse",
  "Energy Sistem",
  "Bookeen",
  "TrekStor",
  "Foxit",
  "reMarkable 2",
  "reMarkable Paper Pro",
  "BOOX Note",
  "BOOX Tab",
  "BOOX Go",
  "Supernote A5 X",
  "Supernote A6 X",
  "viwoods",
  "Daylight Computer",
  "Rabbit",
] as const;

export const UK_PHONE_BRANDS = [
  "Apple",
  "Samsung",
  "Google",
  "Motorola",
  "Nokia",
  "Sony",
  "Honor",
  "Xiaomi",
  "OnePlus",
  "Huawei",
  "OPPO",
  "realme",
  "Nothing",
  "Fairphone",
  "CAT",
  "Doro",
  "TCL",
  "Alcatel",
  "ZTE",
  "Vivo",
  "Asus",
  "Blackview",
  "Ulefone",
  "Doogee",
  "Cubot",
  "Infinix",
  "Tecno",
  "iQOO",
  "Redmi",
  "POCO",
  "Meizu",
  "Sharp",
  "BLU",
  "Wiko",
  "Crosscall",
  "Gigaset",
  "Energizer",
  "Hammer",
  "Unihertz",
  "Oukitel",
  "AGM",
  "Hotwav",
  "IIIFone",
  "Itel",
  "Symphony",
  "Lava",
  "Micromax",
  "HMD",
  "Essential",
  "Palm",
  "Vertu",
  "Light Phone",
  "Punkt",
] as const;

export const UK_LAPTOP_BRANDS = [
  "Apple",
  "Dell",
  "HP",
  "Lenovo",
  "MSI",
  "ASUS",
  "Acer",
  "Samsung",
  "Microsoft",
  "Razer",
  "Alienware",
  "LG",
  "Huawei",
  "Framework",
  "Google",
  "Toshiba",
  "Fujitsu",
  "Gigabyte",
  "Chuwi",
  "Medion",
  "Vaio",
  "System76",
  "Clevo",
  "Origin PC",
  "Eurocom",
  "Dynabook",
  "Packard Bell",
  "Prestigio",
  "Honor",
  "Xiaomi",
  "OnePlus",
  "realme",
  "Avell",
  "Schenker",
  "XMG",
  "Tuxedo",
  "Purism",
  "Star Labs",
  "Pine64",
  "Jumper",
  "Teclast",
  "BMAX",
  "Minisforum",
  "Beelink",
  "GMKtec",
] as const;

export const UK_ELECTRONICS_AUDIO_BRANDS = [
  "Sony",
  "Bose",
  "JBL",
  "Apple",
  "Samsung",
  "Sennheiser",
  "Audio-Technica",
  "Beats",
  "Skullcandy",
  "Anker",
  "Jabra",
  "Bang & Olufsen",
  "Marshall",
  "Sonos",
  "Ultimate Ears",
  "Logitech",
  "Razer",
  "SteelSeries",
  "HyperX",
  "Shure",
  "Audioengine",
  "KEF",
  "Klipsch",
  "Bowers & Wilkins",
  "Devialet",
  "Harman Kardon",
  "JBL Professional",
  "Yamaha",
  "Denon",
  "Pioneer",
  "Onkyo",
  "Cambridge Audio",
  "Naim",
  "Focal",
  "Edifier",
  "Creative",
  "Rode",
  "Blue Microphones",
  "AKG",
  "Beyerdynamic",
  "Neumann",
  "Audeze",
  "Hifiman",
  "Moondrop",
  "Fiio",
  "iFi Audio",
  "Chord Electronics",
  "Astell&Kern",
  "Campfire Audio",
  "Nothing",
  "CMF",
  "OneOdio",
  "Soundcore",
  "EarFun",
  "Tozo",
  "QCY",
  "Haylou",
  "1MORE",
  "Tribit",
  "Polk Audio",
  "Q Acoustics",
  "Monitor Audio",
  "Wharfedale",
  "Mission",
  "DALI",
  "Audio Pro",
  "Bluesound",
  "Marantz",
  "Nakamichi",
  "Sennheiser Professional",
  "Shure Professional",
  "Rode Microphones",
  "Elgato",
  "Fifine",
  "HyperX Cloud",
  "Corsair",
  "SteelSeries Arctis",
  "Epos",
  "Audeze Maxwell",
] as const;

export const UK_CAMERA_BRANDS = [
  "Canon",
  "Nikon",
  "Sony",
  "Fujifilm",
  "Panasonic",
  "Olympus",
  "OM System",
  "GoPro",
  "DJI",
  "Leica",
  "Pentax",
  "Sigma",
  "Tamron",
  "Insta360",
  "Kodak",
  "Polaroid",
  "Ricoh",
  "Hasselblad",
  "Phase One",
  "Blackmagic",
  "RED",
  "Zhiyun",
  "Godox",
  "Profoto",
  "Manfrotto",
  "Gitzo",
  "Peak Design",
  "Lowepro",
  "Think Tank",
  "Samyang",
  "Rokinon",
  "Voigtlander",
  "Zeiss",
  "Tokina",
  "Metz",
  "Nissin",
  "Yongnuo",
  "SmallRig",
  "Tilta",
  "Atomos",
  "Hollyland",
  "DJI Osmo",
  "GoPro Hero",
  "Insta360 X",
  "Canon EOS",
  "Nikon Z",
  "Sony Alpha",
  "Fujifilm X",
  "Leica Q",
  "Panasonic Lumix",
] as const;

export const UK_TV_BRANDS = [
  "Samsung",
  "LG",
  "Sony",
  "Panasonic",
  "TCL",
  "Hisense",
  "Philips",
  "Toshiba",
  "Sharp",
  "Sky",
  "Amazon",
  "Google",
  "Apple",
  "Bang & Olufsen",
  "Loewe",
  "Metz",
  "Grundig",
  "JVC",
  "Hitachi",
  "Xiaomi",
  "OnePlus",
  "Vizio",
  "Roku",
  "Finlux",
  "Celcus",
  "Cello",
  "Vestel",
  "Blaupunkt",
  "Telefunken",
  "Thomson",
  "Strong",
  "Humax",
  "Manhattan",
  "Formuler",
  "NVIDIA",
  "Changhong",
  "Skyworth",
  "Haier",
  "Konka",
  "Westinghouse",
  "Sceptre",
  "Element",
  "Insignia",
  "Anker",
  "Vu+",
  "Dreambox",
  "Engel",
  "Ferguson",
  "Goodmans",
  "Alba",
  "Technika",
  "Luxor",
] as const;

export const UK_SOUNDBAR_AV_BRANDS = [
  "Samsung",
  "LG",
  "Sony",
  "Bose",
  "Sonos",
  "JBL",
  "Yamaha",
  "Denon",
  "Marantz",
  "Pioneer",
  "Onkyo",
  "Harman Kardon",
  "Bang & Olufsen",
  "Bowers & Wilkins",
  "KEF",
  "Klipsch",
  "Polk Audio",
  "Vizio",
  "Hisense",
  "TCL",
  "Philips",
  "Nakamichi",
  "Sennheiser",
  "Audio Pro",
  "Bluesound",
  "Naim",
  "Cambridge Audio",
  "Q Acoustics",
  "Monitor Audio",
  "Wharfedale",
  "Mission",
  "DALI",
  "Focal",
  "Devialet",
  "Roku",
  "Amazon",
  "Google",
  "Apple",
  "Creative",
  "Edifier",
  "Tribit",
  "Anker",
  "Ultimate Ears",
  "Marshall",
  "JBL Professional",
  "Definitive Technology",
  "MartinLogan",
  "SVS",
  "REL",
  "ELAC",
  "Kanto",
  "Fluance",
  "RSL",
  "Emotiva",
  "Anthem",
  "Integra",
] as const;

export const UK_GAMING_BRANDS = [
  "Sony",
  "Microsoft",
  "Nintendo",
  "PlayStation",
  "Xbox",
  "Steam Deck",
  "Razer",
  "Logitech",
  "SteelSeries",
  "HyperX",
  "Corsair",
  "Thrustmaster",
  "Sega",
  "Atari",
  "Valve",
  "ASUS ROG",
  "MSI Gaming",
  "Alienware",
  "Turtle Beach",
  "Astro",
  "Scuf",
  "Nacon",
  "8BitDo",
  "Hori",
  "PowerA",
  "PDP",
  "Elgato",
  "Stream Deck",
  "Cooler Master",
  "NZXT",
] as const;

export const UK_VEHICLE_PART_BRANDS = [
  "Bosch",
  "Febi",
  "Valeo",
  "NGK",
  "Denso",
  "Mann",
  "Mahle",
  "SKF",
  "ATE",
  "Brembo",
  "Castrol",
  "Michelin",
  "Continental",
  "Goodyear",
  "Pirelli",
  "Mann Filter",
  "Halfords",
  "Thule",
  "Bilstein",
  "KYB",
  "Sachs",
  "TRW",
  "Delphi",
  "Gates",
  "Dayco",
  "Textar",
  "Pagid",
  "EBC",
  "Mintex",
  "Ferodo",
  "Lemförder",
  "Meyle",
  "Febi Bilstein",
  "Hella",
  "Osram",
  "Philips Automotive",
  "NGK Spark Plugs",
  "Champion",
  "Fram",
  "Wix",
  "K&N",
  "Pipercross",
  "Eibach",
  "KW Suspensions",
  "AP Racing",
  "Wilwood",
  "StopTech",
  "Zimmermann",
  "Jurid",
  "Pagid Racing",
  "Blue Print",
  "Corteco",
  "Elring",
  "Victor Reinz",
  "Ajusa",
] as const;

export const UK_TYRE_BRANDS = [
  "Michelin",
  "Continental",
  "Goodyear",
  "Pirelli",
  "Bridgestone",
  "Dunlop",
  "Hankook",
  "Yokohama",
  "Falken",
  "Toyo",
  "BFGoodrich",
  "Kumho",
  "Nexen",
  "Avon",
  "Vredestein",
  "Uniroyal",
  "Firestone",
  "Cooper",
  "General Tire",
  "Maxxis",
  "Nankang",
  "Laufenn",
  "GT Radial",
  "Apollo",
  "Sailun",
  "Linglong",
  "Triangle",
  "Wanli",
  "Double Coin",
  "Ceat",
  "MRF",
  "JK Tyre",
  "Giti",
  "Achilles",
  "Federal",
  "Westlake",
  "Goodride",
  "Infinity",
  "Zeetex",
  "Landsail",
  "Rotalla",
  "Kormoran",
  "Barum",
  "Sava",
  "Fulda",
  "Semperit",
  "Kleber",
  "Tigar",
  "Debica",
  "Petlas",
  "Lassa",
  "Marshal",
  "Roadstone",
  "Kelly",
  "Dextero",
] as const;

export const UK_SPORTS_BRANDS = [
  "Nike",
  "Adidas",
  "Puma",
  "Under Armour",
  "Reebok",
  "Decathlon",
  "The North Face",
  "Patagonia",
  "Columbia",
  "Garmin",
  "Salomon",
  "Merrell",
  "Berghaus",
  "Rab",
  "Mammut",
  "Arc'teryx",
  "CamelBak",
  "Osprey",
  "Fitbit",
  "Polar",
  "New Balance",
  "ASICS",
  "Brooks",
  "Hoka",
  "On Running",
  "Saucony",
  "Wilson",
  "Head",
  "Babolat",
  "Yonex",
  "Dunlop Sports",
  "Slazenger",
  "Canterbury",
  "Gilbert",
  "Mitre",
  "Umbro",
  "Castore",
  "Gymshark",
  "Lululemon",
  "Sweaty Betty",
  "Dare 2b",
  "Regatta",
  "Mountain Warehouse",
  "Craghoppers",
  "Sprayway",
  "Montane",
  "Outdoor Research",
  "Black Diamond",
] as const;

export const UK_CAMPING_BRANDS = [
  "Vango",
  "Outwell",
  "Coleman",
  "Quechua",
  "Robens",
  "MSR",
  "Sea to Summit",
  "Therm-a-Rest",
  "Exped",
  "Alpkit",
  "Snugpak",
  "Terra Nova",
  "Hilleberg",
  "Jetboil",
  "Primus",
  "Trangia",
  "Ledlenser",
  "Petzl",
  "Goal Zero",
  "Lifeventure",
  "Easy Camp",
  "Kampa",
  "Dometic",
  "Outdoor Revolution",
  "Berghaus",
  "Regatta",
  "Mountain Warehouse",
  "Nemo",
  "Big Agnes",
  "Kelty",
  "Eureka",
  "Sierra Designs",
  "Black Diamond",
  "Petzl Tikka",
  "BioLite",
  "Goal Zero Yeti",
  "Anker Solix",
] as const;

export const UK_TOY_BRANDS = [
  "LEGO",
  "Hasbro",
  "Mattel",
  "Disney",
  "Nintendo",
  "Playmobil",
  "Hot Wheels",
  "Barbie",
  "Fisher-Price",
  "VTech",
  "Melissa & Doug",
  "Schleich",
  "Sylvanian Families",
  "Nerf",
  "Paw Patrol",
  "Peppa Pig",
  "Thomas & Friends",
  "Ravensburger",
  "Mega Bloks",
  "K'Nex",
  "BRIO",
  "Play-Doh",
  "Crayola",
  "LeapFrog",
  "Tonies",
  "Yoto",
  "Little Tikes",
  "Step2",
  "Chicco",
  "Early Learning Centre",
  "John Lewis Toys",
  "Hamleys",
  "The Entertainer",
] as const;

export const UK_BOOK_BRANDS = [
  "Penguin",
  "HarperCollins",
  "Bloomsbury",
  "Oxford University Press",
  "Cambridge University Press",
  "Vintage",
  "Faber & Faber",
  "Hodder",
  "Pan Macmillan",
  "Scholastic",
  "Usborne",
  "Ladybird",
  "DK",
  "Random House",
  "Simon & Schuster",
  "Hachette",
  "Penguin Classics",
  "Vintage Classics",
  "Picador",
  "Jonathan Cape",
  "Virago",
  "Canongate",
  "Profile Books",
  "Orion",
  "Little, Brown",
  "Michael Joseph",
  "Transworld",
  "Allen Lane",
  "Pelican",
  "Penguin Random House",
  "Vintage Contemporaries",
  "Fourth Estate",
  "William Heinemann",
  "Chatto & Windus",
  "Bodley Head",
  "Hamish Hamilton",
  "Viking",
  "Allen & Unwin",
  "Macmillan",
  "Hodder & Stoughton",
  "Headline",
  "Sceptre",
  "Abacus",
  "Corsair",
  "Quercus",
  "Gollancz",
  "Orbit",
  "Tor",
  "Baen",
  "Angry Robot",
  "Titan Books",
  "SelfMadeHero",
  "Nobrow",
  "Flying Eye",
  "Walker Books",
  "Nosy Crow",
  "Andersen Press",
  "Chicken House",
  "Barrington Stoke",
  "Pushkin Press",
  "Europa Editions",
  "Fitzcarraldo",
  "Galley Beggar",
  "Dead Ink",
  "Rough Trade Books",
] as const;

export const UK_BEAUTY_BRANDS = [
  "The Ordinary",
  "CeraVe",
  "L'Oréal",
  "Maybelline",
  "Clinique",
  "Estée Lauder",
  "MAC",
  "NARS",
  "Charlotte Tilbury",
  "Rare Beauty",
  "Fenty Beauty",
  "e.l.f.",
  "NYX",
  "Rimmel",
  "Max Factor",
  "Benefit",
  "Too Faced",
  "Urban Decay",
  "The Body Shop",
  "Neal's Yard Remedies",
  "Glossier",
  "Rare Beauty by Selena Gomez",
  "Refy",
  "Merit",
  "Tower 28",
  "Saie",
  "Ilia",
  "Kosas",
  "Milk Makeup",
  "Huda Beauty",
  "Pat McGrath Labs",
  "Anastasia Beverly Hills",
  "Morphe",
  "Revolution",
  "Collection",
  "Superdrug Own Brand",
  "Boots No7",
  "Simple",
  "Aveeno",
  "La Roche-Posay",
  "Vichy",
  "Bioderma",
  "Cetaphil",
  "Neutrogena",
  "Olay",
  "Garnier",
  "Nivea",
  "Dove",
  "Pantene",
  "Head & Shoulders",
  "OGX",
] as const;

export const UK_JEWELLERY_BRANDS = [
  "Pandora",
  "Swarovski",
  "Tiffany & Co.",
  "Cartier",
  "Links of London",
  "Thomas Sabo",
  "Monica Vinader",
  "Astrid & Miyu",
  "Daisy London",
  "Alex Monroe",
  "Tatty Devine",
  "Missoma",
  "Olivia Burton",
  "Fossil",
  "Michael Kors",
  "Links of London Classic",
  "Ernest Jones",
  "H.Samuel",
  "Beaverbrooks",
  "Goldsmiths",
  "F.Hinds",
  "Warren James",
  "Argento",
  "Kit Heath",
  "Abbott Lyon",
  "Pura Vida",
  "Mejuri",
  "AUrate",
  "Catbird",
  "Maria Black",
] as const;

export const UK_WATCH_BRANDS = [
  "Rolex",
  "Omega",
  "Casio",
  "Seiko",
  "Citizen",
  "Tag Heuer",
  "Tissot",
  "Swatch",
  "Fossil",
  "Michael Kors",
  "Apple",
  "Samsung",
  "Garmin",
  "Fitbit",
  "Huawei",
  "Breitling",
  "Longines",
  "Hamilton",
  "Cartier",
  "IWC",
  "Jaeger-LeCoultre",
  "Patek Philippe",
  "Audemars Piguet",
  "Tudor",
  "Oris",
  "Certina",
  "Raymond Weil",
  "Frederique Constant",
  "Daniel Wellington",
  "MVMT",
  "Timex",
  "Orient",
  "Bulova",
  "Invicta",
  "Guess Watches",
  "Armani Exchange Watches",
  "Hugo Boss Watches",
  "Withings",
  "Amazfit",
  "Polar",
] as const;

export const UK_KIDS_CLOTHING_BRANDS = [
  "Next",
  "H&M",
  "Zara Kids",
  "Gap Kids",
  "Primark",
  "Matalan",
  "Marks & Spencer",
  "Joules",
  "Boden",
  "Frugi",
  "JoJo Maman Bébé",
  "Mamas & Papas",
  "Carter's",
  "Disney",
  "Nike",
  "Adidas",
  "Puma",
  "The North Face",
  "Regatta",
  "Mountain Warehouse",
  "Mini Boden",
  "Hanna Andersson",
  "Primary",
  "Tea Collection",
  "Cat & Jack",
  "George at Asda",
  "Tu at Sainsbury's",
  "F&F at Tesco",
  "Nutmeg at Morrisons",
  "Name It",
  "Mayoral",
  "Petit Bateau",
  "Jacadi",
  "Bonpoint",
] as const;

export const UK_BABY_BRANDS = [
  "Mamas & Papas",
  "JoJo Maman Bébé",
  "Tommee Tippee",
  "Philips Avent",
  "Nuby",
  "Medela",
  "Chicco",
  "Graco",
  "Maxi-Cosi",
  "Cybex",
  "Bugaboo",
  "Silver Cross",
  "Ickle Bubba",
  "BabyBjörn",
  "Ergobaby",
  "Skip Hop",
  "Stokke",
  "Uppababy",
  "Nuna",
  "Joie",
  "Britax",
  "Cosatto",
  "iCandy",
  "Egg",
  "Out n About",
  "Mothercare",
  "Angelcare",
  "Halo",
  "Aden + Anais",
  "Grobag",
  "The Gro Company",
] as const;

export const UK_DESIGNER_BRANDS = [
  "Gucci",
  "Louis Vuitton",
  "Chanel",
  "Dior",
  "Prada",
  "Hermès",
  "Balenciaga",
  "Saint Laurent",
  "Burberry",
  "Versace",
  "Fendi",
  "Givenchy",
  "Valentino",
  "Bottega Veneta",
  "Celine",
  "Loewe",
  "Alexander McQueen",
  "Stella McCartney",
  "Mulberry",
  "Aspinal of London",
  "Off-White",
  "Balmain",
  "Tom Ford",
  "Dolce & Gabbana",
  "Moschino",
  "Miu Miu",
  "Chloe",
  "Isabel Marant",
  "Acne Studios",
  "Ami Paris",
  "Jacquemus",
  "The Row",
  "Khaite",
  "Toteme",
] as const;

export const UK_COLLECTIBLE_BRANDS = [
  "Funko",
  "Hot Toys",
  "Sideshow",
  "NECA",
  "Bandai",
  "Kotobukiya",
  "McFarlane",
  "Hasbro",
  "Mattel",
  "LEGO",
  "Warhammer",
  "Games Workshop",
  "Pokémon",
  "Magic: The Gathering",
  "Panini",
  "Topps",
  "Upper Deck",
  "Yu-Gi-Oh!",
  "Wizards of the Coast",
  "Sideshow Collectibles",
  "Prime 1 Studio",
  "Iron Studios",
  "Beast Kingdom",
  "Good Smile Company",
  "Banpresto",
  "Pop Mart",
  "Bearbrick",
  "Medicom",
  "Enterbay",
  "ThreeA",
  "ThreeZero",
  "Asmus Toys",
  "Queen Studios",
  "XM Studios",
  "Blizzard",
  "Square Enix",
  "Capcom",
  "Sega",
  "Nintendo",
  "Tamashii Nations",
  "Max Factory",
  "FREEing",
  "Megahouse",
  "Alter",
  "Good Smile",
  "Autoart",
  "Minichamps",
  "Spark Models",
  "Kyosho",
  "Tamiya",
  "Revell",
  "Airfix",
  "Italeri",
  "Hasegawa",
  "Bandai Spirits",
  "Kaiyodo",
  "Revoltech",
] as const;

export const UK_MUSIC_BRANDS = [
  "Sony",
  "Universal",
  "Warner",
  "EMI",
  "Deutsche Grammophon",
  "Naxos",
  "Fender",
  "Gibson",
  "Yamaha",
  "Roland",
  "Casio",
  "Ibanez",
  "Taylor",
  "Martin",
  "PRS",
  "Epiphone",
  "Squier",
  "Gretsch",
  "Jackson",
  "ESP",
  "Schecter",
  "Korg",
  "Nord",
  "Moog",
  "Akai",
  "Native Instruments",
  "Focusrite",
  "Behringer",
  "Shure",
  "Audio-Technica",
  "Sennheiser",
] as const;

export const UK_DIY_TOOL_BRANDS = [
  "Bosch",
  "Makita",
  "DeWalt",
  "Black+Decker",
  "Milwaukee",
  "Ryobi",
  "Hilti",
  "Festool",
  "Stanley",
  "Draper",
  "Sealey",
  "Clarke",
  "Titan",
  "Worx",
  "Metabo",
  "Fein",
  "Hitachi",
  "Hikoki",
  "Einhell",
  "Parkside",
  "Silverline",
  "Bahco",
  "Facom",
  "Snap-on",
  "GearWrench",
  "Irwin",
  "Estwing",
  "Stihl",
  "Husqvarna",
  "Makita Garden",
  "Bosch Garden",
  "Flymo",
  "Qualcast",
] as const;

export const UK_PET_BRANDS = [
  "Pedigree",
  "Whiskas",
  "Royal Canin",
  "Hills",
  "Purina",
  "Iams",
  "Kong",
  "Pets at Home",
  "Animonda",
  "Lily's Kitchen",
  "Applaws",
  "Webbox",
  "Hills Science Plan",
  "Purina Pro Plan",
  "James Wellbeloved",
  "Burns",
  "Harringtons",
  "Wainwrights",
  "Barking Heads",
  "Nature's Menu",
  "Butcher's",
  "Cesar",
  "Felix",
  "Sheba",
  "Dreamies",
  "Greenies",
  "PetSafe",
  "Furminator",
  "Kong Classic",
  "Chuckit",
] as const;

export const UK_PHONE_ACCESSORY_BRANDS = [
  "Apple",
  "Samsung",
  "Anker",
  "Belkin",
  "Spigen",
  "OtterBox",
  "Casetify",
  "Logitech",
  "UGREEN",
  "Baseus",
  "ESR",
  "Nomad",
  "Peak Design",
  "Moshi",
  "Mophie",
  "Native Union",
  "PITAKA",
  "Ringke",
  "Caseology",
  "dbrand",
  "Skinomi",
  "ZAGG",
  "InvisibleShield",
  "PanzerGlass",
  "Tech21",
  "Incipio",
  "Speck",
  "LifeProof",
  "Catalyst",
  "Moment",
  "Rhinoshield",
  "Nillkin",
  "Torras",
  "Supcase",
  "Urban Armor Gear",
  "UAG",
  "Ghostek",
  "Twelve South",
  "Satechi",
  "Hyper",
  "Brydge",
  "PopSockets",
  "Quad Lock",
  "RAM Mounts",
  "iOttie",
  "Scosche",
  "Nite Ize",
  "Moft",
  "Case-Mate",
  "Gear4",
  "Evutec",
  "Mous",
  "Raptic",
  "Pelican",
  "Griffin",
  "X-Doria",
  "Poetic",
  "i-Blason",
  "Aukey",
  "RAVPower",
  "Choetech",
  "Nothing",
  "OnePlus",
  "Xiaomi",
  "Google",
  "Huawei",
  "Honor",
  "OPPO",
  "realme",
  "Nokia",
  "Motorola",
  "Sony",
  "JSAUX",
  "Elago",
  "Uniq",
  "Cyrill",
  "Kajsa",
] as const;
