/**
 * ROVEXO Catalog Master — Leaf Category Brand Overrides (COD SÂNGE V2).
 * Every FINAL selectable product-type owns an independently curated Brand list.
 * Brand may appear in multiple leaves ONLY when it genuinely manufactures for each.
 * No Brand / Other / alphabetical ordering applied by `orderCategoryBrandDatabase`.
 *
 * V2: Global brand discovery enrichment — comprehensive manufacturers per leaf.
 * Brand names only (no product-line placeholders).
 */

/** Travel / neck support pillows — travel specialists + genuine travel-pillow makers. */
export const LEAF_TRAVEL_PILLOW_BRANDS = [
  "Cabeau",
  "BCOZZY",
  "Trtl",
  "Go Travel",
  "Travel Blue",
  "MLVOC",
  "Cocoon",
  "Samsonite",
  "Tempur",
  "Travelrest",
  "Ostrichpillow",
  "Lifeventure",
  "Sea to Summit",
  "Eagle Creek",
  "Pacsafe",
  "Design Go",
  "Huzi",
  "J-Pillow",
  "Dot & Dot",
  "TripPal",
  "Bucky",
  "Cloudz",
  "Lewis N. Clark",
  "Mulisoft",
  "Elviros",
  "Jinxia",
  "Napfun",
  "Everlasting Comfort",
  "Cushion Lab",
  "Aeris",
  "Knirps",
  "Curl",
  "Pluto Pod",
  "Therm-a-Rest",
  "Exped",
  "Nekteck",
  "ComfiLife",
  "Restor",
  "AirComfy",
  "G4Free",
  "Trekology",
  "Veken",
  "Coneke",
  "HomeTop",
  "NEMO",
  "Big Agnes",
  "Quechua",
  "Decathlon",
  "CabinMax",
  "BlitzWolf",
  "Baseus",
  "EPABO",
  "Snuggle-Pedic",
  "Infinity",
  "Moonwalkers",
  "Outad",
  "Lunimous",
  "MemoryFoamStore",
  "Purple",
  "REI Co-op",
  "Osprey",
  "Deuter",
] as const;

/** Maternity / pregnancy body support pillows — maternity specialists only. */
export const LEAF_MATERNITY_PILLOW_BRANDS = [
  "bbhugme",
  "Momcozy",
  "PharMeDoc",
  "Dreamgenii",
  "Queen Rose",
  "Theraline",
  "Doomoo",
  "Boppy",
  "Niimo",
  "BabyMoov",
  "Purflo",
  "Clevamama",
  "Dreamland Baby",
  "Leachco",
  "Frida Mom",
  "Belly Bandit",
  "Ingenuity",
  "Summer Infant",
  "BellaMoon",
  "Mamas & Papas",
  "Simba",
  "Bub's",
  "Newton Baby",
  "Keekaroo",
  "Yogibo",
  "Snuggle Me Organic",
  "Angelcare",
  "Chicco",
  "Tommee Tippee",
  "Medela",
  "Lansinoh",
  "My Brest Friend",
  "Ergobaby",
  "Hiccapop",
  "Meizhi",
  "Red Castle",
  "Joie",
  "Graco",
  "Stokke",
  "Bugaboo",
  "Silver Cross",
  "Ickle Bubba",
  "Hatch",
  "Babymoov",
  "Nurture&",
  "Moonlight",
  "Bumpsuit",
  "Izzie",
  "Angels Nursery",
] as const;

/** Decorative / home-style cushions & pillows. */
export const LEAF_DECORATIVE_PILLOW_BRANDS = [
  "John Lewis",
  "IKEA",
  "Dunelm",
  "Habitat",
  "The White Company",
  "Laura Ashley",
  "Catherine Lansfield",
  "Silentnight",
  "Slumberdown",
  "Next Home",
  "Marks & Spencer",
  "Wayfair",
  "Made.com",
  "Christy",
  "Sheridan",
  "Emma Bridgewater",
  "Joules",
  "Cath Kidston",
  "Sophie Allport",
  "Clarissa Hulse",
  "West Elm",
  "Pottery Barn",
  "Crate & Barrel",
  "Anthropologie",
  "H&M Home",
  "Zara Home",
  "Mango Home",
  "Maisons du Monde",
  "La Redoute",
  "Amara",
  "Oliver Bonas",
  "Graham & Green",
  "Rockett St George",
  "Rose & Grey",
  "Cox & Cox",
  "Swoon",
  "Loaf",
  "Heal's",
  "The Conran Shop",
  "Designers Guild",
  "Sanderson",
  "Morris & Co",
  "Harlequin",
  "Clarke & Clarke",
  "Voyage Maison",
  "Romo",
  "Liberty",
  "Orla Kiely",
  "Scion",
  "Ashley Wilde",
  "Paoletti",
  "Furn",
  "Evans Lichfield",
] as const;

/** Memory foam sleep pillows — foam / mattress / cervical brands. */
export const LEAF_MEMORY_FOAM_PILLOW_BRANDS = [
  "Tempur",
  "Emma",
  "Simba",
  "Dormeo",
  "Panda London",
  "Silentnight",
  "Hypnos",
  "Mammoth",
  "Eve Sleep",
  "Otty",
  "Nectar",
  "Brook + Wilde",
  "Dunlopillo",
  "Casper",
  "Purple",
  "Sleepeezee",
  "Harrison Spinks",
  "Putnams",
  "Orthocare",
  "Mulisoft",
  "Elviros",
  "Becket",
  "Leesa",
  "Puffy",
  "Layla",
  "Nest Bedding",
  "Brooklyn Bedding",
  "Coop Home Goods",
  "Beckham Hotel Collection",
  "Snug",
  "Woolroom",
  "Vispring",
  "Savon",
  "John Lewis",
  "Dunelm",
  "IKEA",
  "Dreams",
  "Slumberdown",
  "EPABO",
  "Snuggle-Pedic",
  "Eli & Elm",
  "Linenspa",
  "Zinus",
  "Lucid",
  "Milliard",
  "Sleep Innovations",
  "ComfiLife",
  "Cushion Lab",
  "Everlasting Comfort",
  "Pharmedoc",
  "Jinxia",
  "Napfun",
  "Sealy",
  "Serta",
  "Beautyrest",
  "Stearns & Foster",
  "Tempur-Pedic",
] as const;

/** Orthopedic / firm support pillows. */
export const LEAF_ORTHOPEDIC_PILLOW_BRANDS = [
  "Tempur",
  "Putnams",
  "Orthocare",
  "Mammoth",
  "Hypnos",
  "Silentnight",
  "Dormeo",
  "Core Products",
  "Sissel",
  "Therapeutica",
  "Mediflow",
  "Brook + Wilde",
  "Emma",
  "Mulisoft",
  "Elviros",
  "EPABO",
  "Cushion Lab",
  "ComfiLife",
  "Pharmedoc",
  "Becket",
  "PhysioRoom",
  "Physique",
  "BodyMed",
  "Drive DeVilbiss",
  "Homecraft",
  "NRS Healthcare",
  "Snuggle-Pedic",
  "Eli & Elm",
  "Coop Home Goods",
  "Purple",
  "Casper",
  "Otty",
  "Nectar",
  "Simba",
  "Panda London",
  "Tempur-Pedic",
  "Sealy",
] as const;

/** Cooling / gel / climate pillows. */
export const LEAF_COOLING_PILLOW_BRANDS = [
  "Tempur",
  "Emma",
  "Simba",
  "Otty",
  "Silentnight",
  "Dormeo",
  "Purple",
  "Becket",
  "Brook + Wilde",
  "Nectar",
  "Eve Sleep",
  "Hypnos",
  "Panda London",
  "Casper",
  "Leesa",
  "Puffy",
  "Layla",
  "Coop Home Goods",
  "Beckham Hotel Collection",
  "Snug",
  "Bedsure",
  "Utopia Bedding",
  "Buffy",
  "Brooklinen",
  "Parachute",
  "Boll & Branch",
  "Slumber Cloud",
  "Sheex",
  "Outlast",
  "HOMCA",
  "Blissbury",
] as const;

/** Feather pillows. */
export const LEAF_FEATHER_PILLOW_BRANDS = [
  "Silentnight",
  "Slumberdown",
  "John Lewis",
  "The White Company",
  "Dunelm",
  "Christy",
  "Sheridan",
  "Hypnos",
  "Harrison Spinks",
  "Soak&Sleep",
  "Secret Linen Store",
  "Devonia",
  "Fogarty",
  "Scooms",
  "And So To Bed",
  "The Fine Cotton Company",
  "Piglet in Bed",
  "Bedeck",
  "Yves Delorme",
  "Frette",
  "Dorma",
  "Emma Bridgewater",
  "Marks & Spencer",
  "Next Home",
  "Habitat",
  "IKEA",
  "Dreams",
  "Sleepeezee",
  "Vispring",
  "Savon",
  "Woolroom",
  "Snuggledown",
] as const;

/** Down pillows. */
export const LEAF_DOWN_PILLOW_BRANDS = [
  "The White Company",
  "John Lewis",
  "Silentnight",
  "Hypnos",
  "Harrison Spinks",
  "Christy",
  "Sheridan",
  "Soak&Sleep",
  "Secret Linen Store",
  "Scooms",
  "Fogarty",
  "Dunelm",
  "And So To Bed",
  "The Fine Cotton Company",
  "Piglet in Bed",
  "Yves Delorme",
  "Frette",
  "Bedeck",
  "Dorma",
  "Vispring",
  "Savon",
  "Devonia",
  "Marks & Spencer",
  "Next Home",
  "Habitat",
  "IKEA",
  "Dreams",
  "Sleepeezee",
  "Brooklinen",
  "Parachute",
  "Boll & Branch",
  "Coyuchi",
  "Snowe",
  "Pacific Coast",
  "Allied Feather + Down",
] as const;

/** Body pillows (non-maternity). */
export const LEAF_BODY_PILLOW_BRANDS = [
  "Silentnight",
  "Slumberdown",
  "Dunelm",
  "John Lewis",
  "IKEA",
  "Emma",
  "Simba",
  "Tempur",
  "Dreams",
  "Wayfair",
  "Putnams",
  "PharMeDoc",
  "Coop Home Goods",
  "Beckham Hotel Collection",
  "Utopia Bedding",
  "Bedsure",
  "Snug",
  "Purple",
  "Casper",
  "Otty",
  "Nectar",
  "Brook + Wilde",
  "Hypnos",
  "Panda London",
  "Marks & Spencer",
  "Next Home",
  "Habitat",
  "Made.com",
  "Loaf",
  "Heal's",
  "Queen Rose",
  "Niimo",
  "Momcozy",
  "bbhugme",
  "Leachco",
  "Snuggledown",
  "Fogarty",
  "Christy",
  "Soak&Sleep",
  "Secret Linen Store",
  "Woolroom",
  "Mammoth",
  "Eve Sleep",
  "Dormeo",
  "Sleepeezee",
] as const;

/** Children's pillows. */
export const LEAF_CHILDRENS_PILLOW_BRANDS = [
  "Silentnight",
  "Slumberdown",
  "Dunelm",
  "IKEA",
  "John Lewis",
  "Mamas & Papas",
  "JoJo Maman Bébé",
  "Grobag",
  "The Gro Company",
  "Dreams",
  "Marks & Spencer",
  "Next Home",
  "Habitat",
  "Mothercare",
  "BabyBjörn",
  "Stokke",
  "Chicco",
  "Tommee Tippee",
  "Purflo",
  "Clevamama",
  "Doomoo",
  "Snuz",
  "Tutti Bambini",
  "Obaby",
  "Cosatto",
  "Silver Cross",
  "Izzie",
  "Aden + Anais",
  "Little Green Sheep",
  "Naturalmat",
] as const;

/** Generic bed pillows (standard). */
export const LEAF_STANDARD_PILLOW_BRANDS = [
  "Silentnight",
  "Slumberdown",
  "Dunelm",
  "John Lewis",
  "IKEA",
  "Habitat",
  "Marks & Spencer",
  "Next Home",
  "Hypnos",
  "Dreams",
  "Emma",
  "Simba",
  "Tempur",
  "Mulisoft",
  "Elviros",
  "Jinxia",
  "Utopia Bedding",
  "Coop Home Goods",
  "Christy",
  "Sheridan",
  "The White Company",
  "Soak&Sleep",
  "Secret Linen Store",
  "Piglet in Bed",
  "Brook + Wilde",
  "Otty",
  "Nectar",
  "Eve Sleep",
  "Panda London",
  "Dormeo",
  "Casper",
  "Purple",
  "Sleepeezee",
  "Harrison Spinks",
  "Dunlopillo",
  "Vispring",
  "Savon",
  "Woolroom",
  "Fogarty",
  "Scooms",
  "Bedeck",
  "Wayfair",
  "Made.com",
  "Beckham Hotel Collection",
  "Bedsure",
  "Snuggledown",
  "Snug",
  "Mammoth",
  "Putnams",
  "Everlasting Comfort",
  "Cushion Lab",
  "Kally Sleep",
  "Levitex",
  "Nanu",
  "Mediflow",
  "Derila",
  "Cosy House",
  "viewstar",
  "Bluewave",
  "Weekender",
  "EPABO",
  "Snuggle-Pedic",
  "Brooklinen",
  "Parachute",
  "Boll & Branch",
  "The Fine Bedding Company",
  "Julian Charles",
  "Catherine Lansfield",
  "Dorma",
  "And So To Bed",
] as const;

/** Pillowcases — bedding textile brands. */
export const LEAF_PILLOWCASE_BRANDS = [
  "Dunelm",
  "John Lewis",
  "IKEA",
  "The White Company",
  "Christy",
  "Sheridan",
  "Marks & Spencer",
  "Next Home",
  "Secret Linen Store",
  "Piglet in Bed",
  "Soak&Sleep",
  "Emma Bridgewater",
  "Habitat",
  "Silentnight",
  "Slumberdown",
  "Hypnos",
  "Bedeck",
  "Yves Delorme",
  "Frette",
  "Dorma",
  "Designers Guild",
  "Sanderson",
  "Liberty",
  "Orla Kiely",
  "Cath Kidston",
  "Joules",
  "Sophie Allport",
  "Laura Ashley",
  "Catherine Lansfield",
  "Zara Home",
  "H&M Home",
  "Mango Home",
  "Brooklinen",
  "Parachute",
  "Boll & Branch",
  "Coyuchi",
  "Snowe",
  "Buffy",
] as const;

/** Seat / lumbar / floor cushions. */
export const LEAF_SEAT_CUSHION_BRANDS = [
  "IKEA",
  "Dunelm",
  "John Lewis",
  "Habitat",
  "Wayfair",
  "Next Home",
  "Made.com",
  "Laura Ashley",
  "Marks & Spencer",
  "Cox & Cox",
  "Oliver Bonas",
  "Loaf",
  "Heal's",
  "West Elm",
  "Pottery Barn",
  "Crate & Barrel",
  "Maisons du Monde",
  "La Redoute",
  "Amara",
  "Graham & Green",
  "Swoon",
  "ComfiLife",
  "Everlasting Comfort",
  "Cushion Lab",
  "PharMeDoc",
  "Tempur",
  "Putnams",
  "Orthocare",
  "BackJoy",
  "ObusForme",
  "Fellowes",
  "Kensington",
  "Homcom",
  "VonHaus",
  "Outsunny",
  "Fatboy",
  "Yogibo",
  "Lounge Pug",
  "Icon",
  "Silentnight",
  "Slumberdown",
  "Emma",
  "Simba",
] as const;

export const LEAF_OUTDOOR_CUSHION_BRANDS = [
  "IKEA",
  "Dunelm",
  "Habitat",
  "Wayfair",
  "Kettler",
  "Hartman",
  "Garden Trading",
  "John Lewis",
  "Next Home",
  "Marks & Spencer",
  "Laura Ashley",
  "Cox & Cox",
  "Made.com",
  "Maisons du Monde",
  "La Redoute",
  "VonHaus",
  "Outsunny",
  "Charles Bentley",
  "Brundle",
  "Rowlinson",
  "Forest Garden",
  "Keter",
  "Suncast",
  "Allibert",
  "Nardi",
  "Fermob",
  "Fatboy",
  "Kettal",
  "Dedon",
  "Cane-line",
  "Gloster",
  "Barlow Tyrie",
  "Vincent Sheppard",
  "Skyline Design",
  "Lifestyle Garden",
  "Nova Outdoor Living",
  "Alexander Rose",
  "Garpa",
  "Manutti",
  "Tribù",
] as const;

/**
 * Path or slug → dedicated leaf Brand list.
 * Path keys (`root/sub/slug`) win over slug-only keys for shared slugs.
 */
export const LEAF_CATEGORY_BRAND_OVERRIDES: Readonly<Record<string, readonly string[]>> = {
  "travel-pillows": LEAF_TRAVEL_PILLOW_BRANDS,
  "neck-pillows": LEAF_TRAVEL_PILLOW_BRANDS,
  "maternity-pillows": LEAF_MATERNITY_PILLOW_BRANDS,
  "pregnancy-pillows": LEAF_MATERNITY_PILLOW_BRANDS,
  "decorative-cushions": LEAF_DECORATIVE_PILLOW_BRANDS,
  "memory-foam-pillows": LEAF_MEMORY_FOAM_PILLOW_BRANDS,
  "orthopedic-pillows": LEAF_ORTHOPEDIC_PILLOW_BRANDS,
  "cooling-pillows": LEAF_COOLING_PILLOW_BRANDS,
  "feather-pillows": LEAF_FEATHER_PILLOW_BRANDS,
  "down-pillows": LEAF_DOWN_PILLOW_BRANDS,
  "body-pillows": LEAF_BODY_PILLOW_BRANDS,
  "children-s-pillows": LEAF_CHILDRENS_PILLOW_BRANDS,
  pillows: LEAF_STANDARD_PILLOW_BRANDS,
  pillowcases: LEAF_PILLOWCASE_BRANDS,
  "seat-cushions": LEAF_SEAT_CUSHION_BRANDS,
  "lumbar-cushions": LEAF_SEAT_CUSHION_BRANDS,
  "floor-cushions": LEAF_SEAT_CUSHION_BRANDS,
  "outdoor-cushions": LEAF_OUTDOOR_CUSHION_BRANDS,
  cushions: LEAF_DECORATIVE_PILLOW_BRANDS,
};

/** Leaf-specific specialty brands appended to vertical clothing cores (genuine manufacturers only). */
export const WOMENS_CLOTHING_LEAF_SPECIALTY: Readonly<Record<string, readonly string[]>> = {
  lingerie: [
    "Triumph",
    "Fantasie",
    "Agent Provocateur",
    "Boux Avenue",
    "Ann Summers",
    "Pour Moi",
    "Figleaves",
    "Panache",
    "Freya",
    "Curvy Kate",
    "Wacoal",
    "Chantelle",
    "Simone Pérèle",
    "Aubade",
    "Cosabella",
    "Hanky Panky",
    "Skims",
    "ThirdLove",
    "Savage X Fenty",
  ],
  swimwear: [
    "Speedo",
    "Seafolly",
    "Pour Moi",
    "Figleaves",
    "Freya",
    "Arena",
    "Funkita",
    "Roxy",
    "Billabong",
    "Rip Curl",
    "Triangl",
    "Solid & Striped",
    "Melissa Odabash",
    "Heidi Klein",
  ],
  activewear: [
    "Gymshark",
    "Lululemon",
    "Sweaty Betty",
    "Alo Yoga",
    "Outdoor Voices",
    "Nike",
    "Adidas",
    "Puma",
    "Under Armour",
    "Castore",
    "Girlfriend Collective",
    "Vuori",
    "Athleta",
    "Fabletics",
  ],
  dresses: [
    "Rixo",
    "Self-Portrait",
    "Reformation",
    "Kitri",
    "Ghost",
    "Never Fully Dressed",
    "Reiss",
    "Whistles",
    "Ted Baker",
    "Phase Eight",
    "Coast",
    "Oasis",
    "& Other Stories",
    "Maje",
    "Sandro",
  ],
  coats: [
    "Canada Goose",
    "Woolrich",
    "Barbour",
    "Belstaff",
    "Mackage",
    "Moncler",
    "The North Face",
    "Patagonia",
    "Arc'teryx",
    "Max Mara",
    "Burberry",
    "Aquascutum",
  ],
  "leather-jackets": ["AllSaints", "Schott", "Belstaff", "Diesel", "Deadwood", "The Kooples", "Muubaa"],
  jeans: [
    "Levi's",
    "Wrangler",
    "Lee",
    "Nudie Jeans",
    "AG Jeans",
    "Citizens of Humanity",
    "Frame",
    "Mother",
    "Good American",
    "Paige",
    "J Brand",
    "7 For All Mankind",
  ],
  nightwear: [
    "Cosabella",
    "Eberjey",
    "Cyberjammies",
    "Chelsea Peers",
    "Pour Moi",
    "Figleaves",
    "Boux Avenue",
    "Marks & Spencer",
    "John Lewis",
    "The White Company",
  ],
};

export const MENS_CLOTHING_LEAF_SPECIALTY: Readonly<Record<string, readonly string[]>> = {
  suits: [
    "Moss Bros",
    "Charles Tyrwhitt",
    "TM Lewin",
    "Hackett",
    "Reiss",
    "Hugo Boss",
    "Canali",
    "Corneliani",
    "SuitSupply",
    "Indochino",
    "Hawes & Curtis",
    "Pink Shirtmaker",
  ],
  shirts: [
    "Charles Tyrwhitt",
    "TM Lewin",
    "Hawes & Curtis",
    "Pink Shirtmaker",
    "Turnbull & Asser",
    "Thomas Pink",
    "Hackett",
    "Reiss",
    "Hugo Boss",
  ],
  activewear: [
    "Gymshark",
    "Under Armour",
    "Lululemon",
    "Castore",
    "Nike",
    "Adidas",
    "Puma",
    "New Balance",
    "Lonsdale",
    "Everlast",
  ],
  swimwear: ["Speedo", "Arena", "Orlebar Brown", "Hussein Chalayan", "Vilebrequin", "Frescobol Carioca"],
  jeans: ["Levi's", "Wrangler", "Lee", "Nudie Jeans", "Edwin", "Diesel", "G-Star RAW", "True Religion", "Replay"],
  "leather-jackets": ["Schott", "Belstaff", "AllSaints", "Lewis Leathers", "Deadwood", "Matchless"],
  underwear: [
    "Calvin Klein",
    "Björn Borg",
    "CDLP",
    "Saxx",
    "Tommy Hilfiger",
    "Emporio Armani",
    "Hugo Boss",
    "Sunspel",
    "Derek Rose",
  ],
};

/** Must-keep manufacturer anchors per leaf family (never path-dropped). */
export const LEAF_BRAND_ANCHORS: Readonly<Record<string, readonly string[]>> = {
  "travel-pillows": [
    "Cabeau",
    "BCOZZY",
    "Trtl",
    "Mulisoft",
    "Elviros",
    "Jinxia",
    "Napfun",
    "Dot & Dot",
    "Huzi",
    "Lewis N. Clark",
    "Tempur",
    "Cocoon",
    "MLVOC",
    "Go Travel",
    "Samsonite",
    "Travel Blue",
    "Everlasting Comfort",
  ],
  "neck-pillows": [
    "Cabeau",
    "BCOZZY",
    "Trtl",
    "Mulisoft",
    "Elviros",
    "Napfun",
    "Dot & Dot",
    "Huzi",
    "Lewis N. Clark",
    "Tempur",
    "Cocoon",
    "MLVOC",
  ],
  "maternity-pillows": [
    "bbhugme",
    "Momcozy",
    "PharMeDoc",
    "Dreamgenii",
    "Queen Rose",
    "Theraline",
    "Doomoo",
    "Boppy",
    "Niimo",
    "BabyMoov",
    "Purflo",
    "Clevamama",
  ],
  "pregnancy-pillows": [
    "bbhugme",
    "Momcozy",
    "PharMeDoc",
    "Dreamgenii",
    "Queen Rose",
    "Niimo",
    "Theraline",
    "Boppy",
    "Purflo",
    "Clevamama",
  ],
  "decorative-cushions": [
    "John Lewis",
    "IKEA",
    "Dunelm",
    "Habitat",
    "The White Company",
    "Laura Ashley",
    "Catherine Lansfield",
    "Silentnight",
    "Slumberdown",
  ],
  cushions: ["John Lewis", "IKEA", "Dunelm", "Habitat", "The White Company"],
  "memory-foam-pillows": [
    "Tempur",
    "Emma",
    "Simba",
    "Dormeo",
    "Panda London",
    "Silentnight",
    "Hypnos",
    "Mammoth",
    "Mulisoft",
    "Elviros",
  ],
  "orthopedic-pillows": ["Tempur", "Putnams", "Orthocare", "Mulisoft", "Elviros", "Sissel"],
  "cooling-pillows": ["Tempur", "Emma", "Simba", "Otty", "Purple", "Silentnight"],
  "feather-pillows": ["Silentnight", "Slumberdown", "John Lewis", "The White Company", "Hypnos"],
  "down-pillows": ["The White Company", "John Lewis", "Silentnight", "Hypnos", "Scooms"],
  pillows: [
    "Silentnight",
    "Slumberdown",
    "Dunelm",
    "John Lewis",
    "IKEA",
    "Tempur",
    "Emma",
    "Simba",
    "Mulisoft",
    "Elviros",
    "Jinxia",
    "Utopia Bedding",
    "Coop Home Goods",
    "Panda London",
  ],
  pillowcases: ["Dunelm", "John Lewis", "IKEA", "The White Company", "Christy"],
  "body-pillows": [
    "Silentnight",
    "Dunelm",
    "John Lewis",
    "Tempur",
    "Emma",
    "Utopia Bedding",
    "Coop Home Goods",
  ],
  "children-s-pillows": ["Silentnight", "Dunelm", "IKEA", "Mamas & Papas", "John Lewis"],
  "seat-cushions": ["IKEA", "Dunelm", "John Lewis", "Habitat"],
  "lumbar-cushions": ["IKEA", "Dunelm", "John Lewis", "ComfiLife"],
  "floor-cushions": ["IKEA", "Dunelm", "John Lewis", "Wayfair"],
  "outdoor-cushions": ["IKEA", "Dunelm", "Kettler", "Hartman", "Fatboy"],
};

export function resolveLeafBrandAnchors(productTypeSlug: string): readonly string[] {
  return LEAF_BRAND_ANCHORS[productTypeSlug] ?? [];
}

export function resolveLeafBrandOverride(
  rootSlug: string,
  subcategorySlug: string,
  productTypeSlug: string,
): readonly string[] | null {
  const pathKey = `${rootSlug}/${subcategorySlug}/${productTypeSlug}`;
  return (
    LEAF_CATEGORY_BRAND_OVERRIDES[pathKey] ??
    LEAF_CATEGORY_BRAND_OVERRIDES[productTypeSlug] ??
    null
  );
}

/** Forced manufacturer anchors for electronics leaves (category-specific). */
export const ELECTRONICS_LEAF_BRAND_SPECIALTY: Readonly<Record<string, readonly string[]>> = {
  iphones: ["Apple"],
  ipads: ["Apple"],
  "android-phones": ["Apple", "Samsung", "Google", "Xiaomi", "OnePlus", "OPPO", "Motorola"],
  "android-tablets": ["Samsung", "Lenovo", "Huawei", "Xiaomi"],
  "feature-phones": ["Nokia", "Doro", "CAT", "Alcatel"],
  "sim-free-phones": ["Apple", "Samsung", "Google", "Nothing", "OnePlus"],
  smartphones: ["Apple", "Samsung", "Google", "Xiaomi", "OnePlus"],
  "e-readers": ["Amazon", "Kobo", "Remarkable", "BOOX"],
  "phone-cases": ["Spigen", "OtterBox", "Apple", "Samsung"],
  "chargers-and-cables": ["Anker", "Belkin", "Apple", "Samsung", "Baseus"],
  "screen-protectors": ["Spigen", "Belkin", "Zagg", "Apple"],
  "power-banks": ["Anker", "Belkin", "Baseus", "Xiaomi"],
  "wireless-chargers": ["Anker", "Belkin", "Apple", "Samsung"],
  "laptop-bags-and-sleeves": ["Samsonite", "Targus", "Thule", "Incase", "Peak Design"],
};
