/**
 * ROVEXO Catalog Master — UK Material pools (content SSOT for product-type Material DBs).
 * COD SÂNGE Category Attribute Database V1.0 — data expansion only.
 */

export const MATERIAL_OTHER = "Other" as const;

export const UK_TRAVEL_PILLOW_MATERIALS = [
  "Memory Foam",
  "Foam",
  "Polyester",
  "Cotton",
  "Microfibre",
  "Velour",
  "Gel Foam",
  "Bamboo",
  "Latex",
  "Velvet",
  "Jersey",
  MATERIAL_OTHER,
] as const;

export const UK_BEDDING_MATERIALS = [
  "Cotton",
  "Egyptian Cotton",
  "Percale",
  "Sateen",
  "Linen",
  "Polyester",
  "Microfibre",
  "Bamboo",
  "Silk",
  "Wool",
  "Down",
  "Feather",
  "Memory Foam",
  "Foam",
  "Flannel",
  "Jersey",
  MATERIAL_OTHER,
] as const;

export const UK_FASHION_MATERIALS = [
  "Cotton",
  "Organic Cotton",
  "Polyester",
  "Wool",
  "Merino Wool",
  "Cashmere",
  "Silk",
  "Linen",
  "Denim",
  "Leather",
  "Faux Leather",
  "Suede",
  "Viscose",
  "Rayon",
  "Acrylic",
  "Nylon",
  "Elastane",
  "Spandex",
  "Modal",
  "Tencel",
  "Lyocell",
  "Velvet",
  "Corduroy",
  "Fleece",
  "Chiffon",
  "Satin",
  "Lace",
  "Tweed",
  "Jersey",
  "Mesh",
  MATERIAL_OTHER,
] as const;

export const UK_MENS_FASHION_MATERIALS = [
  "Cotton",
  "Organic Cotton",
  "Polyester",
  "Wool",
  "Merino Wool",
  "Cashmere",
  "Linen",
  "Denim",
  "Leather",
  "Faux Leather",
  "Suede",
  "Viscose",
  "Acrylic",
  "Nylon",
  "Elastane",
  "Spandex",
  "Modal",
  "Tencel",
  "Corduroy",
  "Fleece",
  "Tweed",
  "Jersey",
  "Mesh",
  "Chambray",
  "Flannel",
  "Ripstop",
  "Technical Fabric",
  MATERIAL_OTHER,
] as const;

export const UK_SHOE_MATERIALS = [
  "Leather",
  "Full Grain Leather",
  "Suede",
  "Nubuck",
  "Faux Leather",
  "Canvas",
  "Mesh",
  "Textile",
  "Rubber",
  "EVA",
  "Synthetic",
  "Patent Leather",
  "Knit",
  "Gore-Tex",
  "Neoprene",
  "Cork",
  MATERIAL_OTHER,
] as const;

export const UK_MENS_SHOE_MATERIALS = [
  "Leather",
  "Full Grain Leather",
  "Suede",
  "Nubuck",
  "Faux Leather",
  "Canvas",
  "Mesh",
  "Textile",
  "Rubber",
  "EVA",
  "Synthetic",
  "Knit",
  "Gore-Tex",
  "Neoprene",
  "Nubuck Suede",
  "Split Leather",
  "Patent Leather",
  "Cork",
  "Vibram",
  "Ortholite",
  MATERIAL_OTHER,
] as const;

export const UK_FURNITURE_MATERIALS = [
  "Wood",
  "Oak",
  "Pine",
  "Walnut",
  "Beech",
  "Mango Wood",
  "MDF",
  "Plywood",
  "Bamboo",
  "Metal",
  "Steel",
  "Iron",
  "Aluminium",
  "Glass",
  "Rattan",
  "Wicker",
  "Fabric",
  "Velvet",
  "Leather",
  "Faux Leather",
  "Marble",
  "Stone",
  "Plastic",
  "Acrylic",
  MATERIAL_OTHER,
] as const;

export const UK_HOME_MATERIALS = [
  "Cotton",
  "Polyester",
  "Ceramic",
  "Porcelain",
  "Glass",
  "Wood",
  "Bamboo",
  "Metal",
  "Stainless Steel",
  "Aluminium",
  "Plastic",
  "Silicone",
  "Rubber",
  "Stoneware",
  "Cast Iron",
  "Copper",
  "Marble",
  "Resin",
  "Paper",
  "Cardboard",
  MATERIAL_OTHER,
] as const;

export const UK_ELECTRONICS_MATERIALS = [
  "Aluminium",
  "Stainless Steel",
  "Plastic",
  "Polycarbonate",
  "Glass",
  "Gorilla Glass",
  "Ceramic",
  "Titanium",
  "Magnesium",
  "Carbon Fibre",
  "Silicone",
  "Rubber",
  "Leather",
  "Fabric",
  "ABS Plastic",
  "PCB",
  "Copper",
  "Tin",
  "Nickel",
  "Tempered Glass",
  "Anodised Aluminium",
  "Zinc Alloy",
  "Nylon",
  "TPU",
  "Recycled Plastic",
  "Wood Accent",
  "Metal Mesh",
  "Foam Padding",
  MATERIAL_OTHER,
] as const;

export const UK_PHONE_MATERIALS = [
  "Glass",
  "Gorilla Glass",
  "Aluminium",
  "Stainless Steel",
  "Plastic",
  "Ceramic",
  "Titanium",
  "Polycarbonate",
  "Silicone",
  "Magnesium",
  "Carbon Fibre",
  "Sapphire Glass",
  "Plastic Frame",
  "Metal Frame",
  "Nano Ceramic",
  MATERIAL_OTHER,
] as const;

export const UK_VEHICLE_PART_MATERIALS = [
  "Steel",
  "Cast Iron",
  "Aluminium",
  "Alloy",
  "Carbon Fibre",
  "Rubber",
  "Plastic",
  "Ceramic",
  "Copper",
  "Brass",
  "Composite",
  "Stainless Steel",
  "Titanium",
  "Silicone",
  "Fabric",
  "Leather",
  MATERIAL_OTHER,
] as const;

export const UK_SPORTS_MATERIALS = [
  "Polyester",
  "Nylon",
  "Spandex",
  "Elastane",
  "Mesh",
  "Neoprene",
  "Rubber",
  "EVA",
  "Carbon Fibre",
  "Aluminium",
  "Steel",
  "Leather",
  "Synthetic",
  "Gore-Tex",
  "Fleece",
  "Cotton",
  MATERIAL_OTHER,
] as const;

export const UK_JEWELLERY_MATERIALS = [
  "Gold",
  "Yellow Gold",
  "White Gold",
  "Rose Gold",
  "Sterling Silver",
  "Silver",
  "Platinum",
  "Stainless Steel",
  "Titanium",
  "Brass",
  "Copper",
  "Pearl",
  "Diamond",
  "Cubic Zirconia",
  "Gemstone",
  "Enamel",
  "Leather",
  "Resin",
  "Rhodium",
  "Palladium",
  "Tungsten",
  "Ceramic",
  "Wood",
  "Acetate",
  "Mother of Pearl",
  "Crystal",
  "Glass",
  "Fabric Strap",
  "Rubber Strap",
  MATERIAL_OTHER,
] as const;

export const UK_TOY_MATERIALS = [
  "Plastic",
  "ABS Plastic",
  "Wood",
  "Fabric",
  "Plush",
  "Rubber",
  "Metal",
  "Cardboard",
  "Paper",
  "Silicone",
  "Foam",
  "EVA",
  "Die-Cast Metal",
  "Vinyl",
  "Felt",
  "Cotton",
  "Polyester",
  "Bamboo",
  "Recycled Plastic",
  "Electronic Components",
  MATERIAL_OTHER,
] as const;

export const UK_BOOK_MATERIALS = [
  "Paper",
  "Cardboard",
  "Hardcover",
  "Paperback",
  "Leather",
  "Cloth",
  "Vinyl",
  MATERIAL_OTHER,
] as const;

export const UK_BEAUTY_MATERIALS = [
  "Plastic",
  "Glass",
  "Aluminium",
  "Metal",
  "Paper",
  "Cardboard",
  "Silicone",
  "Acrylic",
  "Bioplastic",
  "Bamboo",
  "Tin",
  "Ceramic",
  "Wood",
  "Rubber",
  "Recycled Plastic",
  "PET",
  "HDPE",
  "Glass Bottle",
  "Pump Dispenser",
  "Airless Pump",
  "Metal Tube",
  "Laminate Tube",
  "Compacts",
  MATERIAL_OTHER,
] as const;

export const UK_GROOMING_MATERIALS = [
  "Plastic",
  "Glass",
  "Aluminium",
  "Stainless Steel",
  "Metal",
  "Silicone",
  "Rubber",
  "Wood",
  "Ceramic",
  "Paper",
  "Carbon Steel",
  "Titanium",
  "Nylon Bristle",
  "Boar Bristle",
  "Recycled Plastic",
  "ABS Plastic",
  MATERIAL_OTHER,
] as const;

export const UK_BAG_MATERIALS = [
  "Leather",
  "Faux Leather",
  "Canvas",
  "Nylon",
  "Polyester",
  "Cotton",
  "Suede",
  "PVC",
  "Recycled Plastic",
  "Mesh",
  "Ballistic Nylon",
  "Ripstop",
  "Cordura",
  "Waxed Cotton",
  "Vegan Leather",
  "Microfibre",
  "Jacquard",
  "Tweed",
  "Denim",
  "Rattan",
  MATERIAL_OTHER,
] as const;
