/**
 * ROVEXO Catalog Master — Category → Subcategory → Product Type tree.
 * Absolute Law XXX — ten courier-safe roots. Vehicle Parts is its own root.
 * Hierarchy depth locked at 3 (no extra levels).
 */

import type { SectorDef } from "@/lib/categories/enterprise/builder";
import { slugify } from "@/lib/categories/enterprise/builder";

type Item = readonly [name: string, slug: string];

function items(...names: string[]): Item[] {
  return names.map((name) => [name, slugify(name)] as const);
}

/**
 * Catalog Master sectors — ONLY SSOT for marketplace category tree.
 * Forbidden forever as roots: whole vehicles, property, business, jobs, services, live animals.
 * Vehicle Parts & Accessories = own root (never under Electronics).
 */
export const CATALOG_SECTORS: SectorDef[] = [
  {
    id: "cat-womens-fashion",
    name: "Women's Fashion",
    slug: "womens-fashion",
    sortOrder: 1,
    departments: [
      {
        name: "Clothing",
        slug: "clothing",
        items: items(
          "Dresses",
          "Tops & Blouses",
          "T-shirts",
          "Jumpers & Cardigans",
          "Hoodies & Sweatshirts",
          "Jeans",
          "Trousers",
          "Skirts",
          "Shorts",
          "Coats & Jackets",
          "Blazers",
          "Suits",
          "Activewear",
          "Swimwear",
          "Lingerie",
          "Nightwear",
          "Socks & Tights",
        ),
      },
      {
        name: "Shoes",
        slug: "shoes",
        items: items(
          "Trainers",
          "Boots",
          "Heels",
          "Flats",
          "Sandals",
          "Slippers",
          "Formal Shoes",
        ),
      },
      {
        name: "Bags",
        slug: "bags",
        items: items(
          "Handbags",
          "Shoulder Bags",
          "Crossbody Bags",
          "Tote Bags",
          "Clutches",
          "Backpacks",
          "Travel Bags",
        ),
      },
      {
        name: "Accessories",
        slug: "accessories",
        items: items(
          "Belts",
          "Scarves",
          "Hats",
          "Gloves",
          "Sunglasses",
          "Hair Accessories",
          "Wallets & Purses",
        ),
      },
      {
        name: "Beauty",
        slug: "beauty",
        items: items(
          "Makeup",
          "Skincare",
          "Haircare",
          "Fragrance",
          "Nail Care",
          "Beauty Tools",
        ),
      },
    ],
  },
  {
    id: "cat-mens-fashion",
    name: "Men's Fashion",
    slug: "mens-fashion",
    sortOrder: 2,
    departments: [
      {
        name: "Clothing",
        slug: "clothing",
        items: items(
          "T-shirts",
          "Shirts",
          "Polo Shirts",
          "Jumpers & Cardigans",
          "Hoodies & Sweatshirts",
          "Jeans",
          "Trousers",
          "Shorts",
          "Coats & Jackets",
          "Blazers",
          "Suits",
          "Activewear",
          "Swimwear",
          "Underwear",
          "Nightwear",
          "Socks",
        ),
      },
      {
        name: "Shoes",
        slug: "shoes",
        items: items(
          "Trainers",
          "Boots",
          "Formal Shoes",
          "Casual Shoes",
          "Sandals",
          "Slippers",
        ),
      },
      {
        name: "Accessories",
        slug: "accessories",
        items: items(
          "Belts",
          "Hats",
          "Scarves",
          "Gloves",
          "Sunglasses",
          "Ties & Bow Ties",
          "Wallets",
          "Bags & Backpacks",
        ),
      },
      {
        name: "Grooming",
        slug: "grooming",
        items: items(
          "Skincare",
          "Haircare",
          "Fragrance",
          "Shaving",
          "Grooming Tools",
        ),
      },
    ],
  },
  {
    id: "cat-jewellery",
    name: "Designer",
    slug: "jewellery",
    sortOrder: 3,
    departments: [
      {
        name: "Jewellery",
        slug: "fine-jewellery",
        items: items(
          "Rings",
          "Necklaces",
          "Earrings",
          "Bracelets",
          "Watches",
          "Brooches",
          "Jewellery Sets",
        ),
      },
      {
        name: "Designer Fashion",
        slug: "designer-fashion",
        items: items(
          "Designer Clothing",
          "Designer Shoes",
          "Designer Bags",
          "Designer Accessories",
        ),
      },
      {
        name: "Luxury Watches",
        slug: "luxury-watches",
        items: items(
          "Automatic Watches",
          "Quartz Watches",
          "Smart Luxury Watches",
          "Watch Accessories",
        ),
      },
    ],
  },
  {
    id: "cat-kids-fashion",
    name: "Kids & Baby",
    slug: "kids-fashion",
    sortOrder: 4,
    departments: [
      {
        name: "Baby",
        slug: "baby",
        items: items(
          "Baby Clothes",
          "Baby Shoes",
          "Baby Accessories",
          "Nursery",
          "Feeding",
          "Pushchairs & Travel",
          "Baby Safety",
        ),
      },
      {
        name: "Girls Clothing",
        slug: "girls-clothing",
        items: items(
          "Dresses",
          "Tops",
          "Bottoms",
          "Outerwear",
          "Activewear",
          "Swimwear",
          "School Uniform",
        ),
      },
      {
        name: "Boys Clothing",
        slug: "boys-clothing",
        items: items(
          "Tops",
          "Bottoms",
          "Outerwear",
          "Activewear",
          "Swimwear",
          "School Uniform",
        ),
      },
      {
        name: "Kids Shoes",
        slug: "kids-shoes",
        items: items("Trainers", "Boots", "Sandals", "School Shoes", "Wellies"),
      },
      {
        name: "Toys & Games",
        slug: "toys-games",
        items: items(
          "Action Figures",
          "Dolls",
          "Building Sets",
          "Educational Toys",
          "Outdoor Toys",
          "Board Games",
          "Puzzles",
          "Soft Toys",
          "Remote Control",
        ),
      },
    ],
  },
  {
    id: "cat-home-garden",
    name: "Home & Garden",
    slug: "home-garden",
    sortOrder: 5,
    departments: [
      {
        name: "Furniture",
        slug: "furniture",
        items: items(
          "Sofas & Armchairs",
          "Beds & Mattresses",
          "Tables",
          "Chairs",
          "Wardrobes",
          "Chests of Drawers",
          "Shelving",
          "Desks",
          "TV Stands",
          "Outdoor Furniture",
        ),
      },
      {
        name: "Bedding",
        slug: "bedding",
        items: items(
          "Duvets",
          "Duvet Covers",
          "Sheets",
          "Pillowcases",
          "Pillows",
          "Blankets & Throws",
          "Mattress Protectors",
        ),
      },
      {
        name: "Home Textiles",
        slug: "home-textiles",
        items: items(
          "Curtains",
          "Blinds",
          "Cushions",
          "Rugs",
          "Towels",
          "Table Linen",
        ),
      },
      {
        name: "Kitchen",
        slug: "kitchen",
        items: items(
          "Cookware",
          "Bakeware",
          "Tableware",
          "Cutlery",
          "Kitchen Storage",
          "Small Kitchen Appliances",
        ),
      },
      {
        name: "Bathroom",
        slug: "bathroom",
        items: items(
          "Bath Mats",
          "Bathroom Storage",
          "Shower Accessories",
          "Bathroom Mirrors",
        ),
      },
      {
        name: "Garden",
        slug: "garden",
        items: items(
          "Garden Tools",
          "Planters & Pots",
          "Garden Decor",
          "Outdoor Lighting",
          "BBQs & Outdoor Cooking",
          "Lawn Care",
        ),
      },
      {
        name: "DIY & Tools",
        slug: "diy-tools",
        items: items(
          "Hand Tools",
          "Power Tools",
          "Painting & Decorating",
          "Hardware",
          "Electrical Supplies",
          "Plumbing Supplies",
        ),
      },
      {
        name: "Home Appliances",
        slug: "appliances",
        items: items(
          "Vacuum Cleaners",
          "Irons & Steamers",
          "Fans & Heaters",
          "Air Care",
        ),
      },
      {
        name: "Pet Supplies",
        slug: "pet-supplies",
        items: items(
          "Dog Supplies",
          "Cat Supplies",
          "Small Pet Supplies",
          "Pet Toys",
          "Pet Beds",
          "Pet Carriers",
        ),
      },
    ],
  },
  {
    id: "cat-electronics",
    name: "Electronics",
    slug: "electronics",
    sortOrder: 6,
    departments: [
      {
        name: "Phones & Tablets",
        slug: "phones-tablets",
        items: items(
          "Smartphones",
          "Feature Phones",
          "Tablets",
          "Phone Cases",
          "Chargers & Cables",
          "Screen Protectors",
          "Power Banks",
          "Phone Parts",
        ),
      },
      {
        name: "Computers",
        slug: "computers",
        items: items(
          "Laptops",
          "Desktops",
          "Monitors",
          "Keyboards",
          "Mice",
          "Webcams",
          "Printers",
          "Computer Components",
          "Storage Drives",
        ),
      },
      {
        name: "TV & Audio",
        slug: "tv-audio",
        items: items(
          "Televisions",
          "Soundbars",
          "Headphones",
          "Earbuds",
          "Speakers",
          "Streaming Devices",
          "Home Cinema",
        ),
      },
      {
        name: "Cameras",
        slug: "cameras",
        items: items(
          "Digital Cameras",
          "Action Cameras",
          "Lenses",
          "Camera Accessories",
          "Tripods",
        ),
      },
      {
        name: "Wearables",
        slug: "wearables",
        items: items(
          "Smartwatches",
          "Fitness Trackers",
          "VR Headsets",
        ),
      },
      {
        name: "Smart Home",
        slug: "smart-home",
        items: items(
          "Smart Speakers",
          "Smart Lighting",
          "Security Cameras",
          "Smart Plugs",
        ),
      },
      {
        name: "Gaming",
        slug: "gaming",
        items: items(
          "Consoles",
          "Video Games",
          "Controllers",
          "Gaming Headsets",
          "Gaming Chairs",
          "PC Gaming Accessories",
        ),
      },
    ],
  },
  {
    id: "cat-books",
    name: "Books & Media",
    slug: "books",
    sortOrder: 7,
    departments: [
      {
        name: "Books",
        slug: "books",
        items: items(
          "Fiction",
          "Non-Fiction",
          "Children's Books",
          "Textbooks",
          "Comics & Graphic Novels",
          "Magazines",
        ),
      },
      {
        name: "Music",
        slug: "music",
        items: items("Vinyl", "CDs", "Cassettes", "Music Memorabilia"),
      },
      {
        name: "Film & TV",
        slug: "film-tv",
        items: items("DVDs", "Blu-ray", "Box Sets", "Film Memorabilia"),
      },
      {
        name: "Instruments",
        slug: "instruments",
        items: items(
          "Guitars",
          "Keyboards & Pianos",
          "Drums & Percussion",
          "Wind Instruments",
          "String Instruments",
          "Instrument Accessories",
        ),
      },
    ],
  },
  {
    id: "cat-collectibles",
    name: "Hobbies & Collectables",
    slug: "collectibles",
    sortOrder: 8,
    departments: [
      {
        name: "Collectables",
        slug: "collectables",
        items: items(
          "Trading Cards",
          "Figurines",
          "Model Kits",
          "Coins & Banknotes",
          "Stamps",
          "Memorabilia",
          "Vintage Collectables",
        ),
      },
      {
        name: "Arts & Crafts",
        slug: "arts-crafts",
        items: items(
          "Art Supplies",
          "Craft Kits",
          "Sewing & Fabric",
          "Scrapbooking",
          "Handmade Items",
        ),
      },
      {
        name: "Antiques",
        slug: "antiques",
        items: items(
          "Antique Furniture",
          "China & Ceramics",
          "Silverware",
          "Clocks",
          "Decorative Antiques",
        ),
      },
      {
        name: "Hobby Electronics",
        slug: "hobby-electronics",
        items: items(
          "Drones",
          "RC Vehicles",
          "Maker Kits",
          "3D Printing",
        ),
      },
    ],
  },
  {
    id: "cat-sports",
    name: "Sports & Outdoors",
    slug: "sports",
    sortOrder: 9,
    departments: [
      {
        name: "Fitness",
        slug: "fitness",
        items: items(
          "Gym Equipment",
          "Yoga & Pilates",
          "Weights",
          "Fitness Trackers Accessories",
          "Sports Nutrition Accessories",
        ),
      },
      {
        name: "Team Sports",
        slug: "team-sports",
        items: items(
          "Football",
          "Rugby",
          "Basketball",
          "Cricket",
          "Hockey",
          "Netball",
        ),
      },
      {
        name: "Outdoor Sports",
        slug: "outdoor-sports",
        items: items(
          "Cycling",
          "Running",
          "Hiking",
          "Camping",
          "Fishing",
          "Water Sports",
          "Winter Sports",
        ),
      },
      {
        name: "Racket Sports",
        slug: "racket-sports",
        items: items("Tennis", "Badminton", "Squash", "Table Tennis"),
      },
      {
        name: "Sportswear",
        slug: "sportswear",
        items: items(
          "Sports Tops",
          "Sports Bottoms",
          "Sports Jackets",
          "Sports Shoes",
          "Sports Bags",
        ),
      },
    ],
  },
  {
    id: "cat-vehicle-parts",
    name: "Vehicle Parts & Accessories",
    slug: "vehicle-parts",
    sortOrder: 10,
    departments: [
      {
        name: "Car Parts",
        slug: "car-parts",
        items: items(
          "Engine Parts",
          "Brakes",
          "Suspension",
          "Body Panels",
          "Interior Trim",
          "Lighting",
          "Electrical Parts",
          "Exhaust",
          "Cooling",
          "Filters",
          "Transmission Parts",
        ),
      },
      {
        name: "Motorcycle Parts",
        slug: "motorcycle-parts",
        items: items(
          "Motorcycle Engine Parts",
          "Motorcycle Brakes",
          "Motorcycle Bodywork",
          "Motorcycle Lighting",
          "Motorcycle Exhaust",
          "Motorcycle Electrical",
        ),
      },
      {
        name: "Bicycle Parts",
        slug: "bicycle-parts",
        items: items(
          "Frames",
          "Wheels",
          "Drivetrain",
          "Brakes",
          "Handlebars & Stems",
          "Saddles",
          "Pedals",
        ),
      },
      {
        name: "Vehicle Accessories",
        slug: "vehicle-accessories",
        items: items(
          "Floor Mats",
          "Seat Covers",
          "Phone Mounts",
          "Roof Bars",
          "Cargo Nets",
          "Dash Cams",
          "Jump Starters",
        ),
      },
      {
        name: "Car Care",
        slug: "car-care",
        items: items(
          "Cleaning Kits",
          "Polishes & Waxes",
          "Interior Cleaners",
          "Wheel Cleaners",
          "Air Fresheners",
        ),
      },
      {
        name: "Garage Tools",
        slug: "garage-tools",
        items: items(
          "Hand Tools",
          "Diagnostic Tools",
          "Jacks & Stands",
          "Torque Wrenches",
          "Socket Sets",
        ),
      },
      {
        name: "Tyres & Wheels",
        slug: "tyres-and-wheels",
        items: items(
          "Car Tyres",
          "Motorcycle Tyres",
          "Bicycle Tyres",
          "Alloy Wheels",
          "Steel Wheels",
          "Wheel Nuts & Bolts",
        ),
      },
    ],
  },
];

/** Product-type slug → attribute preset key (essential 3–6 attrs). */
export const CATALOG_PRODUCT_TYPE_ATTR_PRESET: Readonly<Record<string, string>> = {
  // Fashion / shoes
  dresses: "fashion",
  "tops-and-blouses": "fashion",
  "t-shirts": "fashion",
  "jumpers-and-cardigans": "fashion",
  "hoodies-and-sweatshirts": "fashion",
  jeans: "fashion",
  trousers: "fashion",
  skirts: "fashion",
  shorts: "fashion",
  "coats-and-jackets": "fashion",
  blazers: "fashion",
  suits: "fashion",
  activewear: "fashion",
  swimwear: "fashion",
  lingerie: "fashion",
  nightwear: "fashion",
  "socks-and-tights": "fashion",
  underwear: "fashion",
  socks: "fashion",
  shirts: "fashion",
  "polo-shirts": "fashion",
  trainers: "shoes",
  boots: "shoes",
  heels: "shoes",
  flats: "shoes",
  sandals: "shoes",
  slippers: "shoes",
  "formal-shoes": "shoes",
  "casual-shoes": "shoes",
  wellies: "shoes",
  "school-shoes": "shoes",
  // Kids
  "baby-clothes": "kidsFashion",
  "baby-shoes": "shoes",
  tops: "kidsFashion",
  bottoms: "kidsFashion",
  outerwear: "kidsFashion",
  "school-uniform": "kidsFashion",
  // Electronics
  smartphones: "phone",
  "feature-phones": "phone",
  tablets: "electronics",
  laptops: "laptop",
  desktops: "laptop",
  "computer-components": "electronics",
  "storage-drives": "electronics",
  televisions: "electronics",
  headphones: "electronics",
  earbuds: "electronics",
  speakers: "electronics",
  "digital-cameras": "electronics",
  "action-cameras": "electronics",
  smartwatches: "electronics",
  "fitness-trackers": "electronics",
  consoles: "electronics",
  "video-games": "generic",
  // Home
  pillows: "pillow",
  duvets: "homeSoft",
  "duvet-covers": "homeSoft",
  sheets: "homeSoft",
  pillowcases: "homeSoft",
  "blankets-and-throws": "homeSoft",
  curtains: "homeSoft",
  blinds: "homeSoft",
  cushions: "homeSoft",
  rugs: "homeSoft",
  towels: "homeSoft",
  "sofas-and-armchairs": "homeHard",
  "beds-and-mattresses": "homeHard",
  tables: "homeHard",
  chairs: "homeHard",
  wardrobes: "homeHard",
  cookware: "homeHard",
  // Jewellery
  rings: "jewellerySized",
  necklaces: "jewellery",
  earrings: "jewellery",
  bracelets: "jewellery",
  watches: "jewellery",
  "automatic-watches": "jewellery",
  "quartz-watches": "jewellery",
  // Vehicle Parts & Accessories (own root — Law XXX)
  "engine-parts": "vehicleParts",
  brakes: "vehicleParts",
  suspension: "vehicleParts",
  "body-panels": "vehicleParts",
  "interior-trim": "vehicleParts",
  lighting: "vehicleParts",
  "electrical-parts": "vehicleParts",
  exhaust: "vehicleParts",
  cooling: "vehicleParts",
  filters: "vehicleParts",
  "transmission-parts": "vehicleParts",
  "motorcycle-engine-parts": "vehicleParts",
  "motorcycle-brakes": "vehicleParts",
  "motorcycle-bodywork": "vehicleParts",
  "motorcycle-lighting": "vehicleParts",
  "motorcycle-exhaust": "vehicleParts",
  "motorcycle-electrical": "vehicleParts",
  frames: "vehicleParts",
  wheels: "vehicleParts",
  drivetrain: "vehicleParts",
  "handlebars-and-stems": "vehicleParts",
  saddles: "vehicleParts",
  pedals: "vehicleParts",
  "floor-mats": "vehicleParts",
  "seat-covers": "vehicleParts",
  "phone-mounts": "vehicleParts",
  "roof-bars": "vehicleParts",
  "cargo-nets": "vehicleParts",
  "dash-cams": "vehicleParts",
  "jump-starters": "vehicleParts",
  "cleaning-kits": "vehicleParts",
  "polishes-and-waxes": "vehicleParts",
  "interior-cleaners": "vehicleParts",
  "wheel-cleaners": "vehicleParts",
  "air-fresheners": "vehicleParts",
  "diagnostic-tools": "vehicleParts",
  "jacks-and-stands": "vehicleParts",
  "torque-wrenches": "vehicleParts",
  "socket-sets": "vehicleParts",
  "car-tyres": "vehicleParts",
  "motorcycle-tyres": "vehicleParts",
  "bicycle-tyres": "vehicleParts",
  "alloy-wheels": "vehicleParts",
  "steel-wheels": "vehicleParts",
  "wheel-nuts-and-bolts": "vehicleParts",
  // Toys / books / sports
  "action-figures": "toy",
  dolls: "toy",
  "building-sets": "toy",
  "board-games": "toy",
  puzzles: "toy",
  "soft-toys": "toy",
  fiction: "book",
  "non-fiction": "book",
  "childrens-books": "book",
  textbooks: "book",
  football: "sports",
  cycling: "sports",
  running: "sports",
  camping: "sports",
  fishing: "sports",
  tennis: "sports",
  "sports-shoes": "shoes",
  "sports-tops": "sports",
  "sports-bottoms": "sports",
  makeup: "beauty",
  skincare: "beauty",
  fragrance: "beauty",
};

export function getAttrPresetForProductTypeSlug(slug: string): string {
  return CATALOG_PRODUCT_TYPE_ATTR_PRESET[slug] ?? "generic";
}
