/**
 * ROVEXO Catalog Master — Category → Subcategory → Product Type tree.
 * Absolute Law XXX — ten courier-safe roots. Vehicle Parts is its own root.
 * Hierarchy depth locked at 3 (no extra levels).
 * UK Catalog Master v1.0 — complete legal marketplace taxonomy (content expansion).
 */

import type { SectorDef } from "@/lib/categories/enterprise/builder";
import { slugify } from "@/lib/categories/enterprise/builder";

type Item = readonly [name: string, slug: string];

function items(...names: string[]): Item[] {
  const seen = new Set<string>();
  const out: Item[] = [];
  for (const name of names) {
    const slug = slugify(name);
    if (seen.has(slug)) continue;
    seen.add(slug);
    out.push([name, slug] as const);
  }
  return out;
}

/**
 * Catalog Master sectors — ONLY SSOT for marketplace category tree.
 * Forbidden forever as roots: whole vehicles, property, business, jobs, services, live animals.
 * Vehicle Parts & Accessories = own root (never under Electronics).
 */
export const CATALOG_SECTORS: SectorDef[] = [
  {
    id: "cat-womens-fashion",
    name: "Women's Fashion",
    slug: "womens-fashion",
    sortOrder: 1,
    departments: [
      {
        name: "Clothing",
        slug: "clothing",
        items: items(
          "Dresses",
          "Maxi Dresses",
          "Mini Dresses",
          "Midi Dresses",
          "Tops & Blouses",
          "T-shirts",
          "Crop Tops",
          "Vests & Camisoles",
          "Jumpers & Cardigans",
          "Hoodies & Sweatshirts",
          "Jeans",
          "Trousers",
          "Leggings",
          "Joggers",
          "Skirts",
          "Shorts",
          "Jumpsuits & Playsuits",
          "Bodysuits",
          "Coats",
          "Blazers",
          "Suits & Tailoring",
          "Activewear",
          "Swimwear",
          "Lingerie",
          "Nightwear",
          "Socks & Tights",
          "Maternity Clothing",
          "Plus Size Clothing",
          "Petite Clothing",
        ),
      },
      {
        name: "Jackets",
        slug: "jackets",
        items: items(
          "Leather Jackets",
          "Denim Jackets",
          "Bomber Jackets",
          "Puffer Jackets",
          "Rain Jackets",
          "Winter Jackets",
          "Softshell Jackets",
          "Blazer Jackets",
          "Utility Jackets",
          "Parkas",
          "Trench Coats",
          "Cape Jackets",
          "Fleece Jackets",
          "Quilted Jackets",
          "Shacket Jackets",
        ),
      },
      {
        name: "Shoes",
        slug: "shoes",
        items: items(
          "Trainers",
          "Boots",
          "Heels",
          "Flats",
          "Sandals",
          "Slippers",
          "Formal Shoes",
          "Ankle Boots",
          "Wellington Boots",
          "Knee-High Boots",
          "Platform Shoes",
          "Espadrilles",
          "Mules",
          "Loafers",
          "Ballet Flats",
          "Court Shoes",
          "Hiking Boots",
          "Wedges",
        ),
      },
      {
        name: "Bags",
        slug: "bags",
        items: items(
          "Handbags",
          "Shoulder Bags",
          "Crossbody Bags",
          "Tote Bags",
          "Clutches",
          "Backpacks",
          "Travel Bags",
          "Laptop Bags",
          "Belt Bags",
          "Bucket Bags",
          "Satchels",
          "Shopper Bags",
          "Evening Bags",
          "Wash Bags",
          "Makeup Bags",
        ),
      },
      {
        name: "Accessories",
        slug: "accessories",
        items: items(
          "Belts",
          "Scarves",
          "Hats",
          "Gloves",
          "Sunglasses",
          "Hair Accessories",
          "Wallets & Purses",
          "Jewellery Accessories",
          "Watches",
          "Umbrellas",
          "Keyrings",
          "Brooches & Pins",
          "Hair Bands",
          "Hair Clips",
        ),
      },
      {
        name: "Beauty",
        slug: "beauty",
        items: items(
          "Makeup",
          "Foundation & Concealer",
          "Lipstick & Lip Care",
          "Eye Makeup",
          "Skincare",
          "Moisturisers",
          "Serums",
          "Cleansers",
          "Haircare",
          "Hair Styling",
          "Fragrance",
          "Nail Care",
          "Nail Polish",
          "Beauty Tools",
          "Bath & Body",
          "Menopause & Wellness",
          "Sun Care",
          "Makeup Removers",
          "Face Masks",
        ),
      },
    ],
  },
  {
    id: "cat-mens-fashion",
    name: "Men's Fashion",
    slug: "mens-fashion",
    sortOrder: 2,
    departments: [
      {
        name: "Clothing",
        slug: "clothing",
        items: items(
          "T-shirts",
          "Shirts",
          "Polo Shirts",
          "Jumpers & Cardigans",
          "Hoodies & Sweatshirts",
          "Jeans",
          "Trousers",
          "Shorts",
          "Coats",
          "Blazers",
          "Suits",
          "Activewear",
          "Swimwear",
          "Underwear",
          "Nightwear",
          "Socks",
          "Tracksuits",
          "Chinos",
          "Joggers",
          "Waistcoats",
          "Formal Shirts",
          "Casual Shirts",
          "Vests",
          "Plus Size Menswear",
        ),
      },
      {
        name: "Jackets",
        slug: "jackets",
        items: items(
          "Leather Jackets",
          "Denim Jackets",
          "Bomber Jackets",
          "Puffer Jackets",
          "Rain Jackets",
          "Winter Jackets",
          "Softshell Jackets",
          "Harrington Jackets",
          "Overshirts",
          "Parkas",
          "Trench Coats",
          "Fleece Jackets",
          "Blouson Jackets",
          "Quilted Jackets",
          "Field Jackets",
        ),
      },
      {
        name: "Shoes",
        slug: "shoes",
        items: items(
          "Trainers",
          "Boots",
          "Formal Shoes",
          "Casual Shoes",
          "Sandals",
          "Slippers",
          "Football Boots",
          "Hiking Boots",
          "Chelsea Boots",
          "Desert Boots",
          "Loafers",
          "Brogues",
          "Derby Shoes",
          "Espadrilles",
          "Boat Shoes",
          "Work Boots",
        ),
      },
      {
        name: "Accessories",
        slug: "accessories",
        items: items(
          "Belts",
          "Hats",
          "Scarves",
          "Gloves",
          "Sunglasses",
          "Ties & Bow Ties",
          "Wallets",
          "Bags & Backpacks",
          "Watches",
          "Cufflinks",
          "Umbrellas",
          "Suspenders",
          "Pocket Squares",
          "Keyrings",
        ),
      },
      {
        name: "Grooming",
        slug: "grooming",
        items: items(
          "Skincare",
          "Haircare",
          "Fragrance",
          "Shaving",
          "Grooming Tools",
          "Beard Care",
          "Hair Styling Mens",
          "Body Care",
          "Nail Care Mens",
          "Dental Care",
        ),
      },
    ],
  },
  {
    id: "cat-jewellery",
    name: "Designer",
    slug: "jewellery",
    sortOrder: 3,
    departments: [
      {
        name: "Jewellery",
        slug: "fine-jewellery",
        items: items(
          "Rings",
          "Necklaces",
          "Earrings",
          "Bracelets",
          "Watches",
          "Brooches",
          "Jewellery Sets",
          "Pendants",
          "Cufflinks",
          "Anklets",
          "Charms",
          "Body Jewellery",
          "Engagement Rings",
          "Wedding Bands",
          "Hoop Earrings",
          "Stud Earrings",
          "Tennis Bracelets",
          "Lockets",
        ),
      },
      {
        name: "Designer Fashion",
        slug: "designer-fashion",
        items: items(
          "Designer Clothing",
          "Designer Shoes",
          "Designer Bags",
          "Designer Accessories",
          "Designer Jackets",
          "Designer Dresses",
          "Designer Trainers",
          "Designer Belts",
          "Designer Scarves",
          "Designer Sunglasses",
          "Designer Coats",
          "Designer Jewellery",
        ),
      },
      {
        name: "Luxury Watches",
        slug: "luxury-watches",
        items: items(
          "Automatic Watches",
          "Quartz Watches",
          "Smart Luxury Watches",
          "Watch Accessories",
          "Dive Watches",
          "Dress Watches",
          "Chronograph Watches",
          "Watch Straps",
          "Pilot Watches",
          "Field Watches",
          "Skeleton Watches",
        ),
      },
    ],
  },
  {
    id: "cat-kids-fashion",
    name: "Kids & Baby",
    slug: "kids-fashion",
    sortOrder: 4,
    departments: [
      {
        name: "Baby",
        slug: "baby",
        items: items(
          "Baby Clothes",
          "Baby Shoes",
          "Baby Accessories",
          "Nursery",
          "Feeding",
          "Pushchairs & Travel",
          "Baby Safety",
          "Baby Monitors",
          "Bottles & Sterilisers",
          "Bibs & Muslins",
          "Nappy Bags",
          "Changing Mats",
          "Baby Carriers",
          "High Chairs",
          "Baby Bathing",
          "Teethers",
          "Maternity & Nursing",
          "Cot Bedding",
          "Pram Accessories",
        ),
      },
      {
        name: "Girls Clothing",
        slug: "girls-clothing",
        items: items(
          "Dresses",
          "Girls Tops",
          "Girls Bottoms",
          "Girls Outerwear",
          "Girls Jackets",
          "Girls Activewear",
          "Girls Swimwear",
          "Girls School Uniform",
          "Girls Sleepwear",
          "Skirts Girls",
          "Leggings Girls",
          "Jeans Girls",
          "Hoodies Girls",
          "Party Wear Girls",
        ),
      },
      {
        name: "Boys Clothing",
        slug: "boys-clothing",
        items: items(
          "Boys Tops",
          "Boys Bottoms",
          "Boys Outerwear",
          "Boys Jackets",
          "Boys Activewear",
          "Boys Swimwear",
          "Boys School Uniform",
          "Boys Sleepwear",
          "Jeans Boys",
          "Hoodies Boys",
          "Shorts Boys",
          "Shirts Boys",
          "Party Wear Boys",
        ),
      },
      {
        name: "Kids Shoes",
        slug: "kids-shoes",
        items: items(
          "Trainers",
          "Boots",
          "Sandals",
          "School Shoes",
          "Wellies",
          "Slippers Kids",
          "Football Boots Kids",
          "Ballet Shoes",
          "Hiking Boots Kids",
        ),
      },
      {
        name: "Toys & Games",
        slug: "toys-games",
        items: items(
          "Action Figures",
          "Dolls",
          "Building Sets",
          "Educational Toys",
          "Outdoor Toys",
          "Board Games",
          "Puzzles",
          "Soft Toys",
          "Remote Control",
          "Cars & Vehicles Toys",
          "Role Play",
          "Arts & Crafts Kids",
          "Musical Toys",
          "STEM Toys",
          "Baby Sensory Toys",
          "LEGO & Construction",
        ),
      },
    ],
  },
  {
    id: "cat-home-garden",
    name: "Home & Garden",
    slug: "home-garden",
    sortOrder: 5,
    departments: [
      {
        name: "Furniture",
        slug: "furniture",
        items: items(
          "Sofas & Armchairs",
          "Beds & Mattresses",
          "Tables",
          "Chairs",
          "Wardrobes",
          "Chests of Drawers",
          "Shelving",
          "Desks",
          "TV Stands",
          "Outdoor Furniture",
          "Dining Tables",
          "Dining Chairs",
          "Coffee Tables",
          "Side Tables",
          "Bookcases",
          "Sideboards",
          "Ottomans & Footstools",
          "Bedside Tables",
          "Dressing Tables",
        ),
      },
      {
        name: "Storage",
        slug: "storage",
        items: items(
          "Storage Boxes",
          "Storage Baskets",
          "Underbed Storage",
          "Shoe Storage",
          "Coat Racks",
          "Hooks & Rails",
          "Cube Storage",
          "Laundry Baskets",
          "Vacuum Storage Bags",
          "Garage Storage",
          "Kitchen Storage Furniture",
        ),
      },
      {
        name: "Lighting",
        slug: "lighting-home",
        items: items(
          "Ceiling Lights",
          "Table Lamps",
          "Floor Lamps",
          "Wall Lights",
          "Pendant Lights",
          "Desk Lamps",
          "Fairy Lights",
          "Night Lights",
          "Lampshades",
          "Light Bulbs",
          "Outdoor Wall Lights",
        ),
      },
      {
        name: "Kitchen",
        slug: "kitchen",
        items: items(
          "Cookware",
          "Bakeware",
          "Tableware",
          "Cutlery",
          "Kitchen Storage",
          "Small Kitchen Appliances",
          "Kitchen Utensils",
          "Knives & Boards",
          "Pots & Pans",
          "Baking Trays",
          "Food Containers",
          "Water Bottles Home",
          "Flasks",
          "Coffee & Tea Accessories",
        ),
      },
      {
        name: "Dining",
        slug: "dining",
        items: items(
          "Dinner Sets",
          "Plates & Bowls",
          "Glasses & Drinkware",
          "Serving Dishes",
          "Placemats",
          "Coasters",
          "Napkins & Rings",
          "Table Runners",
          "Trays",
          "Carafes & Jugs",
        ),
      },
      {
        name: "Bathroom",
        slug: "bathroom",
        items: items(
          "Bath Mats",
          "Bathroom Storage",
          "Shower Accessories",
          "Bathroom Mirrors",
          "Towel Rails",
          "Soap Dishes",
          "Bathroom Sets",
          "Shower Curtains",
          "Bathroom Scales",
          "Toilet Accessories",
          "Bathroom Bins",
        ),
      },
      {
        name: "Bedroom",
        slug: "bedroom",
        items: items(
          "Bed Frames",
          "Mattresses",
          "Mattress Toppers",
          "Headboards",
          "Bedroom Storage",
          "Wardrobe Organisers",
          "Clothes Hangers",
          "Jewellery Boxes",
          "Alarm Clocks",
        ),
      },
      {
        name: "Bedding",
        slug: "bedding",
        items: items(
          "Duvets",
          "Duvet Covers",
          "Sheets",
          "Pillowcases",
          "Pillows",
          "Blankets & Throws",
          "Mattress Protectors",
          "Fitted Sheets",
          "Flat Sheets",
          "Bedspreads",
          "Electric Blankets",
        ),
      },
      {
        name: "Pillows & Cushions",
        slug: "pillows-cushions",
        items: items(
          "Memory Foam Pillows",
          "Orthopedic Pillows",
          "Travel Pillows",
          "Neck Pillows",
          "Pregnancy Pillows",
          "Maternity Pillows",
          "Body Pillows",
          "Cooling Pillows",
          "Feather Pillows",
          "Down Pillows",
          "Children's Pillows",
          "Decorative Cushions",
          "Seat Cushions",
          "Lumbar Cushions",
          "Floor Cushions",
          "Outdoor Cushions",
        ),
      },
      {
        name: "Home Textiles",
        slug: "home-textiles",
        items: items(
          "Curtains",
          "Blinds",
          "Cushions",
          "Rugs",
          "Towels",
          "Table Linen",
          "Throws",
          "Bean Bags",
          "Door Mats",
          "Bathroom Towels",
          "Tea Towels",
        ),
      },
      {
        name: "Rugs",
        slug: "rugs",
        items: items(
          "Area Rugs",
          "Runner Rugs",
          "Doormats",
          "Bathroom Rugs",
          "Outdoor Rugs",
          "Kids Rugs",
          "Rug Pads",
          "Hallway Runners",
        ),
      },
      {
        name: "Curtains & Blinds",
        slug: "curtains-blinds",
        items: items(
          "Eyelet Curtains",
          "Pencil Pleat Curtains",
          "Voile Curtains",
          "Blackout Curtains",
          "Roman Blinds",
          "Roller Blinds",
          "Venetian Blinds",
          "Vertical Blinds",
          "Curtain Poles",
          "Curtain Ties",
        ),
      },
      {
        name: "Decor",
        slug: "decor",
        items: items(
          "Vases",
          "Ornaments",
          "Photo Frames",
          "Clocks Home",
          "Candles",
          "Candle Holders",
          "Diffusers",
          "Artificial Plants",
          "Decorative Bowls",
          "Bookends",
          "Trays Decor",
        ),
      },
      {
        name: "Wall Art",
        slug: "wall-art",
        items: items(
          "Canvas Prints",
          "Framed Prints",
          "Posters",
          "Wall Stickers",
          "Metal Wall Art",
          "Tapestries",
          "Photo Walls",
          "Maps & Charts",
        ),
      },
      {
        name: "Mirrors",
        slug: "mirrors",
        items: items(
          "Wall Mirrors",
          "Full Length Mirrors",
          "Vanity Mirrors",
          "Round Mirrors",
          "Decorative Mirrors",
          "Bathroom Mirrors Decor",
        ),
      },
      {
        name: "Office",
        slug: "office-home",
        items: items(
          "Office Chairs",
          "Office Desks",
          "Filing Cabinets",
          "Desk Organisers",
          "Stationery",
          "Notebooks & Pads",
          "Pens & Pencils",
          "Printer Paper",
          "Whiteboards",
          "Office Storage",
          "Monitor Stands",
        ),
      },
      {
        name: "Cleaning",
        slug: "cleaning",
        items: items(
          "Cleaning Tools",
          "Mops & Buckets",
          "Brooms & Dustpans",
          "Cleaning Cloths",
          "Sponges & Scourers",
          "Bins & Recycling",
          "Dustbins",
          "Cleaning Caddies",
        ),
      },
      {
        name: "Laundry",
        slug: "laundry",
        items: items(
          "Clothes Airers",
          "Ironing Boards",
          "Laundry Baskets Home",
          "Pegs & Lines",
          "Laundry Bags",
          "Clothes Pegs",
          "Ironing Accessories",
        ),
      },
      {
        name: "Garden",
        slug: "garden",
        items: items(
          "Garden Furniture",
          "Garden Chairs",
          "Garden Tables",
          "Garden Benches",
          "Parasols",
          "BBQ",
          "Fire Pits",
          "Garden Tools",
          "Plant Pots",
          "Planters",
          "Watering Equipment",
          "Lawn Care",
          "Outdoor Lighting",
          "Garden Storage",
          "Greenhouses",
          "Garden Decorations",
          "Garden Hose",
          "Compost Bins",
          "Seeds & Bulbs",
          "Garden Kneelers",
          "Wheelbarrows",
        ),
      },
      {
        name: "DIY & Tools",
        slug: "diy-tools",
        items: items(
          "Hand Tools",
          "Power Tools",
          "Painting & Decorating",
          "Hardware",
          "Electrical Supplies",
          "Plumbing Supplies",
          "Screwdrivers",
          "Drills",
          "Saws",
          "Measuring Tools",
          "Safety Equipment DIY",
          "Ladders & Steps",
          "Paint Brushes",
          "Wallpaper Tools",
        ),
      },
      {
        name: "Home Appliances",
        slug: "appliances",
        items: items(
          "Vacuum Cleaners",
          "Irons & Steamers",
          "Fans & Heaters",
          "Air Care",
          "Microwaves",
          "Kettles",
          "Toasters",
          "Coffee Machines",
          "Blenders & Mixers",
          "Air Fryers",
          "Slow Cookers",
          "Dehumidifiers",
        ),
      },
      {
        name: "Pet Supplies",
        slug: "pet-supplies",
        items: items(
          "Dog Supplies",
          "Cat Supplies",
          "Small Pet Supplies",
          "Pet Toys",
          "Pet Beds",
          "Pet Carriers",
          "Dog Leads & Collars",
          "Cat Litter Accessories",
          "Pet Bowls",
          "Pet Clothing",
          "Aquarium Accessories",
          "Bird Supplies",
          "Pet Grooming",
        ),
      },
      {
        name: "Health & Wellness",
        slug: "health-wellness",
        items: items(
          "First Aid",
          "Mobility Aids",
          "Massage Tools",
          "Hot Water Bottles",
          "Thermometers",
          "Scales Health",
          "Supports & Braces",
          "Eye Care Accessories",
          "Hearing Accessories",
        ),
      },
    ],
  },
  {
    id: "cat-electronics",
    name: "Electronics",
    slug: "electronics",
    sortOrder: 6,
    departments: [
      {
        name: "Phones & Tablets",
        slug: "phones-tablets",
        items: items(
          "Android Phones",
          "iPhones",
          "Feature Phones",
          "Tablets",
          "Phone Cases",
          "Chargers & Cables",
          "Screen Protectors",
          "Power Banks",
          "Phone Accessories",
          "Phone Parts",
          "iPads",
          "Android Tablets",
          "E-Readers",
          "SIM-Free Phones",
          "Phone Holders",
          "Wireless Chargers",
        ),
      },
      {
        name: "Computers",
        slug: "computers",
        items: items(
          "Laptops",
          "Desktops",
          "Monitors",
          "Keyboards",
          "Mice",
          "Webcams",
          "Printers",
          "Computer Components",
          "Storage Drives",
          "Docking Stations",
          "Laptop Bags & Sleeves",
          "Graphics Cards",
          "RAM Memory",
          "Motherboards",
          "CPU Processors",
          "PC Cases",
          "Power Supplies",
          "Cooling Fans",
          "USB Hubs",
          "External Hard Drives",
        ),
      },
      {
        name: "TV & Audio",
        slug: "tv-audio",
        items: items(
          "Televisions",
          "Soundbars",
          "Headphones",
          "Earbuds",
          "Speakers",
          "Streaming Devices",
          "Home Cinema",
          "Radios",
          "Turntables",
          "Projectors",
          "TV Mounts",
          "Remote Controls",
          "AV Receivers",
          "Microphones Audio",
          "Bluetooth Speakers",
        ),
      },
      {
        name: "Cameras",
        slug: "cameras",
        items: items(
          "Digital Cameras",
          "Action Cameras",
          "Lenses",
          "Camera Accessories",
          "Tripods",
          "Camera Bags",
          "Drones Cameras",
          "Mirrorless Cameras",
          "DSLR Cameras",
          "Instant Cameras",
          "Camera Flashes",
          "Memory Cards",
          "Gimbals",
        ),
      },
      {
        name: "Wearables",
        slug: "wearables",
        items: items(
          "Smartwatches",
          "Fitness Trackers",
          "VR Headsets",
          "Smart Rings",
          "Smart Bands",
          "Wearable Accessories",
        ),
      },
      {
        name: "Smart Home",
        slug: "smart-home",
        items: items(
          "Smart Speakers",
          "Smart Lighting",
          "Security Cameras",
          "Smart Plugs",
          "Thermostats",
          "Doorbells",
          "Smart Locks",
          "Smart Displays",
          "Robot Vacuums",
          "Smart Sensors",
        ),
      },
      {
        name: "Gaming",
        slug: "gaming",
        items: items(
          "Consoles",
          "Video Games",
          "Controllers",
          "Gaming Headsets",
          "Gaming Chairs",
          "PC Gaming Accessories",
          "Gaming Keyboards",
          "Gaming Mice",
          "PlayStation Consoles",
          "Xbox Consoles",
          "Nintendo Consoles",
          "Gaming Monitors",
          "Capture Cards",
          "VR Gaming",
          "Gaming Merchandise",
        ),
      },
    ],
  },
  {
    id: "cat-books",
    name: "Books & Media",
    slug: "books",
    sortOrder: 7,
    departments: [
      {
        name: "Books",
        slug: "books",
        items: items(
          "Fiction",
          "Non-Fiction",
          "Children's Books",
          "Textbooks",
          "Comics & Graphic Novels",
          "Magazines",
          "Biography & Memoir",
          "Crime & Thriller",
          "Romance",
          "Sci-Fi & Fantasy",
          "Cookbooks",
          "Travel Guides",
          "Audiobooks",
          "History Books",
          "Self-Help",
          "Business Books",
          "Art Books",
          "Poetry",
        ),
      },
      {
        name: "Music",
        slug: "music",
        items: items(
          "Vinyl",
          "CDs",
          "Cassettes",
          "Music Memorabilia",
          "Sheet Music",
          "Music Books",
          "Box Set Albums",
          "Singles",
        ),
      },
      {
        name: "Film & TV",
        slug: "film-tv",
        items: items(
          "DVDs",
          "Blu-ray",
          "Box Sets",
          "Film Memorabilia",
          "4K Ultra HD",
          "TV Series",
          "Documentaries",
          "Anime Media",
        ),
      },
      {
        name: "Instruments",
        slug: "instruments",
        items: items(
          "Guitars",
          "Keyboards & Pianos",
          "Drums & Percussion",
          "Wind Instruments",
          "String Instruments",
          "Instrument Accessories",
          "DJ Equipment",
          "Amplifiers",
          "Microphones",
          "Ukuleles",
          "Bass Guitars",
          "Electric Guitars",
          "Acoustic Guitars",
          "Synthesizers",
          "Pedals & Effects",
        ),
      },
    ],
  },
  {
    id: "cat-collectibles",
    name: "Hobbies & Collectables",
    slug: "collectibles",
    sortOrder: 8,
    departments: [
      {
        name: "Collectables",
        slug: "collectables",
        items: items(
          "Trading Cards",
          "Figurines",
          "Model Kits",
          "Coins & Banknotes",
          "Stamps",
          "Memorabilia",
          "Vintage Collectables",
          "Sports Memorabilia",
          "Autographs",
          "Pin Badges",
          "Keyrings & Charms",
          "Pokémon Cards",
          "Football Cards",
          "Diecast Models",
          "Vinyl Figures",
          "Limited Editions",
        ),
      },
      {
        name: "Arts & Crafts",
        slug: "arts-crafts",
        items: items(
          "Art Supplies",
          "Craft Kits",
          "Sewing & Fabric",
          "Scrapbooking",
          "Handmade Items",
          "Knitting & Crochet",
          "Painting & Drawing",
          "Jewellery Making",
          "Embroidery",
          "Paper Craft",
          "Resin Craft",
          "Clay & Modelling",
          "Yarn & Wool",
        ),
      },
      {
        name: "Antiques",
        slug: "antiques",
        items: items(
          "Antique Furniture",
          "China & Ceramics",
          "Silverware",
          "Clocks",
          "Decorative Antiques",
          "Vintage Glass",
          "Militaria",
          "Vintage Toys",
          "Antique Jewellery",
          "Vintage Clothing Collectables",
        ),
      },
      {
        name: "Hobby Electronics",
        slug: "hobby-electronics",
        items: items(
          "Drones",
          "RC Vehicles",
          "Maker Kits",
          "3D Printing",
          "Arduino & Raspberry Pi",
          "Robotics Kits",
          "Soldering Tools",
          "Electronic Components",
        ),
      },
    ],
  },
  {
    id: "cat-sports",
    name: "Sports & Outdoors",
    slug: "sports",
    sortOrder: 9,
    departments: [
      {
        name: "Fitness",
        slug: "fitness",
        items: items(
          "Gym Equipment",
          "Yoga & Pilates",
          "Weights",
          "Fitness Trackers Accessories",
          "Sports Nutrition Accessories",
          "Dumbbells",
          "Kettlebells",
          "Resistance Bands",
          "Exercise Mats",
          "Yoga Mats",
          "Skipping Ropes",
          "Foam Rollers",
          "Home Gym Machines",
          "Pull-Up Bars",
          "Ab Rollers",
        ),
      },
      {
        name: "Team Sports",
        slug: "team-sports",
        items: items(
          "Football",
          "Rugby",
          "Basketball",
          "Cricket",
          "Hockey",
          "Netball",
          "Football Boots Kit",
          "Shin Pads",
          "Goalkeeper Gloves",
          "Footballs",
          "Training Bibs",
          "Team Kits",
          "Cricket Bats",
          "Basketballs",
        ),
      },
      {
        name: "Football",
        slug: "football-equipment",
        items: items(
          "Match Footballs",
          "Training Footballs",
          "Goal Nets",
          "Football Gloves",
          "Football Bags",
          "Captain Armbands",
          "Football Cones",
          "Water Bottles Sports",
        ),
      },
      {
        name: "Outdoor Sports",
        slug: "outdoor-sports",
        items: items(
          "Cycling",
          "Running",
          "Hiking",
          "Fishing",
          "Water Sports",
          "Winter Sports",
          "Climbing",
          "Skateboarding",
          "Scooters",
          "Golf",
          "Equestrian",
          "Boxing & Martial Arts",
          "Darts",
          "Boules & Petanque",
        ),
      },
      {
        name: "Cycling",
        slug: "cycling-equipment",
        items: items(
          "Road Bike Parts",
          "Mountain Bike Parts",
          "Bike Helmets",
          "Bike Lights",
          "Bike Locks",
          "Cycle Clothing",
          "Bike Pumps",
          "Bike Computers",
          "Bike Bags",
          "Mudguards",
          "Bike Bottles",
          "Cycling Gloves",
          "Bike Tools",
        ),
      },
      {
        name: "Running",
        slug: "running-equipment",
        items: items(
          "Running Shoes Gear",
          "Running Apparel",
          "Running Watches Gear",
          "Hydration Packs",
          "Running Belts",
          "Reflective Gear",
          "Running Socks Gear",
          "Race Bibs Accessories",
        ),
      },
      {
        name: "Fishing",
        slug: "fishing-equipment",
        items: items(
          "Fishing Rods",
          "Fishing Reels",
          "Fishing Tackle",
          "Fishing Lines",
          "Fishing Nets",
          "Keepnets",
          "Fishing Seats",
          "Bait Boxes",
          "Fishing Clothing",
          "Landing Nets",
        ),
      },
      {
        name: "Outdoor & Camping",
        slug: "camping",
        items: items(
          "Sleeping Bags",
          "Tents",
          "Camping Tents",
          "Camping Furniture",
          "Camping Cooking",
          "Camping Lighting",
          "Camping Accessories",
          "Cool Boxes",
          "Backpacks",
          "Sleeping Mats",
          "Survival",
          "Camping Stoves",
          "Water Carriers",
          "Camping Tables",
          "Camping Chairs",
          "Tarps & Shelters",
          "Hammocks",
          "Air Beds",
          "Camping Mattresses",
          "Gas Cookers",
          "Lanterns",
          "Torches",
          "Picnic Equipment",
          "Camping Storage",
          "Water Containers",
          "Camping Cookware",
        ),
      },
      {
        name: "Racket Sports",
        slug: "racket-sports",
        items: items(
          "Tennis",
          "Badminton",
          "Squash",
          "Table Tennis",
          "Padel",
          "Tennis Rackets",
          "Badminton Rackets",
          "Shuttlecocks",
          "Table Tennis Bats",
          "Tennis Balls",
        ),
      },
      {
        name: "Sportswear",
        slug: "sportswear",
        items: items(
          "Sports Tops",
          "Sports Bottoms",
          "Sports Jackets",
          "Sports Shoes",
          "Sports Bags",
          "Helmets",
          "Gloves",
          "Sports Socks",
          "Base Layers",
          "Compression Wear",
          "Sports Caps",
          "Gilets Sports",
        ),
      },
    ],
  },
  {
    id: "cat-vehicle-parts",
    name: "Vehicle Parts & Accessories",
    slug: "vehicle-parts",
    sortOrder: 10,
    departments: [
      {
        name: "Car Parts",
        slug: "car-parts",
        items: items(
          "Engine Parts",
          "Car Brakes",
          "Suspension",
          "Body Panels",
          "Interior Trim",
          "Lighting",
          "Electrical Parts",
          "Exhaust",
          "Cooling",
          "Filters",
          "Transmission Parts",
          "Spark Plugs",
          "Batteries Car",
          "Alternators",
          "Starters",
          "Radiators",
          "Clutches",
          "Windscreen Wipers",
        ),
      },
      {
        name: "Motorcycle Parts",
        slug: "motorcycle-parts",
        items: items(
          "Motorcycle Engine Parts",
          "Motorcycle Brakes",
          "Motorcycle Bodywork",
          "Motorcycle Lighting",
          "Motorcycle Exhaust",
          "Motorcycle Electrical",
          "Motorcycle Helmets Parts",
          "Motorcycle Mirrors",
          "Motorcycle Chains",
        ),
      },
      {
        name: "Bicycle Parts",
        slug: "bicycle-parts",
        items: items(
          "Frames",
          "Wheels",
          "Drivetrain",
          "Bicycle Brakes",
          "Handlebars & Stems",
          "Saddles",
          "Pedals",
          "Bike Chains",
          "Bike Cassettes",
          "Bike Derailleurs",
          "Bike Forks",
        ),
      },
      {
        name: "Vehicle Accessories",
        slug: "vehicle-accessories",
        items: items(
          "Floor Mats",
          "Seat Covers",
          "Phone Mounts",
          "Roof Bars",
          "Cargo Nets",
          "Dash Cams",
          "Jump Starters",
          "Roof Boxes",
          "Tow Bars Accessories",
          "Child Car Seats Accessories",
          "Boot Liners",
          "Steering Wheel Covers",
        ),
      },
      {
        name: "Car Care",
        slug: "car-care",
        items: items(
          "Cleaning Kits",
          "Polishes & Waxes",
          "Interior Cleaners",
          "Wheel Cleaners",
          "Air Fresheners",
          "Car Shampoo",
          "Microfibre Cloths Car",
          "Glass Cleaners Car",
          "Tyre Dressings",
        ),
      },
      {
        name: "Garage Tools",
        slug: "garage-tools",
        items: items(
          "Hand Tools",
          "Diagnostic Tools",
          "Jacks & Stands",
          "Torque Wrenches",
          "Socket Sets",
          "Oil Drainers",
          "Creepers",
          "Workbench Accessories",
          "Tool Chests",
        ),
      },
      {
        name: "Tyres & Wheels",
        slug: "tyres-and-wheels",
        items: items(
          "Car Tyres",
          "Motorcycle Tyres",
          "Bicycle Tyres",
          "Alloy Wheels",
          "Steel Wheels",
          "Wheel Nuts & Bolts",
          "Tyre Pressure Gauges",
          "Wheel Spacers",
          "Centre Caps",
        ),
      },
    ],
  },
];

/** Product-type slug → attribute preset key (essential 3–6 attrs). */
export const CATALOG_PRODUCT_TYPE_ATTR_PRESET: Readonly<Record<string, string>> = {
  // Fashion / shoes
  dresses: "fashion",
  "tops-and-blouses": "fashion",
  "t-shirts": "fashion",
  "jumpers-and-cardigans": "fashion",
  "hoodies-and-sweatshirts": "fashion",
  jeans: "fashion",
  trousers: "fashion",
  skirts: "fashion",
  shorts: "fashion",
  coats: "fashion",
  "leather-jackets": "fashion",
  "denim-jackets": "fashion",
  "bomber-jackets": "fashion",
  "puffer-jackets": "fashion",
  "rain-jackets": "fashion",
  "winter-jackets": "fashion",
  blazers: "fashion",
  suits: "fashion",
  activewear: "fashion",
  swimwear: "fashion",
  lingerie: "fashion",
  nightwear: "fashion",
  "socks-and-tights": "fashion",
  underwear: "fashion",
  socks: "fashion",
  shirts: "fashion",
  "polo-shirts": "fashion",
  trainers: "shoes",
  boots: "shoes",
  heels: "shoes",
  flats: "shoes",
  sandals: "shoes",
  slippers: "shoes",
  "formal-shoes": "shoes",
  "casual-shoes": "shoes",
  wellies: "shoes",
  "school-shoes": "shoes",
  "baby-clothes": "kidsFashion",
  "baby-shoes": "shoes",
  tops: "kidsFashion",
  bottoms: "kidsFashion",
  outerwear: "kidsFashion",
  "school-uniform": "kidsFashion",
  "girls-tops": "kidsFashion",
  "girls-bottoms": "kidsFashion",
  "girls-outerwear": "kidsFashion",
  "girls-jackets": "kidsFashion",
  "girls-activewear": "kidsFashion",
  "girls-swimwear": "kidsFashion",
  "girls-school-uniform": "kidsFashion",
  "girls-sleepwear": "kidsFashion",
  "boys-tops": "kidsFashion",
  "boys-bottoms": "kidsFashion",
  "boys-outerwear": "kidsFashion",
  "boys-jackets": "kidsFashion",
  "boys-activewear": "kidsFashion",
  "boys-swimwear": "kidsFashion",
  "boys-school-uniform": "kidsFashion",
  "boys-sleepwear": "kidsFashion",
  sleepwear: "kidsFashion",
  jackets: "kidsFashion",
  smartphones: "phone",
  "android-phones": "phone",
  iphones: "phone",
  "feature-phones": "phone",
  tablets: "electronics",
  "phone-cases": "generic",
  "chargers-and-cables": "generic",
  "power-banks": "generic",
  "phone-accessories": "generic",
  "screen-protectors": "generic",
  laptops: "laptop",
  desktops: "laptop",
  "computer-components": "electronics",
  "storage-drives": "electronics",
  televisions: "electronics",
  headphones: "electronics",
  earbuds: "electronics",
  speakers: "electronics",
  "digital-cameras": "electronics",
  "action-cameras": "electronics",
  smartwatches: "electronics",
  "fitness-trackers": "electronics",
  consoles: "electronics",
  "video-games": "generic",
  "softshell-jackets": "fashion",
  "blazer-jackets": "fashion",
  "utility-jackets": "fashion",
  "harrington-jackets": "fashion",
  overshirts: "fashion",
  "ankle-boots": "shoes",
  "wellington-boots": "shoes",
  "football-boots": "shoes",
  "hiking-boots": "shoes",
  tracksuits: "fashion",
  chinos: "fashion",
  "laptop-bags": "generic",
  "belt-bags": "generic",
  "jewellery-accessories": "jewellery",
  "bath-and-body": "generic",
  "beard-care": "generic",
  cufflinks: "jewellery",
  pillows: "pillow",
  duvets: "homeSoft",
  "duvet-covers": "homeSoft",
  sheets: "homeSoft",
  pillowcases: "homeSoft",
  "blankets-and-throws": "homeSoft",
  curtains: "homeSoft",
  blinds: "homeSoft",
  cushions: "homeSoft",
  rugs: "homeSoft",
  towels: "homeSoft",
  "sofas-and-armchairs": "furniture",
  "beds-and-mattresses": "furniture",
  tables: "furniture",
  chairs: "furniture",
  wardrobes: "furniture",
  "chests-of-drawers": "furniture",
  shelving: "furniture",
  desks: "furniture",
  "tv-stands": "furniture",
  "outdoor-furniture": "furniture",
  "dining-tables": "furniture",
  "dining-chairs": "furniture",
  "coffee-tables": "furniture",
  "side-tables": "furniture",
  bookcases: "furniture",
  sideboards: "furniture",
  "ottomans-and-footstools": "furniture",
  "bedside-tables": "furniture",
  "dressing-tables": "furniture",
  cookware: "homeHard",
  rings: "jewellerySized",
  necklaces: "jewellery",
  earrings: "jewellery",
  bracelets: "jewellery",
  watches: "jewellery",
  "automatic-watches": "jewellery",
  "quartz-watches": "jewellery",
  "engine-parts": "vehicleParts",
  brakes: "vehicleParts",
  "car-brakes": "vehicleParts",
  "bicycle-brakes": "vehicleParts",
  suspension: "vehicleParts",
  "body-panels": "vehicleParts",
  "interior-trim": "vehicleParts",
  lighting: "vehicleParts",
  "electrical-parts": "vehicleParts",
  exhaust: "vehicleParts",
  cooling: "vehicleParts",
  filters: "vehicleParts",
  "transmission-parts": "vehicleParts",
  "motorcycle-engine-parts": "vehicleParts",
  "motorcycle-brakes": "vehicleParts",
  "motorcycle-bodywork": "vehicleParts",
  "motorcycle-lighting": "vehicleParts",
  "motorcycle-exhaust": "vehicleParts",
  "motorcycle-electrical": "vehicleParts",
  frames: "vehicleParts",
  wheels: "vehicleParts",
  drivetrain: "vehicleParts",
  "handlebars-and-stems": "vehicleParts",
  saddles: "vehicleParts",
  pedals: "vehicleParts",
  "floor-mats": "vehicleParts",
  "seat-covers": "vehicleParts",
  "phone-mounts": "vehicleParts",
  "roof-bars": "vehicleParts",
  "cargo-nets": "vehicleParts",
  "dash-cams": "vehicleParts",
  "jump-starters": "vehicleParts",
  "cleaning-kits": "vehicleParts",
  "polishes-and-waxes": "vehicleParts",
  "interior-cleaners": "vehicleParts",
  "wheel-cleaners": "vehicleParts",
  "air-fresheners": "vehicleParts",
  "diagnostic-tools": "vehicleParts",
  "jacks-and-stands": "vehicleParts",
  "torque-wrenches": "vehicleParts",
  "socket-sets": "vehicleParts",
  "car-tyres": "vehicleParts",
  "motorcycle-tyres": "vehicleParts",
  "bicycle-tyres": "vehicleParts",
  "alloy-wheels": "vehicleParts",
  "steel-wheels": "vehicleParts",
  "wheel-nuts-and-bolts": "vehicleParts",
  "action-figures": "toy",
  dolls: "toy",
  "building-sets": "toy",
  "board-games": "toy",
  puzzles: "toy",
  "soft-toys": "toy",
  fiction: "book",
  "non-fiction": "book",
  "childrens-books": "book",
  textbooks: "book",
  football: "sports",
  cycling: "sports",
  running: "sports",
  hiking: "sports",
  fishing: "sports",
  tennis: "sports",
  "water-sports": "sports",
  "winter-sports": "sports",
  "sleeping-bags": "campingSleepingBag",
  tents: "campingTent",
  "camping-furniture": "campingGear",
  "camping-cooking": "campingGear",
  "camping-lighting": "campingGear",
  "camping-accessories": "campingGear",
  "camping-stoves": "campingGear",
  "water-carriers": "campingGear",
  "cool-boxes": "campingGear",
  backpacks: "campingGear",
  "sleeping-mats": "campingGear",
  survival: "campingGear",
  "camping-lights": "campingGear",
  "sports-shoes": "shoes",
  "sports-tops": "fashion",
  "sports-bottoms": "fashion",
  "sports-jackets": "fashion",
  "sports-bags": "generic",
  gloves: "fashion",
  helmets: "fashion",
  makeup: "beauty",
  skincare: "beauty",
  fragrance: "beauty",
  "memory-foam-pillows": "pillow",
  "orthopedic-pillows": "pillow",
  "travel-pillows": "pillow",
  "neck-pillows": "pillow",
  "pregnancy-pillows": "pillow",
  "maternity-pillows": "pillow",
  "body-pillows": "pillow",
  "cooling-pillows": "pillow",
  "feather-pillows": "pillow",
  "down-pillows": "pillow",
  "childrens-pillows": "pillow",
  "decorative-cushions": "homeSoft",
  "seat-cushions": "homeSoft",
  "lumbar-cushions": "homeSoft",
  "camping-tents": "campingTent",
  "air-beds": "campingGear",
  "camping-mattresses": "campingGear",
  "gas-cookers": "campingGear",
  "lanterns": "campingGear",
  "torches": "campingGear",
  "picnic-equipment": "campingGear",
  "camping-storage": "campingGear",
  "water-containers": "campingGear",
  "camping-cookware": "campingGear",
  "camping-tables": "campingGear",
  "camping-chairs": "campingGear",
  "hammocks": "campingGear",
  "tarps-and-shelters": "campingGear",
  "bbq": "homeHard",
  "fire-pits": "homeHard",
  "garden-furniture": "furniture",
  "garden-chairs": "furniture",
  "garden-tables": "furniture",
  "garden-benches": "furniture",
  "parasols": "homeHard",
  "plant-pots": "homeHard",
  "planters": "homeHard",
  "watering-equipment": "homeHard",
  "lawn-care": "homeHard",
  "outdoor-lighting": "homeHard",
  "garden-storage": "homeHard",
  "greenhouses": "homeHard",
  "garden-decorations": "homeHard",
};

export function getAttrPresetForProductTypeSlug(slug: string): string {
  return CATALOG_PRODUCT_TYPE_ATTR_PRESET[slug] ?? "generic";
}
