export const HOMEPAGE_BUILDER_ROUTES = [
  { id: "dashboard", label: "Dashboard", href: "/super-admin/homepage-builder" },
  { id: "editor", label: "Editor", href: "/super-admin/homepage-builder/editor" },
  { id: "preview", label: "Preview", href: "/super-admin/homepage-builder/preview" },
  { id: "components", label: "Components", href: "/super-admin/homepage-builder/components" },
  { id: "history", label: "History", href: "/super-admin/homepage-builder/history" },
  { id: "schedule", label: "Schedule", href: "/super-admin/homepage-builder/schedule" },
  { id: "settings", label: "Settings", href: "/super-admin/homepage-builder/settings" },
] as const;

export const HOMEPAGE_SECTION_TYPES = [
  "hero-banner",
  "categories",
  "featured-listings",
  "recommended",
  "trending",
  "ai-picks",
  "business-spotlight",
  "flash-deals",
  "auctions",
  "recently-viewed",
  "continue-browsing",
  "brands",
  "collections",
  "new-sellers",
  "recommended-shops",
  "promotions",
  "coupons",
  "statistics",
  "newsletter",
  "footer",
  "custom-section",
  "html-block",
  "markdown-block",
  "widget",
  "ai-widget",
  "video-banner",
  "gallery",
  "announcement-bar",
  "sticky-banner",
  "floating-cta",
  "countdown",
  "reviews",
  "testimonials",
  "faq",
] as const;

export const HOMEPAGE_COMPONENT_TYPES = [
  "button",
  "card",
  "product-card",
  "auction-card",
  "seller-card",
  "business-card",
  "review-card",
  "chart",
  "statistics",
  "countdown",
  "gallery",
  "carousel",
  "video",
  "image",
  "badge",
  "form",
  "pricing",
  "faq",
  "announcement",
  "widget",
] as const;

export const HOMEPAGE_PREVIEW_MODES = [
  "desktop",
  "laptop",
  "tablet",
  "phone",
  "dark",
  "light",
  "landscape",
  "portrait",
] as const;

export const HOMEPAGE_BUILDER_API = {
  snapshot: "/api/super-admin/homepage-builder",
  publish: "/api/super-admin/homepage-builder/publish",
  rollback: "/api/super-admin/homepage-builder/rollback",
  history: "/api/super-admin/homepage-builder/history",
  preview: "/api/super-admin/homepage-builder/preview",
  duplicate: "/api/super-admin/homepage-builder/duplicate",
  clone: "/api/super-admin/homepage-builder/clone",
  validate: "/api/super-admin/homepage-builder/validate",
  export: "/api/super-admin/homepage-builder/export",
  import: "/api/super-admin/homepage-builder/import",
  schedule: "/api/super-admin/homepage-builder/schedule",
  compare: "/api/super-admin/homepage-builder/compare",
  assets: "/api/super-admin/homepage-builder/assets",
  v1Snapshot: "/api/v1/super-admin/homepage-builder",
} as const;
