/**
 * ROVEXO Production Launch Reset v1.0 — ZERO operational data.
 *
 * STATUS: OWNER-GATED · ONE-TIME PRE-LAUNCH · NO SCHEMA CHANGES
 *
 * Apply requires:
 *   --yes
 *   LAUNCH_RESET_OWNER_APPROVED=1
 *   LAUNCH_RESET_ALLOW_PRODUCTION_HOST=1 (when targeting known production Supabase)
 *
 * Default mode is dry-run (counts only).
 */

export const PRODUCTION_LAUNCH_RESET_V1 = {
  id: "production-launch-reset-v1",
  version: "1.0.0",
  status: "OWNER_GATED",
  oneTimePreLaunch: true,
  npm: "launch:reset",
  script: "scripts/production-launch-reset-v1.ts",

  forbidden: [
    "SCHEMA_CHANGES",
    "MIGRATIONS",
    "DROP_TABLES",
    "RECREATE_DATABASE",
    "GITHUB_PUSH",
    "VERCEL_PRODUCTION_DEPLOY",
    "PRODUCTION_LOCK",
  ] as const,

  keep: [
    "database_schema",
    "migrations",
    "application_configuration",
    "super_admin_accounts",
    "admin_accounts",
    "full_demo_accounts",
    "platform_settings",
    "categories",
    "taxonomy",
    "currencies",
    "countries",
    "languages",
    "shipping_configuration",
    "payment_configuration",
    "feature_flags",
    "legal_documents",
    "help_centre",
    "documentation",
    "templates",
    "email_templates",
    "static_assets",
    "icons",
    "branding",
    "hmrc_rules_engine",
    "threshold_engine",
    "calculation_engine",
    "permissions",
    "roles",
    "policies",
    "profiles",
    "user_settings",
    "wallets_shells",
  ] as const,

  /** Delete order: children → parents. Missing tables are skipped with a note. */
  deleteTablesInOrder: [
    "messages",
    "conversation_reports",
    "conversations",
    "notification_delivery_log",
    "notification_events",
    "saved_search_notification_log",
    "notifications",
    "email_outbox",
    "push_subscriptions",
    "reviews",
    "protection_evidence",
    "protection_case_events",
    "protection_cases",
    "resolution_events",
    "carrier_responses",
    "carrier_claims",
    "carrier_returns",
    "resolution_cases",
    "shipping_tracking_events",
    "shipping_quotes",
    "shipping_labels_v1",
    "shipment_parcels",
    "shipping_fallback_events",
    "shipping_records",
    "parcel2go_webhook_events",
    "stripe_webhook_events",
    "escrow_events",
    "refund_events",
    "shipping_transactions",
    "shipping_reserve",
    "commerce_audit_logs",
    "order_items",
    "order_shipments",
    "checkout_sessions",
    "offers",
    "bids",
    "cart_items",
    "saved_items",
    "recently_viewed",
    "product_view_events",
    "product_images",
    "listing_promotions",
    "seller_promotions",
    "promotion_analytics_events",
    "promotion_action_audit",
    "moderation_queue",
    "moderation_audit_logs",
    "content_reports",
    "wallet_transactions",
    "orders",
    "products",
    "user_follows",
    "seller_follows",
    "saved_searches",
    "live_visitor_sessions",
    "platform_analytics_events",
    "help_analytics_events",
    "platform_error_logs",
    "cron_job_runs",
    "seller_performance_event_queue",
    "seller_performance_history",
    "seller_performance_audit",
    "seller_performance_badge_history",
    "seller_performance_scores",
    "badge_overrides",
    "badge_audit_log",
    "trust_events",
    "demo_session_artifacts",
    "demo_certification_sessions",
    "demo_sessions",
    "store_migration_items",
    "store_migration_image_assets",
    "store_marketplace_connector_events",
    "store_migration_jobs",
    "rfq_requests",
    "automation_logs",
    "user_presence",
    "support_tickets",
    "platform_audit_logs",
    "staff_activity_logs",
  ] as const,

  verificationZeroTables: [
    "products",
    "product_images",
    "orders",
    "order_items",
    "offers",
    "messages",
    "conversations",
    "notifications",
    "wallet_transactions",
    "reviews",
    "user_follows",
    "seller_follows",
    "saved_items",
    "recently_viewed",
    "product_view_events",
    "checkout_sessions",
    "shipping_labels_v1",
    "shipping_tracking_events",
    "support_tickets",
    "protection_cases",
    "resolution_cases",
    "demo_session_artifacts",
    "demo_certification_sessions",
  ] as const,

  /** Counted after reset — must remain > 0 for launch readiness of protected config. */
  protectedCountTables: [
    "categories",
    "profiles",
    "platform_settings",
    "help_articles",
    "help_categories",
  ] as const,

  fullDemoEmails: ["demo.buyer@rovexo.co.uk", "demo.seller@rovexo.co.uk"] as const,
  fullDemoWalletFloorGbp: 50_000,

  /**
   * Launch keep-list (Owner). Full Demo retained by Permanent Full Demo Contract.
   * All other auth users/profiles are purged on APPLY.
   */
  keepOwnerEmails: ["palademihaita88@gmail.com", "mihaitaself@gmail.com"] as const,
  keepOwnerRoles: {
    "palademihaita88@gmail.com": "super_admin",
    "mihaitaself@gmail.com": "admin",
  } as const,
  purgeNonKeepUsers: true,
} as const;

export type ProductionLaunchResetV1 = typeof PRODUCTION_LAUNCH_RESET_V1;
