import type { CommandCenterModule, CommandCenterRegistry } from "@/lib/super-admin/command-center/types";

/** Canonical Super Admin module map — Single Source of Truth for routes and coverage. */
const MODULES: CommandCenterModule[] = [
  {
    id: "command-os",
    label: "ROVEXO Command OS",
    description: "Enterprise v4.0 — platform operating system, health, digital twin, one-click ops",
    href: "/super-admin/command-os",
    category: "dashboard",
    status: "live",
    icon: "🧭",
  },
  {
    id: "mission-control",
    label: "Mission Control",
    description: "Marketplace overview, live statistics, service health",
    href: "/super-admin",
    category: "dashboard",
    status: "live",
    icon: "🛰️",
  },
  {
    id: "command-centre",
    label: "Command Centre",
    description: "Emergency actions, audit trail, global search",
    href: "/super-admin/command",
    category: "dashboard",
    status: "live",
    icon: "🎛️",
  },
  {
    id: "users",
    label: "User Management",
    description: "Buyers, sellers, businesses, roles, sessions",
    href: "/super-admin/users",
    category: "users",
    status: "live",
    icon: "👤",
  },
  {
    id: "staff-profile",
    label: "Staff Profile & Audit",
    description: "Platform personnel, multi-role assignments, activity audit",
    href: "/super-admin/staff",
    category: "users",
    status: "live",
    icon: "🪪",
  },
  {
    id: "staff-enterprise",
    label: "Staff Enterprise Platform",
    description: "Android, iOS, Windows, Web — directory, messaging, RBAC, presence",
    href: "/staff",
    category: "users",
    status: "live",
    icon: "📱",
  },
  {
    id: "verification",
    label: "Verification",
    description: "Identity and business verification queue",
    href: "/super-admin/verification",
    category: "users",
    status: "live",
    icon: "✅",
  },
  {
    id: "businesses",
    label: "Business Management",
    description: "Verified business accounts and storefronts",
    href: "/super-admin/businesses",
    category: "users",
    status: "live",
    icon: "🏢",
  },
  {
    id: "listings",
    label: "Listing Management",
    description: "Approve, reject, feature, boost, bulk moderation",
    href: "/super-admin/moderation",
    category: "commerce",
    status: "live",
    icon: "🏷️",
  },
  {
    id: "category-management",
    label: "Categories & Taxonomies",
    description: "Category tree, premium assets, AI review",
    href: "/super-admin/category-management",
    category: "commerce",
    status: "live",
    icon: "📁",
  },
  {
    id: "orders-engine",
    label: "Order Management",
    description: "Orders, refunds, disputes, buyer protection",
    href: "/super-admin/orders-engine",
    category: "commerce",
    status: "live",
    icon: "📦",
  },
  {
    id: "payments-engine",
    label: "Payment Management",
    description: "Stripe Connect, wallets, settlements, chargebacks",
    href: "/super-admin/payments-engine",
    category: "payments",
    status: "live",
    icon: "💳",
  },
  {
    id: "wallet-engine",
    label: "Wallet Engine",
    description: "Platform, seller, and business wallet operations",
    href: "/super-admin/wallet-engine",
    category: "payments",
    status: "live",
    icon: "👛",
  },
  {
    id: "shipping-engine",
    label: "Shipping Management",
    description: "GoShippo, labels, tracking, delivery analytics",
    href: "/super-admin/shipping-engine",
    category: "shipping",
    status: "live",
    icon: "🚚",
  },
  {
    id: "homepage-builder",
    label: "Homepage Builder",
    description: "Visual homepage editor and launch defaults",
    href: "/super-admin/homepage-builder",
    category: "content",
    status: "live",
    icon: "🏠",
  },
  {
    id: "experience-os",
    label: "ROVEXO Experience Operating System",
    description: "XOS Enterprise v3.0 — screens, navigation, widgets, features, analytics, publish",
    href: "/super-admin/experience",
    category: "content",
    status: "live",
    icon: "🎛️",
  },
  {
    id: "design-studio",
    label: "Design Studio",
    description: "Alias to Experience Operating System",
    href: "/super-admin/experience",
    category: "content",
    status: "live",
    icon: "🎨",
  },
  {
    id: "visual-cms",
    label: "Visual CMS",
    description: "Banners, menus, theme studio, static pages",
    href: "/super-admin/visual-cms",
    category: "content",
    status: "live",
    icon: "🖌️",
  },
  {
    id: "help-center",
    label: "Help Centre",
    description: "FAQ, policies, legal pages",
    href: "/super-admin/support",
    category: "content",
    status: "live",
    icon: "📚",
  },
  {
    id: "ai-engine",
    label: "AI Management",
    description: "Category engine, moderation, suggestions, logs",
    href: "/super-admin/ai-engine",
    category: "ai",
    status: "live",
    icon: "🤖",
  },
  {
    id: "notifications-engine",
    label: "Notifications",
    description: "Email, push, SMS, broadcasts, system alerts",
    href: "/super-admin/notifications-engine",
    category: "notifications",
    status: "live",
    icon: "🔔",
  },
  {
    id: "security-engine",
    label: "Security",
    description: "SOC, fraud, rate limits, audit logs",
    href: "/super-admin/security-engine",
    category: "security",
    status: "live",
    icon: "🔒",
  },
  {
    id: "audit",
    label: "Audit & Compliance",
    description: "Audit trail, compliance policies, reports",
    href: "/super-admin/audit",
    category: "security",
    status: "live",
    icon: "📋",
  },
  {
    id: "database",
    label: "Database Command Center",
    description: "Schema health, migrations, RLS, storage",
    href: "/super-admin/database",
    category: "database",
    status: "live",
    icon: "🗄️",
  },
  {
    id: "recovery",
    label: "Backups & Recovery",
    description: "Backup status, restore workflows",
    href: "/super-admin/recovery",
    category: "database",
    status: "live",
    icon: "💾",
  },
  {
    id: "analytics-engine",
    label: "Analytics",
    description: "Revenue, traffic, conversion, marketplace health",
    href: "/super-admin/analytics-engine",
    category: "analytics",
    status: "live",
    icon: "📈",
  },
  {
    id: "business-intelligence",
    label: "Business Intelligence",
    description: "Executive dashboards and forecasting",
    href: "/super-admin/business-intelligence",
    category: "analytics",
    status: "live",
    icon: "📊",
  },
  {
    id: "platform",
    label: "Platform Settings",
    description: "Feature flags, environment, maintenance mode",
    href: "/super-admin/platform",
    category: "system",
    status: "live",
    icon: "⚙️",
  },
  {
    id: "module-registry",
    label: "Module Registry",
    description: "Enterprise module discovery and orchestration",
    href: "/super-admin/module-registry",
    category: "system",
    status: "live",
    icon: "🗂️",
  },
  {
    id: "monitoring",
    label: "Monitoring",
    description: "API health, cache, queues, cron jobs",
    href: "/super-admin/monitoring",
    category: "system",
    status: "live",
    icon: "💚",
  },
  {
    id: "certification",
    label: "Certification Center",
    description: "Production release gate and validation",
    href: "/super-admin/certification",
    category: "system",
    status: "live",
    icon: "🏆",
  },
];

const CATEGORY_LABELS: Record<CommandCenterModule["category"], string> = {
  dashboard: "Dashboard",
  users: "User Management",
  commerce: "Commerce",
  payments: "Payments",
  shipping: "Shipping",
  content: "Content",
  ai: "AI",
  notifications: "Notifications",
  security: "Security",
  database: "Database",
  analytics: "Analytics",
  system: "System",
};

export function getCommandCenterRegistry(): CommandCenterRegistry {
  const categories = (Object.keys(CATEGORY_LABELS) as Array<keyof typeof CATEGORY_LABELS>).map((id) => ({
    id,
    label: CATEGORY_LABELS[id],
    modules: MODULES.filter((mod) => mod.category === id),
  }));

  return {
    version: "1.0.0",
    generatedAt: new Date().toISOString(),
    categories,
  };
}

export function getCommandCenterModule(id: string): CommandCenterModule | undefined {
  return MODULES.find((mod) => mod.id === id);
}

export function listCommandCenterModules(): CommandCenterModule[] {
  return [...MODULES];
}
