import type { HelpArticle } from "@/lib/help/types";

/** P12 Wave A — additional Help articles. Merged into HELP_ARTICLES SSOT. */
export const WAVE_A_HELP_ARTICLES: HelpArticle[] = [
  {
    slug: "buying-total-buyer-pays",
    title: "What Total Buyer Pays means",
    category: "buying",
    topic: "buyer",
    summary: "Understand the full Checkout total including Platform Fee and shipping.",
    keywords: ["total", "buyer pays", "platform fee", "checkout"],
    content: "# What Total Buyer Pays means\n\nTotal Buyer Pays is the full amount you pay at Checkout.\n\n## What it includes\n- Item price\n- Platform Fee (paid by the buyer)\n- Applicable shipping\n\n## What it is not\n- It is not the item price alone\n- It is not a seller commission\n\nAlways review the price summary before Confirm & Pay.",
  },
  {
    slug: "buying-make-offer",
    title: "How to make an offer",
    category: "buying",
    topic: "buyer",
    summary: "Send, receive, and accept offers safely on ROVEXO.",
    keywords: ["offer", "counter", "negotiate"],
    content: "# How to make an offer\n\nUse Make Offer on a listing or in Conversation Hub.\n\n## Steps\n1. Enter your offer amount.\n2. Wait for the seller to accept, decline, or counter.\n3. Pay only through ROVEXO after acceptance.\n\nNever pay outside ROVEXO \u2014 you lose purchase protection.",
  },
  {
    slug: "buying-first-purchase",
    title: "Your first purchase checklist",
    category: "buying",
    topic: "buyer",
    summary: "A simple checklist for first-time buyers.",
    keywords: ["first", "checklist", "new buyer"],
    content: "# Your first purchase checklist\n\n## Before you buy\n- Read the full description and all photos\n- Check seller ratings when available\n- Confirm delivery address\n\n## At Checkout\n- Review Total Buyer Pays\n- Complete payment in ROVEXO only\n\n## After payment\n- Track in Orders and Conversation Hub\n- Message the seller on ROVEXO if anything is unclear",
  },
  {
    slug: "buying-condition-guide",
    title: "Understanding listing condition",
    category: "buying",
    topic: "buyer",
    summary: "How to read condition labels before you buy.",
    keywords: ["condition", "used", "new"],
    content: "# Understanding listing condition\n\nCondition helps you compare listings fairly.\n\n## Tips\n- New should be unused with tags where claimed\n- Like new should show minimal wear\n- Used should disclose flaws\n\nAsk the seller for extra photos if you are unsure.",
  },
  {
    slug: "selling-fees",
    title: "Seller fees on ROVEXO",
    category: "selling",
    topic: "seller",
    summary: "Seller Fee is \u00a30 \u2014 buyers pay Platform Fee.",
    keywords: ["seller fee", "commission", "fees"],
    content: "# Seller fees on ROVEXO\n\n## Seller Fee\nSeller Fee is \u00a30. There is no seller commission on ROVEXO sales.\n\n## Platform Fee\nBuyers pay Platform Fee as part of Total Buyer Pays at Checkout.\n\n## Payouts\nAfter protection timing, funds appear in Balance for withdrawal to a verified bank account.",
  },
  {
    slug: "selling-pricing",
    title: "How to price your listing",
    category: "selling",
    topic: "seller",
    summary: "Price competitively with honest condition and clear photos.",
    keywords: ["price", "pricing", "value"],
    content: "# How to price your listing\n\n## Tips\n- Check similar active listings in your category\n- Price reflects condition and completeness\n- You can reduce price later \u2014 say so if open to offers\n\nAccurate pricing with strong photos sells faster.",
  },
  {
    slug: "selling-parcels",
    title: "Choosing parcel size",
    category: "selling",
    topic: "seller",
    summary: "Match parcel size to packed dimensions at publish time.",
    keywords: ["parcel", "shipping size", "pack"],
    content: "# Choosing parcel size\n\nAt publish, choose the parcel option that fits the packed item.\n\n## Why it matters\n- Labels and carrier options depend on size\n- Under-declaring size can delay shipping\n- Oversize items need honest dimensions in the description",
  },
  {
    slug: "selling-holiday-mode",
    title: "Holiday Mode for sellers",
    category: "selling",
    topic: "seller",
    summary: "Pause visibility when you cannot ship.",
    keywords: ["holiday", "pause", "vacation"],
    content: "# Holiday Mode for sellers\n\nHoliday Mode pauses selling visibility when you are away.\n\n## When to use it\n- Travel\n- Illness\n- Stock or packing delays\n\nTurn it off when you can ship again so buyers are not left waiting.",
  },
  {
    slug: "selling-listing-quality",
    title: "Listing quality checklist",
    category: "selling",
    topic: "seller",
    summary: "Publish listings buyers can trust.",
    keywords: ["quality", "checklist", "photos"],
    content: "# Listing quality checklist\n\n## Checklist\n- Clear photos of the actual item\n- Honest title and description\n- Correct category\n- Realistic price\n- Correct parcel size\n\nMissing any of these slows sales and increases disputes.",
  },
  {
    slug: "payments-platform-fee",
    title: "Platform Fee explained",
    category: "payments",
    topic: "payments",
    summary: "Buyers pay Platform Fee; sellers do not pay commission.",
    keywords: ["platform fee", "buyer fee"],
    content: "# Platform Fee explained\n\nPlatform Fee helps maintain ROVEXO, secure payments, buyer and seller protection, support and platform operations.\n\nIt appears in the buyer Checkout total and is included in Total Buyer Pays.",
  },
  {
    slug: "payments-failed",
    title: "If payment fails at Checkout",
    category: "payments",
    topic: "payments",
    summary: "What to do when card payment does not complete.",
    keywords: ["failed payment", "card declined"],
    content: "# If payment fails at Checkout\n\n## Try\n1. Confirm card details and available funds\n2. Try another payment method if available\n3. Retry Checkout from the same order flow\n\nIf funds were held by your bank but ROVEXO shows unpaid, contact Support with the time of the attempt \u2014 do not create duplicate payments.",
  },
  {
    slug: "wallet-overview",
    title: "Wallet and Balance overview",
    category: "payments",
    topic: "wallet",
    summary: "Where to see Available Balance, transactions and payouts.",
    keywords: ["wallet", "balance", "payout"],
    content: "# Wallet and Balance overview\n\nOpen **Balance** from Profile to access Wallet surfaces.\n\n## You can\n- View Available Balance\n- Review transactions\n- Manage payment methods and bank accounts\n- Request withdrawals when eligible\n\nDemo accounts use virtual money only.",
  },
  {
    slug: "wallet-withdraw",
    title: "How to withdraw funds",
    category: "payments",
    topic: "withdraw",
    summary: "Withdraw Available Balance to a verified bank account.",
    keywords: ["withdraw", "bank", "payout"],
    content: "# How to withdraw funds\n\n## Steps\n1. Complete verification and tax registration where required\n2. Add a bank account in Wallet\n3. Withdraw from Available Balance\n\nPending order protection or reviews can delay availability.",
  },
  {
    slug: "wallet-bank-account",
    title: "Adding a bank account",
    category: "payments",
    topic: "stripe",
    summary: "Connect a UK bank account for withdrawals.",
    keywords: ["bank", "account", "payout"],
    content: "# Adding a bank account\n\nAdd your bank details from Wallet \u2192 Bank accounts.\n\n## Tips\n- Use an account in your legal name\n- Double-check sort code and account number\n- Complete any verification prompts before withdrawing",
  },
  {
    slug: "shipping-change-address",
    title: "Changing delivery address",
    category: "delivery",
    topic: "shipping",
    summary: "Address changes after payment are limited by order status.",
    keywords: ["address", "change", "delivery"],
    content: "# Changing delivery address\n\nAfter payment, address changes are only possible while the order status allows.\n\nMessage the seller and Support in Inbox immediately. Do not arrange off-platform shipping changes.",
  },
  {
    slug: "shipping-late-delivery",
    title: "Late or missing delivery",
    category: "delivery",
    topic: "shipping",
    summary: "What to do if a parcel is late or tracking stops.",
    keywords: ["late", "missing", "tracking"],
    content: "# Late or missing delivery\n\n## Steps\n1. Check tracking in Orders / Conversation Hub\n2. Message the seller on ROVEXO\n3. Wait for carrier updates when in transit\n4. Open Support with your order number if unresolved\n\nKeep evidence inside ROVEXO.",
  },
  {
    slug: "shipping-labels",
    title: "Shipping labels for sellers",
    category: "delivery",
    topic: "shipping",
    summary: "Print labels from the order flow after payment.",
    keywords: ["label", "print", "ship"],
    content: "# Shipping labels for sellers\n\nAfter payment, sellers fulfil using ROVEXO shipping and label flows for that order.\n\n## Tips\n- Pack to the declared parcel size\n- Print and attach the label clearly\n- Mark shipped so the buyer receives tracking",
  },
  {
    slug: "verification-overview",
    title: "Account verification overview",
    category: "account",
    topic: "verification",
    summary: "Why ROVEXO asks you to verify and what it unlocks.",
    keywords: ["verify", "kyc", "identity"],
    content: "# Account verification overview\n\nVerification reduces fraud and unlocks payouts and trust signals.\n\n## Tips\n- Submit clear documents\n- Use your legal name\n- Complete steps in order\n\nYou keep one ROVEXO Account \u2014 verification does not create a second account.",
  },
  {
    slug: "verification-payouts",
    title: "Verification and payouts",
    category: "account",
    topic: "verification",
    summary: "Payouts may wait until verification is complete.",
    keywords: ["payout", "verify", "withdraw"],
    content: "# Verification and payouts\n\nIf withdraw is blocked, check verification and tax registration status in Settings and Wallet.\n\nComplete outstanding steps, then retry withdraw from Available Balance.",
  },
  {
    slug: "business-storefront-tips",
    title: "Storefront tips for sellers",
    category: "business-accounts",
    topic: "business-accounts",
    audience: "business",
    summary: "Present a clear public store using Business tools on your ROVEXO Account.",
    keywords: ["store", "storefront", "business"],
    content: "# Storefront tips for sellers\n\nYour public store or profile shows listings and ratings.\n\n## Tips\n- Keep avatar and bio professional\n- Maintain honest listings\n- Reply promptly in Conversation Hub\n\nBusiness details are verification on the same ROVEXO account.",
  },
  {
    slug: "business-vat-basics",
    title: "VAT and selling basics (informational)",
    category: "business-accounts",
    topic: "business-accounts",
    summary: "High-level UK VAT reminders for sellers \u2014 not tax advice.",
    keywords: ["vat", "tax", "hmrc"],
    content: "# VAT and selling basics (informational)\n\nROVEXO does not replace your accountant.\n\n## Remember\n- Tax registration status on your ROVEXO account must be accurate\n- Thresholds and VAT rules can change \u2014 check HMRC guidance\n- Keep records of sales for your own compliance\n\nThis article is informational only.",
  },
  {
    slug: "safety-scam-red-flags",
    title: "Scam red flags",
    category: "safety",
    topic: "safety",
    summary: "Spot and avoid common marketplace scams.",
    keywords: ["scam", "fraud", "red flags"],
    content: "# Scam red flags\n\n## Red flags\n- Requests to pay outside ROVEXO\n- Urgency to move to WhatsApp or email only\n- Overpayment stories\n- Links to unknown payment sites\n\nStay in ROVEXO Checkout and Messages. Report suspicious behaviour.",
  },
  {
    slug: "safety-meetup",
    title: "Courier vs meetup",
    category: "safety",
    topic: "safety",
    summary: "Prefer tracked courier delivery for most purchases.",
    keywords: ["meetup", "courier", "safety"],
    content: "# Courier vs meetup\n\nTracked courier delivery creates a clearer trail for purchase protection.\n\nKeep payment on ROVEXO for Checkout orders. Never move payment off-platform.",
  },
  {
    slug: "returns-buyer-steps",
    title: "Buyer returns overview",
    category: "buying",
    topic: "returns",
    summary: "How buyers start a return or issue.",
    keywords: ["return", "refund", "issue"],
    content: "# Buyer returns overview\n\nIf an item is not as described or arrives damaged:\n\n1. Message the seller with photos\n2. Use in-product issue flows when available\n3. Contact Support with your order number if unresolved\n\nKeep all evidence in ROVEXO.",
  },
  {
    slug: "returns-seller-steps",
    title: "Seller returns overview",
    category: "selling",
    topic: "returns",
    summary: "How sellers respond to return requests.",
    keywords: ["return", "seller", "refund"],
    content: "# Seller returns overview\n\nRespond quickly in Conversation Hub.\n\n## Tips\n- Ask for clear photos\n- Follow ROVEXO return and refund rules\n- Do not ask buyers to resolve off-platform\n\nFair handling protects your ratings.",
  },
  {
    slug: "community-reviews",
    title: "Reviews and ratings etiquette",
    category: "community-guidelines",
    topic: "trust-score",
    summary: "Leave fair reviews after eligible completed orders.",
    keywords: ["review", "rating", "feedback"],
    content: "# Reviews and ratings etiquette\n\nReviews are for completed eligible orders within the review window.\n\n## Do\n- Be honest and specific\n- Focus on the transaction\n\n## Do not\n- Use reviews to harass\n- Reference unrelated disputes unfairly",
  },
  {
    slug: "community-reporting",
    title: "How to report a listing or user",
    category: "reports-appeals",
    topic: "reports",
    summary: "Report prohibited items, scams, or abuse.",
    keywords: ["report", "abuse", "prohibited"],
    content: "# How to report a listing or user\n\nUse in-app report tools or Contact Support.\n\nInclude:\n- Listing or profile URL\n- Screenshots\n- Short description of the issue\n\nFalse reports may themselves breach policy.",
  },
  {
    slug: "account-notifications",
    title: "Notification settings",
    category: "account",
    topic: "account",
    summary: "Stay informed about offers, orders and shipping.",
    keywords: ["notifications", "alerts", "email"],
    content: "# Notification settings\n\nOpen Settings \u2192 Notifications.\n\nEnable alerts for offers, payment, shipping and disputes so you do not miss time-sensitive steps.",
  },
  {
    slug: "account-delete",
    title: "Delete account information",
    category: "account",
    topic: "account",
    summary: "Where account deletion lives and what to consider.",
    keywords: ["delete", "account", "close"],
    content: "# Delete account information\n\nAccount deletion is available from Settings.\n\n## Before you delete\n- Finish open orders\n- Withdraw Available Balance if eligible\n- Download any records you need\n\nDeletion is permanent subject to legal retention.",
  },
  {
    slug: "uk-buying-secondhand",
    title: "Buying second-hand in the UK",
    category: "buying",
    topic: "buyer",
    summary: "UK marketplace tips for second-hand shopping on ROVEXO.",
    keywords: ["uk", "second-hand", "preloved"],
    content: "# Buying second-hand in the UK\n\nROVEXO is built for UK buyers and sellers.\n\n## Tips\n- Prefer tracked UK delivery\n- Read condition carefully\n- Use ROVEXO Checkout for protection\n- Ask fitment or size questions before you buy",
  },
  {
    slug: "uk-selling-locally",
    title: "Selling with UK courier shipping",
    category: "selling",
    topic: "seller",
    summary: "Ship across the UK with clear parcel choices.",
    keywords: ["uk", "courier", "sell"],
    content: "# Selling with UK courier shipping\n\nMost ROVEXO sales use courier shipping.\n\n## Tips\n- Pack to the declared size\n- Ship promptly after payment\n- Provide tracking via ROVEXO flows\n- Keep communication in Conversation Hub",
  },
  {
    slug: "guide-womens-fashion",
    title: "Women's fashion buying and selling guide",
    category: "buying",
    topic: "buyer",
    summary: "Category guide for Women's Fashion on ROVEXO.",
    keywords: ["women", "fashion", "guide"],
    content: "# Women's fashion buying and selling guide\n\n## Buyers\nCheck size, fabric and flaws in photos.\n\n## Sellers\nUse natural light, true sizes and honest condition.\n\nBrowse the Women's Fashion category on ROVEXO for live listings.",
    relatedFeatureHrefs: [
      { label: "Women's Fashion", href: "/category/womens-fashion" },
      { label: "Newly listed", href: "/collections/newly-listed" },
    ],
  },
  {
    slug: "guide-mens-fashion",
    title: "Men's fashion buying and selling guide",
    category: "selling",
    topic: "seller",
    summary: "Category guide for Men's Fashion on ROVEXO.",
    keywords: ["men", "fashion", "guide"],
    content: "# Men's fashion buying and selling guide\n\n## Buyers\nConfirm sizing systems in the description.\n\n## Sellers\nPhotograph collars, cuffs and soles.\n\nBrowse the Men's Fashion category for live listings.",
    relatedFeatureHrefs: [
      { label: "Men's Fashion", href: "/category/mens-fashion" },
      { label: "Best deals", href: "/collections/best-deals" },
    ],
  },
  {
    slug: "guide-designer",
    title: "Designer and jewellery guide",
    category: "safety",
    topic: "safety",
    summary: "Authenticity and shipping tips for designer items.",
    keywords: ["designer", "jewellery", "authentic"],
    content: "# Designer and jewellery guide\n\nOnly list authentic items. Show hallmarks and packaging.\n\nBuyers should keep payment on ROVEXO and request detail photos.\n\nBrowse the Designer category for live listings.",
    relatedFeatureHrefs: [
      { label: "Designer", href: "/category/jewellery" },
      { label: "Premium listings", href: "/collections/premium-listings" },
    ],
  },
  {
    slug: "guide-kids-baby",
    title: "Kids and baby guide",
    category: "buying",
    topic: "buyer",
    summary: "Safety-minded tips for kids and baby listings.",
    keywords: ["kids", "baby", "safety"],
    content: "# Kids and baby guide\n\nCheck for wear, missing parts and age suitability.\n\nSellers must not list unsafe damaged equipment as fully functional.\n\nBrowse the Kids & Baby category for live listings.",
    relatedFeatureHrefs: [{ label: "Kids & Baby", href: "/category/kids-fashion" }],
  },
  {
    slug: "guide-home-garden",
    title: "Home and garden guide",
    category: "selling",
    topic: "seller",
    summary: "Dimensions, packing and delivery for home items.",
    keywords: ["home", "garden", "furniture"],
    content: "# Home and garden guide\n\nMeasure space and packed dimensions.\n\nSellers should protect corners and choose the correct parcel tier.\n\nBrowse the Home & Garden category for live listings.",
    relatedFeatureHrefs: [{ label: "Home & Garden", href: "/category/home-garden" }],
  },
  {
    slug: "guide-electronics",
    title: "Electronics guide",
    category: "buying",
    topic: "buyer",
    summary: "Condition, accessories and reset tips for electronics.",
    keywords: ["electronics", "phone", "laptop"],
    content: "# Electronics guide\n\nConfirm storage, accessories and faults.\n\nSellers should factory-reset devices before shipping.\n\nBrowse the Electronics category for live listings.",
    relatedFeatureHrefs: [
      { label: "Electronics", href: "/category/electronics" },
      { label: "Electronics deals", href: "/collections/electronics-deals" },
    ],
  },
  {
    slug: "guide-books-media",
    title: "Books and media guide",
    category: "buying",
    topic: "buyer",
    summary: "Condition grading for books, music and film.",
    keywords: ["books", "media", "dvd"],
    content: "# Books and media guide\n\nCheck edition, wear and missing discs.\n\nSellers should photograph spines and disclose annotations.\n\nBrowse the Books & Media category for live listings.",
    relatedFeatureHrefs: [{ label: "Books & Media", href: "/category/books" }],
  },
  {
    slug: "guide-collectables",
    title: "Hobbies and collectables guide",
    category: "selling",
    topic: "seller",
    summary: "Authenticity and packing for collectables.",
    keywords: ["collectables", "cards", "coins"],
    content: "# Hobbies and collectables guide\n\nAvoid exaggerated rarity claims. Use rigid packaging.\n\nBrowse the Hobbies & Collectables category for live listings.",
    relatedFeatureHrefs: [{ label: "Hobbies & Collectables", href: "/category/collectibles" }],
  },
  {
    slug: "guide-sports-outdoors",
    title: "Sports and outdoors guide",
    category: "buying",
    topic: "buyer",
    summary: "Safety and wear checks for sports gear.",
    keywords: ["sports", "outdoors", "fitness"],
    content: "# Sports and outdoors guide\n\nAsk about impact history on protective gear.\n\nDo not buy or sell unsafe damaged safety equipment as fully functional.\n\nBrowse the Sports & Outdoors category for live listings.",
    relatedFeatureHrefs: [{ label: "Sports & Outdoors", href: "/category/sports" }],
  },
  {
    slug: "guide-vehicle-parts",
    title: "Vehicle parts and accessories guide",
    category: "selling",
    topic: "seller",
    summary: "Fitment-first guide \u2014 parts only, not whole vehicles.",
    keywords: ["parts", "vehicle", "fitment"],
    content: "# Vehicle parts and accessories guide\n\nROVEXO Vehicle Parts & Accessories is for courier-shippable parts only.\n\n## Sellers\nInclude make, model, year and part numbers.\n\n## Buyers\nConfirm compatibility before paying.\n\nWhole vehicles are not a catalogue root.",
    relatedFeatureHrefs: [{ label: "Vehicle Parts & Accessories", href: "/category/vehicle-parts" }],
  },
];

export function getWaveAHelpArticleCount(): number {
  return WAVE_A_HELP_ARTICLES.length;
}

