export const EXECUTION_ENGINE_DRAFT_KEY = "enterprise_autonomous_execution_engine_draft_v1";
export const EXECUTION_ENGINE_LIVE_KEY = "enterprise_autonomous_execution_engine_live_v1";
export const EXECUTION_ENGINE_HISTORY_KEY = "enterprise_autonomous_execution_engine_config_history_v1";
export const EXECUTION_ENGINE_SETTINGS_KEY = "enterprise_autonomous_execution_engine_settings_v1";
