import { createDefaultFeatureFlags } from "@/lib/enterprise-architecture";
import { MARKETPLACE_COMPLETION_MODULE_DESCRIPTOR } from "@/lib/enterprise-marketplace-completion-engine/descriptor";
import { createDefaultMarketplaceCompletionSettings } from "@/lib/enterprise-marketplace-completion-engine/engine";
import {
  MARKETPLACE_MODULE_REGISTRY,
  MARKETPLACE_PRODUCTION_GATES,
  MARKETPLACE_RELEASE_BLOCKERS,
  REPORT_TYPES,
} from "@/lib/enterprise-marketplace-completion-engine/registry";
import type {
  MarketplaceCompletionScanResult,
  MarketplaceCompletionSnapshot,
  MarketplaceCompletionState,
  MarketplaceCompletionTab,
} from "@/lib/enterprise-marketplace-completion-engine/types";

function labelize(value: string): string {
  return value.split("-").map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
}

export function createPendingMarketplaceCompletionScanResult(): MarketplaceCompletionScanResult {
  const scannedAt = new Date(0).toISOString();
  return {
    trigger: "full-scan",
    scannedAt,
    passPercent: 0,
    status: "pending",
    modulesComplete: 0,
    modulesTotal: MARKETPLACE_MODULE_REGISTRY.length,
    certificationEligible: false,
    productionReady: false,
    marketplaceReady: false,
    modules: [],
    checks: [],
    scores: [],
    productionGates: MARKETPLACE_PRODUCTION_GATES.map((gate) => ({
      gate,
      label: labelize(gate),
      passPercent: 0,
      status: "pending",
    })),
    blockers: MARKETPLACE_RELEASE_BLOCKERS.map((blocker) => ({
      blocker,
      label: labelize(blocker),
      active: false,
      severity: "low",
      message: `${labelize(blocker)} pending runtime validation`,
    })),
    launchReadinessPass: false,
    homepagePass: false,
    globalUiPass: false,
    intelligencePass: false,
    consistencyPass: false,
    healthPass: false,
    finalRulesPass: false,
    directorPass: false,
    certificationGatePass: false,
    omegaPass: false,
    worldClassStandard: false,
    launchModePass: false,
    launchReady: false,
    zeroDefectPass: false,
    zeroDefectGatePass: false,
    executionReleasePass: false,
    releaseGatePass: false,
    releaseReady: false,
    enterpriseDeliveryPass: false,
    deliveryGatePass: false,
    productionLaunchReady: false,
    executionModePass: false,
    executionPolicyPass: false,
    launchReadyFinal: false,
    homepageCompletionPass: false,
    homepageCertified: false,
    categoryCompletionPass: false,
    categoryCertified: false,
    searchCompletionPass: false,
    searchCertified: false,
    listingCompletionPass: false,
    listingCertified: false,
    buyerCompletionPass: false,
    buyerCertified: false,
    checkoutCompletionPass: false,
    checkoutCertified: false,
    orderCompletionPass: false,
    orderCertified: false,
    shippingCompletionPass: false,
    shippingCertified: false,
    communicationCompletionPass: false,
    communicationCertified: false,
  };
}

/** Lightweight config default — no filesystem scans, safe for build-time fallbacks. */
export function createPendingMarketplaceCompletionState(): MarketplaceCompletionState {
  const completionScan = createPendingMarketplaceCompletionScanResult();
  const emptyCompletion = {
    scannedAt: completionScan.scannedAt,
    active: false,
    passPercent: 0,
    status: "pending" as const,
    productionReady: false,
    launchReady: false,
  };

  return {
    dashboard: {
      overallPassPercent: 0,
      modulesComplete: 0,
      modulesTotal: MARKETPLACE_MODULE_REGISTRY.length,
      openIssues: 0,
      certificationGranted: false,
      productionReady: false,
      marketplaceReady: false,
      enterpriseScore: 0,
      lastScanAt: completionScan.scannedAt,
    },
    scores: [],
    modules: [],
    moduleCompletion: [],
    buttons: [],
    routes: [],
    buyerJourney: [],
    sellerJourney: [],
    companyJourney: [],
    homepage: [],
    search: [],
    categories: [],
    listings: [],
    uiIntegrity: [],
    completionScan,
    productionGates: completionScan.productionGates,
    blockers: completionScan.blockers,
    repairActions: [],
    reports: REPORT_TYPES.map((type, index) => ({
      id: `mc-rpt-pending-${type}`,
      type,
      title: `${labelize(type)} Report`,
      generatedAt: new Date(Date.now() - index * 86400000).toISOString(),
      status: "pending",
    })),
    auditEntries: [],
    intelligence: {
      scannedAt: completionScan.scannedAt,
      passPercent: 0,
      status: "pending",
      findings: [],
      totalDetections: 0,
      clearDetections: 0,
    },
    consistency: {
      scannedAt: completionScan.scannedAt,
      passPercent: 0,
      status: "pending",
      checks: [],
    },
    cleanup: { scannedAt: completionScan.scannedAt, proposals: [], totalProposals: 0, safeProposals: 0 },
    modernization: { scannedAt: completionScan.scannedAt, items: [], passPercent: 0, status: "pending" },
    healthScores: { scannedAt: completionScan.scannedAt, overallScore: 0, status: "pending", scores: [] },
    continuousImprovement: { active: false, triggersEnabled: [] },
    finalRules: [],
    director: {
      scannedAt: completionScan.scannedAt,
      passPercent: 0,
      status: "pending",
      omegaPass: false,
      worldClassStandard: false,
      globalControl: [],
      discovery: { scannedAt: completionScan.scannedAt, passPercent: 0, status: "pending", checks: [] },
      components: { scannedAt: completionScan.scannedAt, passPercent: 0, status: "pending", checks: [] },
      workflows: {
        scannedAt: completionScan.scannedAt,
        passPercent: 0,
        status: "pending",
        workflows: [],
        interactions: [],
      },
      uiIntegrity: { checks: [] },
      premium: { scannedAt: completionScan.scannedAt, passPercent: 0, status: "pending", checks: [] },
      infrastructure: {
        scannedAt: completionScan.scannedAt,
        passPercent: 0,
        status: "pending",
        checks: [],
        launchReadinessPass: false,
      },
      improvements: { scannedAt: completionScan.scannedAt, passPercent: 0, status: "pending", items: [] },
      dashboardScores: [],
    },
    certificationGate: {
      ...emptyCompletion,
      gates: [],
      certificationEligible: false,
      worldClassStandard: false,
    },
    launchMode: {
      ...emptyCompletion,
      priorities: [],
      uiQuality: [],
      uxQuality: [],
      marketplaceRules: [],
      infrastructure: [],
      cleanupProposals: [],
      blockers: [],
      certificationScores: [],
      report: [],
      launchRules: [],
      safeRepairs: [],
      activeBlockers: 0,
    },
    zeroDefect: {
      ...emptyCompletion,
      zeroDefectPass: false,
      zeroDefectGatePass: false,
      criticalDefects: 0,
      highPriorityDefects: 0,
      openDefects: 0,
      resolvedDefects: 0,
      domains: [],
      discoveryChecks: [],
      qualityChecks: [],
      regressionChecks: [],
      defects: [],
      classifications: [],
      gates: [],
      certification: [],
      report: [],
      repairWorkflow: [],
      safeRepairs: [],
      activeGates: 0,
    },
    executionRelease: {
      ...emptyCompletion,
      executionReleasePass: false,
      releaseGatePass: false,
      releaseReady: false,
      releaseApproved: false,
      modulesComplete: 0,
      modulesTotal: 0,
      criticalDefects: 0,
      blockedTasks: 0,
      board: [],
      modules: [],
      features: [],
      implementation: [],
      dashboard: [],
      readiness: [],
      gates: [],
      successCriteria: [],
      safeActions: [],
      activeGates: 0,
    },
    enterpriseDelivery: {
      ...emptyCompletion,
      enterpriseDeliveryPass: false,
      deliveryGatePass: false,
      productionLaunchReady: false,
      worldClassStandard: false,
      criticalDefects: 0,
      platformComplete: 0,
      platformTotal: 0,
      management: [],
      discovery: [],
      platform: [],
      globalUi: [],
      globalUx: [],
      marketplace: [],
      infrastructure: [],
      integrity: [],
      dashboard: [],
      zeroDefectPolicy: [],
      releaseGate: [],
      safeOptimizations: [],
      activePolicies: 0,
    },
    executionMode: {
      ...emptyCompletion,
      phase: "enterprise-delivery",
      executionModePass: false,
      executionPolicyPass: false,
      launchReadyFinal: false,
      enterpriseCertified: false,
      criticalDefects: 0,
      prioritiesComplete: 0,
      prioritiesTotal: 0,
      cycle: [],
      priorities: [],
      improvements: [],
      infrastructure: [],
      dashboard: [],
      releasePolicy: [],
      finalSuccess: [],
      safeAutomation: [],
      activePolicies: 0,
      directive: "Does this change move ROVEXO closer to Production Launch?",
    },
    homepageCompletion: {
      ...emptyCompletion,
      launchPriority: 1,
      homepageCompletionPass: false,
      homepageCertified: false,
      componentsComplete: 0,
      componentsTotal: 0,
      components: [],
      visualIntegrity: [],
      searchArea: [],
      categoryValidation: [],
      layoutValidation: [],
      featuredContent: [],
      buttonValidation: [],
      responsiveValidation: [],
      performance: [],
      seo: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    categoryCompletion: {
      ...emptyCompletion,
      launchPriority: 2,
      categoryCompletionPass: false,
      categoryCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      integrity: [],
      homepageSync: [],
      searchSync: [],
      listingSync: [],
      aiCategoryEngine: [],
      seo: [],
      buttonValidation: [],
      databaseValidation: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    searchCompletion: {
      ...emptyCompletion,
      launchPriority: 3,
      searchCompletionPass: false,
      searchCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      searchEngine: [],
      filters: [],
      sorting: [],
      results: [],
      emptyStates: [],
      performance: [],
      database: [],
      seo: [],
      aiSearch: [],
      omegaGlobal: [],
      accessibility: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    listingCompletion: {
      ...emptyCompletion,
      launchPriority: 4,
      listingCompletionPass: false,
      listingCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      workflow: [],
      fields: [],
      photoEngine: [],
      aiListing: [],
      liveValidation: [],
      previewEngine: [],
      publishValidation: [],
      buttonValidation: [],
      databaseValidation: [],
      omegaGlobal: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    buyerCompletion: {
      ...emptyCompletion,
      launchPriority: 5,
      buyerCompletionPass: false,
      buyerCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      workflow: [],
      profile: [],
      shopping: [],
      productPage: [],
      cart: [],
      checkout: [],
      orders: [],
      notifications: [],
      buttons: [],
      database: [],
      omegaGlobal: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    checkoutCompletion: {
      ...emptyCompletion,
      launchPriority: 8,
      checkoutCompletionPass: false,
      checkoutCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      flow: [],
      payment: [],
      order: [],
      security: [],
      ux: [],
      buttons: [],
      database: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    orderCompletion: {
      ...emptyCompletion,
      launchPriority: 9,
      orderCompletionPass: false,
      orderCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      workflow: [],
      buyer: [],
      seller: [],
      company: [],
      statusEngine: [],
      database: [],
      security: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    shippingCompletion: {
      ...emptyCompletion,
      launchPriority: 11,
      shippingCompletionPass: false,
      shippingCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      platform: [],
      database: [],
      security: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
    communicationCompletion: {
      ...emptyCompletion,
      launchPriority: 12,
      communicationCompletionPass: false,
      communicationCertified: false,
      domainsComplete: 0,
      domainsTotal: 0,
      domains: [],
      emailPlatform: [],
      emailSecurity: [],
      pushPlatform: [],
      cronQueues: [],
      realtime: [],
      database: [],
      security: [],
      accessibility: [],
      performance: [],
      certificationScores: [],
      passConditions: [],
      autoRepairs: [],
    },
  };
}

/** Sync shell for admin pages — no DB access, no OMEGA scans. Data loads via API after mount. */
export function createMarketplaceCompletionShellSnapshot(tab: MarketplaceCompletionTab = "dashboard"): MarketplaceCompletionSnapshot {
  const settings = createDefaultMarketplaceCompletionSettings();
  const pending = createPendingMarketplaceCompletionState();
  const featureFlagsConfig = createDefaultFeatureFlags(MARKETPLACE_COMPLETION_MODULE_DESCRIPTOR.featureFlags) as Record<string, boolean>;

  return {
    tab,
    ...pending,
    settings,
    history: [],
    auditLog: [],
    featureFlagsConfig,
    pendingPublish: false,
    health: {
      status: "warning",
      score: 0,
      message: "Marketplace Completion — awaiting runtime validation. Run Validate or refresh to load scan results.",
    },
  };
}
