export const MARKETPLACE_COMPLETION_ROUTES = [
  { id: "dashboard", label: "Completion Board", href: "/super-admin/marketplace-completion" },
  { id: "modules", label: "Modules", href: "/super-admin/marketplace-completion/modules" },
  { id: "buttons", label: "Buttons", href: "/super-admin/marketplace-completion/buttons" },
  { id: "routes", label: "Routes", href: "/super-admin/marketplace-completion/routes" },
  { id: "buyer-journey", label: "Buyer Journey", href: "/super-admin/marketplace-completion/buyer-journey" },
  { id: "seller-journey", label: "Seller Journey", href: "/super-admin/marketplace-completion/seller-journey" },
  { id: "company-journey", label: "Company Journey", href: "/super-admin/marketplace-completion/company-journey" },
  { id: "homepage", label: "Homepage", href: "/super-admin/marketplace-completion/homepage" },
  { id: "search", label: "Search", href: "/super-admin/marketplace-completion/search" },
  { id: "categories", label: "Categories", href: "/super-admin/marketplace-completion/categories" },
  { id: "listings", label: "Listings", href: "/super-admin/marketplace-completion/listings" },
  { id: "infrastructure", label: "Infrastructure", href: "/super-admin/marketplace-completion/infrastructure" },
  { id: "ui-integrity", label: "UI Integrity", href: "/super-admin/marketplace-completion/ui-integrity" },
  { id: "launch-gate", label: "Launch Gate", href: "/super-admin/marketplace-completion/launch-gate" },
  { id: "certification", label: "Certification", href: "/super-admin/marketplace-completion/certification" },
  { id: "intelligence", label: "Intelligence", href: "/super-admin/marketplace-completion/intelligence" },
  { id: "consistency", label: "Consistency", href: "/super-admin/marketplace-completion/consistency" },
  { id: "cleanup", label: "Cleanup", href: "/super-admin/marketplace-completion/cleanup" },
  { id: "modernization", label: "Modernization", href: "/super-admin/marketplace-completion/modernization" },
  { id: "health-scores", label: "Health Scores", href: "/super-admin/marketplace-completion/health-scores" },
  { id: "continuous-improvement", label: "Continuous", href: "/super-admin/marketplace-completion/continuous-improvement" },
  { id: "director", label: "Director", href: "/super-admin/marketplace-completion/director" },
  { id: "components", label: "Components", href: "/super-admin/marketplace-completion/components" },
  { id: "workflows", label: "Workflows", href: "/super-admin/marketplace-completion/workflows" },
  { id: "premium", label: "Premium", href: "/super-admin/marketplace-completion/premium" },
  { id: "improvements", label: "Improvements", href: "/super-admin/marketplace-completion/improvements" },
  { id: "certification-gate", label: "Cert Gate", href: "/super-admin/marketplace-completion/certification-gate" },
  { id: "launch-mode", label: "Launch Mode", href: "/super-admin/marketplace-completion/launch-mode" },
  { id: "zero-defect", label: "Zero Defect", href: "/super-admin/marketplace-completion/zero-defect" },
  { id: "execution-release", label: "Execution", href: "/super-admin/marketplace-completion/execution-release" },
  { id: "enterprise-delivery", label: "Delivery", href: "/super-admin/marketplace-completion/enterprise-delivery" },
  { id: "execution-mode", label: "Exec Mode", href: "/super-admin/marketplace-completion/execution-mode" },
  { id: "homepage-completion", label: "Homepage", href: "/super-admin/marketplace-completion/homepage-completion" },
  { id: "category-completion", label: "Cat Complete", href: "/super-admin/marketplace-completion/category-completion" },
  { id: "search-completion", label: "Search", href: "/super-admin/marketplace-completion/search-completion" },
  { id: "listing-completion", label: "Listing", href: "/super-admin/marketplace-completion/listing-completion" },
  { id: "buyer-completion", label: "Buyer", href: "/super-admin/marketplace-completion/buyer-completion" },
  { id: "checkout-completion", label: "Checkout", href: "/super-admin/marketplace-completion/checkout-completion" },
  { id: "order-completion", label: "Orders", href: "/super-admin/marketplace-completion/order-completion" },
  { id: "shipping-completion", label: "Shipping", href: "/super-admin/marketplace-completion/shipping-completion" },
  { id: "communication-completion", label: "Comms", href: "/super-admin/marketplace-completion/communication-completion" },
  { id: "reports", label: "Reports", href: "/super-admin/marketplace-completion/reports" },
] as const;

export const EXECUTION_TRIGGERS = [
  "communication-completion",
  "shipping-completion",
  "order-completion",
  "checkout-completion",
  "buyer-completion",
  "listing-completion",
  "search-completion",
  "category-completion",
  "homepage-completion",
  "execution-mode",
  "launch-mode",
  "marketplace-finalization",
  "full-scan",
  "enterprise-qa",
  "enterprise-certification",
  "pre-release",
  "production-validation",
  "commit",
  "merge",
  "pull-request",
  "deployment",
  "migration",
  "database-change",
  "component-change",
  "page-change",
  "api-change",
] as const;

export const MARKETPLACE_MODULE_REGISTRY = [
  { id: "homepage", label: "Homepage", route: "/", pageRef: "app/page.tsx", apiRef: "components/home/HomeContent.tsx" },
  { id: "categories", label: "Categories", route: "/categories", pageRef: "app/categories/page.tsx" },
  { id: "search", label: "Search", route: "/search", pageRef: "app/search/page.tsx", apiRef: "app/api/search/route.ts" },
  { id: "listing-creation", label: "Listing Creation", route: "/sell", pageRef: "app/sell/page.tsx", apiRef: "app/sell/new/page.tsx" },
  { id: "listing-details", label: "Listing Details", route: "/listing/[slug]", pageRef: "app/listing/[slug]/page.tsx" },
  { id: "featured-listings", label: "Featured Listings", route: "/", pageRef: "components/home/FeaturedListingsSection.tsx" },
  { id: "recommended-listings", label: "Recommended Listings", route: "/", pageRef: "components/home/HomeProductSection.tsx" },
  { id: "latest-listings", label: "Latest Listings", route: "/", pageRef: "components/home/HomeProductSection.tsx" },
  { id: "auctions", label: "Auctions", route: "/auctions", pageRef: "app/auctions/page.tsx" },
  { id: "buyer-dashboard", label: "Buyer Dashboard", route: "/account", pageRef: "app/account/page.tsx" },
  { id: "seller-dashboard", label: "Seller Dashboard", route: "/seller/dashboard", pageRef: "app/seller/dashboard/page.tsx" },
  { id: "company-dashboard", label: "Company Dashboard", route: "/business/dashboard", pageRef: "app/business/dashboard/page.tsx" },
  { id: "orders", label: "Orders", route: "/account/orders", pageRef: "app/account/orders/page.tsx", apiRef: "app/seller/orders/page.tsx" },
  { id: "checkout", label: "Checkout", route: "/checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { id: "wallet", label: "Wallet", route: "/wallet", pageRef: "app/wallet/page.tsx", apiRef: "app/account/wallet/page.tsx" },
  { id: "payments", label: "Payments", route: "/account/payment-methods", pageRef: "app/account/payment-methods/page.tsx", apiRef: "lib/stripe/server.ts" },
  { id: "shipping", label: "Shipping", route: "/shipping", pageRef: "app/shipping/page.tsx", apiRef: "app/account/seller/shipping/page.tsx" },
  { id: "returns", label: "Returns", route: "/resolution", pageRef: "app/resolution/page.tsx" },
  { id: "disputes", label: "Disputes", route: "/protection", pageRef: "app/protection/page.tsx" },
  { id: "messages", label: "Messages", route: "/messages", pageRef: "app/messages/page.tsx" },
  { id: "notifications", label: "Notifications", route: "/notifications", pageRef: "app/notifications/page.tsx" },
  { id: "community", label: "Community", route: "/trust", pageRef: "app/trust/page.tsx" },
  { id: "help-center", label: "Help Center", route: "/help", pageRef: "app/help/page.tsx" },
  { id: "business-center", label: "Business Center", route: "/business/center", pageRef: "app/business/center/page.tsx" },
  { id: "analytics", label: "Analytics", route: "/seller/analytics", pageRef: "app/seller/analytics/page.tsx", apiRef: "app/business/analytics/page.tsx" },
] as const;

export const MODULE_COMPLETION_CHECKS = [
  "missing-pages",
  "missing-buttons",
  "missing-routes",
  "missing-validations",
  "missing-permissions",
  "missing-api-integration",
  "missing-database-integration",
  "missing-loading-states",
  "missing-error-states",
  "missing-empty-states",
  "missing-responsive-layouts",
  "missing-accessibility",
  "missing-seo",
  "missing-translations",
  "missing-analytics",
  "missing-notifications",
] as const;

export const BUTTON_VALIDATION_CHECKS = [
  "button",
  "icon-button",
  "card",
  "menu",
  "dropdown",
  "modal",
  "dialog",
  "tab",
  "filter",
  "shortcut",
  "quick-action",
  "floating-action-button",
  "context-menu",
  "navigation-item",
  "click",
  "tap",
  "hover",
  "focus",
  "redirect",
  "permission",
  "api",
  "database",
  "notification",
  "ui-update",
  "animation",
  "success",
  "failure",
  "retry",
  "offline",
] as const;

export const ROUTE_VALIDATION_CHECKS = [
  "internal-routes",
  "external-routes",
  "deep-links",
  "protected-routes",
  "role-permissions",
  "404",
  "403",
  "back-navigation",
  "forward-navigation",
  "browser-refresh",
  "session-recovery",
] as const;

export const BUYER_JOURNEY_STEPS = [
  "register",
  "login",
  "search",
  "categories",
  "filters",
  "listing",
  "wishlist",
  "cart",
  "checkout",
  "payment",
  "orders",
  "tracking",
  "delivery",
  "review",
  "support",
  "logout",
] as const;

export const SELLER_JOURNEY_STEPS = [
  "register",
  "business-verification",
  "profile",
  "create-listing",
  "upload-photos",
  "ai-category",
  "ai-validation",
  "stock",
  "shipping",
  "draft",
  "preview",
  "publish",
  "orders",
  "analytics",
  "wallet",
  "messages",
  "vacation-mode",
] as const;

export const COMPANY_JOURNEY_STEPS = [
  "company-registration",
  "business-verification",
  "employees",
  "permissions",
  "reports",
  "analytics",
  "invoices",
  "settings",
] as const;

export const HOMEPAGE_VALIDATION_CHECKS = [
  "header",
  "search",
  "category-rail",
  "category-grid",
  "hero-banner",
  "featured",
  "recommended",
  "latest",
  "business",
  "footer",
  "bottom-navigation",
  "duplicate-categories",
  "duplicate-widgets",
  "duplicate-banners",
  "duplicate-sections",
  "unused-containers",
  "empty-space",
  "layout-inconsistencies",
  "broken-redirects",
  "broken-buttons",
] as const;

export const SEARCH_VALIDATION_CHECKS = [
  "search",
  "suggestions",
  "autocomplete",
  "filters",
  "sorting",
  "search-history",
  "saved-searches",
  "ai-search",
  "routing",
  "performance",
] as const;

export const CATEGORY_VALIDATION_CHECKS = [
  "tree",
  "hierarchy",
  "icons",
  "images",
  "seo",
  "slug",
  "relationships",
  "marketplace-usage",
  "listing-counts",
  "ai-suggestions",
] as const;

export const LISTING_VALIDATION_CHECKS = [
  "title",
  "description",
  "category",
  "attributes",
  "compatibility",
  "condition",
  "brand",
  "stock",
  "pricing",
  "shipping",
  "photos",
  "image-quality",
  "policies",
  "preview",
  "publish",
] as const;

export const UI_INTEGRITY_CHECKS = [
  "duplicated-ui",
  "duplicated-categories",
  "duplicated-sections",
  "empty-spaces",
  "broken-alignment",
  "broken-premium-styling",
  "dead-components",
  "hidden-containers",
  "viewport-waste",
  "responsive-problems",
] as const;

export const MARKETPLACE_COMPLETION_SCORES = [
  "architecture",
  "marketplace",
  "ui",
  "ux",
  "navigation",
  "performance",
  "accessibility",
  "seo",
  "security",
  "business-logic",
  "enterprise",
] as const;

export const MARKETPLACE_PRODUCTION_GATES = [
  "typecheck",
  "marketplace-tests",
  "infrastructure-tests",
  "e2e-tests",
  "enterprise-tests",
  "qa-validation",
  "security-validation",
  "governance-validation",
  "launch-readiness",
  "enterprise-certification",
] as const;

export const MARKETPLACE_RELEASE_BLOCKERS = [
  "critical-bugs",
  "broken-workflow",
  "broken-checkout",
  "broken-publish-flow",
  "broken-search",
  "broken-categories",
  "broken-listing",
  "broken-dashboard",
  "broken-notifications",
  "broken-messages",
  "critical-infrastructure-failures",
  "critical-security-findings",
  "critical-performance-regressions",
  "critical-accessibility-issues",
  "critical-seo-issues",
] as const;

export const REPORT_TYPES = [
  "completion",
  "modules",
  "journeys",
  "certification",
  "infrastructure",
  "ui-integrity",
  "launch-gate",
  "intelligence",
  "consistency",
  "cleanup",
  "modernization",
  "health-scores",
  "continuous-improvement",
  "director",
  "components",
  "workflows",
  "premium",
  "improvements",
  "certification-gate",
  "launch-mode",
  "zero-defect",
  "execution-release",
  "enterprise-delivery",
  "execution-mode",
  "homepage-completion",
  "category-completion",
  "search-completion",
  "listing-completion",
  "buyer-completion",
  "checkout-completion",
  "order-completion",
  "shipping-completion",
  "communication-completion",
] as const;
export const EXPORT_FORMATS = ["pdf", "excel", "csv", "json"] as const;

export const MARKETPLACE_INTELLIGENCE_DETECTIONS = [
  "missing-features",
  "incomplete-features",
  "legacy-components",
  "duplicate-components",
  "dead-code",
  "broken-components",
  "broken-buttons",
  "broken-routes",
  "broken-apis",
  "broken-database-relations",
  "broken-marketplace-rules",
  "missing-images",
  "missing-icons",
  "missing-categories",
  "missing-subcategories",
  "missing-seo",
  "missing-metadata",
  "missing-accessibility",
  "missing-responsive-layout",
  "missing-loading-states",
  "missing-empty-states",
  "missing-notifications",
  "missing-analytics",
  "missing-logs",
  "missing-audit-entries",
  "missing-ai-integration",
  "missing-validation",
  "missing-translation",
  "debug-components",
] as const;

export const MARKETPLACE_CONSISTENCY_DOMAINS = [
  "homepage",
  "categories",
  "search",
  "listings",
  "buyer",
  "seller",
  "company",
  "orders",
  "checkout",
  "wallet",
  "payments",
  "shipping",
  "messages",
  "notifications",
  "community",
  "business",
  "analytics",
] as const;

export const MARKETPLACE_CONSISTENCY_DIMENSIONS = [
  "visual",
  "functional",
  "enterprise",
  "premium-2026",
] as const;

export const CLEANUP_CATEGORIES = [
  "unused-components",
  "unused-css",
  "unused-images",
  "unused-icons",
  "unused-assets",
  "unused-apis",
  "unused-database-tables",
  "unused-routes",
  "unused-imports",
  "duplicate-files",
  "legacy-files",
  "temporary-files",
  "experimental-files",
  "debug-components",
  "orphan-components",
] as const;

export const MODERNIZATION_CATEGORIES = [
  "outdated-ui",
  "outdated-ux",
  "old-components",
  "old-animations",
  "old-layout",
  "old-cards",
  "old-tables",
  "old-forms",
  "old-navigation",
  "old-dialogs",
] as const;

export const ENTERPRISE_HEALTH_SCORES = [
  "marketplace",
  "homepage",
  "categories",
  "search",
  "buyer",
  "seller",
  "company",
  "checkout",
  "orders",
  "wallet",
  "infrastructure",
  "security",
  "performance",
  "seo",
  "accessibility",
  "architecture",
  "enterprise",
  "overall-platform",
] as const;

export const CONTINUOUS_IMPROVEMENT_TRIGGERS = [
  "commit",
  "merge",
  "pull-request",
  "deployment",
  "migration",
  "database-change",
  "component-change",
  "page-change",
  "api-change",
] as const;

export const FINAL_COMPLETION_RULES = [
  "no-legacy",
  "no-dead-code",
  "no-broken-routes",
  "no-broken-buttons",
  "no-broken-workflow",
  "no-duplicate-ui",
  "no-empty-layout",
  "no-missing-validation",
  "no-critical-security",
  "no-critical-performance",
  "no-critical-seo",
  "no-critical-accessibility",
  "no-critical-infrastructure",
  "pass-100",
  "enterprise-certified",
  "production-ready",
  "launch-ready",
] as const;

export const GLOBAL_MARKETPLACE_CONTROL = [
  { id: "homepage", label: "Homepage", pageRef: "app/page.tsx" },
  { id: "categories", label: "Categories", pageRef: "app/categories/page.tsx" },
  { id: "search", label: "Search", pageRef: "app/search/page.tsx" },
  { id: "listing-create", label: "Listing Create", pageRef: "app/sell/new/page.tsx" },
  { id: "listing-edit", label: "Listing Edit", pageRef: "app/seller/listings/page.tsx" },
  { id: "listing-preview", label: "Listing Preview", pageRef: "app/sell/new/page.tsx" },
  { id: "listing-publish", label: "Listing Publish", pageRef: "app/sell/page.tsx" },
  { id: "listing-details", label: "Listing Details", pageRef: "app/listing/[slug]/page.tsx" },
  { id: "buyer", label: "Buyer", pageRef: "app/account/page.tsx" },
  { id: "seller", label: "Seller", pageRef: "app/seller/dashboard/page.tsx" },
  { id: "company", label: "Company", pageRef: "app/business/dashboard/page.tsx" },
  { id: "business", label: "Business", pageRef: "app/business/center/page.tsx" },
  { id: "orders", label: "Orders", pageRef: "app/account/orders/page.tsx" },
  { id: "checkout", label: "Checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { id: "wallet", label: "Wallet", pageRef: "app/wallet/page.tsx" },
  { id: "payments", label: "Payments", pageRef: "app/account/payment-methods/page.tsx" },
  { id: "shipping", label: "Shipping", pageRef: "app/shipping/page.tsx" },
  { id: "returns", label: "Returns", pageRef: "app/resolution/page.tsx" },
  { id: "disputes", label: "Disputes", pageRef: "app/protection/page.tsx" },
  { id: "messages", label: "Messages", pageRef: "app/messages/page.tsx" },
  { id: "notifications", label: "Notifications", pageRef: "app/notifications/page.tsx" },
  { id: "community", label: "Community", pageRef: "app/trust/page.tsx" },
  { id: "help-center", label: "Help Center", pageRef: "app/help/page.tsx" },
  { id: "support", label: "Support", pageRef: "app/support/page.tsx" },
  { id: "analytics", label: "Analytics", pageRef: "app/seller/analytics/page.tsx" },
  { id: "marketplace-settings", label: "Marketplace Settings", pageRef: "app/account/settings/page.tsx" },
] as const;

export const AUTONOMOUS_DISCOVERY_CHECKS = [
  "missing-features",
  "incomplete-features",
  "missing-pages",
  "missing-components",
  "missing-apis",
  "missing-database-relations",
  "missing-validation",
  "missing-permissions",
  "missing-responsive-layout",
  "missing-accessibility",
  "missing-seo",
  "missing-metadata",
  "missing-categories",
  "missing-images",
  "missing-icons",
  "missing-loading-states",
  "missing-empty-states",
  "missing-analytics",
  "missing-notifications",
  "missing-logs",
  "missing-audit-trails",
  "missing-ai-integration",
] as const;

export const GLOBAL_COMPONENT_TYPES = [
  "page",
  "component",
  "card",
  "widget",
  "table",
  "form",
  "button",
  "dropdown",
  "dialog",
  "modal",
  "bottom-sheet",
  "drawer",
  "navigation",
  "search",
  "banner",
  "category",
  "listing",
  "dashboard",
] as const;

export const GLOBAL_BUTTON_INTERACTIONS = [
  "click",
  "tap",
  "hover",
  "focus",
  "keyboard",
  "redirect",
  "animation",
  "loading",
  "api",
  "database",
  "notification",
  "success",
  "failure",
  "retry",
  "offline",
  "permission",
] as const;

export const GLOBAL_WORKFLOW_JOURNEYS = [
  "buyer-journey",
  "seller-journey",
  "company-journey",
  "business-journey",
  "super-admin-journey",
  "checkout",
  "orders",
  "wallet",
  "payments",
  "shipping",
  "messaging",
  "notifications",
  "listing-publish",
  "ai-category",
  "ai-validation",
] as const;

export const GLOBAL_UI_INTEGRITY_CHECKS = [
  "duplicate-ui",
  "duplicate-categories",
  "duplicate-cards",
  "duplicate-sections",
  "duplicate-widgets",
  "duplicate-menus",
  "duplicate-icons",
  "duplicate-routes",
  "duplicate-seo",
  "duplicate-metadata",
  "duplicate-components",
  "unused-containers",
  "empty-layout-areas",
  "viewport-waste",
  "broken-alignment",
  "broken-premium-styling",
  "dead-components",
  "legacy-components",
] as const;

export const PREMIUM_CONSISTENCY_CHECKS = [
  "spacing",
  "typography",
  "cards",
  "radius",
  "icons",
  "colors",
  "animations",
  "responsive",
  "safe-area",
  "visual-rhythm",
  "design-language",
] as const;

export const GLOBAL_INFRASTRUCTURE_CHECKS = [
  "email",
  "smtp",
  "cron-jobs",
  "workers",
  "queues",
  "redis",
  "storage",
  "database",
  "indexes",
  "caching",
  "pwa",
  "manifest",
  "service-worker",
  "offline-mode",
  "push-notifications",
  "health-checks",
  "search-index",
  "seo",
  "security",
  "environment-variables",
  "deployment-configuration",
  "cdn",
  "monitoring",
  "logging",
  "tracing",
  "alerts",
] as const;

export const SMART_IMPROVEMENT_CATEGORIES = [
  "ui-improvements",
  "ux-improvements",
  "architecture-improvements",
  "performance-improvements",
  "security-improvements",
  "seo-improvements",
  "accessibility-improvements",
  "database-improvements",
  "infrastructure-improvements",
  "marketplace-improvements",
  "scalability-improvements",
  "maintainability-improvements",
] as const;

export const DIRECTOR_DASHBOARD_SCORES = [
  "homepage",
  "categories",
  "search",
  "listings",
  "buyer",
  "seller",
  "company",
  "checkout",
  "orders",
  "wallet",
  "payments",
  "infrastructure",
  "performance",
  "security",
  "seo",
  "accessibility",
  "architecture",
  "marketplace",
  "enterprise",
  "overall-platform",
] as const;

export const FINAL_CERTIFICATION_GATES = [
  "no-legacy-components",
  "no-dead-code",
  "no-broken-buttons",
  "no-broken-routes",
  "no-broken-workflow",
  "no-duplicate-ui",
  "no-empty-layout",
  "no-critical-security",
  "no-critical-performance",
  "no-critical-accessibility",
  "no-critical-seo",
  "no-critical-infrastructure",
  "no-missing-validation",
  "no-missing-business-rules",
  "no-missing-marketplace-features",
  "qa-pass-100",
  "security-pass-100",
  "governance-pass-100",
  "performance-pass-100",
  "accessibility-pass-100",
  "seo-pass-100",
  "infrastructure-pass-100",
  "marketplace-pass-100",
  "enterprise-pass-100",
  "omega-pass-100",
  "overall-platform-pass-100",
] as const;

export const AUTONOMOUS_SAFE_REPAIR_ACTIONS = [
  "repair-duplicate-rendering",
  "repair-layout-spacing",
  "repair-alignment",
  "repair-cache",
  "warm-cache",
  "restart-failed-workers",
  "restart-cron-jobs",
  "repair-search-indexes",
  "repair-missing-metadata",
  "repair-responsive-layout",
  "repair-premium-inconsistencies",
] as const;

export const LAUNCH_PRIORITIES = [
  { priority: 1, id: "homepage", label: "Homepage", pageRef: "app/page.tsx" },
  { priority: 2, id: "categories", label: "Categories", pageRef: "app/categories/page.tsx" },
  { priority: 3, id: "search", label: "Search", pageRef: "app/search/page.tsx" },
  { priority: 4, id: "listing-create", label: "Listing Create", pageRef: "app/sell/new/page.tsx" },
  { priority: 5, id: "listing-publish", label: "Listing Publish", pageRef: "app/sell/page.tsx" },
  { priority: 6, id: "buyer-dashboard", label: "Buyer Dashboard", pageRef: "app/account/page.tsx" },
  { priority: 7, id: "seller-dashboard", label: "Seller Dashboard", pageRef: "app/seller/dashboard/page.tsx" },
  { priority: 8, id: "company-dashboard", label: "Company Dashboard", pageRef: "app/business/dashboard/page.tsx" },
  { priority: 9, id: "checkout", label: "Checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { priority: 10, id: "orders", label: "Orders", pageRef: "app/account/orders/page.tsx" },
  { priority: 11, id: "wallet", label: "Wallet", pageRef: "app/wallet/page.tsx" },
  { priority: 12, id: "payments", label: "Payments", pageRef: "app/account/payment-methods/page.tsx" },
  { priority: 13, id: "shipping", label: "Shipping", pageRef: "app/shipping/page.tsx" },
  { priority: 14, id: "messages", label: "Messages", pageRef: "app/messages/page.tsx" },
  { priority: 15, id: "notifications", label: "Notifications", pageRef: "app/notifications/page.tsx" },
  { priority: 16, id: "community", label: "Community", pageRef: "app/trust/page.tsx" },
  { priority: 17, id: "business-center", label: "Business Center", pageRef: "app/business/center/page.tsx" },
  { priority: 18, id: "final-launch-certification", label: "Final Launch Certification", pageRef: "app/super-admin/marketplace-completion/page.tsx" },
] as const;

export const MODULE_SCAN_TYPES = [
  "architecture-scan",
  "ui-scan",
  "ux-scan",
  "duplicate-scan",
  "layout-scan",
  "button-scan",
  "route-scan",
  "api-scan",
  "database-scan",
  "seo-scan",
  "accessibility-scan",
  "performance-scan",
  "security-scan",
  "infrastructure-scan",
  "enterprise-validation",
  "e2e-validation",
  "regression-validation",
  "certification-validation",
] as const;

export const GLOBAL_UI_QUALITY_CHECKS = [
  "duplicated-ui",
  "duplicated-categories",
  "duplicated-sections",
  "duplicated-cards",
  "duplicated-widgets",
  "duplicated-menus",
  "duplicated-icons",
  "duplicated-routes",
  "duplicated-seo",
  "broken-premium-layout",
  "broken-alignment",
  "unused-containers",
  "empty-layout-areas",
  "hidden-components",
  "broken-responsive-layout",
  "legacy-components",
] as const;

export const GLOBAL_UX_QUALITY_CHECKS = [
  "click",
  "tap",
  "hover",
  "focus",
  "keyboard",
  "loading",
  "error",
  "offline",
  "success",
  "retry",
  "animation",
  "permission",
  "redirect",
  "api",
  "database",
  "notification",
] as const;

export const MARKETPLACE_RULES = [
  "categories",
  "subcategories",
  "listings",
  "images",
  "ai-category",
  "ai-validation",
  "stock",
  "price",
  "shipping",
  "compatibility",
  "policies",
  "buyer-protection",
  "trust-score",
  "orders",
  "payments",
  "wallet",
  "search",
  "homepage",
  "featured",
  "recommended",
] as const;

export const LAUNCH_BLOCKERS = [
  "critical-bugs",
  "broken-buttons",
  "broken-routes",
  "broken-checkout",
  "broken-search",
  "broken-categories",
  "broken-listing-publish",
  "broken-buyer-flow",
  "broken-seller-flow",
  "broken-company-flow",
  "critical-security-findings",
  "critical-infrastructure-issues",
  "critical-performance-issues",
  "critical-accessibility-issues",
  "critical-seo-issues",
  "critical-database-issues",
  "critical-email-issues",
  "critical-queue-failures",
  "critical-cron-failures",
  "critical-push-failures",
] as const;

export const LAUNCH_CERTIFICATION_SCORES = [
  "architecture",
  "marketplace",
  "ui",
  "ux",
  "navigation",
  "performance",
  "accessibility",
  "seo",
  "security",
  "infrastructure",
  "business-logic",
  "enterprise",
] as const;

export const LAUNCH_RULE_REQUIREMENTS = [
  "homepage-pass-100",
  "categories-pass-100",
  "search-pass-100",
  "listings-pass-100",
  "buyer-pass-100",
  "seller-pass-100",
  "company-pass-100",
  "checkout-pass-100",
  "orders-pass-100",
  "wallet-pass-100",
  "payments-pass-100",
  "shipping-pass-100",
  "messages-pass-100",
  "notifications-pass-100",
  "infrastructure-pass-100",
  "qa-pass-100",
  "security-pass-100",
  "governance-pass-100",
  "accessibility-pass-100",
  "performance-pass-100",
  "seo-pass-100",
  "enterprise-pass-100",
  "omega-pass-100",
  "production-ready",
  "launch-ready",
] as const;

export const LAUNCH_REPORT_SECTIONS = [
  "homepage-completion",
  "categories-completion",
  "search-completion",
  "listing-completion",
  "buyer-completion",
  "seller-completion",
  "company-completion",
  "checkout-completion",
  "orders-completion",
  "wallet-completion",
  "payments-completion",
  "shipping-completion",
  "messages-completion",
  "notifications-completion",
  "community-completion",
  "infrastructure-completion",
  "overall-marketplace-completion",
  "enterprise-readiness",
  "production-readiness",
  "launch-readiness",
] as const;

export const LAUNCH_SAFE_REPAIR_ACTIONS = [
  "remove-duplicate-rendering",
  "compress-empty-layouts",
  "optimise-spacing",
  "optimise-cache",
  "warm-cache",
  "restart-failed-workers",
  "restart-failed-cron-jobs",
  "rebuild-search-indexes",
  "repair-premium-inconsistencies",
  "repair-responsive-layouts",
  "revalidate-affected-module",
] as const;

export const ZERO_DEFECT_SCAN_DOMAINS = [
  { id: "homepage", label: "Homepage", pageRef: "app/page.tsx" },
  { id: "categories", label: "Categories", pageRef: "app/categories/page.tsx" },
  { id: "search", label: "Search", pageRef: "app/search/page.tsx" },
  { id: "listing-create", label: "Listing Create", pageRef: "app/sell/new/page.tsx" },
  { id: "listing-edit", label: "Listing Edit", pageRef: "app/seller/listings/page.tsx" },
  { id: "listing-publish", label: "Listing Publish", pageRef: "app/sell/page.tsx" },
  { id: "listing-details", label: "Listing Details", pageRef: "app/listing/[slug]/page.tsx" },
  { id: "buyer", label: "Buyer", pageRef: "app/account/page.tsx" },
  { id: "seller", label: "Seller", pageRef: "app/seller/dashboard/page.tsx" },
  { id: "company", label: "Company", pageRef: "app/business/dashboard/page.tsx" },
  { id: "business", label: "Business", pageRef: "app/business/center/page.tsx" },
  { id: "orders", label: "Orders", pageRef: "app/account/orders/page.tsx" },
  { id: "checkout", label: "Checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { id: "wallet", label: "Wallet", pageRef: "app/wallet/page.tsx" },
  { id: "payments", label: "Payments", pageRef: "app/account/payment-methods/page.tsx" },
  { id: "shipping", label: "Shipping", pageRef: "app/shipping/page.tsx" },
  { id: "messages", label: "Messages", pageRef: "app/messages/page.tsx" },
  { id: "notifications", label: "Notifications", pageRef: "app/notifications/page.tsx" },
  { id: "community", label: "Community", pageRef: "app/trust/page.tsx" },
  { id: "help-center", label: "Help Center", pageRef: "app/help/page.tsx" },
  { id: "support", label: "Support", pageRef: "app/support/page.tsx" },
  { id: "super-admin", label: "Super Admin", pageRef: "app/super-admin/marketplace-completion/page.tsx" },
  { id: "omega-centers", label: "OMEGA Centers", pageRef: "app/super-admin/launch-readiness/page.tsx" },
] as const;

export const DEFECT_DISCOVERY_CHECKS = [
  "broken-buttons",
  "broken-routes",
  "broken-links",
  "broken-apis",
  "broken-database-relations",
  "broken-ui",
  "broken-ux",
  "broken-forms",
  "broken-validation",
  "broken-navigation",
  "broken-search",
  "broken-filters",
  "broken-categories",
  "broken-listings",
  "broken-checkout",
  "broken-payments",
  "broken-wallet",
  "broken-shipping",
  "broken-messaging",
  "broken-notifications",
  "broken-responsive-layout",
  "broken-accessibility",
  "broken-seo",
  "broken-analytics",
  "broken-permissions",
  "broken-authentication",
  "broken-authorization",
  "broken-webhooks",
  "broken-background-jobs",
] as const;

export const QUALITY_VALIDATION_CHECKS = [
  "button",
  "card",
  "menu",
  "dropdown",
  "modal",
  "drawer",
  "dialog",
  "route",
  "api",
  "database-query",
  "marketplace-rule",
  "business-rule",
  "role-permission",
  "notification",
  "email",
  "push-notification",
  "scheduled-job",
] as const;

export const REGRESSION_SCAN_TYPES = [
  "regression-scan",
  "ui-scan",
  "ux-scan",
  "infrastructure-scan",
  "security-scan",
  "performance-scan",
  "accessibility-scan",
  "seo-scan",
  "marketplace-scan",
  "e2e-validation",
] as const;

export const BUG_CLASSIFICATIONS = [
  "critical",
  "high",
  "medium",
  "low",
  "cosmetic",
  "infrastructure",
  "security",
  "performance",
  "accessibility",
  "seo",
  "marketplace",
  "business-logic",
  "database",
  "api",
] as const;

export const REPAIR_WORKFLOW_STEPS = [
  "identify",
  "analyse",
  "classify",
  "estimate-impact",
  "suggest-repair",
  "validate-repair",
  "re-test",
  "re-certify",
  "update-enterprise-score",
] as const;

export const ZERO_DEFECT_SAFE_REPAIR_ACTIONS = [
  "repair-duplicate-rendering",
  "repair-layout-spacing",
  "repair-premium-ui-consistency",
  "repair-responsive-alignment",
  "repair-cache",
  "repair-search-indexes",
  "restart-workers",
  "restart-cron",
  "repair-metadata",
] as const;

export const ENTERPRISE_REPORT_METRICS = [
  "open-defects",
  "resolved-defects",
  "critical-defects",
  "regression-status",
  "marketplace-health",
  "infrastructure-health",
  "security-health",
  "performance-health",
  "seo-health",
  "accessibility-health",
  "overall-platform-health",
] as const;

export const ZERO_DEFECT_GATES = [
  "critical-defects-zero",
  "broken-checkout",
  "broken-listing-publish",
  "broken-search",
  "broken-homepage",
  "broken-categories",
  "broken-buyer-journey",
  "broken-seller-journey",
  "broken-company-journey",
  "critical-security-findings",
  "critical-infrastructure-failures",
  "critical-performance-regressions",
  "critical-accessibility-issues",
  "critical-seo-issues",
] as const;

export const ZERO_DEFECT_CERTIFICATION_REQUIREMENTS = [
  "critical-defects-zero",
  "high-priority-defects-zero",
  "marketplace-pass-100",
  "infrastructure-pass-100",
  "qa-pass-100",
  "security-pass-100",
  "performance-pass-100",
  "accessibility-pass-100",
  "seo-pass-100",
  "governance-pass-100",
  "e2e-pass-100",
  "overall-enterprise-pass-100",
] as const;

export const EXECUTION_BOARD_QUEUES = [
  "global-roadmap",
  "sprint-progress",
  "module-progress",
  "feature-progress",
  "task-queue",
  "blocked-tasks",
  "dependencies",
  "regression-queue",
  "qa-queue",
  "security-queue",
  "seo-queue",
  "accessibility-queue",
  "infrastructure-queue",
  "certification-queue",
  "release-queue",
] as const;

export const EXECUTION_MODULE_TRACKING = [
  { id: "homepage", label: "Homepage", pageRef: "app/page.tsx" },
  { id: "categories", label: "Categories", pageRef: "app/categories/page.tsx" },
  { id: "search", label: "Search", pageRef: "app/search/page.tsx" },
  { id: "listing-create", label: "Listing Create", pageRef: "app/sell/new/page.tsx" },
  { id: "listing-edit", label: "Listing Edit", pageRef: "app/seller/listings/page.tsx" },
  { id: "listing-publish", label: "Listing Publish", pageRef: "app/sell/page.tsx" },
  { id: "listing-details", label: "Listing Details", pageRef: "app/listing/[slug]/page.tsx" },
  { id: "buyer-dashboard", label: "Buyer Dashboard", pageRef: "app/account/page.tsx" },
  { id: "seller-dashboard", label: "Seller Dashboard", pageRef: "app/seller/dashboard/page.tsx" },
  { id: "company-dashboard", label: "Company Dashboard", pageRef: "app/business/dashboard/page.tsx" },
  { id: "orders", label: "Orders", pageRef: "app/account/orders/page.tsx" },
  { id: "checkout", label: "Checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { id: "wallet", label: "Wallet", pageRef: "app/wallet/page.tsx" },
  { id: "payments", label: "Payments", pageRef: "app/account/payment-methods/page.tsx" },
  { id: "shipping", label: "Shipping", pageRef: "app/shipping/page.tsx" },
  { id: "returns", label: "Returns", pageRef: "app/resolution/page.tsx" },
  { id: "disputes", label: "Disputes", pageRef: "app/protection/page.tsx" },
  { id: "messages", label: "Messages", pageRef: "app/messages/page.tsx" },
  { id: "notifications", label: "Notifications", pageRef: "app/notifications/page.tsx" },
  { id: "community", label: "Community", pageRef: "app/trust/page.tsx" },
  { id: "support", label: "Support", pageRef: "app/support/page.tsx" },
  { id: "business-center", label: "Business Center", pageRef: "app/business/center/page.tsx" },
  { id: "analytics", label: "Analytics", pageRef: "app/seller/analytics/page.tsx" },
  { id: "super-admin", label: "Super Admin", pageRef: "app/super-admin/marketplace-completion/page.tsx" },
] as const;

export const FEATURE_COMPLETION_CHECKS = [
  "ui-complete",
  "ux-complete",
  "business-logic-complete",
  "api-complete",
  "database-complete",
  "permissions-complete",
  "responsive-complete",
  "accessibility-complete",
  "seo-complete",
  "infrastructure-complete",
  "documentation-complete",
  "testing-complete",
] as const;

export const IMPLEMENTATION_CONTROL_CHECKS = [
  "architecture-review",
  "code-review",
  "typecheck",
  "build",
  "unit-tests",
  "integration-tests",
  "regression-tests",
  "end-to-end-tests",
  "performance-validation",
  "accessibility-validation",
  "seo-validation",
  "security-validation",
  "governance-validation",
  "infrastructure-validation",
  "marketplace-validation",
  "certification-validation",
] as const;

export const QUALITY_DASHBOARD_METRICS = [
  "overall-marketplace",
  "homepage",
  "categories",
  "search",
  "listing",
  "buyer",
  "seller",
  "company",
  "checkout",
  "orders",
  "wallet",
  "payments",
  "shipping",
  "infrastructure",
  "qa",
  "security",
  "seo",
  "performance",
  "accessibility",
  "enterprise",
  "launch",
] as const;

export const RELEASE_READINESS_CHECKS = [
  "critical-bugs",
  "open-bugs",
  "blocked-tasks",
  "infrastructure-issues",
  "security-issues",
  "performance-issues",
  "seo-issues",
  "accessibility-issues",
  "marketplace-completion",
  "deployment-readiness",
] as const;

export const EXECUTION_SAFE_ACTIONS = [
  "run-validations",
  "generate-reports",
  "detect-missing-implementation",
  "generate-implementation-recommendations",
  "prioritise-work",
  "optimise-execution-order",
  "re-run-validation-after-changes",
] as const;

export const RELEASE_GATES = [
  "critical-defects-zero",
  "launch-critical-workflows-complete",
  "homepage-complete",
  "search-complete",
  "listing-publish-complete",
  "checkout-complete",
  "payments-complete",
  "security-pass",
  "performance-pass",
  "accessibility-pass",
  "seo-pass",
  "infrastructure-pass",
  "enterprise-pass",
] as const;

export const RELEASE_SUCCESS_CRITERIA = [
  "marketplace-completion-100",
  "infrastructure-pass",
  "qa-pass",
  "security-pass",
  "performance-pass",
  "accessibility-pass",
  "seo-pass",
  "governance-pass",
  "e2e-pass",
  "enterprise-certification-pass",
  "production-build-pass",
  "zero-critical-defects",
  "release-approved",
] as const;

export const DELIVERY_MANAGEMENT_QUEUES = [
  "master-roadmap",
  "sprint-progress",
  "module-progress",
  "feature-progress",
  "task-queue",
  "blocked-queue",
  "dependency-queue",
  "regression-queue",
  "security-queue",
  "qa-queue",
  "infrastructure-queue",
  "certification-queue",
  "release-queue",
  "technical-debt-queue",
  "optimization-queue",
] as const;

export const AUTONOMOUS_FEATURE_DISCOVERY = [
  "missing-features",
  "incomplete-features",
  "missing-components",
  "missing-pages",
  "missing-routes",
  "missing-apis",
  "missing-database-relations",
  "missing-validation",
  "missing-permissions",
  "missing-responsive-layout",
  "missing-accessibility",
  "missing-seo",
  "missing-metadata",
  "missing-analytics",
  "missing-notifications",
  "missing-monitoring",
  "missing-logging",
  "missing-health-checks",
  "missing-infrastructure",
  "missing-enterprise-integration",
] as const;

export const PLATFORM_VALIDATION_DOMAINS = [
  { id: "homepage", label: "Homepage", pageRef: "app/page.tsx" },
  { id: "categories", label: "Categories", pageRef: "app/categories/page.tsx" },
  { id: "search", label: "Search", pageRef: "app/search/page.tsx" },
  { id: "listing-create", label: "Listing Create", pageRef: "app/sell/new/page.tsx" },
  { id: "listing-edit", label: "Listing Edit", pageRef: "app/seller/listings/page.tsx" },
  { id: "listing-publish", label: "Listing Publish", pageRef: "app/sell/page.tsx" },
  { id: "listing-details", label: "Listing Details", pageRef: "app/listing/[slug]/page.tsx" },
  { id: "buyer-dashboard", label: "Buyer Dashboard", pageRef: "app/account/page.tsx" },
  { id: "seller-dashboard", label: "Seller Dashboard", pageRef: "app/seller/dashboard/page.tsx" },
  { id: "company-dashboard", label: "Company Dashboard", pageRef: "app/business/dashboard/page.tsx" },
  { id: "orders", label: "Orders", pageRef: "app/account/orders/page.tsx" },
  { id: "checkout", label: "Checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { id: "wallet", label: "Wallet", pageRef: "app/wallet/page.tsx" },
  { id: "payments", label: "Payments", pageRef: "app/account/payment-methods/page.tsx" },
  { id: "shipping", label: "Shipping", pageRef: "app/shipping/page.tsx" },
  { id: "returns", label: "Returns", pageRef: "app/resolution/page.tsx" },
  { id: "disputes", label: "Disputes", pageRef: "app/protection/page.tsx" },
  { id: "messaging", label: "Messaging", pageRef: "app/messages/page.tsx" },
  { id: "notifications", label: "Notifications", pageRef: "app/notifications/page.tsx" },
  { id: "community", label: "Community", pageRef: "app/trust/page.tsx" },
  { id: "support", label: "Support", pageRef: "app/support/page.tsx" },
  { id: "business-center", label: "Business Center", pageRef: "app/business/center/page.tsx" },
  { id: "analytics", label: "Analytics", pageRef: "app/seller/analytics/page.tsx" },
  { id: "super-admin", label: "Super Admin", pageRef: "app/super-admin/marketplace-completion/page.tsx" },
  { id: "enterprise-modules", label: "Enterprise Modules", pageRef: "app/super-admin/launch-readiness/page.tsx" },
] as const;

export const GLOBAL_UI_VALIDATION_CHECKS = [
  "every-page",
  "every-card",
  "every-component",
  "every-button",
  "every-icon",
  "every-form",
  "every-table",
  "every-widget",
  "every-modal",
  "every-drawer",
  "every-banner",
  "every-category",
  "every-listing",
  "every-dashboard",
  "every-navigation-item",
] as const;

export const GLOBAL_UX_VALIDATION_CHECKS = [
  "click",
  "tap",
  "hover",
  "focus",
  "keyboard",
  "loading",
  "error",
  "offline",
  "retry",
  "animation",
  "permission",
  "redirect",
  "api",
  "database",
  "notification",
  "success",
  "failure",
] as const;

export const GLOBAL_MARKETPLACE_VALIDATION_CHECKS = [
  "categories",
  "search",
  "filters",
  "listings",
  "photos",
  "ai-category",
  "ai-validation",
  "stock",
  "pricing",
  "shipping",
  "compatibility",
  "wishlist",
  "cart",
  "checkout",
  "payments",
  "wallet",
  "orders",
  "tracking",
  "buyer-protection",
  "trust-score",
  "reviews",
  "messages",
  "notifications",
] as const;

export const ENTERPRISE_INFRASTRUCTURE_CHECKS = [
  "smtp",
  "email",
  "email-queue",
  "templates",
  "spf",
  "dkim",
  "dmarc",
  "cron-jobs",
  "queues",
  "workers",
  "redis",
  "caching",
  "cdn",
  "pwa",
  "manifest",
  "service-worker",
  "offline",
  "push-notifications",
  "health-checks",
  "monitoring",
  "tracing",
  "logging",
  "database",
  "indexes",
  "storage",
  "environment-variables",
  "deployment-configuration",
  "search-index",
  "seo",
  "security",
] as const;

export const OMEGA_GLOBAL_INTEGRITY_CHECKS = [
  "duplicate-ui",
  "duplicate-categories",
  "duplicate-components",
  "duplicate-routes",
  "duplicate-metadata",
  "duplicate-seo",
  "duplicate-assets",
  "dead-code",
  "unused-css",
  "unused-components",
  "unused-files",
  "unused-images",
  "unused-apis",
  "unused-imports",
  "legacy-components",
  "broken-components",
  "broken-routes",
  "broken-buttons",
  "broken-workflow",
  "broken-responsive",
  "empty-layout",
  "viewport-waste",
] as const;

export const DELIVERY_SAFE_OPTIMIZATION_ACTIONS = [
  "optimize-layout",
  "optimize-premium-ui",
  "optimize-responsive",
  "optimize-performance",
  "optimize-cache",
  "optimize-images",
  "optimize-search-index",
  "optimize-database-indexes",
  "restart-workers",
  "restart-cron-jobs",
  "warm-cache",
  "rebuild-metadata",
  "revalidate-modules",
  "generate-repair-plan",
] as const;

export const EXECUTIVE_DASHBOARD_METRICS = [
  "homepage-completion",
  "categories-completion",
  "search-completion",
  "listing-completion",
  "buyer-completion",
  "seller-completion",
  "company-completion",
  "checkout-completion",
  "orders-completion",
  "wallet-completion",
  "payments-completion",
  "shipping-completion",
  "messaging-completion",
  "notifications-completion",
  "community-completion",
  "infrastructure-completion",
  "security-completion",
  "seo-completion",
  "accessibility-completion",
  "performance-completion",
  "enterprise-completion",
  "overall-platform-completion",
  "launch-readiness",
] as const;

export const DELIVERY_ZERO_DEFECT_POLICY = [
  "critical-bugs",
  "critical-security-findings",
  "critical-infrastructure-failures",
  "critical-performance-regressions",
  "critical-accessibility-issues",
  "critical-seo-issues",
  "broken-homepage",
  "broken-search",
  "broken-categories",
  "broken-listing-publish",
  "broken-checkout",
  "broken-payments",
  "broken-wallet",
  "broken-orders",
  "broken-shipping",
  "broken-buyer-journey",
  "broken-seller-journey",
  "broken-company-journey",
  "broken-notifications",
  "broken-messages",
  "broken-enterprise-modules",
] as const;

export const FINAL_RELEASE_GATE_REQUIREMENTS = [
  "marketplace-completion-100",
  "infrastructure-pass",
  "homepage-pass",
  "categories-pass",
  "search-pass",
  "listings-pass",
  "buyer-pass",
  "seller-pass",
  "company-pass",
  "checkout-pass",
  "orders-pass",
  "wallet-pass",
  "payments-pass",
  "shipping-pass",
  "messaging-pass",
  "notifications-pass",
  "qa-pass",
  "security-pass",
  "performance-pass",
  "accessibility-pass",
  "seo-pass",
  "governance-pass",
  "enterprise-pass",
  "omega-pass",
  "zero-critical-defects",
  "production-build-pass",
  "release-approved",
] as const;

export const AUTONOMOUS_EXECUTION_CYCLE_STEPS = [
  "discover",
  "plan",
  "prioritize",
  "implement",
  "validate",
  "optimize",
  "retest",
  "certify",
  "report",
  "repeat",
] as const;

export const EXECUTION_MODE_PRIORITIES = [
  { priority: 1, id: "homepage", label: "Homepage", pageRef: "app/page.tsx" },
  { priority: 2, id: "categories", label: "Categories", pageRef: "app/categories/page.tsx" },
  { priority: 3, id: "search", label: "Search", pageRef: "app/search/page.tsx" },
  { priority: 4, id: "listing-create", label: "Listing Create", pageRef: "app/sell/new/page.tsx" },
  { priority: 5, id: "listing-publish", label: "Listing Publish", pageRef: "app/sell/page.tsx" },
  { priority: 6, id: "buyer", label: "Buyer", pageRef: "app/account/page.tsx" },
  { priority: 7, id: "seller", label: "Seller", pageRef: "app/seller/dashboard/page.tsx" },
  { priority: 8, id: "company", label: "Company", pageRef: "app/business/dashboard/page.tsx" },
  { priority: 9, id: "checkout", label: "Checkout", pageRef: "app/checkout/[slug]/page.tsx" },
  { priority: 10, id: "orders", label: "Orders", pageRef: "app/account/orders/page.tsx" },
  { priority: 11, id: "wallet", label: "Wallet", pageRef: "app/wallet/page.tsx" },
  { priority: 12, id: "payments", label: "Payments", pageRef: "app/account/payment-methods/page.tsx" },
  { priority: 13, id: "shipping", label: "Shipping", pageRef: "app/shipping/page.tsx" },
  { priority: 14, id: "messages", label: "Messages", pageRef: "app/messages/page.tsx" },
  { priority: 15, id: "notifications", label: "Notifications", pageRef: "app/notifications/page.tsx" },
  { priority: 16, id: "community", label: "Community", pageRef: "app/trust/page.tsx" },
  { priority: 17, id: "business", label: "Business", pageRef: "app/business/center/page.tsx" },
  { priority: 18, id: "launch-certification", label: "Launch Certification", pageRef: "app/super-admin/marketplace-completion/page.tsx" },
] as const;

export const MODULE_SCAN_LAYERS = [
  "architecture",
  "ui",
  "ux",
  "navigation",
  "buttons",
  "routes",
  "apis",
  "database",
  "seo",
  "accessibility",
  "performance",
  "security",
  "infrastructure",
  "qa",
  "governance",
  "e2e",
  "enterprise-certification",
] as const;

export const EXECUTION_GLOBAL_IMPROVEMENTS = [
  "duplicate-ui",
  "duplicate-categories",
  "duplicate-components",
  "duplicate-assets",
  "unused-components",
  "unused-css",
  "unused-imports",
  "unused-images",
  "legacy-code",
  "dead-code",
  "broken-buttons",
  "broken-routes",
  "broken-workflow",
  "broken-redirects",
  "broken-api",
  "broken-validation",
  "broken-responsive",
  "empty-layout",
  "viewport-waste",
  "premium-inconsistencies",
] as const;

export const EXECUTION_SAFE_AUTOMATION = [
  "optimize-layout",
  "optimize-spacing",
  "optimize-cache",
  "optimize-images",
  "optimize-metadata",
  "optimize-search-indexes",
  "restart-failed-workers",
  "restart-failed-cron-jobs",
  "warm-cache",
  "revalidate-affected-module",
] as const;

export const EXECUTION_INFRASTRUCTURE_VALIDATION = [
  "smtp",
  "transactional-email",
  "email-queue",
  "spf",
  "dkim",
  "dmarc",
  "cron-jobs",
  "queue-workers",
  "redis",
  "caching",
  "cdn",
  "database",
  "indexes",
  "storage",
  "pwa",
  "manifest",
  "service-worker",
  "offline-mode",
  "push-notifications",
  "search-index",
  "monitoring",
  "tracing",
  "logging",
  "health-checks",
  "environment-variables",
  "deployment-configuration",
] as const;

export const EXECUTION_DASHBOARD_METRICS = [
  "overall-completion",
  "homepage",
  "categories",
  "search",
  "listings",
  "buyer",
  "seller",
  "company",
  "checkout",
  "orders",
  "wallet",
  "payments",
  "shipping",
  "messages",
  "notifications",
  "community",
  "infrastructure",
  "security",
  "performance",
  "accessibility",
  "seo",
  "enterprise",
  "launch-readiness",
] as const;

export const EXECUTION_RELEASE_POLICY = [
  "critical-bugs",
  "critical-security-findings",
  "critical-infrastructure-failures",
  "critical-performance-regressions",
  "critical-accessibility-issues",
  "critical-seo-issues",
  "critical-business-workflow-failures",
] as const;

export const EXECUTION_FINAL_SUCCESS = [
  "marketplace-completion-100",
  "homepage-pass",
  "categories-pass",
  "search-pass",
  "listings-pass",
  "buyer-pass",
  "seller-pass",
  "company-pass",
  "checkout-pass",
  "orders-pass",
  "wallet-pass",
  "payments-pass",
  "shipping-pass",
  "messaging-pass",
  "notifications-pass",
  "infrastructure-pass",
  "qa-pass",
  "security-pass",
  "performance-pass",
  "accessibility-pass",
  "seo-pass",
  "governance-pass",
  "enterprise-pass",
  "production-build-pass",
  "zero-critical-defects",
  "enterprise-certified",
  "production-ready",
  "launch-ready",
] as const;

export const GLOBAL_HOMEPAGE_SCAN_COMPONENTS = [
  { id: "header", label: "Header", ref: "components/home/HomePageShell.tsx" },
  { id: "search", label: "Search", ref: "components/header/HeaderSearchBar.tsx" },
  { id: "category-rail", label: "Category Rail", ref: "components/home/RovexoCategoryRail.tsx" },
  { id: "category-drawer", label: "Category Drawer", ref: "components/home/RovexoCategoryRail.tsx" },
  { id: "hero-banner", label: "Hero Banner", ref: "features/seller/migration/components/StoreMigrationHeroBanner.tsx" },
  { id: "featured-listings", label: "Featured Listings", ref: "components/home/RovexoAllListings.tsx" },
  { id: "recommended-listings", label: "Recommended Listings", ref: "components/home/RovexoAllListings.tsx" },
  { id: "recently-added", label: "Recently Added", ref: "components/home/RovexoAllListings.tsx" },
  { id: "trending", label: "Trending", ref: "components/home/RovexoAllListings.tsx" },
  { id: "all-listings", label: "All Listings", ref: "components/home/RovexoAllListings.tsx" },
  { id: "popular-categories", label: "Popular Categories", ref: "components/home/RovexoCategoryRail.tsx" },
  { id: "business-banner", label: "Business Banner", ref: "components/home/RovexoAllListings.tsx" },
  { id: "promotions", label: "Promotions", ref: "components/home/RovexoAllListings.tsx" },
  { id: "footer", label: "Footer", ref: "app/page.tsx" },
  { id: "bottom-navigation", label: "Bottom Navigation", ref: "components/home/RovexoFooterNavigation.tsx" },
  { id: "floating-actions", label: "Floating Actions", ref: "components/ui/Button.tsx" },
  { id: "widgets", label: "Widgets", ref: "components/home/RovexoHomePage.tsx" },
] as const;

export const HOMEPAGE_VISUAL_INTEGRITY_CHECKS = [
  "duplicate-categories",
  "duplicate-sections",
  "duplicate-cards",
  "duplicate-widgets",
  "duplicate-banners",
  "duplicate-icons",
  "duplicate-buttons",
  "unused-containers",
  "invisible-components",
  "legacy-components",
  "dead-components",
  "empty-layout-areas",
  "viewport-waste",
  "incorrect-padding",
  "incorrect-margin",
  "broken-alignment",
  "broken-grid",
  "broken-responsive-layout",
] as const;

export const HOMEPAGE_SEARCH_VALIDATION = [
  "search-bar",
  "suggestions",
  "autocomplete",
  "history",
  "voice-search",
  "image-search",
  "loading-state",
  "error-state",
  "empty-state",
  "routing",
  "performance",
] as const;

export const HOMEPAGE_CATEGORY_VALIDATION = [
  "single-category-rail",
  "no-duplicated-category-sections",
  "correct-hierarchy",
  "correct-icons",
  "correct-translations",
  "correct-routing",
  "correct-seo",
  "correct-responsive-layout",
  "correct-spacing",
  "correct-ordering",
  "correct-scroll-behaviour",
] as const;

export const HOMEPAGE_LAYOUT_VALIDATION = [
  "no-empty-space-above-search",
  "no-duplicated-category-rows",
  "no-duplicated-widgets",
  "consistent-premium-spacing",
  "consistent-card-sizes",
  "consistent-icon-sizes",
  "consistent-typography",
  "consistent-animations",
  "safe-area-compliance",
  "premium-2026-design-language",
] as const;

export const HOMEPAGE_FEATURED_CONTENT = [
  "featured-listings",
  "recommended-listings",
  "latest-listings",
  "trending-listings",
  "sponsored-listings",
  "business-promotions",
  "banner-rotation",
  "carousel-behaviour",
  "lazy-loading",
] as const;

export const HOMEPAGE_BUTTON_VALIDATION = [
  "click",
  "tap",
  "hover",
  "focus",
  "keyboard",
  "redirect",
  "permission",
  "api",
  "database",
  "animation",
  "notification",
  "success",
  "failure",
  "retry",
] as const;

export const HOMEPAGE_RESPONSIVE_VALIDATION = [
  "iphone-se",
  "iphone-12-16",
  "android-phones",
  "tablets",
  "desktop",
  "landscape",
  "portrait",
  "safe-areas",
] as const;

export const HOMEPAGE_PERFORMANCE_CHECKS = [
  "lcp",
  "cls",
  "inp",
  "bundle-size",
  "image-optimisation",
  "lazy-loading",
  "caching",
  "render-time",
] as const;

export const HOMEPAGE_SEO_CHECKS = [
  "homepage-metadata",
  "canonical",
  "opengraph",
  "structured-data",
  "internal-links",
  "indexability",
] as const;

export const HOMEPAGE_AUTO_REPAIR_ACTIONS = [
  "remove-duplicate-rendering",
  "remove-duplicated-category-rows",
  "remove-empty-layout-gaps",
  "optimise-spacing",
  "optimise-responsive-layout",
  "optimise-banner-positioning",
  "optimise-image-loading",
  "optimise-caching",
  "repair-premium-inconsistencies",
] as const;

export const HOMEPAGE_CERTIFICATION_SCORES = [
  "architecture",
  "ui",
  "ux",
  "navigation",
  "performance",
  "seo",
  "accessibility",
  "security",
  "marketplace",
  "enterprise",
] as const;

export const HOMEPAGE_PASS_CONDITIONS = [
  "no-duplicate-categories",
  "no-duplicate-homepage-sections",
  "no-empty-space-above-search",
  "all-buttons-functional",
  "all-routes-functional",
  "all-widgets-functional",
  "responsive-pass",
  "performance-pass",
  "seo-pass",
  "accessibility-pass",
  "enterprise-pass",
  "omega-pass",
  "homepage-completion-100",
] as const;

export const GLOBAL_CATEGORY_SCAN_DOMAINS = [
  { id: "top-categories", label: "Top Categories", ref: "lib/categories/enterprise/index.ts" },
  { id: "subcategories", label: "Subcategories", ref: "lib/categories/tree.ts" },
  { id: "leaf-categories", label: "Leaf Categories", ref: "lib/categories/marketplace-tree.ts" },
  { id: "ai-categories", label: "AI Categories", ref: "lib/sell/canonical-category-search.ts" },
  { id: "listing-categories", label: "Listing Categories", ref: "lib/categories/resolve-listing.ts" },
  { id: "business-categories", label: "Business Categories", ref: "lib/categories/enterprise/sectors.ts" },
  { id: "homepage-categories", label: "Homepage Categories", ref: "components/home/HomeCategoryRail.tsx" },
  { id: "search-categories", label: "Search Categories", ref: "lib/sell/category-picker-search.ts" },
  { id: "seller-categories", label: "Seller Categories", ref: "lib/sell/suggest-category-from-title.ts" },
  { id: "company-categories", label: "Company Categories", ref: "lib/categories/marketplace-tree.ts" },
] as const;

export const CATEGORY_INTEGRITY_CHECKS = [
  "duplicate-categories",
  "duplicate-slugs",
  "duplicate-icons",
  "duplicate-images",
  "duplicate-attributes",
  "duplicate-seo-metadata",
  "duplicate-parent-relations",
  "duplicate-homepage-rendering",
  "unused-categories",
  "hidden-categories",
  "legacy-categories",
  "broken-category-links",
  "broken-parent-trees",
  "broken-child-trees",
  "circular-relations",
  "empty-categories",
  "orphan-categories",
] as const;

export const CATEGORY_HOMEPAGE_SYNC_CHECKS = [
  "single-canonical-category-rail",
  "no-duplicated-category-sections",
  "no-duplicated-category-cards",
  "homepage-taxonomy-synchronized",
  "no-manual-homepage-duplicates",
] as const;

export const CATEGORY_SEARCH_SYNC_CHECKS = [
  "search-index",
  "autocomplete",
  "suggestions",
  "ai-search",
  "popular-searches",
  "filters",
  "saved-searches",
  "search-categories",
] as const;

export const CATEGORY_LISTING_SYNC_CHECKS = [
  "listing-category",
  "listing-subcategory",
  "listing-attributes",
  "listing-compatibility",
  "marketplace-rules",
  "ai-recommendation",
  "seo-mapping",
  "search-mapping",
] as const;

export const AI_CATEGORY_VALIDATION_CHECKS = [
  "ai-category-suggestions",
  "ai-parent-detection",
  "ai-duplicate-detection",
  "ai-attribute-suggestions",
  "ai-marketplace-rules",
  "ai-confidence-score",
  "manual-override",
  "learning-feedback",
] as const;

export const CATEGORY_SEO_CHECKS = [
  "slug",
  "canonical-url",
  "meta-title",
  "meta-description",
  "structured-data",
  "breadcrumb",
  "opengraph",
  "internal-links",
  "indexability",
] as const;

export const CATEGORY_BUTTON_VALIDATION = [
  "create-category",
  "edit-category",
  "delete-category",
  "merge-category",
  "split-category",
  "move-category",
  "import",
  "export",
  "search",
  "filter",
  "sort",
  "pagination",
  "expand",
  "collapse",
  "preview",
  "synchronize",
  "validate",
  "certify",
] as const;

export const CATEGORY_DATABASE_VALIDATION = [
  "category-table",
  "relationships",
  "indexes",
  "constraints",
  "translations",
  "images",
  "icons",
  "marketplace-mapping",
  "search-mapping",
  "homepage-mapping",
] as const;

export const CATEGORY_SAFE_REPAIR_ACTIONS = [
  "remove-duplicate-categories",
  "remove-duplicate-homepage-rendering",
  "repair-hierarchy",
  "repair-parent-child-mapping",
  "repair-slug-conflicts",
  "repair-icon-mapping",
  "repair-search-mapping",
  "repair-responsive-layout",
  "repair-spacing",
] as const;

export const CATEGORY_CERTIFICATION_SCORES = [
  "integrity",
  "homepage-sync",
  "search-sync",
  "listing-sync",
  "seo",
  "accessibility",
  "performance",
  "architecture",
  "marketplace",
  "enterprise",
] as const;

export const CATEGORY_PASS_CONDITIONS = [
  "no-duplicate-categories",
  "no-duplicate-homepage-rendering",
  "no-orphan-categories",
  "no-circular-hierarchy",
  "no-broken-routes",
  "no-broken-listings",
  "search-synchronization-pass",
  "homepage-synchronization-pass",
  "listing-synchronization-pass",
  "seo-pass",
  "accessibility-pass",
  "performance-pass",
  "enterprise-pass",
  "omega-pass",
  "category-completion-100",
] as const;

export const GLOBAL_SEARCH_SCAN_DOMAINS = [
  { id: "homepage-search", label: "Homepage Search", ref: "components/header/HeaderSearchBar.tsx" },
  { id: "header-search", label: "Header Search", ref: "components/header/HeaderSearchBar.tsx" },
  { id: "global-search", label: "Global Search", ref: "app/search/page.tsx" },
  { id: "category-search", label: "Category Search", ref: "lib/sell/category-picker-search.ts" },
  { id: "business-search", label: "Business Search", ref: "app/business/directory/page.tsx" },
  { id: "seller-search", label: "Seller Search", ref: "features/search/components/SellerResults.tsx" },
  { id: "company-search", label: "Company Search", ref: "features/search/components/StoreResults.tsx" },
  { id: "listing-search", label: "Listing Search", ref: "app/api/search/results/route.ts" },
  { id: "ai-search", label: "AI Search", ref: "lib/search-engine/engine.ts" },
  { id: "voice-search", label: "Voice Search", ref: "lib/search-engine/registry.ts" },
  { id: "image-search", label: "Image Search", ref: "lib/search-engine/registry.ts" },
] as const;

export const SEARCH_ENGINE_VALIDATION = [
  "realtime-search",
  "autocomplete",
  "suggestions",
  "trending-searches",
  "popular-searches",
  "recent-searches",
  "saved-searches",
  "recommended-searches",
  "ai-suggestions",
  "misspelling-correction",
  "synonyms",
  "plural-detection",
  "category-detection",
  "brand-detection",
] as const;

export const SEARCH_FILTER_VALIDATION = [
  "category",
  "subcategory",
  "brand",
  "condition",
  "price",
  "location-rules",
  "seller",
  "company",
  "business",
  "delivery",
  "buyer-protection",
  "featured",
  "verified-seller",
  "auction",
  "stock",
  "compatibility",
  "scope",
  "collection",
] as const;

export const SEARCH_SORT_VALIDATION = [
  "relevance",
  "newest",
  "oldest",
  "lowest-price",
  "highest-price",
  "most-popular",
  "featured",
  "recommended",
  "distance-future",
  "best-match",
] as const;

export const SEARCH_RESULTS_VALIDATION = [
  "listing-cards",
  "images",
  "titles",
  "prices",
  "badges",
  "seller",
  "business",
  "ratings",
  "buyer-protection",
  "sponsored-listings",
  "featured-listings",
  "pagination",
  "infinite-scroll",
  "result-metadata",
] as const;

export const SEARCH_EMPTY_STATE_VALIDATION = [
  "no-results",
  "offline",
  "api-failure",
  "loading",
  "retry",
  "connection-lost",
  "maintenance-mode",
  "idle-state",
] as const;

export const SEARCH_PERFORMANCE_VALIDATION = [
  "query-speed",
  "response-time",
  "database-queries",
  "search-index",
  "caching",
  "lazy-loading",
  "infinite-scroll",
  "memory-usage",
  "debounce",
] as const;

export const SEARCH_DATABASE_VALIDATION = [
  "search-indexes",
  "category-indexes",
  "listing-indexes",
  "brand-indexes",
  "full-text-indexes",
  "duplicate-indexes",
  "missing-indexes",
  "unused-indexes",
  "index-health",
] as const;

export const SEARCH_SEO_VALIDATION = [
  "search-urls",
  "canonical",
  "meta",
  "opengraph",
  "breadcrumb",
  "structured-data",
  "index-rules",
] as const;

export const AI_SEARCH_VALIDATION = [
  "ai-category-detection",
  "ai-intent-detection",
  "ai-keyword-expansion",
  "ai-marketplace-suggestions",
  "ai-confidence-score",
  "ai-learning-feedback",
  "ai-fallback",
] as const;

export const OMEGA_GLOBAL_SEARCH_VALIDATION = [
  "broken-search",
  "broken-filters",
  "broken-sorting",
  "broken-suggestions",
  "broken-autocomplete",
  "broken-search-index",
  "duplicate-results",
  "missing-results",
  "slow-queries",
  "incorrect-ranking",
  "broken-pagination",
  "broken-infinite-scroll",
  "broken-responsive",
] as const;

export const SEARCH_SAFE_REPAIR_ACTIONS = [
  "repair-search-indexes",
  "warm-search-cache",
  "optimize-database-indexes",
  "optimize-search-performance",
  "repair-duplicate-search-results",
  "repair-search-mapping",
  "repair-responsive-layout",
  "revalidate-search",
] as const;

export const SEARCH_CERTIFICATION_SCORES = [
  "accuracy",
  "performance",
  "ux",
  "ui",
  "seo",
  "accessibility",
  "architecture",
  "marketplace",
  "enterprise",
  "reliability",
] as const;

export const SEARCH_PASS_CONDITIONS = [
  "search-accuracy-pass",
  "autocomplete-pass",
  "suggestions-pass",
  "filters-pass",
  "sorting-pass",
  "pagination-pass",
  "infinite-scroll-pass",
  "performance-pass",
  "seo-pass",
  "accessibility-pass",
  "enterprise-pass",
  "omega-pass",
  "search-results-pass",
  "search-completion-100",
] as const;

export const GLOBAL_LISTING_SCAN_DOMAINS = [
  { id: "draft-listings", label: "Draft Listings", ref: "lib/sell/draft-storage.ts" },
  { id: "create-listing", label: "Create Listing", ref: "app/sell/page.tsx" },
  { id: "edit-listing", label: "Edit Listing", ref: "app/seller/listings/[id]/edit/page.tsx" },
  { id: "duplicate-listing", label: "Duplicate Listing", ref: "app/api/listings/[id]/duplicate/route.ts" },
  { id: "preview-listing", label: "Preview Listing", ref: "app/listing/[slug]/page.tsx" },
  { id: "publish-listing", label: "Publish Listing", ref: "app/api/listings/route.ts" },
  { id: "scheduled-listings", label: "Scheduled Listings", ref: "lib/listings/repository.ts" },
  { id: "archived-listings", label: "Archived Listings", ref: "features/seller/listings/components/SellerListingsPage.tsx" },
  { id: "expired-listings", label: "Expired Listings", ref: "lib/promotions/format.ts" },
  { id: "featured-listings", label: "Featured Listings", ref: "app/api/listings/feature/route.ts" },
  { id: "auction-listings", label: "Auction Listings", ref: "app/sell/auction/page.tsx" },
  { id: "business-listings", label: "Business Listings", ref: "app/business/directory/page.tsx" },
] as const;

export const LISTING_WORKFLOW_VALIDATION = [
  "create",
  "save-draft",
  "resume-draft",
  "auto-save",
  "edit",
  "duplicate",
  "preview",
  "publish",
  "pause",
  "archive",
  "delete",
  "republish",
] as const;

export const LISTING_FIELD_VALIDATION = [
  "title",
  "subtitle",
  "description",
  "short-description",
  "category",
  "subcategory",
  "attributes",
  "compatibility",
  "brand",
  "model",
  "condition",
  "price",
  "sale-price",
  "currency",
  "quantity",
  "sku",
  "barcode",
  "stock-status",
  "location-rules",
  "collection",
  "delivery-options",
  "return-policy",
  "warranty",
  "buyer-protection",
  "tags",
  "seo-title",
  "seo-description",
  "slug",
] as const;

export const LISTING_PHOTO_VALIDATION = [
  "upload",
  "multiple-upload",
  "drag-and-drop",
  "reorder",
  "crop",
  "rotate",
  "compression",
  "thumbnail-generation",
  "image-quality",
  "duplicate-detection",
  "supported-formats",
  "maximum-size",
  "minimum-resolution",
  "background-validation",
  "primary-image",
  "gallery-images",
  "alt-text",
] as const;

export const AI_LISTING_VALIDATION = [
  "ai-category",
  "ai-title-suggestions",
  "ai-description-suggestions",
  "ai-attribute-suggestions",
  "ai-seo-suggestions",
  "ai-duplicate-detection",
  "ai-compatibility-detection",
  "ai-listing-quality-score",
  "ai-publish-readiness-score",
  "manual-override",
  "learning-feedback",
] as const;

export const LISTING_LIVE_VALIDATION = [
  "required-fields",
  "character-limits",
  "duplicate-titles",
  "duplicate-listings",
  "invalid-prices",
  "invalid-stock",
  "invalid-category",
  "missing-images",
  "broken-images",
  "missing-attributes",
  "invalid-seo",
  "marketplace-rule-violations",
] as const;

export const LISTING_PREVIEW_VALIDATION = [
  "desktop-preview",
  "tablet-preview",
  "mobile-preview",
  "marketplace-card",
  "search-card",
  "featured-card",
  "category-preview",
  "seo-preview",
  "published-step",
] as const;

export const LISTING_PUBLISH_VALIDATION = [
  "listing-visibility",
  "search-index",
  "category-mapping",
  "homepage-eligibility",
  "featured-eligibility",
  "business-rules",
  "seo-indexing",
  "notification-generation",
  "analytics-registration",
  "audit-log",
] as const;

export const LISTING_BUTTON_VALIDATION = [
  "save-draft",
  "continue",
  "back",
  "preview",
  "publish",
  "archive",
  "delete",
  "duplicate",
  "upload-image",
  "remove-image",
  "ai-category",
  "ai-improve",
  "validate",
  "certify",
] as const;

export const LISTING_DATABASE_VALIDATION = [
  "listing-tables",
  "relations",
  "indexes",
  "images",
  "attributes",
  "categories",
  "search-mapping",
  "seo-mapping",
  "audit-trail",
] as const;

export const OMEGA_GLOBAL_LISTING_VALIDATION = [
  "broken-publish",
  "broken-draft",
  "broken-preview",
  "broken-image-upload",
  "broken-validation",
  "broken-category-mapping",
  "broken-search-mapping",
  "broken-homepage-mapping",
  "broken-seo",
  "broken-responsive",
  "duplicate-listings",
  "duplicate-images",
  "duplicate-drafts",
  "orphan-drafts",
] as const;

export const LISTING_SAFE_REPAIR_ACTIONS = [
  "repair-duplicate-listings",
  "repair-missing-mappings",
  "repair-search-indexing",
  "repair-homepage-eligibility",
  "repair-image-metadata",
  "repair-responsive-layout",
  "repair-preview-rendering",
  "revalidate-listing",
] as const;

export const LISTING_CERTIFICATION_SCORES = [
  "quality",
  "seo",
  "performance",
  "ux",
  "accessibility",
  "marketplace",
  "architecture",
  "enterprise",
  "reliability",
  "publish-readiness",
] as const;

export const LISTING_PASS_CONDITIONS = [
  "create-pass",
  "draft-pass",
  "preview-pass",
  "publish-pass",
  "image-upload-pass",
  "ai-validation-pass",
  "seo-pass",
  "accessibility-pass",
  "performance-pass",
  "marketplace-pass",
  "enterprise-pass",
  "omega-pass",
  "field-validation-pass",
  "listing-completion-100",
] as const;

export const GLOBAL_BUYER_SCAN_DOMAINS = [
  { id: "landing", label: "Landing", ref: "app/page.tsx" },
  { id: "registration-auth", label: "Registration & Auth", ref: "app/(auth)/register/page.tsx" },
  { id: "buyer-profile", label: "Buyer Profile", ref: "app/account/profile/page.tsx" },
  { id: "address-book", label: "Address Book", ref: "app/account/addresses/page.tsx" },
  { id: "shopping-discovery", label: "Shopping Discovery", ref: "app/search/page.tsx" },
  { id: "category-browse", label: "Category Browse", ref: "app/categories/page.tsx" },
  { id: "product-details", label: "Product Details", ref: "app/listing/[slug]/page.tsx" },
  { id: "wishlist-saved", label: "Wishlist & Saved", ref: "app/saved/page.tsx" },
  { id: "cart", label: "Cart", ref: "app/cart/page.tsx" },
  { id: "checkout", label: "Checkout", ref: "app/checkout/[slug]/page.tsx" },
  { id: "order-management", label: "Order Management", ref: "app/account/orders/page.tsx" },
  { id: "notifications-support", label: "Notifications & Support", ref: "app/notifications/page.tsx" },
] as const;

export const BUYER_WORKFLOW_VALIDATION = [
  "landing",
  "registration",
  "login",
  "email-verification",
  "two-factor-authentication",
  "profile-setup",
  "address-book",
  "search",
  "categories",
  "filters",
  "wishlist",
  "recently-viewed",
  "product-details",
  "share-listing",
  "report-listing",
  "contact-seller",
  "cart",
  "checkout",
  "payment",
  "buyer-protection",
  "order-confirmation",
  "order-tracking",
  "delivery",
  "order-completion",
  "review",
  "support",
  "logout",
] as const;

export const BUYER_PROFILE_VALIDATION = [
  "profile",
  "avatar",
  "display-name",
  "addresses",
  "phone",
  "language",
  "appearance",
  "notification-preferences",
  "privacy",
  "security",
  "saved-payment-methods",
  "saved-searches",
  "wishlist",
  "recently-viewed",
] as const;

export const BUYER_SHOPPING_VALIDATION = [
  "homepage",
  "search",
  "category-navigation",
  "filters",
  "sorting",
  "recommendations",
  "featured-listings",
  "sponsored-listings",
  "recently-viewed",
  "saved-searches",
] as const;

export const BUYER_PRODUCT_PAGE_VALIDATION = [
  "images",
  "gallery",
  "zoom",
  "description",
  "attributes",
  "compatibility",
  "seller-information",
  "business-information",
  "buyer-protection",
  "shipping",
  "returns",
  "reviews",
  "related-listings",
  "share",
  "wishlist",
] as const;

export const BUYER_CART_VALIDATION = [
  "add",
  "remove",
  "update-quantity",
  "save-for-later",
  "coupons",
  "delivery-calculation",
  "taxes",
  "totals",
  "persist",
] as const;

export const BUYER_CHECKOUT_VALIDATION = [
  "address",
  "delivery-method",
  "payment",
  "buyer-protection",
  "order-summary",
  "terms",
  "confirmation",
] as const;

export const BUYER_ORDER_VALIDATION = [
  "confirmation",
  "invoice",
  "tracking",
  "status",
  "delivery-confirmation",
  "return-request",
  "dispute",
  "cancellation-rules",
  "receipt",
] as const;

export const BUYER_NOTIFICATION_VALIDATION = [
  "email",
  "push",
  "in-app",
  "sms-future",
  "order-updates",
  "shipping-updates",
  "buyer-protection-updates",
  "preferences",
  "marketing",
] as const;

export const BUYER_BUTTON_VALIDATION = [
  "search",
  "category",
  "wishlist",
  "cart",
  "checkout",
  "pay",
  "track-order",
  "confirm-delivery",
  "open-dispute",
  "contact-seller",
  "review",
  "settings",
  "support",
] as const;

export const BUYER_DATABASE_VALIDATION = [
  "buyer-profile",
  "orders",
  "addresses",
  "wishlist",
  "saved-searches",
  "notifications",
  "payment-references",
  "buyer-protection-records",
] as const;

export const OMEGA_GLOBAL_BUYER_VALIDATION = [
  "broken-registration",
  "broken-login",
  "broken-checkout",
  "broken-orders",
  "broken-wishlist",
  "broken-saved-searches",
  "broken-notifications",
  "broken-buyer-protection",
  "broken-tracking",
  "broken-reviews",
  "broken-responsive",
  "orphan-sessions",
] as const;

export const BUYER_SAFE_REPAIR_ACTIONS = [
  "repair-navigation",
  "repair-responsive-layout",
  "repair-duplicate-rendering",
  "repair-cache",
  "repair-search-mapping",
  "repair-notification-mapping",
  "repair-profile-synchronization",
  "revalidate-buyer",
] as const;

export const BUYER_CERTIFICATION_SCORES = [
  "ux",
  "ui",
  "checkout",
  "order",
  "security",
  "accessibility",
  "performance",
  "marketplace",
  "enterprise",
  "reliability",
] as const;

export const BUYER_PASS_CONDITIONS = [
  "registration-pass",
  "login-pass",
  "search-pass",
  "wishlist-pass",
  "cart-pass",
  "checkout-pass",
  "orders-pass",
  "tracking-pass",
  "notifications-pass",
  "buyer-protection-pass",
  "performance-pass",
  "accessibility-pass",
  "security-pass",
  "marketplace-pass",
  "enterprise-pass",
  "omega-pass",
  "buyer-completion-100",
] as const;

export const GLOBAL_CHECKOUT_SCAN_DOMAINS = [
  { id: "cart", label: "Cart", ref: "app/cart/page.tsx" },
  { id: "checkout", label: "Checkout", ref: "app/checkout/[slug]/page.tsx" },
  { id: "buyer-protection", label: "Purchase Protection", ref: "features/checkout/components/CheckoutReturnPolicy.tsx" },
  { id: "delivery-address", label: "Delivery Address", ref: "features/checkout/components/CheckoutAddressCard.tsx" },
  { id: "billing-address", label: "Billing Address", ref: "lib/checkout/address.ts" },
  { id: "delivery-method", label: "Delivery Method", ref: "features/checkout/components/CheckoutDeliverySection.tsx" },
  { id: "payment-method", label: "Payment Method", ref: "features/checkout/components/CheckoutPaymentMethodCard.tsx" },
  { id: "promo-codes", label: "Promo Codes", ref: "app/api/promotions/checkout/route.ts" },
  { id: "gift-cards-future", label: "Gift Cards (Future)", ref: "lib/payments-engine/registry.ts" },
  { id: "order-summary", label: "Order Summary", ref: "features/checkout/components/OrderSummary.tsx" },
  { id: "confirmation-success", label: "Confirmation & Success", ref: "features/checkout/components/CheckoutSuccessView.tsx" },
] as const;

export const CHECKOUT_FLOW_VALIDATION = [
  "guest-checkout-future",
  "registered-checkout",
  "address-validation",
  "shipping-validation",
  "payment-validation",
  "review-order",
  "terms-acceptance",
  "confirmation",
  "order-creation",
  "invoice-generation",
  "receipt",
] as const;

export const CHECKOUT_PAYMENT_VALIDATION = [
  "stripe",
  "apple-pay",
  "google-pay",
  "credit-card",
  "debit-card",
  "saved-cards",
  "payment-retry",
  "payment-failure",
  "refund-trigger",
] as const;

export const CHECKOUT_ORDER_VALIDATION = [
  "items",
  "stock",
  "prices",
  "discounts",
  "buyer-protection",
  "vat",
  "shipping-cost",
  "grand-total",
  "invoice",
  "order-number",
] as const;

export const CHECKOUT_SECURITY_VALIDATION = [
  "csrf",
  "rate-limits",
  "fraud-detection",
  "bot-protection",
  "session-integrity",
  "webhook-validation",
  "payment-integrity",
] as const;

export const CHECKOUT_UX_VALIDATION = [
  "loading",
  "progress",
  "errors",
  "retry",
  "accessibility",
  "responsive",
  "animations",
] as const;

export const CHECKOUT_BUTTON_VALIDATION = [
  "continue",
  "back",
  "pay-now",
  "apply-coupon",
  "remove-coupon",
  "confirm",
  "cancel",
  "retry-payment",
] as const;

export const CHECKOUT_DATABASE_VALIDATION = [
  "orders",
  "payments",
  "invoices",
  "buyer-protection",
  "taxes",
  "addresses",
  "transactions",
] as const;

export const CHECKOUT_SAFE_REPAIR_ACTIONS = [
  "checkout-cache",
  "broken-routes",
  "responsive-layout",
  "payment-mapping",
  "order-mapping",
  "invoice-mapping",
] as const;

export const CHECKOUT_CERTIFICATION_SCORES = [
  "checkout",
  "payment",
  "security",
  "performance",
  "accessibility",
  "marketplace",
  "enterprise",
  "reliability",
  "order",
  "ux",
] as const;

export const CHECKOUT_PASS_CONDITIONS = [
  "cart-pass",
  "checkout-pass",
  "payment-pass",
  "order-pass",
  "invoice-pass",
  "buyer-protection-pass",
  "delivery-pass",
  "address-pass",
  "promo-pass",
  "performance-pass",
  "security-pass",
  "accessibility-pass",
  "marketplace-pass",
  "enterprise-pass",
  "omega-pass",
  "confirmation-pass",
  "checkout-completion-100",
] as const;

export const GLOBAL_ORDER_SCAN_DOMAINS = [
  { id: "pending-orders", label: "Pending Orders", ref: "app/api/orders/route.ts" },
  { id: "paid-orders", label: "Paid Orders", ref: "lib/orders/checkout.ts" },
  { id: "processing-orders", label: "Processing Orders", ref: "features/orders/components/SellerFulfillmentCard.tsx" },
  { id: "packed-orders", label: "Packed Orders", ref: "features/shipping/components/ShipmentWizard.tsx" },
  { id: "shipped-orders", label: "Shipped Orders", ref: "lib/orders/status.ts" },
  { id: "delivered-orders", label: "Delivered Orders", ref: "features/orders/components/DeliveryStatusCard.tsx" },
  { id: "completed-orders", label: "Completed Orders", ref: "lib/orders/types.ts" },
  { id: "cancelled-orders", label: "Cancelled Orders", ref: "lib/orders/status.ts" },
  { id: "refunded-orders", label: "Refunded Orders", ref: "lib/stripe/refunds.ts" },
  { id: "returned-orders", label: "Returned Orders", ref: "features/orders/components/IssueResolutionLink.tsx" },
  { id: "disputed-orders", label: "Disputed Orders", ref: "app/protection/page.tsx" },
  { id: "archived-orders", label: "Archived Orders", ref: "lib/orders/cleanup.ts" },
] as const;

export const ORDER_WORKFLOW_VALIDATION = [
  "create",
  "confirm",
  "reserve-stock",
  "payment-verification",
  "invoice-generation",
  "seller-notification",
  "shipping-creation",
  "tracking-assignment",
  "delivery-confirmation",
  "completion",
  "archive",
] as const;

export const ORDER_BUYER_VALIDATION = [
  "order-history",
  "tracking",
  "invoices",
  "returns",
  "refund-requests",
  "buyer-protection",
  "notifications",
] as const;

export const ORDER_SELLER_VALIDATION = [
  "order-queue",
  "packing",
  "dispatch",
  "tracking-update",
  "order-completion",
  "returns",
  "disputes",
] as const;

export const ORDER_COMPANY_VALIDATION = [
  "bulk-orders",
  "bulk-dispatch",
  "analytics",
  "exports",
  "accounting-integration",
] as const;

export const ORDER_STATUS_ENGINE = [
  "pending",
  "awaiting-payment",
  "paid",
  "preparing",
  "packed",
  "dispatched",
  "in-transit",
  "delivered",
  "completed",
  "cancelled",
  "refunded",
  "returned",
  "disputed",
] as const;

export const ORDER_DATABASE_VALIDATION = [
  "orders",
  "invoices",
  "order-items",
  "tracking",
  "returns",
  "refunds",
  "disputes",
  "audit-logs",
] as const;

export const ORDER_SAFE_REPAIR_ACTIONS = [
  "order-synchronization",
  "tracking-synchronization",
  "notification-synchronization",
  "analytics-mapping",
  "dashboard-rendering",
  "responsive-layout",
] as const;

export const ORDER_CERTIFICATION_SCORES = [
  "order-integrity",
  "tracking",
  "workflow",
  "security",
  "performance",
  "accessibility",
  "marketplace",
  "enterprise",
] as const;

export const ORDER_PASS_CONDITIONS = [
  "order-creation-pass",
  "tracking-pass",
  "invoices-pass",
  "returns-pass",
  "refund-workflow-pass",
  "notifications-pass",
  "security-pass",
  "performance-pass",
  "accessibility-pass",
  "enterprise-pass",
  "omega-pass",
  "order-completion-100",
] as const;

export const GLOBAL_SHIPPING_SCAN_DOMAINS = [
  { id: "shipping-labels", label: "Shipping Labels", ref: "features/shipping/components/ParcelCard.tsx" },
  { id: "carrier-integration", label: "Carrier Integration", ref: "lib/shipping/carriers.ts" },
  { id: "tracking-numbers", label: "Tracking Numbers", ref: "features/shipping/components/ParcelCard.tsx" },
  { id: "collection-points", label: "Collection Points", ref: "lib/shipping-engine/defaults.ts" },
  { id: "home-delivery", label: "Home Delivery", ref: "lib/checkout/delivery.ts" },
  { id: "international-shipping", label: "International Shipping", ref: "lib/seller/shipping-settings.ts" },
  { id: "shipping-rules", label: "Shipping Rules", ref: "lib/shipping-engine/registry.ts" },
  { id: "shipping-profiles", label: "Shipping Profiles", ref: "features/account/components/AddressBookPage.tsx" },
  { id: "delivery-estimates", label: "Delivery Estimates", ref: "lib/shipping/carriers.ts" },
  { id: "shipping-zones", label: "Shipping Zones", ref: "lib/shipping-engine/defaults.ts" },
  { id: "shipping-prices", label: "Shipping Prices", ref: "lib/seller/shipping-settings.ts" },
  { id: "buyer-protection-shipping", label: "Purchase Protection Shipping", ref: "app/protection/page.tsx" },
  { id: "lost-parcel-workflow", label: "Lost Parcel Workflow", ref: "lib/protection-engine/registry.ts" },
  { id: "damaged-parcel-workflow", label: "Damaged Parcel Workflow", ref: "lib/protection-engine/registry.ts" },
  { id: "returns-workflow", label: "Returns Workflow", ref: "features/orders/components/IssueResolutionLink.tsx" },
] as const;

export const SHIPPING_PLATFORM_VALIDATION = [
  "shipping-labels",
  "carrier-integration",
  "tracking-numbers",
  "collection-points",
  "home-delivery",
  "international-shipping",
  "shipping-rules",
  "shipping-profiles",
  "delivery-estimates",
  "shipping-zones",
  "shipping-prices",
  "buyer-protection-shipping",
  "lost-parcel-workflow",
  "damaged-parcel-workflow",
  "returns-workflow",
] as const;

export const SHIPPING_DATABASE_VALIDATION = [
  "shipping-tables",
  "tracking-tables",
  "carrier-mapping",
  "delivery-status",
  "parcel-history",
  "notifications",
  "audit-logs",
] as const;

export const SHIPPING_SAFE_REPAIR_ACTIONS = [
  "tracking-sync",
  "carrier-mapping",
  "notification-mapping",
  "dashboard-rendering",
  "responsive-layout",
] as const;

export const SHIPPING_CERTIFICATION_SCORES = [
  "shipping",
  "tracking",
  "carrier",
  "performance",
  "security",
  "accessibility",
  "marketplace",
  "enterprise",
] as const;

export const SHIPPING_PASS_CONDITIONS = [
  "shipping-pass",
  "tracking-pass",
  "returns-pass",
  "carrier-pass",
  "notifications-pass",
  "security-pass",
  "performance-pass",
  "accessibility-pass",
  "enterprise-pass",
  "omega-pass",
  "shipping-completion-100",
] as const;

export const GLOBAL_COMMUNICATION_SCAN_DOMAINS = [
  { id: "messages", label: "Messages", ref: "app/messages/page.tsx" },
  { id: "inbox", label: "Inbox", ref: "features/messages/components/MessagesListPage.tsx" },
  { id: "threads", label: "Threads", ref: "app/messages/[id]/page.tsx" },
  { id: "attachments", label: "Attachments", ref: "lib/messages-engine/registry.ts" },
  { id: "photos", label: "Photos", ref: "lib/messages/types.ts" },
  { id: "videos", label: "Videos", ref: "lib/messages-engine/registry.ts" },
  { id: "documents", label: "Documents", ref: "lib/messages-engine/registry.ts" },
  { id: "emoji", label: "Emoji", ref: "lib/messages/types.ts" },
  { id: "typing-indicator", label: "Typing Indicator", ref: "app/api/messages/presence/route.ts" },
  { id: "read-receipts", label: "Read Receipts", ref: "lib/messages-engine/registry.ts" },
  { id: "online-status", label: "Online Status", ref: "lib/messages/realtime.ts" },
  { id: "push-notifications", label: "Push Notifications", ref: "lib/integrations-engine/defaults.ts" },
  { id: "email-notifications", label: "Email Notifications", ref: "lib/email/service.ts" },
  { id: "admin-notifications", label: "Admin Notifications", ref: "lib/super-admin/notifications.ts" },
  { id: "seller-notifications", label: "Seller Notifications", ref: "lib/seller/migration/notifications.ts" },
  { id: "buyer-notifications", label: "Buyer Notifications", ref: "lib/orders/notifications.ts" },
  { id: "company-notifications", label: "Company Notifications", ref: "lib/notifications-engine/registry.ts" },
  { id: "support-notifications", label: "Support Notifications", ref: "app/support/page.tsx" },
  { id: "security-notifications", label: "Security Notifications", ref: "lib/trust/notifications.ts" },
  { id: "fraud-alerts", label: "Fraud Alerts", ref: "lib/moderation/notifications.ts" },
  { id: "marketplace-alerts", label: "Marketplace Alerts", ref: "features/notifications/components/NotificationsPage.tsx" },
] as const;

export const EMAIL_PLATFORM_VALIDATION = [
  "smtp",
  "transactional-email",
  "templates",
  "welcome-email",
  "verification-email",
  "password-reset",
  "order-confirmation",
  "shipping-updates",
  "refund-emails",
  "dispute-emails",
  "seller-emails",
  "company-emails",
  "support-emails",
] as const;

export const EMAIL_SECURITY_VALIDATION = [
  "spf",
  "dkim",
  "dmarc",
  "tls",
  "bounce-handling",
  "suppression-lists",
  "delivery-reports",
] as const;

export const PUSH_PLATFORM_VALIDATION = [
  "android-push",
  "ios-push",
  "web-push",
  "silent-push",
  "badge-updates",
  "deep-linking",
  "notification-actions",
] as const;

export const CRON_QUEUE_VALIDATION = [
  "cron-jobs",
  "scheduled-tasks",
  "email-queue",
  "push-queue",
  "retry-queue",
  "dead-letter-queue",
  "notification-queue",
  "cleanup-jobs",
  "health-checks",
] as const;

export const REALTIME_ENGINE_VALIDATION = [
  "realtime-messages",
  "realtime-notifications",
  "presence",
  "connection-recovery",
  "reconnect",
  "offline-queue",
  "sync",
] as const;

export const COMMUNICATION_DATABASE_VALIDATION = [
  "messages",
  "threads",
  "attachments",
  "notifications",
  "templates",
  "email-queue",
  "push-queue",
  "cron-logs",
  "audit-logs",
] as const;

export const COMMUNICATION_SAFE_REPAIR_ACTIONS = [
  "smtp",
  "cron-jobs",
  "email-queue",
  "push-queue",
  "realtime-queue",
  "notification-queue",
  "connection-recovery",
  "cache",
  "indexes",
] as const;

export const COMMUNICATION_CERTIFICATION_SCORES = [
  "messaging",
  "notification",
  "email",
  "push",
  "realtime",
  "security",
  "performance",
  "accessibility",
  "enterprise",
] as const;

export const COMMUNICATION_PASS_CONDITIONS = [
  "messages-pass",
  "notifications-pass",
  "email-pass",
  "push-pass",
  "realtime-pass",
  "cron-pass",
  "smtp-pass",
  "performance-pass",
  "accessibility-pass",
  "enterprise-pass",
  "omega-pass",
  "communication-completion-100",
] as const;

export const MARKETPLACE_COMPLETION_API = {
  snapshot: "/api/super-admin/marketplace-completion",
  action: "/api/super-admin/marketplace-completion/action",
  validate: "/api/super-admin/marketplace-completion/validate",
  repair: "/api/super-admin/marketplace-completion/repair",
  certify: "/api/super-admin/marketplace-completion/certify",
  export: "/api/super-admin/marketplace-completion/export",
  v1Snapshot: "/api/v1/super-admin/marketplace-completion",
} as const;
