import { node, option, solution, tree } from "@/lib/help/decision-trees/builder";

const LAST_UPDATED = "2025-06-19";

export const WITHDRAW_DECISION_TREE = tree(
  "withdraw",
  "Withdraw help",
  "root",
  [
    node("root", "What would you like help with?", [
      option("how", "How do I withdraw money?", { nextNodeId: "how-guide" }),
      option("where", "Where is my withdrawal?", { nextNodeId: "status-check" }),
      option("processing", "Processing time", { solutionId: "processing-time" }),
      option("pending", "Withdrawal pending", { nextNodeId: "pending-flow" }),
      option("failed", "Withdrawal failed", { nextNodeId: "failed-flow" }),
      option("bank-verify", "Bank verification", { solutionId: "bank-verification" }),
      option("bank-details", "Incorrect bank details", { solutionId: "incorrect-bank" }),
      option("limits", "Withdrawal limits", { solutionId: "withdrawal-limits" }),
      option("minimum", "Minimum withdrawal amount", { solutionId: "minimum-withdrawal" }),
      option("methods", "Payout methods", { solutionId: "payout-methods" }),
      option("stripe", "Stripe payouts", { topicSlug: "stripe" }),
      option("support", "Contact Support", { solutionId: "contact-support-prep" }),
    ]),
    node("how-guide", "Have you connected Stripe and completed seller verification?", [
      option("yes", "Yes", { solutionId: "how-withdraw-steps" }),
      option("no", "No", { solutionId: "setup-before-withdraw" }),
    ]),
    node("status-check", "Is your identity verified?", [
      option("yes", "Yes", { nextNodeId: "bank-verified" }),
      option("no", "No", { solutionId: "verify-identity-first" }),
    ]),
    node("bank-verified", "Is your bank account verified in Stripe?", [
      option("yes", "Yes", { nextNodeId: "days-passed" }),
      option("no", "No", { solutionId: "verify-bank-first" }),
    ]),
    node("days-passed", "Has more than 3 business days passed since the withdrawal was approved?", [
      option("yes", "Yes", { solutionId: "escalate-late-withdrawal" }),
      option("no", "No", { solutionId: "processing-time" }),
    ]),
    node("pending-flow", "What status do you see in your seller wallet?", [
      option("review", "Waiting for review", { solutionId: "processing-time" }),
      option("approved", "Approved — transferring", { solutionId: "processing-time" }),
      option("failed", "Failed", { nextNodeId: "failed-flow" }),
    ]),
    node("failed-flow", "What error message do you see?", [
      option("bank", "Bank account issue", { solutionId: "incorrect-bank" }),
      option("verify", "Verification required", { solutionId: "verify-identity-first" }),
      option("other", "Other / no message", { solutionId: "escalate-failed-withdrawal" }),
    ]),
  ],
  [
    solution("processing-time", {
      title: "Withdrawal processing",
      overview:
        "ROVEXO seller withdrawals are reviewed for security before funds are sent to your connected bank account via Stripe.",
      currentStatus: "Waiting for review",
      estimatedReviewTime: "Up to 24 hours",
      estimatedTransferTime: "1–3 business days after approval (per Stripe payout policy)",
      possibleDelays: [
        "Weekends and UK public holidays",
        "Security or fraud review",
        "Incorrect or unverified bank information",
        "Stripe identity verification pending",
      ],
      steps: [
        "Open **Seller → Wallet** and check the withdrawal status.",
        "Ensure Stripe Connect and identity verification are complete.",
        "Wait for the review window to finish before contacting Support.",
      ],
      requirements: ["Verified ROVEXO seller account", "Connected Stripe account", "Verified bank account"],
      processingTime: "Review up to 24 hours; bank transfer 1–3 business days after approval",
      commonMistakes: [
        "Requesting support before the review window ends",
        "Using a bank account name that does not match your Stripe identity",
        "Checking balance on weekends and expecting same-day transfer",
      ],
      troubleshooting: [
        "Refresh the wallet page after 24 hours if status has not changed.",
        "Confirm your Stripe dashboard shows no required actions.",
        "Verify your available balance meets the minimum withdrawal amount.",
      ],
      relatedQuestions: [
        { label: "Minimum withdrawal amount", href: "/help/category/withdraw" },
        { label: "Stripe payout setup", href: "/help/category/stripe" },
      ],
      relatedTopics: ["stripe", "verification", "payments"],
      relatedFeatures: [
        { label: "Seller Wallet", href: "/seller/wallet" },
        { label: "Withdraw", href: "/seller/wallet/withdraw" },
        { label: "Payment Settings", href: "/settings" },
      ],
      relatedPolicies: [
        { label: "Seller payouts policy", href: "/help/payments-checkout" },
        { label: "Terms of service", href: "/help/terms-of-service" },
      ],
      faqs: [
        {
          question: "Why is my withdrawal still pending?",
          answer: "Withdrawals pass a security review before Stripe sends funds. Most reviews complete within 24 hours.",
        },
        {
          question: "Can I cancel a pending withdrawal?",
          answer: "Contact Support before the withdrawal is approved if you need to cancel.",
        },
      ],
      lastUpdated: LAST_UPDATED,
    }),
    solution("how-withdraw-steps", {
      title: "How to withdraw money",
      overview: "Withdraw available seller balance to your connected bank account through Stripe.",
      steps: [
        "Complete seller tax registration and connect Stripe from **Seller → Wallet**.",
        "Ensure your identity and bank account are verified in Stripe.",
        "Open **Withdraw**, enter an amount above the minimum, and confirm.",
        "Track status in your wallet transaction history.",
      ],
      requirements: ["Available balance", "Stripe Connect", "Verified identity"],
      processingTime: "Review up to 24 hours; transfer 1–3 business days",
      commonMistakes: ["Withdrawing before completing tax registration", "Entering wrong bank details in Stripe"],
      troubleshooting: ["Check Stripe dashboard for required actions", "Confirm available balance is not reserved for open orders"],
      relatedQuestions: [{ label: "Processing time", href: "/help/category/withdraw" }],
      relatedTopics: ["stripe", "verification", "seller"],
      relatedFeatures: [
        { label: "Seller Wallet", href: "/seller/wallet" },
        { label: "Withdraw", href: "/seller/wallet/withdraw" },
      ],
      relatedPolicies: [{ label: "Payments and checkout", href: "/help/payments-checkout" }],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("setup-before-withdraw", {
      title: "Set up payouts before withdrawing",
      overview: "You must complete seller setup before your first withdrawal.",
      steps: [
        "Finish seller tax registration from **Seller → Tax**.",
        "Connect Stripe from **Seller → Wallet**.",
        "Complete Stripe identity verification.",
        "Return to **Withdraw** once your available balance is ready.",
      ],
      requirements: ["ROVEXO seller account", "Tax registration", "Stripe Connect"],
      processingTime: "Stripe verification usually completes within 24–48 hours",
      commonMistakes: ["Skipping tax registration", "Using a Stripe account registered to another person"],
      troubleshooting: ["Open Stripe from wallet and resolve any required actions"],
      relatedQuestions: [{ label: "Seller tax registration", href: "/help/seller-tax-registration" }],
      relatedTopics: ["verification", "stripe", "seller"],
      relatedFeatures: [
        { label: "Seller Tax", href: "/seller/tax" },
        { label: "Seller Wallet", href: "/seller/wallet" },
      ],
      relatedPolicies: [{ label: "Terms of service", href: "/help/terms-of-service" }],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("verify-identity-first", {
      title: "Complete identity verification",
      overview: "Withdrawals are paused until Stripe identity verification is complete.",
      steps: [
        "Open **Seller → Wallet** and follow the Stripe verification link.",
        "Upload the requested ID and confirm your details match your bank account.",
        "Wait for Stripe approval, then retry your withdrawal.",
      ],
      requirements: ["Government ID", "Matching legal name on bank account"],
      processingTime: "Usually within 24–48 hours",
      commonMistakes: ["Uploading expired ID", "Name mismatch between ID and bank account"],
      troubleshooting: ["Check email from Stripe for additional document requests"],
      relatedQuestions: [{ label: "Verification help", href: "/help/category/verification" }],
      relatedTopics: ["verification", "stripe"],
      relatedFeatures: [{ label: "Seller Wallet", href: "/seller/wallet" }],
      relatedPolicies: [{ label: "Privacy policy", href: "/help/privacy-policy" }],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("verify-bank-first", {
      title: "Verify your bank account",
      overview: "Stripe must verify your bank account before payouts can be sent.",
      steps: [
        "Open your Stripe Connect dashboard from **Seller → Wallet**.",
        "Add or confirm your bank account details.",
        "Complete any micro-deposit or instant verification steps required by Stripe.",
      ],
      requirements: ["UK bank account in your name", "Stripe Connect access"],
      processingTime: "Instant or 1–2 business days depending on verification method",
      commonMistakes: ["Wrong sort code", "Business account name mismatch"],
      troubleshooting: ["Remove and re-add the bank account in Stripe if verification fails twice"],
      relatedQuestions: [{ label: "Incorrect bank details", href: "/help/category/withdraw" }],
      relatedTopics: ["stripe", "verification"],
      relatedFeatures: [{ label: "Seller Wallet", href: "/seller/wallet" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("incorrect-bank", {
      title: "Fix incorrect bank details",
      overview: "Failed or delayed withdrawals are often caused by incorrect bank information in Stripe.",
      steps: [
        "Open Stripe from **Seller → Wallet**.",
        "Update your bank account to match your verified identity exactly.",
        "Submit a new withdrawal after Stripe confirms the account.",
      ],
      requirements: ["Access to Stripe Connect", "Correct UK bank details"],
      processingTime: "New withdrawal follows standard review and transfer times",
      commonMistakes: ["Using a joint account with a different primary name", "Outdated bank account after switching banks"],
      troubleshooting: ["Check failed withdrawal notes in wallet transaction history"],
      relatedQuestions: [{ label: "Withdrawal failed", href: "/help/category/withdraw" }],
      relatedTopics: ["stripe", "payments"],
      relatedFeatures: [{ label: "Wallet transactions", href: "/seller/wallet" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("bank-verification", {
      title: "Bank verification for withdrawals",
      overview: "ROVEXO uses Stripe Connect to verify bank accounts before sending seller payouts.",
      steps: [
        "Connect Stripe from **Seller → Wallet**.",
        "Add your bank account and complete Stripe verification.",
        "Wait for verification to show as complete before withdrawing.",
      ],
      requirements: ["Stripe Connect", "Matching legal name"],
      processingTime: "Instant to 2 business days",
      commonMistakes: ["Skipping verification prompts", "Using third-party bank accounts"],
      troubleshooting: ["Review Stripe notifications for missing documents"],
      relatedQuestions: [],
      relatedTopics: ["stripe", "verification"],
      relatedFeatures: [{ label: "Seller Wallet", href: "/seller/wallet" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("withdrawal-limits", {
      title: "Withdrawal limits",
      overview: "Withdrawal limits protect sellers and buyers while payouts are processed securely.",
      steps: [
        "Check your available balance in **Seller → Wallet**.",
        "Confirm no funds are reserved for open orders or disputes.",
        "Contact Support if your limit seems incorrect after verifying Stripe status.",
      ],
      requirements: ["Available cleared balance"],
      processingTime: "Limits update when orders complete and disputes close",
      commonMistakes: ["Trying to withdraw reserved funds", "Confusing pending and available balance"],
      troubleshooting: ["Review open orders and protection cases"],
      relatedQuestions: [{ label: "Minimum withdrawal", href: "/help/category/withdraw" }],
      relatedTopics: ["payments", "seller"],
      relatedFeatures: [{ label: "Seller Wallet", href: "/seller/wallet" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("minimum-withdrawal", {
      title: "Minimum withdrawal amount",
      overview: "You can withdraw once your available balance meets the platform minimum shown in **Seller → Wallet → Withdraw**.",
      steps: [
        "Open the withdraw page to see the current minimum.",
        "Wait for additional sales to clear if your balance is below the minimum.",
      ],
      requirements: ["Available balance above minimum"],
      processingTime: "Immediate once minimum is met and verification is complete",
      commonMistakes: ["Attempting partial withdrawals below the minimum"],
      troubleshooting: ["Check whether recent sales are still pending clearance"],
      relatedQuestions: [],
      relatedTopics: ["seller", "payments"],
      relatedFeatures: [{ label: "Withdraw", href: "/seller/wallet/withdraw" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("payout-methods", {
      title: "Payout methods",
      overview: "ROVEXO seller payouts are sent to your verified UK bank account through Stripe Connect.",
      steps: [
        "Connect and verify Stripe from **Seller → Wallet**.",
        "Ensure your bank account supports GBP payouts.",
        "Withdraw to the verified account shown in Stripe.",
      ],
      requirements: ["Stripe Connect", "Verified UK bank account"],
      processingTime: "1–3 business days after approval",
      commonMistakes: ["Expecting unsupported payout methods outside Stripe"],
      troubleshooting: ["Update payout account in Stripe if you changed banks"],
      relatedQuestions: [{ label: "Stripe payouts", href: "/help/category/stripe" }],
      relatedTopics: ["stripe", "payments"],
      relatedFeatures: [{ label: "Seller Wallet", href: "/seller/wallet" }],
      relatedPolicies: [{ label: "Payments and checkout", href: "/help/payments-checkout" }],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("escalate-late-withdrawal", {
      title: "Withdrawal delayed beyond expected time",
      overview: "If more than 3 business days have passed after approval, Support can trace the payout with Stripe.",
      steps: [
        "Open **Seller → Wallet** and copy the withdrawal transaction ID.",
        "Confirm Stripe shows no pending requirements.",
        "Contact Support with your transaction ID and bank last-four digits.",
      ],
      requirements: ["Withdrawal transaction ID", "Completed decision tree troubleshooting"],
      processingTime: "Support review within 1 business day",
      commonMistakes: ["Contacting Support before completing verification steps"],
      troubleshooting: ["Check spam for Stripe payout notifications"],
      relatedQuestions: [],
      relatedTopics: ["support", "stripe"],
      relatedFeatures: [{ label: "Contact Support", href: "/support" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("escalate-failed-withdrawal", {
      title: "Failed withdrawal — next steps",
      overview: "Review Stripe requirements, update bank details if needed, then retry or contact Support.",
      steps: [
        "Open the failed transaction in **Seller → Wallet**.",
        "Follow the Stripe action link if provided.",
        "Retry withdrawal after fixing the issue.",
        "Contact Support if the failure repeats with the same error.",
      ],
      requirements: ["Transaction ID", "Stripe error details if shown"],
      processingTime: "Varies by issue",
      commonMistakes: ["Retrying without fixing bank or verification issues"],
      troubleshooting: ["Screenshot the error message before retrying"],
      relatedQuestions: [],
      relatedTopics: ["support", "stripe"],
      relatedFeatures: [{ label: "Contact Support", href: "/support" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
    solution("contact-support-prep", {
      title: "Before you contact Support",
      overview: "Complete the guided troubleshooting steps so Support can resolve your withdrawal faster.",
      steps: [
        "Finish the withdrawal decision tree options above.",
        "Review the suggested articles and wallet transaction history.",
        "Contact Support only if the issue remains unresolved.",
      ],
      requirements: ["Completed troubleshooting", "Withdrawal transaction ID if applicable"],
      processingTime: "Support responds within 1 business day",
      commonMistakes: ["Opening duplicate tickets for the same withdrawal"],
      troubleshooting: ["Include your transaction ID and screenshots of wallet status"],
      relatedQuestions: [],
      relatedTopics: ["support"],
      relatedFeatures: [{ label: "Contact Support", href: "/support" }],
      relatedPolicies: [],
      faqs: [],
      lastUpdated: LAST_UPDATED,
    }),
  ],
);
