"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  type MutableRefObject,
  type ReactNode,
} from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/ui/Toast";
import type { FlatCategoryPath } from "@/lib/categories/types";
import { clearSellDraft, loadSellDraft, loadUploadSessionId } from "@/lib/sell/draft-storage";
import { loadDraftPhotos } from "@/lib/sell/draft-photo-storage";
import { uploadListingImageWithBackoff, deleteListingImage } from "@/lib/sell/storage-engine";
import { resolveEffectiveSellDraft } from "@/lib/sell/resolve-effective-draft";
import {
  DRAFT_AUTOSAVE_MS,
  discardLocalDraft,
  loadLocalDraftForRestore,
  persistDraftOnPublishFailure,
} from "@/lib/sell/draft-engine";
import {
  PublishEngineError,
  PUBLISH_FAILURE_MESSAGE,
  runPublishPipeline,
  type PublishPhase,
} from "@/lib/sell/publish-engine";
import { safeRandomUUID } from "@/lib/uuid";
import { compressListingImage, createListingThumbnail, validateClientImage } from "@/lib/storage/client-images";
import { persistSellDraftSnapshot, persistSellDraftTextSync } from "@/lib/sell/persist-sell-draft";
import { applyDeterministicPrefill, buildDeterministicPrefill } from "@/lib/sell/deterministic-prefill";
import { detectColourFromImageFile } from "@/lib/sell/detect-colour-from-image";
import {
  applyPrefillRespectingLocks,
  createEmptyUserModified,
  inferUserModifiedFromDraft,
  markFieldsUserModified,
  shouldApplyPhotoColourSuggestion,
  type SuggestionFieldId,
} from "@/lib/sell/suggestion-field-lock";
import {
  createPhotoMetadataEntry,
  readPhotoDimensions,
  type PhotoMetadataEntry,
} from "@/lib/sell/photo-metadata";
import {
  buildSmartDescription,
  canStartSmartDescriptionEngine,
  markDescriptionAsUserEdited,
  shouldApplyAutoDescription,
  type DescriptionEditState,
} from "@/lib/sell/smart-description-engine";
import {
  createEmptyDraft,
  isListingValid,
  SELL_PHOTO_MAX,
  type SellListingDraft,
  type SellPhoto,
  type SellView,
} from "@/features/sell/types";
import {
  getFirstSellValidationIssue,
  isSellListingPublishable,
} from "@/lib/sell/sell-validation";
import { scrollToSellField } from "@/lib/sell/sell-progressive-flow";
import { sellInputDiag } from "@/lib/sell/sell-input-diagnostics";
import {
  initSellProfiler,
  sellProfileAutosave,
  sellProfileSetDraft,
  sellProfileSyncText,
} from "@/lib/sell/sell-profiler";
import type { SellListingMode } from "@/lib/profile/account";
import { createNewListingSession } from "@/lib/sell/new-listing-session";
import { trackListingPublished } from "@/lib/sell/publish-analytics";
import type { PublishSuccessPayload } from "@/lib/sell/publish-success";
import { bumpPendingTextVersion } from "@/lib/sell/pending-text-store";

export type SellProviderOptions = {
  listingMode?: SellListingMode;
  editListingId?: string;
  initialDraft?: SellListingDraft;
  /** Clears stored draft and starts empty (default for /sell). */
  freshSession?: boolean;
  /** Auto-restore local draft without recovery prompt (My Account → Draft Listings). */
  restoreDraft?: boolean;
  /** Pause autosave while draft recovery prompt is open. */
  draftRecoveryPending?: boolean;
};

export type SellContextValue = {
  view: SellView;
  draft: SellListingDraft;
  formError: string | null;
  isPublishing: boolean;
  publishPhase: PublishPhase;
  uploadProgress: number;
  publishSuccess: PublishSuccessPayload | null;
  editListingId?: string;
  listingMode: SellListingMode;
  showValidation: boolean;
  pendingTitleRef: MutableRefObject<string>;
  pendingDescriptionRef: MutableRefObject<string>;
  flushTitleCommitRef: MutableRefObject<(() => void) | null>;
  flushDescriptionCommitRef: MutableRefObject<(() => void) | null>;
  syncTitleToDraft: (title: string) => void;
  syncDescriptionToDraft: (description: string) => void;
  addPhotos: (files: FileList | File[]) => Promise<void>;
  removePhoto: (id: string) => Promise<void>;
  replacePhoto: (id: string, file: File) => void;
  reorderPhotos: (fromIndex: number, toIndex: number) => void;
  setMainPhoto: (id: string) => void;
  retryPhotoUpload: (id: string) => Promise<void>;
  updateDraft: (patch: Partial<SellListingDraft>, options?: { userModifiedFields?: SuggestionFieldId[] }) => void;
  setCategoryPath: (categoryPath: FlatCategoryPath) => void;
  publishListing: () => Promise<void>;
  restoreLocalDraft: () => Promise<void>;
  discardRecoveryDraft: () => Promise<void>;
  markDescriptionManuallyEdited: (text: string) => void;
  descriptionIsAutoGenerated: boolean;
  resetForAnotherListing: () => Promise<void>;
};

const SellContext = createContext<SellContextValue | null>(null);

function useSellFormInternal(options: SellProviderOptions = {}): SellContextValue {
  const {
    listingMode = "quick",
    editListingId,
    initialDraft,
    freshSession = false,
    restoreDraft = false,
    draftRecoveryPending = false,
  } = options;
  const router = useRouter();
  const { pushToast } = useToast();
  const [view, setView] = useState<SellView>("form");
  const [draft, setDraft] = useState<SellListingDraft>(() => {
    if (initialDraft) return initialDraft;
    return createEmptyDraft();
  });
  const [formError, setFormError] = useState<string | null>(null);
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishPhase, setPublishPhase] = useState<PublishPhase>("idle");
  const [uploadProgress, setUploadProgress] = useState(0);
  const [publishSuccess, setPublishSuccess] = useState<PublishSuccessPayload | null>(null);
  const publishStartedAtRef = useRef(0);
  const uploadStartedAtRef = useRef(0);
  const uploadFinishedAtRef = useRef(0);
  const [showValidation, setShowValidation] = useState(false);
  const uploadSessionRef = useRef<string>("");
  const [removedImageIds, setRemovedImageIds] = useState<string[]>([]);
  const pendingTitleRef = useRef(draft.title);
  const pendingDescriptionRef = useRef(draft.description);
  const draftRef = useRef(draft);
  const flushTitleCommitRef = useRef<(() => void) | null>(null);
  const flushDescriptionCommitRef = useRef<(() => void) | null>(null);
  const draftRevisionRef = useRef(0);
  const descriptionEditRef = useRef<DescriptionEditState>({ lastAuto: "", userEdited: false });
  const photoMetadataRef = useRef<PhotoMetadataEntry[]>([]);
  const [descriptionIsAutoGenerated, setDescriptionIsAutoGenerated] = useState(false);

  useEffect(() => {
    initSellProfiler();
  }, []);

  useEffect(() => {
    draftRef.current = draft;
    draftRevisionRef.current += 1;
    sellProfileSetDraft("draft", `revision-${draftRevisionRef.current}`);
  }, [draft]);

  useEffect(() => {
    if (initialDraft || editListingId || freshSession || restoreDraft) return;

    let cancelled = false;

    void (async () => {
      const stored = loadSellDraft();
      const photos = await loadDraftPhotos();
      const sessionId = loadUploadSessionId();

      if (sessionId) {
        uploadSessionRef.current = sessionId;
      } else {
        uploadSessionRef.current = safeRandomUUID();
      }

      if (!stored && photos.length === 0) return;
      if (cancelled) return;

      setDraft((current) => {
        const userStartedEditing =
          current.photos.length > 0 ||
          current.title.trim().length > 0 ||
          current.description.trim().length > 0 ||
          current.categoryPath !== null;
        if (userStartedEditing) return current;

        const merged = {
          ...createEmptyDraft(),
          ...stored,
          parcelSize: stored?.parcelSize ?? "medium",
          photos: photos.length > 0 ? photos : current.photos,
          userModified: inferUserModifiedFromDraft(stored ?? {}),
        };
        pendingTitleRef.current = merged.title;
        pendingDescriptionRef.current = merged.description;
        return merged;
      });
    })();

    return () => {
      cancelled = true;
    };
  }, [editListingId, freshSession, initialDraft, restoreDraft]);

  const restoreLocalDraft = useCallback(async () => {
    const { draft: restored, uploadSessionId } = await loadLocalDraftForRestore();
    if (uploadSessionId) {
      uploadSessionRef.current = uploadSessionId;
    } else {
      uploadSessionRef.current = safeRandomUUID();
    }
    pendingTitleRef.current = restored.title;
    pendingDescriptionRef.current = restored.description;
    setDraft(restored);
    setFormError(null);
    setShowValidation(false);
  }, []);

  const discardRecoveryDraft = useCallback(async () => {
    await discardLocalDraft();
    uploadSessionRef.current = safeRandomUUID();
    pendingTitleRef.current = "";
    pendingDescriptionRef.current = "";
    setDraft(createEmptyDraft());
    setFormError(null);
    setShowValidation(false);
    setRemovedImageIds([]);
    window.scrollTo(0, 0);
  }, []);

  useEffect(() => {
    if (!restoreDraft || initialDraft || editListingId) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- restoration intentionally populates the draft after its asynchronous storage read.
    void restoreLocalDraft();
  }, [editListingId, initialDraft, restoreDraft, restoreLocalDraft]);

  const runDeterministicPrefill = useCallback((base: SellListingDraft): SellListingDraft => {
    const patch = buildDeterministicPrefill(base, base.categoryPath);
    const merged = applyPrefillRespectingLocks(base, patch);
    return Object.keys(merged).length > 0 ? { ...base, ...merged } : base;
  }, []);

  const refreshSmartDescription = useCallback((source?: SellListingDraft, title?: string) => {
    const current = source ?? draftRef.current;
    const effectiveTitle = title ?? pendingTitleRef.current;
    if (!canStartSmartDescriptionEngine(current, effectiveTitle)) return;

    const { description } = buildSmartDescription({
      draft: current,
      title: effectiveTitle,
      photoMetadata: photoMetadataRef.current,
    });

    if (!shouldApplyAutoDescription(current.description, description, descriptionEditRef.current)) {
      setDescriptionIsAutoGenerated(false);
      return;
    }

    descriptionEditRef.current = { lastAuto: description, userEdited: false };
    pendingDescriptionRef.current = description;
    setDescriptionIsAutoGenerated(true);
    setDraft((existing) =>
      existing.description === description ? existing : { ...existing, description },
    );
  }, []);

  const markDescriptionManuallyEdited = useCallback((text: string) => {
    descriptionEditRef.current = markDescriptionAsUserEdited(text, descriptionEditRef.current);
    if (text.trim() !== descriptionEditRef.current.lastAuto.trim()) {
      setDescriptionIsAutoGenerated(false);
    }
  }, []);

  useEffect(() => {
    refreshSmartDescription();
  }, [
    draft.brand,
    draft.categoryPath,
    draft.color,
    draft.condition,
    draft.material,
    draft.photos.length,
    draft.size,
    draft.title,
    refreshSmartDescription,
  ]);

  const syncTitleToDraft = useCallback((title: string) => {
    sellProfileSyncText("title", title.length, "syncTitleToDraft");
    pendingTitleRef.current = title;
    setDraft((current) => {
      const next = current.title === title ? current : { ...current, title };
      return runDeterministicPrefill(next);
    });
  }, [runDeterministicPrefill]);

  const syncDescriptionToDraft = useCallback(
    (description: string) => {
      sellInputDiag("syncDescriptionToDraft", {
        len: description.length,
        caller: new Error().stack?.split("\n").slice(2, 5).join(" | "),
      });
      sellProfileSyncText("description", description.length, "syncDescriptionToDraft");
      pendingDescriptionRef.current = description;
      setDraft((current) =>
        current.description === description ? current : runDeterministicPrefill({ ...current, description }),
      );
      // Detection is title-driven only — typing/editing the description never
      // triggers analysis, keeping the Description field perfectly responsive.
    },
    [runDeterministicPrefill],
  );

  const flushPendingText = useCallback(() => {
    flushTitleCommitRef.current?.();
    flushDescriptionCommitRef.current?.();
  }, []);

  const persistDraftSnapshot = useCallback(() => {
    if (initialDraft || editListingId || draftRecoveryPending) return;
    void persistSellDraftSnapshot({
      draftRef,
      pendingTitleRef,
      pendingDescriptionRef,
      uploadSessionId: uploadSessionRef.current,
    });
  }, [draftRecoveryPending, editListingId, initialDraft]);

  const persistDraftTextSync = useCallback(() => {
    if (initialDraft || editListingId || draftRecoveryPending) return false;
    return persistSellDraftTextSync({
      draftRef,
      pendingTitleRef,
      pendingDescriptionRef,
      uploadSessionId: uploadSessionRef.current,
    });
  }, [draftRecoveryPending, editListingId, initialDraft]);

  useEffect(() => {
    if (initialDraft || editListingId || draftRecoveryPending) return;

    sellProfileAutosave("schedule");
    const autosaveTimer = window.setTimeout(() => {
      sellInputDiag("autosave.timer.fire", {
        draftDescriptionLen: draftRef.current.description.length,
        pendingDescriptionLen: pendingDescriptionRef.current.length,
      });
      sellProfileAutosave("fire");
      persistDraftSnapshot();
    }, DRAFT_AUTOSAVE_MS);

    return () => window.clearTimeout(autosaveTimer);
  }, [draft, draftRecoveryPending, editListingId, initialDraft, persistDraftSnapshot]);

  useEffect(() => {
    if (initialDraft || editListingId || draftRecoveryPending) return;

    const persistOnHide = () => {
      persistDraftTextSync();
      void persistDraftSnapshot();
    };

    const restoreOnShow = (event: PageTransitionEvent) => {
      if (!event.persisted) return;

      void (async () => {
        const stored = loadSellDraft();
        const photos = await loadDraftPhotos();
        if (!stored && photos.length === 0) return;

        setDraft((current) => {
          const merged = {
            ...createEmptyDraft(),
            ...stored,
            parcelSize: stored?.parcelSize ?? "medium",
            photos: photos.length > 0 ? photos : current.photos,
            userModified: inferUserModifiedFromDraft(stored ?? {}),
          };
          pendingTitleRef.current = merged.title;
          pendingDescriptionRef.current = merged.description;
          return merged;
        });
      })();
    };

    const onVisibilityChange = () => {
      if (document.visibilityState === "hidden") persistOnHide();
    };

    window.addEventListener("visibilitychange", onVisibilityChange);
    window.addEventListener("pagehide", persistOnHide);
    window.addEventListener("pageshow", restoreOnShow);

    return () => {
      window.removeEventListener("visibilitychange", onVisibilityChange);
      window.removeEventListener("pagehide", persistOnHide);
      window.removeEventListener("pageshow", restoreOnShow);
    };
  }, [draftRecoveryPending, editListingId, initialDraft, persistDraftSnapshot, persistDraftTextSync]);

  const ensureUploadSessionId = useCallback(() => {
    if (!uploadSessionRef.current) {
      uploadSessionRef.current = safeRandomUUID();
    }
    return uploadSessionRef.current;
  }, []);

  const uploadPhoto = useCallback(
    async (photo: SellPhoto, onFraction?: (fraction: number) => void) => {
      if (!photo.file || photo.uploaded) return photo;

      setDraft((current) => ({
        ...current,
        photos: current.photos.map((item) =>
          item.id === photo.id ? { ...item, uploading: true, uploadError: undefined } : item,
        ),
      }));

      try {
        const result = await uploadListingImageWithBackoff({
          file: photo.file,
          productId: editListingId,
          sessionId: ensureUploadSessionId(),
          onProgress: (progress) => onFraction?.(progress),
        });

        return {
          ...photo,
          uploaded: true,
          uploading: false,
          url: result.url,
          thumbnailUrl: result.thumbnailUrl,
          storagePath: result.storagePath,
          thumbnailStoragePath: result.thumbnailStoragePath,
          previewUrl: result.thumbnailUrl || result.url,
        } satisfies SellPhoto;
      } catch (error) {
        const message = error instanceof Error ? error.message : "Upload failed.";
        setDraft((current) => ({
          ...current,
          photos: current.photos.map((item) =>
            item.id === photo.id ? { ...item, uploading: false, uploadError: message } : item,
          ),
        }));
        throw error;
      }
    },
    [editListingId, ensureUploadSessionId],
  );

  const addPhotos = useCallback(async (files: FileList | File[]) => {
    const remaining = SELL_PHOTO_MAX - draftRef.current.photos.length;
    const selected = Array.from(files).slice(0, remaining);
    if (selected.length === 0) return;

    const failures: string[] = [];

    const incoming = await Promise.all(
      selected.map(async (file) => {
        try {
          validateClientImage(file);
          let compressed = file;
          let previewSource = file;

          try {
            compressed = await compressListingImage(file);
            previewSource = await createListingThumbnail(compressed);
          } catch {
            // Mobile browsers and some test environments can fail web-worker compression;
            // still show the photo using the original file so publish is not blocked.
            compressed = file;
            previewSource = file;
          }

          return {
            id: safeRandomUUID(),
            file: compressed,
            previewUrl: URL.createObjectURL(previewSource),
            uploaded: false,
          } satisfies SellPhoto;
        } catch (error) {
          failures.push(error instanceof Error ? error.message : "Unable to add photo.");
          return null;
        }
      }),
    );

    const added = incoming.filter((photo) => photo !== null) as SellPhoto[];

    if (added.length > 0) {
      setDraft((current) => ({
        ...current,
        photos: [...current.photos, ...added].slice(0, SELL_PHOTO_MAX),
      }));

      const firstFile = selected[0];
      if (firstFile && shouldApplyPhotoColourSuggestion(draftRef.current)) {
        void detectColourFromImageFile(firstFile).then((colour) => {
          if (!colour || !shouldApplyPhotoColourSuggestion(draftRef.current)) return;
          setDraft((current) =>
            shouldApplyPhotoColourSuggestion(current) ? { ...current, color: colour } : current,
          );
        });
      }

      for (const photo of added) {
        void (async () => {
          if (photo.file) {
            const [dimensions, colour] = await Promise.all([
              readPhotoDimensions(photo.file),
              detectColourFromImageFile(photo.file),
            ]);
            if (dimensions) {
              photoMetadataRef.current = [
                ...photoMetadataRef.current.filter((entry) => entry.id !== photo.id),
                createPhotoMetadataEntry(photo, dimensions, colour),
              ];
              refreshSmartDescription();
            }
          }

          void uploadPhoto(photo)
            .then((uploaded) => {
              setDraft((current) => ({
                ...current,
                photos: current.photos.map((item) => (item.id === uploaded.id ? uploaded : item)),
              }));
            })
            .catch(() => undefined);
        })();
      }
    }

    if (failures.length > 0) {
      pushToast({
        title: "Photo not added",
        description: failures[0] ?? "Unable to add one or more photos.",
        variant: "error",
      });
    }
  }, [pushToast, refreshSmartDescription, uploadPhoto]);

  const removePhoto = useCallback(async (id: string) => {
    const photo = draftRef.current.photos.find((item) => item.id === id);
    if (photo?.existingImageId) {
      setRemovedImageIds((current) =>
        current.includes(photo.existingImageId!) ? current : [...current, photo.existingImageId!],
      );
    }
    if (photo?.storagePath && photo.file) {
      await deleteListingImage({
        storagePath: photo.storagePath,
        thumbnailStoragePath: photo.thumbnailStoragePath,
      }).catch(() => undefined);
    }

    setDraft((current) => {
      const target = current.photos.find((item) => item.id === id);
      if (target?.file) URL.revokeObjectURL(target.previewUrl);
      photoMetadataRef.current = photoMetadataRef.current.filter((entry) => entry.id !== id);
      return { ...current, photos: current.photos.filter((item) => item.id !== id) };
    });
  }, []);

  const retryPhotoUpload = useCallback(
    async (id: string) => {
      const photos = draftRef.current.photos;
      const index = photos.findIndex((photo) => photo.id === id);
      const photo = photos[index];
      if (!photo?.file || index < 0) return;

      try {
        const uploaded = await uploadPhoto(photo, (fraction) => setUploadProgress(fraction));
        setDraft((current) => ({
          ...current,
          photos: current.photos.map((item) => (item.id === id ? uploaded : item)),
        }));
      } catch {
        // uploadPhoto already sets uploadError on the photo
      }
    },
    [uploadPhoto],
  );

  const replacePhoto = useCallback((id: string, file: File) => {
    const existing = draftRef.current.photos.find((photo) => photo.id === id);
    if (existing?.existingImageId) {
      setRemovedImageIds((current) =>
        current.includes(existing.existingImageId!)
          ? current
          : [...current, existing.existingImageId!],
      );
    }

    setDraft((current) => ({
      ...current,
      photos: current.photos.map((photo) => {
        if (photo.id !== id) return photo;
        if (photo.file) URL.revokeObjectURL(photo.previewUrl);
        return {
          id: photo.id,
          file,
          previewUrl: URL.createObjectURL(file),
          uploaded: false,
          storagePath: undefined,
        };
      }),
    }));
  }, []);

  const reorderPhotos = useCallback((fromIndex: number, toIndex: number) => {
    if (fromIndex === toIndex) return;
    setDraft((current) => {
      const photos = [...current.photos];
      const [moved] = photos.splice(fromIndex, 1);
      photos.splice(toIndex, 0, moved);
      return { ...current, photos };
    });
  }, []);

  const updateDraft = useCallback(
    (patch: Partial<SellListingDraft>, options?: { userModifiedFields?: SuggestionFieldId[] }) => {
      setDraft((current) => {
        const next = { ...current, ...patch };
        if (options?.userModifiedFields?.length) {
          next.userModified = markFieldsUserModified(current.userModified, options.userModifiedFields);
        }
        return next;
      });
    },
    [],
  );

  const setMainPhoto = useCallback((id: string) => {
    setDraft((current) => {
      const index = current.photos.findIndex((photo) => photo.id === id);
      if (index <= 0) return current;
      const photos = [...current.photos];
      const [moved] = photos.splice(index, 1);
      photos.unshift(moved);
      return { ...current, photos };
    });
  }, []);

  const setCategoryPath = useCallback((categoryPath: FlatCategoryPath) => {
    setDraft((current) => {
      const prefilled = runDeterministicPrefill({
        ...current,
        categoryPath,
        parcelSize: current.parcelSize,
      });
      return {
        ...prefilled,
        userModified: markFieldsUserModified(current.userModified, ["category"]),
      };
    });
  }, [runDeterministicPrefill]);

  const publishListing = useCallback(async () => {
    if (isPublishing) return;

    flushPendingText();
    setShowValidation(true);
    setFormError(null);

    const baseDraft = resolveEffectiveSellDraft(draftRef.current, {
      title: pendingTitleRef.current,
      description: pendingDescriptionRef.current,
    });

    if (!isSellListingPublishable(baseDraft, {
      title: pendingTitleRef.current,
      description: pendingDescriptionRef.current,
    })) {
      const issue = getFirstSellValidationIssue(baseDraft, {
        title: pendingTitleRef.current,
        description: pendingDescriptionRef.current,
      });
      if (issue) scrollToSellField(issue.fieldDomId);
      return;
    }

    publishStartedAtRef.current = performance.now();
    uploadStartedAtRef.current = 0;
    uploadFinishedAtRef.current = 0;

    setIsPublishing(true);
    setPublishPhase("validating");
    setUploadProgress(0);

    const handlePhase = (phase: PublishPhase) => {
      if (phase === "uploading" && uploadStartedAtRef.current === 0) {
        uploadStartedAtRef.current = performance.now();
      }
      if (phase === "creating" && uploadFinishedAtRef.current === 0 && uploadStartedAtRef.current > 0) {
        uploadFinishedAtRef.current = performance.now();
      }
      setPublishPhase(phase);
    };

    try {
      try {
        const gateResponse = await fetch(
          `/api/account/profile-gate?intent=publish&returnTo=${encodeURIComponent(window.location.pathname)}`,
        );
        const gatePayload = (await gateResponse.json()) as { redirect?: string | null };
        if (gatePayload.redirect) {
          router.push(gatePayload.redirect);
          return;
        }
      } catch {
        setFormError("Unable to verify your profile. Please try again.");
        return;
      }

      const result = await runPublishPipeline({
        draft: baseDraft,
        editListingId,
        removedImageIds,
        uploadPhoto,
        onPhase: handlePhase,
        onUploadProgress: setUploadProgress,
      });

      setDraft((current) => ({ ...current, photos: result.photos }));

      if (editListingId) {
        clearSellDraft();
        router.push("/seller/listings");
        router.refresh();
        return;
      }

      clearSellDraft();
      const publishDurationMs = performance.now() - publishStartedAtRef.current;
      const uploadDurationMs =
        uploadFinishedAtRef.current > 0 && uploadStartedAtRef.current > 0
          ? uploadFinishedAtRef.current - uploadStartedAtRef.current
          : undefined;

      const { photos: _photos, ...successPayload } = result;
      setPublishSuccess(successPayload);
      trackListingPublished(successPayload, { publishDurationMs, uploadDurationMs });
    } catch (error) {
      if (
        error instanceof PublishEngineError &&
        "redirect" in error &&
        typeof (error as PublishEngineError & { redirect?: string }).redirect === "string"
      ) {
        router.push((error as PublishEngineError & { redirect: string }).redirect);
        return;
      }

      if (error instanceof PublishEngineError && error.persistDraft) {
        await persistDraftOnPublishFailure({
          draftRef,
          pendingTitleRef,
          pendingDescriptionRef,
          uploadSessionId: uploadSessionRef.current,
        });
        setFormError(error.message || PUBLISH_FAILURE_MESSAGE);
        setPublishPhase("error");
        return;
      }

      setFormError(
        error instanceof Error ? error.message : "Unable to publish listing. Please try again.",
      );
      setPublishPhase("error");
    } finally {
      setIsPublishing(false);
      setUploadProgress(0);
      setPublishPhase((current) => (current === "published" ? "published" : "idle"));
    }
  }, [editListingId, flushPendingText, isPublishing, removedImageIds, router, uploadPhoto]);

  const resetForAnotherListing = useCallback(async () => {
    const session = await createNewListingSession(draftRef.current, safeRandomUUID());
    setView("form");
    setPublishSuccess(null);
    setPublishPhase("idle");
    setFormError(null);
    setShowValidation(false);
    pendingTitleRef.current = "";
    pendingDescriptionRef.current = "";
    uploadSessionRef.current = session.uploadSessionId;
    descriptionEditRef.current = session.descriptionEdit;
    photoMetadataRef.current = session.photoMetadata;
    setDescriptionIsAutoGenerated(false);
    setDraft(session.draft);
    setRemovedImageIds([]);
    bumpPendingTextVersion();
  }, []);

  return {
    view,
    draft,
    formError,
    isPublishing,
    publishPhase,
    uploadProgress,
    publishSuccess,
    editListingId,
    listingMode,
    showValidation,
    pendingTitleRef,
    pendingDescriptionRef,
    flushTitleCommitRef,
    flushDescriptionCommitRef,
    syncTitleToDraft,
    syncDescriptionToDraft,
    addPhotos,
    removePhoto,
    replacePhoto,
    reorderPhotos,
    setMainPhoto,
    retryPhotoUpload,
    updateDraft,
    setCategoryPath,
    publishListing,
    restoreLocalDraft,
    discardRecoveryDraft,
    markDescriptionManuallyEdited,
    descriptionIsAutoGenerated,
    resetForAnotherListing,
  };
}

type SellProviderProps = SellProviderOptions & {
  children: ReactNode;
};

export function SellProvider({ children, ...options }: SellProviderProps) {
  const value = useSellFormInternal(options);
  return <SellContext.Provider value={value}>{children}</SellContext.Provider>;
}

export function useSell(): SellContextValue {
  const context = useContext(SellContext);
  if (!context) {
    throw new Error("useSell must be used within SellProvider");
  }
  return context;
}

export const useSellForm = useSellFormInternal;
export type SellFormController = SellContextValue;
