export const WORKFLOW_ENGINE_ROUTES = [
  { id: "dashboard", label: "Dashboard", href: "/super-admin/workflows" },
  { id: "workflows", label: "Workflows", href: "/super-admin/workflows/list" },
  { id: "builder", label: "Builder", href: "/super-admin/workflows/builder" },
  { id: "templates", label: "Templates", href: "/super-admin/workflows/templates" },
  { id: "executions", label: "Executions", href: "/super-admin/workflows/executions" },
  { id: "scheduler", label: "Scheduler", href: "/super-admin/workflows/scheduler" },
  { id: "approvals", label: "Approvals", href: "/super-admin/workflows/approvals" },
  { id: "analytics", label: "Analytics", href: "/super-admin/workflows/analytics" },
  { id: "versions", label: "Versions", href: "/super-admin/workflows/versions" },
  { id: "history", label: "History", href: "/super-admin/workflows/history" },
  { id: "settings", label: "Settings", href: "/super-admin/workflows/settings" },
] as const;

export const WORKFLOW_NODE_TYPES = [
  "start",
  "end",
  "condition",
  "decision",
  "delay",
  "timer",
  "approval",
  "notification",
  "email",
  "payment",
  "shipping",
  "ai-action",
  "database",
  "http-request",
  "queue",
  "loop",
  "switch",
  "merge",
  "split",
] as const;

export const WORKFLOW_TRIGGER_TYPES = [
  "user-registered",
  "seller-approved",
  "order-created",
  "order-paid",
  "order-shipped",
  "order-delivered",
  "dispute-opened",
  "refund-requested",
  "auction-ended",
  "listing-created",
  "listing-updated",
  "verification-passed",
  "verification-failed",
  "subscription-changed",
  "wallet-updated",
  "payment-failed",
  "support-ticket-created",
  "security-alert",
  "fraud-alert",
  "system-event",
  "webhook",
  "api",
  "manual",
  "cron",
] as const;

export const WORKFLOW_PERMISSION_ROLES = [
  "workflow-admin",
  "workflow-editor",
  "workflow-operator",
  "workflow-viewer",
] as const;

export const WORKFLOW_ENGINE_API = {
  snapshot: "/api/workflows",
  history: "/api/workflows/history",
  templates: "/api/workflows/templates",
  run: "/api/workflows/run",
  publish: "/api/workflows/publish",
  rollback: "/api/workflows/rollback",
  export: "/api/workflows/export",
  import: "/api/workflows/import",
  v1Snapshot: "/api/v1/workflows",
  v1History: "/api/v1/workflows/history",
  v1Templates: "/api/v1/workflows/templates",
  v1Run: "/api/v1/workflows/run",
  v1Publish: "/api/v1/workflows/publish",
  v1Rollback: "/api/v1/workflows/rollback",
  v1Export: "/api/v1/workflows/export",
  v1Import: "/api/v1/workflows/import",
  superAdminSnapshot: "/api/super-admin/workflows",
  superAdminAction: "/api/super-admin/workflows/action",
} as const;
