"use client";

import { memo, useEffect, useId, useRef, useState } from "react";
import { CanonicalCard, CanonicalTextarea } from "@/src/components/canonical";
import { bumpPendingTextVersion } from "@/lib/sell/pending-text-store";
import { useSell } from "@/features/sell/context/SellProvider";

const DESCRIPTION_MAX = 500;
const PENDING_BUMP_MS = 300;

export const SellDescriptionBlock = memo(function SellDescriptionBlock({
  onStepComplete,
}: {
  onStepComplete?: () => void;
}) {
  const {
    draft,
    pendingDescriptionRef,
    flushDescriptionCommitRef,
    syncDescriptionToDraft,
    markDescriptionManuallyEdited,
    descriptionIsAutoGenerated,
  } = useSell();
  const descId = useId();
  const [description, setDescription] = useState(draft.description);
  const descRef = useRef(description);
  const typingDesc = useRef(false);
  const bumpTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const autoGrow = () => {
    const el = document.getElementById(descId) as HTMLTextAreaElement | null;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${el.scrollHeight}px`;
  };

  useEffect(() => {
    descRef.current = description;
  });

  useEffect(() => {
    flushDescriptionCommitRef.current = () => {
      typingDesc.current = false;
      syncDescriptionToDraft(descRef.current);
    };
    return () => {
      flushDescriptionCommitRef.current = null;
    };
  }, [flushDescriptionCommitRef, syncDescriptionToDraft]);

  useEffect(() => {
    if (typingDesc.current) return;
    setDescription((current) => (current === draft.description ? current : draft.description));
    pendingDescriptionRef.current = draft.description;
  }, [draft.description, pendingDescriptionRef]);

  useEffect(() => {
    autoGrow();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- descId is stable for the field lifetime
  }, [description]);

  useEffect(() => () => {
    if (bumpTimer.current) clearTimeout(bumpTimer.current);
  }, []);

  const scheduleBump = () => {
    if (bumpTimer.current) clearTimeout(bumpTimer.current);
    bumpTimer.current = setTimeout(() => {
      bumpTimer.current = null;
      bumpPendingTextVersion();
    }, PENDING_BUMP_MS);
  };

  const flushBump = () => {
    if (bumpTimer.current) {
      clearTimeout(bumpTimer.current);
      bumpTimer.current = null;
    }
    bumpPendingTextVersion();
  };

  return (
    <CanonicalCard variant="medium" className="p-ds-4">
      {descriptionIsAutoGenerated ? (
        <p className="mb-ds-2 text-xs text-text-secondary">
          Suggested description — edit freely. Your changes are never overwritten.
        </p>
      ) : null}
      <CanonicalTextarea
        id={descId}
        label="Description"
        value={description}
        onChange={(event) => {
          typingDesc.current = true;
          const next = event.target.value.slice(0, DESCRIPTION_MAX);
          setDescription(next);
          pendingDescriptionRef.current = next;
          markDescriptionManuallyEdited(next);
          autoGrow();
          scheduleBump();
        }}
        onBlur={() => {
          typingDesc.current = false;
          syncDescriptionToDraft(descRef.current);
          flushBump();
          onStepComplete?.();
        }}
        placeholder="Add extra details (optional)"
        rows={3}
        maxLength={DESCRIPTION_MAX}
        autoComplete="off"
        enterKeyHint="done"
        aria-label="Listing description"
        className="min-h-[5.5rem] resize-none overflow-hidden"
      />
    </CanonicalCard>
  );
});
