/**
 * ROVEXO BLOOD CODE v7.1 — FINALIZATION + USER SINGULARITY (Cod Sânge v1.0 SSOT)
 * (ROVEXO v1.0 · Priority 1 · Owner Law)
 *
 * THERE IS ONLY USER ACCOUNT.
 * Self-purchase Absolute Law: currentUser.id === listing.owner.id → BLOCK.
 * Never compare buyerId==sellerId for that gate — see self-purchase-absolute-law-v1.ts.
 *
 * NOTHING HAS HIGHER PRIORITY THAN:
 * BUY NOW → CHECKOUT → PAYMENT → SUCCESS → ORDER
 *
 * Evolve-in-place (… → v7.0 Finalization → v7.1 User Singularity).
 */

export const BUY_NOW_ABSOLUTE_LAW_V1 = {
  version: "7.1",
  status: "FINALIZATION_LOCKED",
  priority: 1 as const,
  bloodCode: "v7.1" as const,
  rovexoVersion: "v1.0" as const,
  absoluteLaw: "NOTHING_HIGHER_PRIORITY_THAN_BUY_NOW_CHECKOUT_PAYMENT_SUCCESS_ORDER" as const,
  ownerLaw: "BUY_NOW_IS_PRIORITY_1_OWNER_LAW" as const,
  userSingularity: "THERE_IS_ONLY_USER_ACCOUNT" as const,
  selfPurchaseSsot: "lib/checkout/self-purchase-absolute-law-v1.ts" as const,
  finalizationLaw:
    "NOT_COMPLETE_UNTIL_100_PERCENT_REAL_E2E_ON_LOCALHOST_3000" as const,
  /** Official Cod Sânge status board — agent evidence only until Owner PASS. */
  officialStatusBoard: {
    localhost3000: "PASS",
    build: "PASS",
    listing: "PASS",
    buyNowButton: "PASS",
    sellerProtection: "PASS",
    selfPurchaseProtection: "PASS",
    login: "PASS",
    buyer: "PASS",
    seller: "PASS",
    buyNow: "PASS",
    lock: "PASS",
    inventory: "PASS",
    reserved: "PASS",
    /** Only blocker until Owner applies inventory SQL migrations. */
    sqlMigration: "BLOCKER",
    checkout: "WAITING",
    payment: "WAITING",
    stripe: "WAITING",
    success: "WAITING",
    order: "WAITING",
    realE2e: "WAITING",
  } as const,
  measurableTests: [
    "LOGIN",
    "BUYER_ID",
    "SELLER_ID",
    "LISTING_OWNER",
    "BUY_NOW",
    "CHECKOUT",
    "PAYMENT",
    "STRIPE",
    "ORDER",
    "REAL_E2E",
  ] as const,
  onlyAcceptedSuccessPath: [
    "ALT_BUYER_ACCOUNT",
    "OPEN_LISTING",
    "BUY_NOW",
    "CHECKOUT_OPENS",
    "PAYMENT",
    "STRIPE",
    "SUCCESS",
    "ORDER_CREATED",
    "BUYER_ORDERS",
    "SELLER_ORDERS",
    "REAL_E2E_PASS",
    "OWNER_PASS",
    "FREEZE",
    "CERTIFICATION",
    "DEPLOY",
  ] as const,
  defaultStatusUntilOwnerPass: "IN_DEVELOPMENT" as const,
  equation: "BUY_NOW !== ADD_TO_CART",
  userEquation: "BUY_NOW = CHECKOUT",
  mustOpen: "/checkout" as const,
  absoluteEquations: [
    "NO_PAYMENT = NO_SUCCESS",
    "NO_ORDER = NO_SUCCESS",
    "NO_CHECKOUT = NO_PAYMENT",
    "NO_BUYER = NO_CHECKOUT",
    "NO_SELLER = NO_CHECKOUT",
    "NO_STOCK = NO_CHECKOUT",
    "NO_STRIPE_SUCCESS = NO_ORDER",
    "NO_ORDER = NO_CERTIFICATION",
    "NO_CERTIFICATION = NO_FREEZE",
    "NO_FREEZE = NO_DEPLOY",
    "ONE_STEP_FAILS = NO_PASS",
  ] as const,
  sellerPhase: [
    "CREATE_LISTING",
    "SAVE",
    "PUBLISH",
    "ACTIVE",
    "VISIBLE",
    "STOCK_GT_0",
    "SELLER_ACTIVE",
    "NOT_HOLIDAY_MODE",
    "PASS",
  ] as const,
  buyerPhase: [
    "LOGIN",
    "NOT_SELLER",
    "ACTIVE_ACCOUNT",
    "OPEN_LISTING",
    "BUY_NOW",
    "LISTING_VERIFIED",
    "SELLER_VERIFIED",
    "BUYER_VERIFIED",
    "STOCK_VERIFIED",
    "PRICE_VERIFIED",
    "PASS",
  ] as const,
  checkoutPhase: [
    "PRODUCT_VERIFIED",
    "DELIVERY_VERIFIED",
    "PLATFORM_FEE_VERIFIED",
    "TOTAL_VERIFIED",
    "ADDRESS_VERIFIED",
    "BUY_NOW",
    "PASS",
  ] as const,
  paymentPhase: [
    "CREATE_STRIPE_SESSION",
    "PAYMENT_VERIFIED",
    "THREE_D_SECURE",
    "PAYMENT_SUCCESS",
    "PASS",
  ] as const,
  orderPhase: [
    "CREATE_ORDER",
    "CREATE_TRANSACTION",
    "CREATE_ORDER_NUMBER",
    "CREATE_BUYER_ORDER",
    "CREATE_SELLER_ORDER",
    "LOCK_LISTING",
    "REDUCE_STOCK",
    "PASS",
  ] as const,
  postPaymentPhase: [
    "BUYER_NOTIFICATION",
    "SELLER_NOTIFICATION",
    "TRACKING_CREATED",
    "TRACKING_UPDATED",
    "DELIVERED",
    "COMPLETE",
    "PASS",
  ] as const,
  onlyAllowedPath: [
    "SELLER_CREATE_LISTING",
    "PUBLISH_LISTING",
    "LISTING_ACTIVE",
    "STOCK_GT_0",
    "BUYER_LOGIN",
    "OPEN_LISTING",
    "BUY_NOW",
    "LISTING_VERIFIED",
    "SELLER_VERIFIED",
    "BUYER_VERIFIED",
    "SELF_PURCHASE_CHECK",
    "STOCK_VERIFIED",
    "PRICE_VERIFIED",
    "CHECKOUT_CREATED",
    "DELIVERY_VERIFIED",
    "PLATFORM_FEE_VERIFIED",
    "TOTAL_VERIFIED",
    "BUY_NOW_CTA",
    "CREATE_STRIPE_SESSION",
    "PAYMENT_PAGE",
    "PAYMENT_SUCCESS",
    "PAYMENT_VERIFIED",
    "ORDER_CREATED",
    "TRANSACTION_CREATED",
    "LISTING_LOCKED",
    "BUYER_NOTIFIED",
    "SELLER_NOTIFIED",
    "TRACKING_CREATED",
    "DELIVERED",
    "COMPLETE",
    "SUCCESS",
    "OWNER_PASS",
    "CERTIFICATION",
    "FREEZE",
    "DEPLOY",
  ] as const,
  statusRequiredForCompletion: [
    "BUILD_PASS",
    "BUY_NOW_PASS",
    "CHECKOUT_PASS",
    "PAYMENT_PASS",
    "STRIPE_PASS",
    "SUCCESS_PASS",
    "ORDER_PASS",
    "BUYER_ORDERS_PASS",
    "SELLER_ORDERS_PASS",
    "TRACKING_PASS",
    "DELIVERY_PASS",
    "COMPLETE_PASS",
    "OWNER_PASS",
    "CERTIFICATION_PASS",
    "FREEZE_PASS",
    "DEPLOY_PASS",
  ] as const,
  zeroSkipForbidden: [
    "SKIP_429",
    "SKIP_500",
    "SKIP_SELLER_VALIDATION",
    "SKIP_CHECKOUT",
    "SKIP_PAYMENT",
    "SKIP_STRIPE",
    "SKIP_ORDER",
    "SKIP_SUCCESS_PAGE",
    "SKIP_E2E",
    "SKIP_VALIDATION_TO_CHECKOUT",
    "FORCE_CHECKOUT",
    "FORCE_PAYMENT",
    "FORCE_SUCCESS",
    "FAKE_PAYMENT",
    "FAKE_ORDER",
    "FAKE_STRIPE",
    "FAKE_SUCCESS",
    "HARDCODED_SUCCESS",
    "MOCK_ORDER",
    "MANUAL_DATABASE_UPDATE",
    "DISABLING_VALIDATIONS",
    "BYPASSING_SECURITY",
    "DISABLING_SELLER_GATE",
    "DISABLING_BUYER_GATE",
    "DISABLED_GATES",
  ] as const,
  sellerValidationMustOpenCheckoutWhen: [
    "SELLER_EXISTS",
    "SELLER_ACTIVE",
    "SELLER_IS_NOT_BUYER",
    "LISTING_AVAILABLE",
    "SELLER_ACCEPTS_ORDERS",
  ] as const,
  /** Development Lock — blocked until Buy Now Owner PASS. */
  developmentLockBlocked: [
    "Deploy",
    "Freeze",
    "Certification",
    "Wallet",
    "Business",
    "Followers",
    "Analytics",
    "Reviews",
    "Theme Engine",
    "Super Admin",
    "New Features",
    "UI Changes",
    "Refactoring",
    "Messages",
    "Notifications",
    "Coupons",
    "Statistics",
  ] as const,
  /** Only allowed development until Buy Now E2E Owner PASS. */
  allowedDevelopmentOnly: [
    "BUY_NOW",
    "CHECKOUT",
    "PAYMENT",
    "STRIPE",
    "ORDERS",
    "SUCCESS_PAGE",
    "E2E_TESTING",
    "BUG_FIXES",
    "PERFORMANCE_FIXES",
  ] as const,
  priorityOneChain: [
    "BUY_NOW",
    "CHECKOUT",
    "PAYMENT",
    "SUCCESS",
    "ORDER",
  ] as const,
  priorityOneObjective: "BUY_NOW_CHECKOUT_PAYMENT_SUCCESS_ORDER" as const,
  successPath: [
    "BUY_NOW",
    "CHECKOUT",
    "PAYMENT",
    "SUCCESS",
    "ORDER_CREATED",
    "PASS",
  ] as const,
  /**
   * Owner unlock (COD SÂNGE consolidated release):
   * Public error UX = action context + optional Retry + OK (not Sorry+OK only).
   * SSOT dialog: features/checkout/components/BuyNowPublicErrorDialog.tsx
   * Messages still via toBuyNowPublicMessage — never RVX / engine / jargon in UI.
   */
  failurePath: ["BUY_NOW", "PUBLIC_ERROR", "RETRY_OR_OK", "LISTING_PAGE", "PASS"] as const,
  publicErrorUx: {
    dialog: "BuyNowPublicErrorDialog",
    actionContext: true,
    retryWhenSafe: true,
    okDismiss: true,
    forbiddenInUi: ["RVX-*", "engine names", "validation jargon", "Checkout blocked"],
  } as const,
  performanceBudgetsMs: {
    buyNowToCheckout: 2000,
    checkoutLoad: 3000,
    payment: 5000,
    successPage: 2000,
  } as const,
  e2eQuotas: {
    buyNowTests: 20,
    checkoutTests: 20,
    paymentTests: 20,
    stripeTests: 20,
    orderTests: 20,
    failureTests: 20,
    successTests: 20,
    totalRequired: 140,
  } as const,
  /** Prerequisite chain — any NO blocks all downstream tests/PASS. */
  prerequisiteChain: [
    "BUILD_PASS",
    "APPLICATION_PASS",
    "BUY_NOW_PASS",
    "CHECKOUT_PASS",
    "PAYMENT_PASS",
    "SUCCESS_PASS",
    "E2E_PASS",
    "CERTIFICATION_PASS",
    "FREEZE",
    "GITHUB_PUSH",
    "LIVE_DEPLOY",
  ] as const,
  /** Cursor / agent must never declare these without every Owner gate TRUE. */
  forbiddenCursorDeclarations: [
    "PASS",
    "CERTIFIED",
    "COMPLETE",
    "DEPLOY READY",
    "FREEZE READY",
    "PRODUCTION READY",
    "E2E PASS",
    "100% WORKING",
    "100% COMPLETE",
  ] as const,
  /** Only surfaces the buyer may see on the happy path (user-visible). */
  userVisibleJourney: [
    "LISTING",
    "BUY_NOW",
    "CHECKOUT",
    "ADDRESS",
    "SHIPPING",
    "PAYMENT_METHOD",
    "BUY_NOW",
    "STRIPE_PAYMENT",
    "PAYMENT_SUCCESS",
    "ORDER_CREATED",
    "TRANSACTION_CREATED",
    "LISTING_LOCKED",
    "ESCROW_CREATED",
    "SELLER_NOTIFIED",
    "BUYER_NOTIFIED",
    "ORDER_VISIBLE",
    "TRANSACTION_VISIBLE",
    "SUCCESS_PAGE",
    "E2E_PASS",
    "CERTIFICATION_PASS",
    "FREEZE",
    "GITHUB_PUSH",
    "LIVE",
  ] as const,
  /** Allowed user-facing failure copy (Security Law). Seeing these in E2E ≠ PASS. */
  publicFailureMessages: [
    "Sorry.\nThis item is currently unavailable.",
    "Sorry.\nThe seller is temporarily unavailable.",
    "Sorry.\nSomething went wrong.\nPlease try again.",
  ] as const,
  /** Failure Absolute Law — these outcomes are NEVER certification PASS. */
  failureMeansNotPass: [
    "Sorry. Something went wrong. Please try again.",
    "Checkout blocked.",
    "Payment failed.",
    "Validation failed.",
    "500 Error",
    "404 Error",
    "API Error",
    "Stripe Error",
    "Database Error",
    "Infinite Loading",
    "White Screen",
    "Listing unlocked after payment.",
    "Order not created.",
    "Transaction not created.",
    "Shipping not created.",
    "Escrow not created.",
  ] as const,
  forbiddenInUserUi: [
    "RVX-2001",
    "RVX-2002",
    "RVX-2003",
    "VALIDATION FAILED",
    "PAYMENT FAILED",
    "AUDIT FAILED",
    "ESCROW FAILED",
    "ORDER FAILED",
    "FRAUD FAILED",
    "SHIPPING FAILED",
    "Checkout blocked.",
    "API Error",
    "Database Error",
    "ENGINE FAILED",
    "CHECKOUT FAILED",
    "SELLER FAILED",
    "BUYER FAILED",
    "DATABASE FAILED",
  ] as const,
  ownerCertificationRequires: [
    "BUILD_PASS",
    "BUY_NOW_PASS",
    "CHECKOUT_PASS",
    "PAYMENT_PASS",
    "STRIPE_PASS",
    "SUCCESS_PASS",
    "ORDER_PASS",
    "BUYER_ORDERS_PASS",
    "SELLER_ORDERS_PASS",
    "TRACKING_PASS",
    "DELIVERY_PASS",
    "COMPLETE_PASS",
    "PAYMENT_SUCCESS",
    "STRIPE_SUCCESS",
    "ORDER_CREATED",
    "SUCCESS_PAGE",
    "DATABASE_PASS",
    "E2E_PASS",
    "OWNER_VISUAL_PASS",
    "OWNER_APPROVAL",
    "OWNER_PASS",
    "CERTIFICATION_PASS",
    "FREEZE_PASS",
    "DEPLOY_PASS",
    "APPLICATION_PASS",
    "TRANSACTION_PASS",
    "ESCROW_PASS",
    "SHIPPING_PASS",
    "OWNER_CERTIFICATION_PASS",
  ] as const,
  finalLaw: [
    "NO_E2E = NO_PASS",
    "NO_PAYMENT = NO_PASS",
    "NO_SUCCESS = NO_PASS",
    "NO_ORDER = NO_PASS",
    "NO_TESTS = NO_PASS",
    "NO_OWNER_PASS = NO_PASS",
    "NO_CERTIFICATION = NO_PASS",
    "NO_FREEZE = NO_PASS",
    "NO_DEPLOY = NO_PASS",
    "NO_CERTIFICATION = NO_FREEZE",
    "NO_FREEZE = NO_DEPLOY",
    "NO_BUILD_PASS = NO_BUY_NOW_TEST",
    "NO_APPLICATION_PASS = NO_BUY_NOW_TEST",
    "BUY_NOW_IS_LAW",
  ] as const,
  developmentOnly: "http://localhost:3000" as const,
  productionLocked: "https://www.rovexo.co.uk" as const,
  productionPolicy: "SECURITY_FIX_ONLY" as const,
  /** Never expose these as UI labels, steps, or jargon. */
  invisibleToUser: [
    "seller validation",
    "inventory validation",
    "listing validation",
    "price validation",
    "payment validation",
    "shipping validation",
    "transaction validation",
    "fraud validation",
    "wallet validation",
    "stripe validation",
    "tracking validation",
    "notification validation",
    "order validation",
    "refund validation",
    "escrow validation",
    "payment release validation",
  ] as const,
  forbiddenUserFacingWords: [
    "validation",
    "verify",
    "audit",
    "idempotency",
    "fraud engine",
    "risk engine",
  ] as const,
  automationPercent: 100 as const,
  forbiddenDestinations: [
    "/cart",
    "/basket",
    "/shopping-cart",
    "cart.tsx",
    "cartAPI",
    "cartSession",
    "cartMiddleware",
    "CartProvider",
    "addToCart()",
    "createCart()",
  ] as const,
  mustVerifyBeforeLock: [
    "listingID",
    "sellerID",
    "buyerID",
    "price",
    "platformFee",
    "inventory",
    "listingActive",
    "sellerActive",
    "buyerActive",
    "currentUserNotListingOwner",
    "sellerNotSuspended",
    "checkoutSessionReady",
    "orderReady",
    "transactionReady",
    "paymentSessionReady",
  ] as const,
  failClosedWhen: [
    "listing price changes",
    "listing deleted",
    "listing sold",
    "seller suspended",
    "checkout expired",
    "price mismatch",
    "platform fee mismatch",
    "payment mismatch",
    "inventory mismatch",
  ] as const,
  absoluteGates: [
    "NO_PAYMENT = NO_COMPLETED_ORDER",
    "NO_VALIDATION = NO_PAYMENT",
    "NO_PASS = NO_NEXT_STEP",
    "EVERY_STEP_MUST_PASS",
    "FAIL_SAFE_FIRST",
    "ZERO_SHORTCUTS",
  ] as const,
  buyNowSequence: [
    "BUY_NOW",
    "VERIFY_LISTING",
    "VERIFY_BUYER",
    "VERIFY_SELLER",
    "VERIFY_PRICE",
    "VERIFY_PLATFORM_FEE",
    "VERIFY_DELIVERY",
    "VERIFY_INVENTORY",
    "LOCK_LISTING",
    "CREATE_ORDER",
    "CREATE_TRANSACTION",
    "CREATE_CHECKOUT_SESSION",
    "LOCK_INVENTORY",
    "LOAD_CHECKOUT",
    "BUY_NOW_CTA",
    "PAYMENT",
    "SUCCESS",
    "MY_ORDERS",
    "TRANSACTION_HUB",
    "COMPLETE",
  ] as const,
  checkoutCopy: {
    cta: "Buy Now",
    fee: "Platform Fee",
    forbiddenCta: ["Pay", "Pay Securely", "Continue", "Proceed", "Checkout"] as const,
    forbiddenFee: [
      "Buyer Protection",
      "Buyer Protection Fee",
      "Buyer Protection Included",
    ] as const,
  },
  sellerValidationRvx: "RVX-2003" as const,
  productPageBuyNowSsot: [
    "features/product-detail/ProductDetailPage.tsx",
    "features/product-detail/use-product-action-bar.ts",
    "features/checkout/hooks/use-buy-now-navigation.ts",
    "app/api/checkout/buy-now/route.ts",
    "lib/checkout/engines/buy-now-engine-v1.ts",
  ] as const,
} as const;

/** Alias — Absolute Law v2+ is the live contract (same object). */
export const BUY_NOW_ABSOLUTE_LAW_V2 = BUY_NOW_ABSOLUTE_LAW_V1;

export function isForbiddenBuyNowCartPath(path: string): boolean {
  const normalized = path.trim().toLowerCase();
  return (
    normalized.includes("/cart") ||
    normalized.includes("/basket") ||
    normalized.includes("/shopping-cart") ||
    normalized.includes("cartsession") ||
    normalized.includes("cartprovider")
  );
}

export function assertBuyNowCheckoutPath(path: string): boolean {
  const trimmed = path.trim();
  if (isForbiddenBuyNowCartPath(trimmed)) return false;
  return trimmed.startsWith("/checkout");
}

/** Fail-closed money compare (pence). */
export function amountsMatch(a: number, b: number, epsilon = 0.001): boolean {
  return Number.isFinite(a) && Number.isFinite(b) && Math.abs(a - b) < epsilon;
}

/** User-facing RVX body must never expose validation/engine jargon. */
export function isUserVisibleValidationJargon(message: string): boolean {
  const lower = message.toLowerCase();
  return BUY_NOW_ABSOLUTE_LAW_V1.forbiddenUserFacingWords.some((word) => lower.includes(word));
}
