/**
 * Extended marketplace synonym mappings — merged into category search at runtime.
 * UK/US/colloquial terms for Vinted, eBay, Gumtree, AutoTrader-style search behaviour.
 */

export const EXTENDED_MARKETPLACE_SYNONYMS: Record<string, string> = {
  // Home & furniture
  closet: "wardrobes",
  closets: "wardrobes",
  dresser: "drawers",
  sideboards: "cabinets",
  loveseat: "sofa",
  divan: "sofa",
  chesterfield: "sofa",
  ottoman: "chairs",
  headboard: "beds",
  footboard: "beds",
  quilt: "duvets",
  valance: "bed sheets",
  roman: "roman blinds",
  roller: "roller blinds",
  venetian: "venetian blinds",
  blackout: "blackout curtains",
  voile: "voile curtains",
  net: "net curtains",
  velvet: "velvet curtains",

  // Phones & electronics
  phone: "smartphones",
  mob: "mobile phone",
  moby: "mobile phone",
  android: "smartphones",
  galaxy: "samsung galaxy",
  pixel: "google pixel",
  macbook: "macbooks",
  imac: "desktops",
  chromebook: "chromebooks",
  gpu: "gpus",
  cpu: "cpus",
  ps5: "playstation",
  ps4: "playstation",
  switch: "nintendo",
  kindle: "tablets",
  ipad: "tablets",
  airpods: "earbuds",
  beats: "headphones",
  gopro: "action cameras",
  drone: "drones",

  // Vehicles
  auto: "cars",
  automobile: "cars",
  motor: "cars",
  motors: "cars",
  fourbyfour: "4x4",
  pickup: "pickups",
  lorry: "lorries",
  van: "panel vans",
  reg: "registration",
  numberplate: "registration",
  alloys: "alloy wheels",
  rims: "alloy wheels",
  wingmirror: "car mirrors",
  bumper: "bumpers",
  spoiler: "spoilers",
  roofrack: "roof boxes",
  boot: "boot liners",
  bonnet: "body parts",
  gearbox: "transmission",
  diesel: "fuel",
  petrol: "fuel",
  hybrid: "fuel",
  ev: "electric cars",
  mls: "mileage",

  // Fashion
  kicks: "trainers",
  sneaker: "trainers",
  sneaks: "trainers",
  tee: "tops",
  tshirt: "tops",
  hoodie: "tops",
  sweatshirt: "tops",
  denim: "jeans",
  coat: "coats",
  jacket: "coats",
  purse: "handbags",
  stilettos: "heels",
  loafers: "flats",
  wellies: "boots",
  scarf: "accessories",
  hat: "accessories",
  belt: "accessories",
  watch: "accessories",
  jewelry: "jewellery",

  // Sports & outdoors
  dumbbell: "weights",
  dumbbells: "weights",
  kettlebell: "weights",
  exercisebike: "exercise bikes",
  rod: "fishing rods",
  reel: "fishing reels",
  tackle: "fishing tackle",
  mtb: "mountain bikes",
  bmx: "bikes",

  // Property & business
  apartment: "flats",
  house: "houses",
  bungalow: "bungalows",
  studio: "flats",
  retail: "retail space",

  // Pets & baby
  dog: "dogs",
  cat: "cats",
  puppy: "dogs",
  kitten: "cats",
  aquarium: "fish",
  terrarium: "reptiles",
  cot: "cots",
  bouncer: "baby",
  moses: "baby",

  // UK / US spellings & terms
  faucet: "taps",
  trash: "storage boxes",
  garbage: "storage boxes",
  diaper: "nappy",
  diapers: "nappies",
  pacifier: "baby",
  elevator: "lift",
  yard: "garden",
};
