import {
  AI_ENGINE_MODULE_IDS,
  AI_ENGINE_PROVIDERS,
  AI_ENGINE_ROLES,
} from "@/lib/ai-engine/registry";
import type { AiEngineDocument, AiEngineHistoryEntry } from "@/lib/ai-engine/types";

const now = () => new Date().toISOString();

export function createDefaultAiEngineDocument(label = "ROVEXO AI Engine"): AiEngineDocument {
  return {
    version: 1,
    updatedAt: now(),
    label,
    marketplaceVersion: "ROVEXO v1.0",
    primaryCountry: "United Kingdom",
    currency: "GBP",
    globalEnabled: false,
    modules: AI_ENGINE_MODULE_IDS.map((m) => ({ ...m, enabled: m.id === "control-center" || m.id === "marketplace-assistant" })),
    marketplaceAi: {
      listingGenerator: true,
      descriptionGenerator: true,
      titleGenerator: true,
      seoGenerator: true,
      categoryDetection: true,
      priceSuggestions: true,
      conditionSuggestions: true,
      brandDetection: true,
      duplicateDetection: true,
      missingInformationDetection: true,
    },
    imageAi: {
      imageQualityCheck: true,
      backgroundDetection: true,
      objectRecognition: true,
      categoryRecognition: true,
      brandRecognition: true,
      ocr: true,
      imageOptimization: true,
      imageValidation: true,
      futureVisionModels: false,
    },
    languageAi: {
      automaticTranslation: true,
      grammarImprovement: true,
      spellCheck: true,
      languageDetection: true,
      regionalEnglish: true,
      romanianSupport: true,
      futureMultiLanguage: false,
    },
    buyerAi: {
      shoppingAssistant: true,
      searchSuggestions: true,
      productRecommendations: true,
      relatedListings: true,
      savedSearchSuggestions: true,
      wishlistIntelligence: true,
    },
    sellerAi: {
      listingOptimizer: true,
      performanceSuggestions: true,
      salesInsights: true,
      pricingGuidance: true,
      inventorySuggestions: true,
      sellerAnalyticsAssistant: true,
    },
    businessAi: {
      businessReports: true,
      revenueForecast: true,
      performanceInsights: true,
      growthSuggestions: true,
      marketTrends: true,
    },
    supportAi: {
      ticketClassification: true,
      suggestedReplies: true,
      priorityDetection: true,
      knowledgeSearch: true,
      faqAssistant: true,
    },
    moderationAi: {
      listingModeration: true,
      imageModeration: true,
      descriptionValidation: true,
      spamDetection: true,
      fraudDetection: true,
      scamIndicators: true,
      riskScore: true,
    },
    analyticsAi: {
      businessInsights: true,
      trendDetection: true,
      forecasting: true,
      patternRecognition: true,
      revenueAnalysis: true,
      marketplaceIntelligence: true,
    },
    automation: {
      workflowAutomation: true,
      scheduledTasks: true,
      smartNotifications: true,
      autoClassification: true,
      autoRouting: true,
      recommendationEngine: true,
    },
    providers: AI_ENGINE_PROVIDERS.map((p) => ({
      ...p,
      enabled: p.id === "local" || p.id === "ollama",
    })),
    permissions: AI_ENGINE_ROLES.map((r) => ({ ...r, enabled: true })),
    performance: {
      lazyLoading: true,
      streamingResponses: true,
      caching: true,
      queueProcessing: true,
      backgroundTasks: true,
      optimizedExecution: true,
    },
    security: {
      encryptedPrompts: true,
      secureApiKeys: true,
      permissionValidation: true,
      providerIsolation: true,
      auditLogging: true,
      rateLimiting: true,
    },
    executionPolicy: {
      defaultDisabled: true,
      priorityLocal: true,
      priorityEdge: true,
      cloudWhenRequired: true,
      autoFallback: true,
    },
    integrations: {
      ordersEngine: true,
      shippingEngine: true,
      walletEngine: true,
      paymentsEngine: true,
      protectionEngine: true,
      messagesEngine: true,
      notificationsEngine: true,
      analyticsEngine: true,
      securityEngine: true,
      searchEngine: true,
      missionControl: true,
    },
    futureReady: [
      "Voice Assistant",
      "Vision Assistant",
      "Document AI",
      "Video AI",
      "Audio AI",
      "Marketplace Copilot",
      "Autonomous Workflows",
      "Predictive AI",
      "Private Local Models",
    ],
    auditLog: [],
  };
}

export function createDefaultAiEngineHistory(): AiEngineHistoryEntry[] {
  return [];
}
