/**
 * Brand expansion lines — deterministic sub-brand / product-line generation.
 * Format: [parentBrand, productLines[], vertical]
 */

export const BRAND_EXPANSION_LINES: readonly (readonly [string, readonly string[], string])[] = [
  ["Apple", ["iPhone", "iPad", "MacBook", "AirPods", "Watch", "HomePod", "iMac", "Mac Mini", "Mac Pro", "Mac Studio"], "electronics"],
  ["Samsung", ["Galaxy", "QLED", "Bespoke", "Jet", "Soundbar", "Tab", "Book", "Buds", "Watch"], "electronics"],
  ["Sony", ["Alpha", "Bravia", "PlayStation", "WH", "WF", "Xperia", "LinkBuds", "INZONE"], "electronics"],
  ["Nike", ["Air Max", "Air Force", "Dunk", "Jordan", "Pegasus", "React", "Blazer", "Cortez", "Mercurial", "Tiempo"], "fashion"],
  ["Adidas", ["Ultraboost", "Stan Smith", "Superstar", "Gazelle", "Samba", "Forum", "NMD", "Campus", "Ozweego", "Predator"], "fashion"],
  ["BMW", ["M Sport", "xDrive", "iX", "i4", "i5", "i7", "Alpina"], "vehicles"],
  ["Mercedes-Benz", ["AMG", "EQS", "EQE", "EQB", "EQC", "Maybach", "Sprinter"], "vehicles"],
  ["Audi", ["RS", "S Line", "e-tron", "Quattro", "Sportback"], "vehicles"],
  ["Ford", ["ST", "Raptor", "Mustang Mach-E", "Transit Custom", "Puma ST"], "vehicles"],
  ["Volkswagen", ["GTI", "R-Line", "ID.", "T-Roc R", "Arteon R"], "vehicles"],
  ["Dyson", ["V", "Airwrap", "Supersonic", "Purifier", "Corrale", "Zone"], "home"],
  ["KitchenAid", ["Artisan", "Pro Line", "Professional", "Classic"], "home"],
  ["LEGO", ["Technic", "City", "Friends", "Star Wars", "Creator", "Ninjago", "Duplo", "Architecture", "Ideas", "Speed Champions"], "toys"],
  ["Tempur", ["Original", "Sensation", "Cloud", "Hybrid", "Breeze"], "pillows"],
  ["Silentnight", ["Eco Comfort", "Studio", "Geltex", "Miracoil", "So Snug"], "pillows"],
  ["Emma", ["Original", "Hybrid", "Premium", "Flip", "Diamond"], "pillows"],
  ["Simba", ["Hybrid", "Hybrid Pro", "Hybrid Luxe", "Hybrid Ultra"], "pillows"],
  ["Dell", ["XPS", "Alienware", "Latitude", "Inspiron", "Precision", "Vostro"], "electronics"],
  ["HP", ["Spectre", "Envy", "Pavilion", "Omen", "EliteBook", "Victus"], "electronics"],
  ["Lenovo", ["ThinkPad", "Yoga", "Legion", "IdeaPad", "ThinkBook"], "electronics"],
  ["Asus", ["ROG", "ZenBook", "VivoBook", "TUF", "ProArt"], "electronics"],
  ["Canon", ["EOS", "PowerShot", "PIXMA", "imageCLASS", "RF"], "electronics"],
  ["Nikon", ["Z", "D", "Coolpix", "Nikkor", "Z fc"], "electronics"],
  ["Bosch", ["Professional", "Green", "Serie 8", "Serie 6", "GCM"], "tools"],
  ["DeWalt", ["XR", "FlexVolt", "Atomic", "Powerstack"], "tools"],
  ["Makita", ["LXT", "XGT", "CXT", "HP"], "tools"],
  ["Milwaukee", ["M18", "M12", "Fuel", "Packout"], "tools"],
  ["Patagonia", ["Nano Puff", "Better Sweater", "Torrentshell", "Black Hole"], "fashion"],
  ["The North Face", ["Nuptse", "Denali", "Thermoball", "Base Camp"], "fashion"],
  ["Barbour", ["Ashby", "Bedale", "Beaufort", "International"], "fashion"],
  ["Le Creuset", ["Signature", "Classic", "Stoneware", "Cast Iron"], "home"],
  ["Smeg", ["50s Style", "Victoria", "FAB", "Cucina"], "home"],
  ["Shark", ["Ninja", "Anti Hair Wrap", "Stratos", "Detect Pro"], "home"],
  ["Miele", ["Complete", "Triflex", "Blizzard", "Gourmet"], "home"],
  ["Hotpoint", ["ActiveCare", "Anti-Stain", "Ultima", "Aquarius"], "home"],
  ["Beko", ["ProSmart", "HarvestFresh", "AeroPerfect", "SlimFit"], "home"],
  ["Grohe", ["Essence", "Eurosmart", "Atrio", "Blue"], "home"],
  ["Hansgrohe", ["Raindance", "Metropol", "Talis", "Focus"], "home"],
  ["IKEA", ["Billy", "Kallax", "Malm", "Ektorp", "Poang", "Hemnes", "Brimnes"], "home"],
  ["John Lewis", ["Anyday", "Partners", "Collection", "Essential"], "home"],
  ["Dunelm", ["Dorma", "Fogarty", "Catherine Lansfield", "Julian Charles"], "home"],
  ["Wilson", ["Pro Staff", "Blade", "Clash", "Ultra"], "sports"],
  ["Head", ["Radical", "Speed", "Gravity", "Prestige"], "sports"],
  ["Callaway", ["Rogue", "Paradym", "Apex", "Big Bertha"], "sports"],
  ["TaylorMade", ["Stealth", "Qi", "P790", "Spider"], "sports"],
  ["Specialized", ["Tarmac", "Roubaix", "Stumpjumper", "Turbo"], "sports"],
  ["Trek", ["Domane", "Emonda", "Fuel EX", "Marlin"], "sports"],
  ["Cannondale", ["Synapse", "SuperSix", "Scalpel", "Topstone"], "sports"],
  ["Giant", ["TCR", "Defy", "Trance", "Propel"], "sports"],
  ["Shimano", ["Dura-Ace", "Ultegra", "105", "Deore", "XT"], "sports"],
  ["Garmin", ["Fenix", "Forerunner", "Edge", "Venu", "Instinct"], "sports"],
  ["Bugaboo", ["Fox", "Donkey", "Bee", "Butterfly", "Cameleon"], "baby"],
  ["Silver Cross", ["Wave", "Dune", "Reef", "Spirit"], "baby"],
  ["Cybex", ["Priam", "Mios", "Balios", "Eezy"], "baby"],
  ["Maxi-Cosi", ["Pebble", "CabrioFix", "Pearl", "Rodifix"], "baby"],
  ["Chicco", ["Next2Me", "Seats", "Strollers", "Boppy"], "baby"],
  ["Tommee Tippee", ["Closer to Nature", "Advanced", "Twist and Click"], "baby"],
  ["Philips Avent", ["Natural", "Anti-Colic", "Soothie", "SCD"], "baby"],
  ["Estée Lauder", ["Advanced Night Repair", "Double Wear", "Revitalizing"], "beauty"],
  ["Clinique", ["Dramatically Different", "Moisture Surge", "Even Better"], "beauty"],
  ["MAC", ["Studio Fix", "Ruby Woo", "Prep + Prime"], "beauty"],
  ["L'Oréal", ["Revitalift", "True Match", "Elvive", "Excellence"], "beauty"],
  ["Maybelline", ["Fit Me", "Lash Sensational", "Superstay", "Instant Age"], "beauty"],
  ["Nivea", ["Soft", "Q10", "Sun Protect", "Men"], "beauty"],
  ["Olay", ["Regenerist", "Total Effects", "Retinol24"], "beauty"],
  ["Garnier", ["Micellar", "Fructis", "SkinActive", "Ambre Solaire"], "beauty"],
  ["The Ordinary", ["Niacinamide", "Hyaluronic Acid", "Retinol", "AHA BHA"], "beauty"],
  ["CeraVe", ["Moisturising Cream", "SA Cleanser", "AM Facial", "PM Facial"], "beauty"],
  ["Charlotte Tilbury", ["Pillow Talk", "Flawless Filter", "Magic Cream"], "beauty"],
  ["Fenty Beauty", ["Pro Filt'r", "Gloss Bomb", "Match Stix"], "beauty"],
  ["Rare Beauty", ["Soft Pinch", "Liquid Touch", "Kind Words"], "beauty"],
  ["Hasbro", ["Nerf", "Transformers", "Monopoly", "Play-Doh", "FurReal"], "toys"],
  ["Mattel", ["Barbie", "Hot Wheels", "Fisher-Price", "UNO", "Mega"], "toys"],
  ["Playmobil", ["City Life", "Pirates", "Knights", "Dinos"], "toys"],
  ["Ravensburger", ["GraviTrax", "Puzzle", "Labyrinth", "Scotland Yard"], "toys"],
  ["Scalextric", ["Digital", "ARC", "Super", "GT"], "toys"],
  ["Hornby", ["Railways", "Skale", "Airfix", "Corgi"], "toys"],
  ["Penguin", ["Classics", "Modern", "Paperback", "Hardback"], "books"],
  ["Oxford", ["Dictionary", "Thesaurus", "Atlas", "University Press"], "books"],
  ["Collins", ["Dictionary", "Thesaurus", "Gem", "Easy Learning"], "books"],
  ["Hachette", ["Orion", "Little Brown", "Headline", "Quercus"], "books"],
  ["HarperCollins", ["4th Estate", "Voyager", "Avon", "HQ"], "books"],
  ["Pan Macmillan", ["Picador", "Tor", "Bluebird", "Kingfisher"], "books"],
  ["Bloomsbury", ["Harry Potter", "Academic", "Children's", "Adult"], "books"],
  ["Faber", ["Poetry", "Fiction", "Non-Fiction", "Children's"], "books"],
  ["Vintage", ["Classics", "Crime", "Science Fiction", "Modern"], "books"],
  ["Penguin Random House", ["Cornerstone", "Transworld", "Ebury", "Century"], "books"],
];
