/**
 * Brand seed database — curated marketplace brands by vertical.
 * Combined with expansion-lines.ts to reach 2,000+ canonical brands.
 */

export type BrandSeedEntry =
  | string
  | {
      name: string;
      aliases?: readonly string[];
      keywords?: readonly string[];
      country?: string;
      website?: string;
      formerNames?: readonly string[];
    };

export const BRAND_SEEDS: Record<string, readonly BrandSeedEntry[]> = {
  vehicles: [
    "Audi", "BMW", "Citroen", "Fiat", "Ford", "Honda", "Hyundai", "Jaguar", "Kia",
    "Land Rover", "Lexus", "Mazda", "Mercedes-Benz", "Mini", "Mitsubishi", "Nissan",
    "Peugeot", "Porsche", "Renault", "Seat", "Skoda", "Subaru", "Suzuki", "Tesla",
    "Toyota", "Vauxhall", "Volkswagen", "Volvo", "Alfa Romeo", "Bentley", "Chevrolet",
    "Dacia", "Dodge", "Jeep", "Lamborghini", "Maserati", "McLaren", "Rolls-Royce",
    "Aston Martin", "MG", "Cupra", "Polestar", "Genesis", "Infiniti", "Cadillac",
    "Lincoln", "Chrysler", "Buick", "GMC", "Ram", "Isuzu", "SsangYong", "DS Automobiles",
    "Abarth", "Alpine", "Lotus", "Caterham", "Morgan", "Rimac", "Lucid", "Rivian",
    "BYD", "NIO", "XPeng", "Geely", "Great Wall", "Chery", "Maxus", "LDV",
    "Piaggio", "Vespa", "Aprilia", "Ducati", "Triumph", "Harley-Davidson", "Kawasaki",
    "Yamaha", "KTM", "Husqvarna", "Royal Enfield", "Benelli", "MV Agusta",
    "Bailey", "Swift", "Coachman", "Lunar", "Elddis", "Adria", "Hymer", "Knaus",
    "Beneteau", "Jeanneau", "Bavaria", "Sunseeker", "Princess", "Bayliner",
    { name: "Mercedes", aliases: ["Mercedes-Benz"], formerNames: ["Daimler"], country: "Germany" },
    { name: "VW", aliases: ["Volkswagen"], country: "Germany" },
  ],
  electronics: [
    "Apple", "Samsung", "Sony", "LG", "Panasonic", "Philips", "Bosch", "Siemens",
    "Google", "Huawei", "OnePlus", "Xiaomi", "Oppo", "Motorola", "Nokia", "Asus",
    "Acer", "Dell", "HP", "Lenovo", "Microsoft", "MSI", "Razer", "Canon", "Nikon",
    "Fujifilm", "GoPro", "DJI", "Bose", "JBL", "Sennheiser", "Dyson", "KitchenAid",
    "DeLonghi", "Nintendo", "PlayStation", "Xbox", "Garmin", "Fitbit", "Amazon",
    "Ring", "Nest", "TP-Link", "Netgear", "Logitech", "Anker", "Belkin", "Intel",
    "AMD", "NVIDIA", "Qualcomm", "Corsair", "HyperX", "SteelSeries", "Alienware",
    "Gigabyte", "BenQ", "ViewSonic", "Hisense", "TCL", "Sharp", "Honor", "Realme",
    "Nothing", "Fairphone", "Sonos", "Denon", "Yamaha", "Pioneer", "Marshall",
    "Skullcandy", "Beats", "Jabra", "Elgato", "Rode", "Shure", "Audio-Technica",
    "AKG", "Beyerdynamic", "Creality", "Prusa", "Anycubic", "Elegoo", "Bambu Lab",
    "Western Digital", "Seagate", "SanDisk", "Kingston", "Crucial", "G.Skill",
    "Thermaltake", "Cooler Master", "NZXT", "Fractal Design", "be quiet!",
    "Noctua", "Arctic", "EVGA", "Zotac", "Sapphire", "PowerColor", "ASRock",
    "Wacom", "Huion", "XP-Pen", "Epson", "Brother", "HP Smart", "Lexmark",
    "TomTom", "Navman", "Garmin", "Wahoo", "Polar", "Suunto", "Coros", "Whoop",
    "Oura", "Withings", "Omron", "Beurer", "Braun", "Oral-B", "Philips Sonicare",
  ],
  fashion: [
    "Nike", "Adidas", "Puma", "Reebok", "New Balance", "Under Armour", "Converse", "Vans",
    "Zara", "H&M", "Uniqlo", "Mango", "Primark", "Next", "ASOS", "River Island",
    "Boohoo", "PrettyLittleThing", "Levi's", "Tommy Hilfiger", "Calvin Klein",
    "Ralph Lauren", "Lacoste", "Boss", "Hollister", "Superdry", "The North Face",
    "Patagonia", "Columbia", "Barbour", "Burberry", "Gucci", "Prada", "Versace",
    "Balenciaga", "Louis Vuitton", "Chanel", "Dior", "Michael Kors", "Coach",
    "Ted Baker", "Radley", "Mulberry", "Clarks", "Dr Martens", "Timberland", "Ugg",
    "Skechers", "Crocs", "Moncler", "Stone Island", "Armani", "Hugo Boss", "Fendi",
    "Givenchy", "Saint Laurent", "Valentino", "Bottega Veneta", "Celine", "Loewe",
    "Jacquemus", "Off-White", "Supreme", "Palace", "Stussy", "Carhartt", "Dickies",
    "Champion", "Fila", "Kappa", "Ellesse", "Lonsdale", "Slazenger", "Fred Perry",
    "Lyle and Scott", "Ben Sherman", "Paul Smith", "Reiss", "Whistles", "Hobbs",
    "Phase Eight", "Monsoon", "Accessorize", "Oasis", "Warehouse", "Coast", "Karen Millen",
    "French Connection", "AllSaints", "Reformation", "Ganni", "Sandro", "Maje",
    "COS", "Arket", "Weekday", "Monki", "Stories", "Massimo Dutti", "Pull and Bear",
    "Bershka", "Stradivarius", "Oysho", "Lefties", "Uterqüe", "Desigual", "Scotch and Soda",
    "G-Star RAW", "Diesel", "Replay", "Pepe Jeans", "Lee", "Wrangler", "True Religion",
    "7 For All Mankind", "Citizens of Humanity", "AG Jeans", "Paige", "Frame", "Mother",
  ],
  home: [
    "IKEA", "Habitat", "John Lewis", "Dunelm", "Laura Ashley", "M&S", "The White Company",
    "Cath Kidston", "Joseph Joseph", "Le Creuset", "Smeg", "Russell Hobbs", "Morphy Richards",
    "Tefal", "Dualit", "KitchenAid", "Ninja", "Shark", "Henry", "Vax", "Bissell",
    "Silentnight", "Tempur", "Emma", "Simba", "Dyson", "Miele", "AEG", "Hotpoint",
    "Beko", "Indesit", "Zanussi", "Bosch", "Siemens", "NEFF", "Grohe", "Hansgrohe",
    "Wayfair", "Made", "Sofa.com", "Oak Furniture Land", "Bensons for Beds", "Dreams",
    "Mattress Online", "Mattressman", "Warren Evans", "Loaf", "Heal's", "Conran Shop",
    "Cox and Cox", "Nkuku", "Graham and Green", "Rockett St George", "H&M Home",
    "Zara Home", "M&S Home", "Argos", "Wilko", "B&M", "The Range", "Home Bargains",
    "Poundland", "Savers", "Robert Dyas", "Lakeland", "ProCook", "Stellar", "Judge",
    "Circulon", "Anolon", "Calphalon", "All-Clad", "Scanpan", "GreenPan", "Zwilling",
    "WMF", "Fissler", "Ballarini", "Berghoff", "Sage", "Magimix", "Kenwood", "Breville",
    "George Home", "Tu", "F&F", "Sainsbury's Home", "Tesco Home", "Asda George",
  ],
  pillows: [
    "Derila", "Elviros", "BCOZZY", "Cabeau", "Mulisoft", "Tempur", "Silentnight", "Emma",
    "Dunelm", "IKEA", "Simba", "Panda", "Eve", "Casper", "Dormeo", "Hypnos", "Sealy",
    "Dreams", "John Lewis", "M&S", "The White Company", "Kally Sleep", "Nanu", "Levitex",
    "Putnams", "Mediflow", "Coop Home Goods", "Beckham Hotel Collection", "Utopia Bedding",
    "viewstar", "Cosy House", "Pharmedoc", "EPABO", "Weekender", "Bluewave", "Snuggle-Pedic",
    "Panda London", "Otty", "Emma Diamond", "Nectar", "Emma Original", "Emma Hybrid",
    "Brook and Wilde", "Mattress Online", "Bed Factory", "Soak and Sleep", "The Fine Bedding Company",
    "Fogarty", "Dorma", "Catherine Lansfield", "Julian Charles", "Christy", "Sheridan",
  ],
  tools: [
    "Bosch", "DeWalt", "Makita", "Milwaukee", "Ryobi", "Black and Decker", "Festool",
    "Einhell", "Stanley", "Bahco", "Snap-on", "Metabo", "Hilti", "Worx", "Karcher",
    "Hitachi", "HiKOKI", "Panasonic Tools", "AEG Powertools", "Skil", "Dremel",
    "Rothenberger", "Ridgid", "Irwin", "Vaughan", "Estwing", "Fiskars", "Gerber",
    "Leatherman", "Victorinox", "Wera", "Wiha", "Knipex", "Gedore", "Stahlwille",
    "Facom", "Beta", "King Tony", "Sealey", "Draper", "Silverline", "Faithfull",
    "Trend", "Triton", "Record Power", "Axminster", "Rutlands", "Screwfix",
    "Toolstation", "Wickes", "B&Q", "Homebase", "Travis Perkins", "Jewson", "Selco",
  ],
  sports: [
    "Nike", "Adidas", "Puma", "Under Armour", "Reebok", "New Balance", "Asics", "Brooks",
    "Saucony", "Wilson", "Head", "Babolat", "Yonex", "Callaway", "TaylorMade", "Ping",
    "Specialized", "Trek", "Cannondale", "Giant", "Shimano", "SRAM", "Garmin", "Wahoo",
    "Mizuno", "Umbro", "Kappa", "Lotto", "Diadora", "Hummel", "Joma", "Kelme",
    "Decathlon", "Kipsta", "Quechua", "Wedze", "Simond", "Salomon", "Merrell", "Keen",
    "Columbia", "The North Face", "Berghaus", "Rab", "Montane", "Mountain Equipment",
    "Arc'teryx", "Mammut", "Black Diamond", "Petzl", "Camp", "Edelrid", "DMM",
    "Speedo", "Arena", "Zoggs", "TYR", "Finis", "Aqua Sphere", "Zone3", "Huub",
    "Gymshark", "Lululemon", "Sweaty Betty", "Fabletics", "MyProtein", "Bulk",
    "Optimum Nutrition", "BSN", "MuscleTech", "Dymatize", "PhD", "Applied Nutrition",
  ],
  baby: [
    "Bugaboo", "Silver Cross", "iCandy", "Cybex", "Maxi-Cosi", "Joie", "Chicco", "Graco",
    "Mamas and Papas", "Stokke", "Ergobaby", "Tommee Tippee", "Avent", "Philips Avent",
    "Nuna", "UPPAbaby", "Baby Jogger", "Britax", "Cosatto", "Egg", "Joolz", "Mountain Buggy",
    "Out n About", "Red Kite", "Ickle Bubba", "Kinderkraft", "Hauck", "Obaby", "Babystyle",
    "Mee-Go", "My Babiie", "Peg Perego", "Inglesina", "Bébécar", "Bebecar", "Jane",
    "Maclaren", "Babyzen", "YOYO", "Doona", "Bambino Mio", "TotsBots", "Baba+Boo",
    "Close Parent", "Charlie Banana", "Little Lamb", "GroVia", "Thirsties", "Alva Baby",
  ],
  beauty: [
    "Estée Lauder", "Clinique", "MAC", "L'Oréal", "Maybelline", "Nivea", "Olay", "Garnier",
    "The Ordinary", "CeraVe", "Charlotte Tilbury", "Fenty Beauty", "Rare Beauty", "NARS",
    "Bobbi Brown", "La Mer", "SK-II", "Shiseido", "Clarins", "Lancôme", "Yves Saint Laurent",
    "Giorgio Armani", "Tom Ford", "Dior", "Chanel", "Guerlain", "Givenchy", "Benefit",
    "Urban Decay", "Too Faced", "Tarte", "IT Cosmetics", "Smashbox", "BareMinerals",
    "e.l.f.", "NYX", "Revolution", "Collection", "Rimmel", "Bourjois", "Max Factor",
    "Revlon", "Covergirl", "Neutrogena", "Aveeno", "Eucerin", "La Roche-Posay", "Vichy",
    "Bioderma", "Avène", "Caudalie", "Fresh", "Kiehl's", "Origins", "Drunk Elephant",
    "Paula's Choice", "Pixi", "Glossier", "Milk Makeup", "Kosas", "Ilia", "Merit",
    "Saie", "Tower 28", "Lawless", "Hourglass", "Pat McGrath", "Huda Beauty", "Anastasia Beverly Hills",
    "Morphe", "ColourPop", "Juvia's Place", "BH Cosmetics", "Sigma", "Real Techniques",
    "EcoTools", "Spectrum", "Beauty Blender", "Flawless", "Look Fantastic", "Cult Beauty",
  ],
  toys: [
    "LEGO", "Hasbro", "Mattel", "Playmobil", "Ravensburger", "Scalextric", "Hornby",
    "Fisher-Price", "Barbie", "Hot Wheels", "Nerf", "Transformers", "Monopoly", "Play-Doh",
    "FurReal", "UNO", "Mega Bloks", "Duplo", "Technic", "Star Wars LEGO", "Harry Potter LEGO",
    "Marvel", "DC Comics", "Pokemon", "Nintendo", "Sonic", "Minecraft", "Roblox", "Fortnite",
    "Squishmallows", "Jellycat", "Steiff", "Build-A-Bear", "TY", "Beanie Boo", "Sylvanian Families",
    "Schleich", "Papo", "CollectA", "Safari Ltd", "Brio", "Hape", "Melissa and Doug",
    "VTech", "LeapFrog", "Clementoni", "Galt", "Orchard Toys", "Djeco", "Janod", "Tender Leaf",
    "Bigjigs", "Tidlo", "John Crane", "Lanka Kade", "Plan Toys", "Grimms", "Ostheimer",
    "Maileg", "Lottie Dolls", "Corolle", "Baby Annabell", "Baby Born", "Our Generation",
    "American Girl", "Gotz", "Zapf Creation", "Smoby", "Little Tikes", "Step2", "Plum Play",
  ],
  books: [
    "Penguin", "Penguin Random House", "HarperCollins", "Hachette", "Pan Macmillan",
    "Bloomsbury", "Faber", "Vintage", "Oxford University Press", "Cambridge University Press",
    "Collins", "Pearson", "Routledge", "Sage", "Wiley", "Springer", "Elsevier", "Taylor and Francis",
    "DK", "Usborne", "Walker Books", "Nosy Crow", "Scholastic", "Egmont", "Hodder",
    "Orion", "Transworld", "Century", "Viking", "Hamish Hamilton", "Allen Lane", "Michael Joseph",
    "Picador", "Tor", "Headline", "Quercus", "4th Estate", "Sceptre", "John Murray",
    "Little Brown", "Sphere", "Abacus", "Virago", "Corsair", "Constable", "Robinson",
    "Canongate", "Profile Books", "Atlantic Books", "Granta", "Serpent's Tail", "Oneworld",
    "Verso", "Pluto Press", "Zed Books", "Repeater Books", "Fitzcarraldo", "Daunt Books",
    "Waterstones", "WHSmith", "Blackwell's", "Foyles", "Hatchards", "Daunt Books",
  ],
  garden: [
    "Flymo", "Bosch Garden", "Stihl", "Husqvarna", "Mountfield", "Hayter", "Webb",
    "Cobra", "Einhell Garden", "Greenworks", "EGO", "Worx Garden", "Ryobi Garden",
    "Makita Garden", "DeWalt Garden", "Spear and Jackson", "Wilkinson Sword", "Fiskars Garden",
    "Burgon and Ball", "Kent and Stowe", "Draper Garden", "Faithfull Garden", "Silverline Garden",
    "Gardena", "Hozelock", "Kärcher Garden", "Nilfisk", "Karcher", "Bosch AQT",
    "Dobbies", "B&Q Garden", "Homebase Garden", "Wilko Garden", "The Range Garden",
    "Suttons", "Thompson and Morgan", "Mr Fothergill's", "Unwins", "Johnson's Seeds",
    "Miracle-Gro", "Westland", "Levington", "J Arthur Bowers", "Vitax", "Baby Bio",
    "Garland", "Elho", "Stewart", "Sankey", "Strata", "Zest", "Forest Garden",
  ],
  pets: [
    "Royal Canin", "Hill's", "Purina", "Iams", "Eukanuba", "Burns", "James Wellbeloved",
    "Lily's Kitchen", "Barking Heads", "Forthglade", "Natures Menu", "Applaws", "Scrumbles",
    "Pooch and Mutt", "Beco", "Yarrah", "Edgard and Cooper", "Canagan", "Orijen", "Acana",
    "Wellness", "Blue Buffalo", "Taste of the Wild", "Nutro", "Pedigree", "Whiskas",
    "Felix", "Sheba", "Gourmet", "Dreamies", "Temptations", "Catit", "Feliway",
    "Kong", "Nylabone", "Chuckit", "West Paw", "Outward Hound", "Ruffwear", "Julius-K9",
    "Hurtta", "Ancol", "Company of Animals", "PetSafe", "SureFlap", "Cat Mate", "Ferplast",
    "Savic", "Midwest", "Rosewood", "Burgess", "Supreme", "Beaphar", "Johnson's Veterinary",
  ],
  health: [
    "Boots", "Superdrug", "Holland and Barrett", "Lloyds Pharmacy", "Well Pharmacy",
    "Rowlands Pharmacy", "Day Lewis", "Numark", "Pharmacy2U", "Chemist Direct",
    "Medela", "Lansinoh", "Tommee Tippee Health", "Elvie", "Willow", "Spectra",
    "Omron", "Beurer", "Braun Health", "Withings", "Fitbit", "Garmin Health",
    "Philips Health", "ResMed", "Fisher and Paykel", "Devilbiss", "Drive DeVilbiss",
    "Invacare", "Sunrise Medical", "Pride Mobility", "Karma Mobility", "Days Healthcare",
    "Aidapt", "Homecraft", "Performance Health", "Patterson Medical", "Medline",
  ],
  food: [
    "Tesco", "Sainsbury's", "Asda", "Morrisons", "Aldi", "Lidl", "Waitrose", "M&S Food",
    "Co-op", "Iceland", "Ocado", "HelloFresh", "Gousto", "Mindful Chef", "Allplants",
    "Heinz", "Kellogg's", "Nestlé", "Unilever", "Mars", "Mondelez", "Cadbury", "Galaxy",
    "Maltesers", "Ferrero", "Lindt", "Green and Black's", "Hotel Chocolat", "Thorntons",
    "Walkers", "McVitie's", "Jacob's", "Carr's", "Fox's", "Bahlsen", "Lotus", "Oreo",
    "Tyrrells", "Kettle Chips", "Pipers", "Burts", "Propercorn", "Metcalfe's",
  ],
  music: [
    "Fender", "Gibson", "Epiphone", "Ibanez", "Taylor", "Martin", "Yamaha Music",
    "Roland", "Korg", "Casio", "Nord", "Moog", "Arturia", "Native Instruments",
    "Focusrite", "PreSonus", "Universal Audio", "Mackie", "Behringer", "Midas",
    "Allen and Heath", "Soundcraft", "QSC", "JBL Pro", "Electro-Voice", "RCF",
    "Zildjian", "Sabian", "Paiste", "Meinl", "Pearl", "Tama", "DW", "Ludwig",
    "Gretsch", "Sonor", "Mapex", "Pioneer DJ", "Technics", "Numark", "Denon DJ",
  ],
  luxury: [
    "Rolex", "Omega", "TAG Heuer", "Breitling", "Cartier", "IWC", "Panerai", "Hublot",
    "Audemars Piguet", "Patek Philippe", "Jaeger-LeCoultre", "Vacheron Constantin",
    "Hermès", "Chanel", "Louis Vuitton", "Gucci", "Prada", "Dior", "Burberry",
    "Tiffany and Co", "Bulgari", "Van Cleef and Arpels", "Chopard", "Piaget",
    "Montblanc", "Bottega Veneta", "Celine", "Loewe", "Saint Laurent", "Balenciaga",
    "Givenchy", "Fendi", "Valentino", "Versace", "Dolce and Gabbana", "Ferragamo",
  ],
  retail: [
    "Argos", "Currys", "PC World", "Carphone Warehouse", "AO.com", "Very", "Littlewoods",
    "Shop Direct", "QVC", "Ideal World", "Amazon UK", "eBay", "Etsy", "Depop", "Vinted",
    "Sports Direct", "JD Sports", "Foot Locker", "Size", "Footasylum", "Office", "Schuh",
    "Kurt Geiger", "Dune", "Russell and Bromley", "Clarks", "Shoe Zone", "Wynsors",
    "Halfords", "Euro Car Parts", "GSF Car Parts", "Motor Factor", "Andrew Page",
    "Toolstation", "Screwfix", "Wickes", "B&Q", "Homebase", "Robert Dyas", "Lakeland",
  ],
  industrial: [
    "Siemens Industrial", "ABB", "Schneider Electric", "Emerson", "Honeywell Industrial",
    "Rockwell Automation", "Omron", "Mitsubishi Electric", "Fanuc", "KUKA", "Yaskawa",
    "Parker", "Eaton", "Legrand", "Hager", "MK Electric", "Wylex", "Crabtree",
    "Contactum", "BG Electrical", "LAP", "Time", "Deta", "Scolmore", "Hamilton",
    "Varilight", "Retrotouch", "Lightwave", "Lutron", "Rako", "Collingwood", "JCC",
  ],
  stationery: [
    "Staedtler", "Faber-Castell", "Parker", "Waterman", "Cross", "Sheaffer", "Lamy",
    "Pilot", "Uni-ball", "Zebra", "Pentel", "Stabilo", "Sharpie", "Bic", "Paper Mate",
    "Moleskine", "Leuchtturm", "Rhodia", "Clairefontaine", "Oxford Stationery",
    "Ryman", "WHSmith Stationery", "Paperchase", "Hamelin", "Elba", "Rexel", "Fellowes",
  ],
  hospitality: [
    "Premier Inn", "Travelodge", "Hilton", "Marriott", "Holiday Inn", "Best Western",
    "Radisson", "Novotel", "Ibis", "Mercure", "Crowne Plaza", "DoubleTree", "Hyatt",
    "Four Seasons", "Ritz", "Savoy", "Claridge's", "Connaught", "Langham", "Corinthia",
  ],
  eyewear: [
    "Ray-Ban", "Oakley", "Persol", "Oliver Peoples", "Warby Parker", "Specsavers",
    "Vision Express", "Boots Opticians", "Asda Opticians", "Tesco Opticians", "Cubitts",
    "Ace and Tate", "Glasses Direct", "SmartBuyGlasses", "Designer Frames", "Silhouette",
    "Tom Ford Eyewear", "Prada Eyewear", "Gucci Eyewear", "Dior Eyewear", "Cutler and Gross",
  ],
  watches_extra: [
    "Casio", "Citizen", "Seiko", "Tissot", "Longines", "Hamilton", "Rado", "Certina",
    "Mido", "Oris", "Tudor", "Bell and Ross", "Zenith", "Blancpain", "Breguet",
    "Glashütte Original", "Grand Seiko", "Nomos", "Sinn", "Damasko", "Stowa", "Laco",
  ],
  pharma: [
    "GSK", "AstraZeneca", "Pfizer", "Novartis", "Roche", "Sanofi", "Bayer", "Merck",
    "Johnson and Johnson", "AbbVie", "Bristol Myers Squibb", "Amgen", "Gilead",
    "Takeda", "Boehringer Ingelheim", "Novo Nordisk", "Eli Lilly", "Biogen",
    "Regeneron", "Moderna", "BioNTech", "CSL", "Teva", "Mylan", "Sandoz",
  ],
  cleaning: [
    "Dettol", "Domestos", "Cif", "Flash", "Mr Muscle", "Harpic", "Finish", "Fairy",
    "Persil", "Ariel", "Daz", "Bold", "Surf", "Comfort", "Lenor", "Vanish",
    "Calgon", "Viakal", "Bloo", "Bref", "Glade", "Febreze", "Air Wick", "Yankee Candle",
    "Woodwick", "Method", "Ecover", "Bio-D", "Smol", "Splosh", "Iron and Velvet",
  ],
  appliances: [
    "Bosch Home", "Siemens Home", "AEG", "Zanussi", "Electrolux", "Whirlpool",
    "Candy", "Hoover", "Baumatic", "Rangemaster", "Belling", "Stoves", "Leisure",
    "Blomberg", "Grundig", "Sharp Home", "Panasonic Home", "LG Home", "Samsung Home",
    "Hisense Home", "Haier", "TCL Home", "Amica", "Statesman", "Servis", "White Knight",
  ],
  flooring: [
    "Karndean", "Amtico", "Quick-Step", "Pergo", "Balterio", "Kaindl", "Egger",
    "Kronospan", "Wineo", "Moduleo", "Polyflor", "Altro", "Forbo", "Interface",
    "Milliken", "Desso", "Victoria Carpets", "Cormar", "Abingdon", "Brintons",
  ],
  paint_brands: [
    "Dulux", "Crown", "Johnstone's", "Leyland", "Armstead", "Macpherson", "Sandtex",
    "Cuprinol", "Ronseal", "Sadolin", "Sikkens", "Farrow and Ball", "Little Greene",
    "Paint and Paper Library", "Edward Bulmer", "Mylands", "COAT", "Lick", "YesColours",
  ],
  gaming: [
    "Nintendo", "PlayStation", "Xbox", "Steam", "Epic Games", "Ubisoft", "EA", "Activision",
    "Blizzard", "Bethesda", "Rockstar", "CD Projekt", "FromSoftware", "Bandai Namco",
    "Capcom", "Square Enix", "Sega", "Konami", "Atlus", "PlatinumGames", "Remedy",
    "IO Interactive", "Creative Assembly", "Sports Interactive", "Frontier Developments",
    "Team17", "Rebellion", "Sumo Digital", "Codemasters", "DICE", "BioWare", "Denuvo",
    "Razer", "Logitech G", "Corsair", "HyperX", "SteelSeries", "Turtle Beach", "Astro",
    "Scuf", "Thrustmaster", "Fanatec", "Secretlab", "noblechairs", "AKRacing",
    "Playseat", "Next Level Racing", "Elgato", "Blue", "NZXT", "Hyte", "Lian Li",
  ],
  software: [
    "Microsoft", "Adobe", "Autodesk", "Oracle", "SAP", "Salesforce", "Intuit", "VMware",
    "Citrix", "Zoom", "Slack", "Atlassian", "Notion", "Monday.com", "Asana", "Trello",
    "Dropbox", "Box", "Google Workspace", "Canva", "Figma", "Sketch", "InVision",
    "Corel", "Serif", "Affinity", "Quark", "Avid", "Blackmagic", "DaVinci", "Final Cut",
    "Logic Pro", "Ableton", "FL Studio", "Pro Tools", "Cubase", "Reason", "Bitwig",
  ],
  uk_retail: [
    "Marks and Spencer", "Boots", "Superdrug", "Holland and Barrett", "Poundland",
    "B&M", "Home Bargains", "The Range", "Wilko", "Savers", "Card Factory", "Claire's",
    "Accessorize", "H Samuel", "Ernest Jones", "Beaverbrooks", "Goldsmiths", "F Hinds",
    "Pandora", "Swarovski", "Thomas Sabo", "Links of London", "Monica Vinader", "Missoma",
    "Oliver Bonas", "Anthropologie", "Free People", "Urban Outfitters", "Fat Face",
    "White Stuff", "Joules", "Crew Clothing", "Boden", "Toast", "Seasalt Cornwall",
    "Weird Fish", "Regatta", "Craghoppers", "Dare 2b", "Sprayway", "Rohan",
    "Trespass", "Mountain Warehouse", "Go Outdoors", "Blacks", "Millets", "Cotswold Outdoor",
    "Snow and Rock", "Ellis Brigham", "Tiso", "Nevisport", "Campbell's of Beauly",
  ],
  additional: [
    "3M", "Abbott", "AkzoNobel", "Alstom", "Amcor", "Amphenol", "Anglo American",
    "ArcelorMittal", "Arla", "Arm Holdings", "Arup", "Associated British Foods",
    "Atlas Copco", "Autoglass", "Aviva", "BAE Systems", "Bakkavor", "Balfour Beatty",
    "Barratt", "BAT", "Bellway", "Berkeley Group", "Biffa", "BP", "BT Group",
    "Burberry Group", "Centrica", "Compass Group", "Convatec", "Croda", "Diageo",
    "Direct Line", "Dunelm Group", "Entain", "Experian", "Ferrexpo", "Flutter",
    "Frasers Group", "GlaxoSmithKline", "Glencore", "Halma", "Hammerson", "Hikma",
    "Hiscox", "Howden Joinery", "IG Group", "Imperial Brands", "Informa",
    "InterContinental Hotels", "Intertek", "ITV", "JD Wetherspoon", "Kingfisher",
    "Land Securities", "Legal and General", "Lloyds Banking Group", "London Stock Exchange",
    "Melrose Industries", "Mondi", "National Grid", "NatWest Group", "Ocado Group",
    "Pearson", "Persimmon", "Phoenix Group", "Prudential", "Reckitt", "RELX",
    "Rentokil Initial", "Rightmove", "Rio Tinto", "Rolls-Royce Holdings", "RSA Insurance",
    "Sage Group", "Sainsbury's", "Schroders", "Scottish Mortgage", "Segro", "Severn Trent",
    "Smith and Nephew", "Smiths Group", "Smurfit Kappa", "Spirax-Sarco", "SSE",
    "Standard Chartered", "St James's Place", "Taylor Wimpey", "Tesco", "TUI",
    "Unilever", "United Utilities", "Vodafone", "Weir Group", "Whitbread", "WPP",
    "3i Group", "Admiral Group", "Airtel Africa", "Antofagasta", "Ashtead Group",
    "Auto Trader", "AVEVA", "Babcock International", "BBA Aviation", "Beazley",
    "Big Yellow Group", "Bovis Homes", "British Land", "Britvic", "Bunzl", "Carnival",
    "Cineworld", "Clarkson", "Close Brothers", "Computacenter", "DCC", "Dechra Pharmaceuticals",
    "Derwent London", "Diploma", "Domino's Pizza", "Drax Group", "Electrocomponents",
    "Elementis", "EnQuest", "Evraz", "FirstGroup", "Galliford Try", "Games Workshop",
    "Go-Ahead Group", "Grafton Group", "Grainger", "Great Portland Estates", "Greencore",
    "Greggs", "Harbour Energy", "Hargreaves Lansdown", "Hays", "Hilton Food Group",
    "Hochschild Mining", "Homeserve", "Hunting", "Ibstock", "Inchcape", "Indivior",
    "IntegraFin", "Investec", "IP Group", "JD Sports Fashion", "John Laing",
    "Johnson Matthey", "Jupiter Fund Management", "Just Eat Takeaway", "Kainos",
    "Kaz Minerals", "Keller Group", "Kier Group", "Lancashire Holdings", "Laird",
    "Learning Technologies", "Liontrust Asset Management", "LondonMetric Property",
    "Man Group", "Marston's", "McCarthy and Stone", "Mediclinic", "Meggitt", "Merlin Entertainments",
    "Micro Focus", "Mitchells and Butlers", "Mitie Group", "Moneysupermarket",
    "Morgan Advanced Materials", "Morgan Sindall", "National Express", "NCC Group",
    "Network International", "Nex Group", "Northgate", "Old Mutual", "OneSavings Bank",
    "Oxford Instruments", "PageGroup", "Pennon Group", "Pets at Home", "Playtech",
    "Plus500", "Polypipe", "Premier Farnell", "Primary Health Properties",
    "Provident Financial", "PZ Cussons", "QinetiQ", "Quilter", "Rathbone Brothers",
    "Reach", "Redrow", "Renishaw", "Restaurant Group", "Restore", "Ricardo",
    "Riverstone Energy", "Rotork", "Royal Mail", "RPC Group", "RS Group", "Safestore",
    "Saga", "Savills", "Severfield", "Shaftesbury", "SIG", "Softcat", "Spirent",
    "St Modwen Properties", "Stagecoach", "Synthomer", "Tate and Lyle", "Telecom Plus",
    "The Gym Group", "TP ICAP", "Travis Perkins", "Tullow Oil", "UDG Healthcare",
    "Ultra Electronics", "Unite Group", "Vesuvius", "Victrex", "Vistry Group",
    "Volution Group", "Watches of Switzerland", "Workspace Group", "Worldpay", "WSP Global",
    "Xaar", "Young and Co", "Aggreko", "Ashmore", "Bodycote", "Card Factory",
    "Crest Nicholson", "Dairy Crest", "De La Rue", "Dialight", "Domino Printing Sciences",
    "Ei Group", "Esure", "Fenner", "Fidessa", "Foxtons", "G4S", "GKN", "GVC Holdings",
    "Hammerson", "Henderson Group", "Hochschild Mining", "Ibstock", "IG Design Group",
    "Inmarsat", "ITE Group", "JTC", "Lazards", "Marston's", "Meggitt", "Mitie Group",
    "Nostrum Oil and Gas", "Pennon", "Record", "RPC", "Shaftesbury", "SIG",
    "Sirius Minerals", "SMA Solar", "Smiths News", "Sonic Healthcare", "Stobart Group",
    "Templeton Emerging Markets", "UDG", "Victrex", "Workspace", "Xaar",
  ],
};
