import { INTEGRATIONS_ENGINE_MODULE_IDS } from "@/lib/integrations-engine/registry";
import type { IntegrationsEngineDocument, IntegrationsEngineHistoryEntry } from "@/lib/integrations-engine/types";

const now = () => new Date().toISOString();

export function createDefaultIntegrationsEngineDocument(
  label = "ROVEXO Integrations Engine",
): IntegrationsEngineDocument {
  return {
    version: 1,
    updatedAt: now(),
    label,
    marketplaceVersion: "ROVEXO v1.0",
    primaryCountry: "United Kingdom",
    currency: "GBP",
    modules: INTEGRATIONS_ENGINE_MODULE_IDS.map((m) => ({ ...m, enabled: true })),
    paymentProviders: {
      stripe: true,
      paypal: false,
      applePay: false,
      googlePay: false,
      klarna: false,
      revolutPay: false,
    },
    shippingProviders: {
      royalMail: true,
      evri: true,
      dpd: true,
      dhl: true,
      ups: true,
      fedex: true,
      parcelforce: true,
      inpost: true,
      amazonShipping: true,
      rovexoShipping: false,
    },
    mapsLocation: {
      googleMaps: true,
      googlePlaces: true,
      addressValidation: true,
      geocoding: true,
      reverseGeocoding: true,
      distanceMatrix: true,
    },
    googleServices: {
      ga4: true,
      tagManager: true,
      searchConsole: true,
      recaptcha: true,
      googleOAuth: true,
      googleDrive: false,
    },
    appleServices: {
      appleSignIn: false,
      apns: false,
      appleWallet: false,
    },
    microsoftServices: {
      microsoftOAuth: false,
      microsoftGraph: false,
      azureIntegration: false,
    },
    emailServices: {
      brevo: false,
      smtp: true,
      sendgrid: false,
      mailgun: false,
      amazonSes: false,
      templateManager: true,
      emailQueue: true,
    },
    smsServices: {
      twilio: false,
      vonage: false,
      awsSns: false,
      futureProviders: false,
    },
    pushNotifications: {
      fcm: false,
      apns: false,
      webPush: true,
      browserPush: true,
    },
    fileStorage: {
      localStorage: true,
      cloudStorageReady: true,
      cdnReady: true,
      imageOptimization: true,
      fileValidation: true,
    },
    apiManagement: {
      restApi: true,
      webhookApi: true,
      oauth: true,
      apiKeys: true,
      rateLimits: true,
      apiHealth: true,
      apiMonitoring: true,
      apiLogs: true,
    },
    webhooks: {
      incomingWebhooks: true,
      outgoingWebhooks: true,
      retryQueue: true,
      failureQueue: true,
      webhookLogs: true,
      webhookTesting: true,
    },
    secretsManagement: {
      apiKeys: true,
      oauthSecrets: true,
      tokens: true,
      certificates: true,
      environmentVariables: true,
      keyRotationReady: true,
    },
    performance: {
      lazyLoading: true,
      backgroundQueue: true,
      retryLogic: true,
      caching: true,
      connectionPooling: true,
      optimizedRequests: true,
    },
    security: {
      encryptedSecrets: true,
      permissionValidation: true,
      secureWebhooks: true,
      rateLimiting: true,
      auditLogging: true,
      roleBasedAccess: true,
    },
    aiAssistant: {
      globalEnabled: false,
      providerRecommendations: true,
      healthAnalysis: true,
      failureDetection: true,
      performanceInsights: true,
      automaticDiagnostics: true,
      execution: "local",
    },
    integrations: {
      ordersEngine: true,
      shippingEngine: true,
      walletEngine: true,
      paymentsEngine: true,
      protectionEngine: true,
      messagesEngine: true,
      notificationsEngine: true,
      analyticsEngine: true,
      securityEngine: true,
      searchEngine: true,
      aiEngine: true,
      missionControl: true,
    },
    futureReady: [
      "ERP Integrations",
      "CRM Integrations",
      "Accounting Platforms",
      "Marketplace Connectors",
      "Supplier APIs",
      "Warehouse APIs",
      "Carrier APIs",
      "Tax Providers",
      "Insurance Providers",
    ],
    auditLog: [],
  };
}

export function createDefaultIntegrationsEngineHistory(): IntegrationsEngineHistoryEntry[] {
  return [];
}
