import type { CommandOsRootModule, CommandOsRootModuleId } from "@/lib/command-os-v4/types";

/** ROVEXO Command OS Enterprise v4.0 — canonical root module SSOT. */
export const COMMAND_OS_ROOT_MODULES: CommandOsRootModule[] = [
  {
    id: "mission-control",
    label: "Mission Control",
    description: "Single realtime dashboard — platform status, users, orders, revenue, health",
    icon: "🛰️",
    href: "/super-admin",
    status: "live",
    capabilities: ["realtime", "metrics", "alerts", "world-map"],
  },
  {
    id: "experience-os",
    label: "Experience OS",
    description: "Navigation, layouts, pages, components, widgets, responsive UX, localization",
    icon: "🎛️",
    href: "/super-admin/experience",
    status: "live",
    capabilities: ["screens", "navigation", "features", "analytics", "publish"],
  },
  {
    id: "design-os",
    label: "Design OS",
    description: "Icons, illustrations, typography, colors, assets, themes, design tokens",
    icon: "🎨",
    href: "/super-admin/experience?tab=icons",
    status: "live",
    capabilities: ["icons", "assets", "themes", "replace-engine"],
  },
  {
    id: "brand-os",
    label: "Brand OS",
    description: "Brand DNA, logo, banner, brand compliance and guardian rules",
    icon: "✨",
    href: "/super-admin/experience?tab=guardian",
    status: "live",
    capabilities: ["brand-dna", "guardian", "compliance"],
  },
  {
    id: "commerce-os",
    label: "Commerce OS",
    description: "Products, orders, inventory, discounts, checkout, returns, marketplace rules",
    icon: "🛒",
    href: "/super-admin/orders-engine",
    status: "live",
    capabilities: ["orders", "checkout", "returns", "fees"],
  },
  {
    id: "marketplace-os",
    label: "Marketplace OS",
    description: "Listings, categories, moderation, search, discovery, marketplace health",
    icon: "🏪",
    href: "/super-admin/moderation",
    status: "live",
    capabilities: ["listings", "categories", "moderation", "search"],
  },
  {
    id: "seller-os",
    label: "Seller OS",
    description: "Seller dashboards, listings, orders, fulfillment, bring your item",
    icon: "📦",
    href: "/import",
    status: "live",
    capabilities: ["listings", "orders", "import", "analytics"],
  },
  {
    id: "buyer-os",
    label: "Buyer OS",
    description: "Buyer journeys, saved items, cart, checkout, messaging, protection",
    icon: "🛍️",
    href: "/super-admin/protection-engine",
    status: "live",
    capabilities: ["cart", "checkout", "saved", "messages"],
  },
  {
    id: "business-os",
    label: "Business OS",
    description: "Verified business accounts, inventory, analytics, tax, directory",
    icon: "🏢",
    href: "/super-admin/businesses",
    status: "live",
    capabilities: ["verification", "inventory", "analytics", "tax"],
  },
  {
    id: "wallet-os",
    label: "Wallet OS",
    description: "Platform, seller, and business wallet balances, withdrawals, ledger",
    icon: "👛",
    href: "/super-admin/wallet-engine",
    status: "live",
    capabilities: ["balances", "withdrawals", "ledger"],
  },
  {
    id: "payment-os",
    label: "Payment OS",
    description: "Transactions, payouts, refunds, disputes, settlement, provider health",
    icon: "💳",
    href: "/super-admin/payments-engine",
    status: "live",
    capabilities: ["transactions", "payouts", "refunds", "disputes"],
  },
  {
    id: "shipping-os",
    label: "Shipping OS",
    description: "Sendcloud labels, tracking, carriers, delivery, returns, rate engine",
    icon: "🚚",
    href: "/super-admin/shipping-engine",
    status: "live",
    capabilities: ["labels", "tracking", "carriers", "rates", "webhooks"],
  },
  {
    id: "ai-os",
    label: "AI OS",
    description: "AI health, models, recommendations, search AI, moderation, assistant",
    icon: "🤖",
    href: "/super-admin/ai-engine",
    status: "live",
    capabilities: ["moderation", "category-ai", "assistant", "predictions"],
  },
  {
    id: "automation-os",
    label: "Automation OS",
    description: "Scheduled jobs, cron, workflows, automation rules, approval flows",
    icon: "⚡",
    href: "/super-admin/workflows",
    status: "live",
    capabilities: ["cron", "workflows", "notifications", "rules"],
  },
  {
    id: "communication-os",
    label: "Communication OS",
    description: "Messages, notifications, email, push, SMS, broadcasts",
    icon: "💬",
    href: "/super-admin/messages-engine",
    status: "live",
    capabilities: ["messages", "notifications", "email", "broadcasts"],
  },
  {
    id: "analytics-os",
    label: "Analytics OS",
    description: "Marketplace analytics, revenue, traffic, conversion, BI, funnels",
    icon: "📈",
    href: "/super-admin/analytics-engine",
    status: "live",
    capabilities: ["revenue", "traffic", "conversion", "retention", "bi"],
  },
  {
    id: "security-os",
    label: "Security OS",
    description: "Authentication, authorization, fraud, audit logs, rate limiting, encryption",
    icon: "🔒",
    href: "/super-admin/security-engine",
    status: "live",
    capabilities: ["auth", "permissions", "fraud", "audit", "rate-limits"],
  },
  {
    id: "infrastructure-os",
    label: "Infrastructure OS",
    description: "Database, API, storage, queues, workers, CDN, servers",
    icon: "🗄️",
    href: "/super-admin/database",
    status: "live",
    capabilities: ["database", "api", "storage", "queues", "cdn"],
  },
  {
    id: "release-os",
    label: "Release OS",
    description: "Release management, preview, approval, rollback, deployment, version history",
    icon: "🚀",
    href: "/super-admin/certification",
    status: "live",
    capabilities: ["preview", "approval", "rollback", "deploy", "notes"],
  },
  {
    id: "developer-os",
    label: "Developer OS",
    description: "Feature flags, environment, API keys, logs, CI/CD, diagnostics",
    icon: "🧰",
    href: "/super-admin/platform",
    status: "live",
    capabilities: ["feature-flags", "env", "logs", "diagnostics"],
  },
  {
    id: "monitoring-os",
    label: "Monitoring OS",
    description: "CPU, memory, API, queues, workers, performance, observability",
    icon: "💚",
    href: "/super-admin/monitoring",
    status: "live",
    capabilities: ["cpu", "memory", "api", "performance", "observability"],
  },
  {
    id: "certification-center",
    label: "Certification Center",
    description: "TypeScript, ESLint, build, Playwright, performance, security certification",
    icon: "🏆",
    href: "/super-admin/certification",
    status: "live",
    capabilities: ["typescript", "eslint", "build", "playwright", "e2e"],
  },
  {
    id: "audit-center",
    label: "Audit Center",
    description: "Marketplace, security, performance, design, payment, shipping audits",
    icon: "📋",
    href: "/super-admin/audit",
    status: "live",
    capabilities: ["marketplace", "security", "performance", "design", "shipping"],
  },
  {
    id: "backup-center",
    label: "Backup Center",
    description: "Automatic backup, manual backup, restore, snapshots, recovery validation",
    icon: "💾",
    href: "/super-admin/recovery",
    status: "live",
    capabilities: ["backup", "restore", "snapshots", "recovery"],
  },
  {
    id: "emergency-center",
    label: "Emergency Center",
    description: "Maintenance mode, read-only, disable marketplace/payments/shipping, broadcast",
    icon: "🚨",
    href: "/super-admin/command",
    status: "live",
    capabilities: ["maintenance", "read-only", "disable", "broadcast", "incidents"],
  },
];

export function getCommandOsRootModule(id: CommandOsRootModuleId): CommandOsRootModule | undefined {
  return COMMAND_OS_ROOT_MODULES.find((mod) => mod.id === id);
}

export function listCommandOsRootModules(): CommandOsRootModule[] {
  return [...COMMAND_OS_ROOT_MODULES];
}
