import type { ProductCategoryManual } from "@/lib/documentation/documentation-engine-v1";
import { product } from "@/lib/documentation/product-seed-v1";

const RELATED = [
  { title: "Shipping Policy", href: "/legal/shipping-policy" },
  { title: "Seller Terms", href: "/legal/seller-terms" },
  { title: "Help — Shipping", href: "/help/category/shipping" },
];

export const ELECTRONICS_CATEGORY: ProductCategoryManual = {
  id: "electronics",
  title: "Electronics, batteries, and devices",
  overview: "Most second-hand phones, laptops, and tablets are Allowed when honestly described. Loose lithium batteries, recalled chargers, IMEI-blocked phones, and counterfeit electronics are Restricted or Prohibited.",
  marketplaceRule: "Disclose functionality, locks, battery health, and accessories. Do not sell recalled or dangerous power products. Carrier rules for lithium batteries apply.",
  ukLegal: "Product safety, electrical safety, and waste battery rules apply. Stolen or blocked devices must not be sold.",
  allowedExamples: ["Working phones with clear IMEI/status", "Laptops with honest fault lists", "Sealed genuine chargers"],
  restrictedExamples: ["Devices with known faults", "Power banks (lithium content)", "Smartwatches with account locks disclosed"],
  prohibitedExamples: ["IMEI blacklisted stolen phones", "Recalled chargers", "Loose damaged lithium cells", "Counterfeit electronics"],
  specialConditions: "Remove personal data before shipping. State iCloud/Google lock status. Follow lithium shipping limits.",
  buyerRisks: "Stolen devices, cloud locks, fire risk from damaged batteries, fake chargers.",
  sellerResponsibilities: "Factory reset where possible, disclose locks/faults, use safe packaging for batteries, never sell recalled items.",
  moderationRules: "Brand/counterfeit detection; keyword flags for “blocked IMEI”, “iCloud locked”, “recall”.",
  aiDetection: "Image/brand detection, serial/IMEI language, lithium/battery risk scoring, duplicate fraud patterns.",
  commonMistakes: "Selling iCloud-locked phones as working; shipping loose batteries; fake Apple chargers.",
  products: [
    product({ id: "phones", name: "Phones", classification: "allowed", why: "Second-hand phones are core Allowed inventory when lawful and unlocked/disclosed.", rule: "Allowed with honest condition, functionality, and lock status. Stolen/blocked devices Prohibited.", faq: [{ question: "Can I sell a phone?", answer: "Yes if it is yours to sell, honestly described, and not stolen/IMEI-blocked. Disclose cloud locks." }] }),
    product({ id: "laptops", name: "Laptops", classification: "allowed", why: "Laptops are Allowed with accurate specs and faults.", rule: "Allowed. Disclose battery health and account locks." }),
    product({ id: "desktop-pcs", name: "Desktop PCs", classification: "allowed", why: "Desktops are Allowed when ownership is clear.", rule: "Allowed. List major components honestly." }),
    product({ id: "tablets", name: "Tablets", classification: "allowed", why: "Tablets follow phone-like disclosure rules.", rule: "Allowed with lock/fault disclosure." }),
    product({ id: "smartwatches", name: "Smartwatches", classification: "allowed", why: "Wearables are Allowed with pairing/lock disclosure.", rule: "Allowed. State if activation lock remains." }),
    product({ id: "chargers", name: "Chargers", classification: "restricted", why: "Unsafe or counterfeit chargers cause fire risk.", rule: "Restricted. Genuine/safe chargers only. Recalled or obvious fakes Prohibited.", faq: [{ question: "Can I sell a recalled charger?", answer: "No. Recalled chargers are Prohibited." }] }),
    product({ id: "power-banks", name: "Power Banks", classification: "restricted", why: "Lithium power banks have shipping and safety limits.", rule: "Restricted. Must be intact and shippable under carrier rules." }),
    product({ id: "lithium-batteries", name: "Lithium Batteries", classification: "restricted", why: "Lithium cells are hazardous goods for post.", rule: "Restricted when installed in devices; loose cells often Prohibited by carrier rules on ROVEXO." }),
    product({ id: "loose-batteries", name: "Loose Batteries", classification: "prohibited", why: "Loose lithium and damaged cells are high fire risk in transit.", rule: "Prohibited for loose lithium / damaged cells. Retail sealed alkaline AA/AAA may be Restricted." }),
    product({ id: "damaged-batteries", name: "Damaged Batteries", classification: "prohibited", why: "Swollen or punctured batteries are dangerous.", rule: "Prohibited." }),
    product({ id: "recalled-electronics", name: "Recalled Electronics", classification: "prohibited", why: "Recalled products must not re-enter the market.", rule: "Prohibited.", faq: [{ question: "Can I sell a recalled charger?", answer: "No." }] }),
    product({ id: "modified-electronics", name: "Modified Electronics", classification: "restricted", why: "Modifications can void safety certifications.", rule: "Restricted. Disclose all modifications. Unsafe electrical mods Prohibited." }),
    product({ id: "counterfeit-electronics", name: "Counterfeit Electronics", classification: "prohibited", why: "Fake branded electronics are IP and safety violations.", rule: "Prohibited." }),
    product({ id: "imei-blocked-devices", name: "IMEI Blocked Devices", classification: "prohibited", why: "Blacklisted devices are typically stolen or unpaid.", rule: "Prohibited.", faq: [{ question: "Can I sell an IMEI blocked phone?", answer: "No. Prohibited." }] }),
    product({ id: "cloud-locked-devices", name: "Cloud Locked Devices", classification: "restricted", why: "Activation locks prevent normal use.", rule: "Restricted only if clearly disclosed as parts/faulty; marketing as working while locked is Prohibited misrepresentation." }),
  ],
  faqs: [
    { question: "Can I sell a drone?", answer: "Yes if lawful consumer drones are honestly described (Restricted review may apply for cameras/flight range). Weaponised or illegal surveillance kits are Prohibited." },
    { question: "Can I sell a recalled charger?", answer: "No." },
    { question: "Can I sell loose lithium batteries?", answer: "Generally no — Prohibited when loose/damaged; follow carrier and ROVEXO rules." },
  ],
  relatedPolicies: RELATED,
};

export const VEHICLES_CATEGORY: ProductCategoryManual = {
  id: "vehicle-parts",
  title: "Vehicle parts and accessories (no whole vehicles)",
  overview: "ROVEXO sells vehicle parts and accessories as a catalogue root. Whole cars, motorcycles, vans, boats, and similar complete vehicles are Prohibited. Safety-critical parts have extra duties.",
  marketplaceRule: "Parts only. State fitment, OEM vs aftermarket, and condition. Airbags and seat belts are Restricted with strict authenticity rules. VIN plates and catalytic converters have elevated fraud risk.",
  ukLegal: "Road safety law and stolen parts rules apply. Do not sell airbags of unknown provenance. Catalytic converter theft is a known crime pattern.",
  allowedExamples: ["Alloy wheels", "Body mirrors", "Performance air filters", "Non-safety accessories"],
  restrictedExamples: ["Engines and gearboxes", "ECUs", "Tyres with remaining tread disclosed", "Diagnostic tools"],
  prohibitedExamples: ["Whole vehicles", "Stolen catalytic converters", "Tampered VIN plates", "Counterfeit airbags"],
  specialConditions: "ROVEXO Vehicle Parts & Accessories is its own catalogue root — never list whole vehicles. Courier-shippable parts only.",
  buyerRisks: "Incorrect fitment, unsafe airbags, stolen parts, fluids that leak in transit.",
  sellerResponsibilities: "Confirm ownership/provenance. Provide vehicle compatibility. Package fluids under carrier rules.",
  moderationRules: "Flags for VIN, cat converter, airbag keywords; whole-vehicle listing detection.",
  aiDetection: "Title/category mismatch (car for sale), image detection of whole vehicles, brand/fitment language, risk scoring for cats/airbags.",
  commonMistakes: "Listing a whole car under parts; selling used airbags without provenance; undervaluing stolen cats.",
  products: [
    product({ id: "car-parts", name: "Car Parts", classification: "allowed", why: "Courier-shippable car parts are core Allowed inventory.", rule: "Allowed when lawful and accurately fitted/described. Whole cars Prohibited." }),
    product({ id: "motorcycle-parts", name: "Motorcycle Parts", classification: "allowed", why: "Bike parts are Allowed; whole bikes are Prohibited.", rule: "Allowed for parts only." }),
    product({ id: "bicycle-parts", name: "Bicycle Parts", classification: "allowed", why: "Bicycle parts and accessories are Allowed.", rule: "Allowed. Complete bicycles may be Allowed as goods if not motor vehicles — describe accurately." }),
    product({ id: "ecus", name: "ECUs", classification: "restricted", why: "ECUs may be coded to a VIN and affect emissions/safety.", rule: "Restricted. Disclose vehicle compatibility and coding status.", faq: [{ question: "Can I sell a modified ECU?", answer: "Restricted — disclose modifications. Illegal emissions defeat devices are Prohibited." }] }),
    product({ id: "airbags", name: "Airbags", classification: "restricted", why: "Counterfeit/stolen airbags kill.", rule: "Restricted with provenance. Unknown-source or counterfeit airbags Prohibited." }),
    product({ id: "seat-belts", name: "Seat Belts", classification: "restricted", why: "Safety-critical restraint parts.", rule: "Restricted. Must be genuine and compatible. Damaged belts Prohibited." }),
    product({ id: "engines", name: "Engines", classification: "restricted", why: "Heavy parts with fitment and shipping complexity.", rule: "Restricted. Parts-only; no whole vehicle. Buyer must confirm shipping feasibility." }),
    product({ id: "gearboxes", name: "Gearboxes", classification: "restricted", why: "Same as engines — fitment and weight.", rule: "Restricted." }),
    product({ id: "vin-plates", name: "VIN Plates", classification: "prohibited", why: "VIN plates are used in identity fraud and stolen vehicle ringing.", rule: "Prohibited." }),
    product({ id: "catalytic-converters", name: "Catalytic Converters", classification: "restricted", why: "High theft category.", rule: "Restricted with proof of legitimate source. Suspected stolen cats Prohibited." }),
    product({ id: "tyres", name: "Tyres", classification: "restricted", why: "Unsafe worn tyres endanger road users.", rule: "Restricted. Disclose tread, age, damage. Illegal part-worn sales may be removed." }),
    product({ id: "vehicle-fluids", name: "Vehicle Fluids", classification: "restricted", why: "Flammable/leak hazards in post.", rule: "Restricted. Sealed retail containers only; follow carrier dangerous goods rules." }),
    product({ id: "diagnostic-equipment", name: "Diagnostic Equipment", classification: "allowed", why: "OBD tools are Allowed when not paired with theft devices.", rule: "Allowed. Relay attack / theft tools Prohibited." }),
    product({ id: "whole-vehicles", name: "Whole vehicles", classification: "prohibited", why: "ROVEXO catalogue forbids whole vehicles as a product type on this marketplace root.", rule: "Prohibited. Use Vehicle Parts & Accessories for parts only.", faq: [{ question: "Can I sell my car on ROVEXO?", answer: "No. Whole vehicles are Prohibited. You may sell eligible parts." }] }),
  ],
  faqs: [
    { question: "Can I sell a modified ECU?", answer: "Restricted with full disclosure. Emissions defeat hardware/software is Prohibited." },
    { question: "Can I sell catalytic converters?", answer: "Only with legitimate provenance under Restricted review." },
    { question: "Can I sell a whole car?", answer: "No." },
  ],
  relatedPolicies: RELATED,
};
