import type { ProductCategoryManual } from "@/lib/documentation/documentation-engine-v1";
import { product } from "@/lib/documentation/product-seed-v1";

const RELATED = [
  { title: "Prohibited & Restricted Items Policy", href: "/legal/prohibited-restricted-items" },
  { title: "Acceptable Use Policy", href: "/legal/acceptable-use-policy" },
  { title: "Help — Safety", href: "/help/category/safety" },
];

export const HOME_CATEGORY: ProductCategoryManual = {
  id: "home-garden-tools",
  title: "Home, garden, tools, and gas equipment",
  overview: "Furniture and most home goods are Allowed. Gas cylinders, generators, and some power tools are Restricted due to shipping and safety. Pressurised gas and unsafe electricals may be Prohibited.",
  marketplaceRule: "Describe condition, weight, and collection vs courier. Never list filled banned gas cylinders or dangerous pressure vessels against carrier rules.",
  ukLegal: "Product safety and gas safety rules apply. Do not sell unsafe second-hand gas appliances without required checks where law demands them.",
  allowedExamples: ["Furniture", "Lamps with safe wiring disclosed", "Manual garden tools"],
  restrictedExamples: ["Power tools", "Generators", "Glass tabletops", "Home appliances with electrical risk disclosed"],
  prohibitedExamples: ["Filled recreational gas cylinders sold unlawfully", "Recalled heaters", "Explosives / fireworks"],
  specialConditions: "Large items may require local delivery arranged in Messages but payment must stay on ROVEXO Checkout.",
  buyerRisks: "Injury from unsafe electrics, gas leaks, heavy lifting injuries, broken glass.",
  sellerResponsibilities: "Test electrics where claiming working; package glass; follow courier rules for tools with batteries.",
  moderationRules: "Flags for gas, generator, firework, cylinder keywords.",
  aiDetection: "Keyword/image risk for cylinders, fireworks, heaters; weight/shipping mismatch detection.",
  commonMistakes: "Listing fireworks as party supplies; selling damaged heaters; under-describing collection-only heavy furniture.",
  products: [
    product({ id: "furniture", name: "Furniture", classification: "allowed", why: "Furniture is standard Allowed inventory.", rule: "Allowed. State defects, stains, and collection needs." }),
    product({ id: "home-appliances", name: "Home Appliances", classification: "restricted", why: "Electrical safety varies.", rule: "Restricted. Working status and PAT/safety honesty required. Recalled appliances Prohibited." }),
    product({ id: "kitchen-equipment", name: "Kitchen Equipment", classification: "allowed", why: "Most kitchenware is Allowed.", rule: "Allowed. Knives follow Weapons/kitchen knife rules." }),
    product({ id: "glass", name: "Glass", classification: "restricted", why: "Breakage and injury risk in transit.", rule: "Restricted. Excellent packaging required; disclose chips." }),
    product({ id: "lighting", name: "Lighting", classification: "allowed", why: "Lamps and shades are Allowed when safe.", rule: "Allowed. Exposed unsafe wiring Prohibited until repaired/disclosed as parts." }),
    product({ id: "garden-tools", name: "Garden Tools", classification: "allowed", why: "Manual garden tools are Allowed.", rule: "Allowed. Machetes/axes follow blade rules." }),
    product({ id: "power-tools", name: "Power Tools", classification: "restricted", why: "Battery and electrical hazards.", rule: "Restricted. Include battery state; damaged lithium packs Prohibited." }),
    product({ id: "generators", name: "Generators", classification: "restricted", why: "Fuel, carbon monoxide, and shipping risks.", rule: "Restricted. Must be empty of fuel for shipping; CO warnings in description." }),
    product({ id: "gas-equipment", name: "Gas Equipment", classification: "restricted", why: "Gas appliances can kill if unsafe.", rule: "Restricted. Follow UK gas safety expectations; unsafe/recalled units Prohibited." }),
    product({ id: "pressure-cylinders", name: "Pressure Cylinders", classification: "prohibited", why: "Pressurised cylinders are dangerous goods.", rule: "Prohibited for filled hazardous cylinders on ROVEXO postal flows. Empty retail-compliant cases may be Restricted only if carrier-legal.", faq: [{ question: "Can I sell gas cylinders?", answer: "Filled hazardous pressure cylinders are Prohibited. Follow carrier law — when unsure, do not list." }] }),
  ],
  faqs: [
    { question: "Can I sell fireworks?", answer: "No. Fireworks and explosives are Prohibited." },
    { question: "Can I sell a generator?", answer: "Restricted — empty of fuel, honest condition, safety warnings." },
  ],
  relatedPolicies: RELATED,
};

export const ANIMALS_CATEGORY: ProductCategoryManual = {
  id: "animals",
  title: "Animals, pet products, and wildlife",
  overview: "Live animals are Prohibited. Pet accessories and sealed pet food are generally Allowed. Animal medicines and protected species products are Prohibited or Restricted.",
  marketplaceRule: "No live animals, no animal fighting equipment, no ivory/protected species products.",
  ukLegal: "Animal welfare and wildlife trade laws apply. CITES-protected products are banned.",
  allowedExamples: ["Pet beds", "Leashes", "Sealed pet food"],
  restrictedExamples: ["Specialist animal equipment", "Some animal feed supplements"],
  prohibitedExamples: ["Live animals", "Animal medicines", "Protected species parts", "Animal abuse content"],
  specialConditions: "ROVEXO is not a pet shop for live sales.",
  buyerRisks: "Illegal wildlife products; unsafe animal medicines.",
  sellerResponsibilities: "Do not list live animals or POM animal medicines.",
  moderationRules: "Automatic block for live animal / puppy sale language.",
  aiDetection: "Keywords for puppies, livestock, ivory, tortoise shell; image cues for live animals.",
  commonMistakes: "Puppy listings; selling prescription pet meds; ivory “vintage” claims.",
  products: [
    product({ id: "live-animals", name: "Live Animals", classification: "prohibited", why: "Live animal sales are not supported on ROVEXO.", rule: "Prohibited.", faq: [{ question: "Can I sell a puppy?", answer: "No. Live animals are Prohibited." }] }),
    product({ id: "animal-parts", name: "Animal Parts", classification: "prohibited", why: "Many animal parts are illegal or unethical to trade.", rule: "Prohibited for protected/illegal parts. Some processed legal leather goods are Allowed as fashion — not raw restricted wildlife parts." }),
    product({ id: "animal-medicines", name: "Animal Medicines", classification: "prohibited", why: "Veterinary medicines are regulated.", rule: "Prohibited." }),
    product({ id: "pet-food", name: "Pet Food", classification: "allowed", why: "Sealed pet food is Allowed.", rule: "Allowed when sealed and in-date. Opened pet food Prohibited." }),
    product({ id: "pet-accessories", name: "Pet Accessories", classification: "allowed", why: "Collars, toys, beds are Allowed.", rule: "Allowed. No shock devices that breach welfare expectations — those may be Prohibited." }),
    product({ id: "animal-equipment", name: "Animal Equipment", classification: "restricted", why: "Some equipment can enable harm.", rule: "Restricted. Fighting/cruelty equipment Prohibited." }),
    product({ id: "protected-species", name: "Protected Species", classification: "prohibited", why: "CITES and UK wildlife offences.", rule: "Prohibited." }),
  ],
  faqs: [
    { question: "Can I sell live animals?", answer: "No." },
    { question: "Can I sell sealed pet food?", answer: "Yes if in-date and sealed." },
  ],
  relatedPolicies: RELATED,
};

export const DIGITAL_CATEGORY: ProductCategoryManual = {
  id: "digital-goods",
  title: "Digital goods, accounts, and crypto",
  overview: "Many digital goods create fraud and ToS conflicts. Gift card physical cards may be Restricted. Account selling, cracked software, and most crypto asset dealing on ROVEXO are Prohibited.",
  marketplaceRule: "Do not sell login accounts, stolen codes, or pirated software. Physical media (games discs you own) may be Allowed.",
  ukLegal: "Fraud, copyright, and financial promotions rules may apply.",
  allowedExamples: ["Second-hand game discs you own", "Books/media physical copies"],
  restrictedExamples: ["Sealed retail software boxes", "Unused retail gift cards with proof of legitimacy"],
  prohibitedExamples: ["Account selling", "Pirated keys", "NFT pump schemes as unregulated investments on chat", "Crypto wallet seed sales"],
  specialConditions: "ROVEXO Checkout is for marketplace goods — not an exchange.",
  buyerRisks: "Burned gift cards, banned accounts, malware-laced files.",
  sellerResponsibilities: "Only sell rights you own. No cracked keys.",
  moderationRules: "Blocks for Steam account, Netflix account, license key dumps.",
  aiDetection: "Keywords for accounts, OTP, seed phrase, cracked, OEM key lists.",
  commonMistakes: "Selling Netflix accounts; grey-market keys; seed phrases.",
  products: [
    product({ id: "software", name: "Software", classification: "restricted", why: "Licensing determines legality.", rule: "Physical retail copies Restricted/Allowed; pirated copies Prohibited." }),
    product({ id: "activation-keys", name: "Activation Keys", classification: "prohibited", why: "Grey-market and stolen keys are fraud vectors.", rule: "Prohibited for bulk/grey keys. Retail sealed box products follow Software rules." }),
    product({ id: "streaming-accounts", name: "Streaming Accounts", classification: "prohibited", why: "Account trading violates provider terms and enables fraud.", rule: "Prohibited." }),
    product({ id: "game-accounts", name: "Game Accounts", classification: "prohibited", why: "Account selling is Prohibited.", rule: "Prohibited." }),
    product({ id: "gift-cards", name: "Gift Cards", classification: "restricted", why: "High fraud category.", rule: "Restricted with proof; stolen/resold scam cards Prohibited." }),
    product({ id: "digital-codes", name: "Digital Codes", classification: "prohibited", why: "Standalone code dumping is high fraud.", rule: "Prohibited unless part of sealed retail product rules." }),
    product({ id: "subscriptions", name: "Subscriptions", classification: "prohibited", why: "Selling access credentials is Prohibited.", rule: "Prohibited." }),
    product({ id: "nfts", name: "NFTs", classification: "prohibited", why: "ROVEXO is not an NFT marketplace.", rule: "Prohibited as listed digital assets for sale on ROVEXO." }),
    product({ id: "crypto-assets", name: "Crypto Assets", classification: "prohibited", why: "ROVEXO is not a crypto exchange.", rule: "Prohibited. No wallets, seeds, or token sales.", faq: [{ question: "Can I sell crypto on ROVEXO?", answer: "No. Crypto assets are Prohibited." }] }),
  ],
  faqs: [
    { question: "Can I sell a game account?", answer: "No." },
    { question: "Can I sell gift cards?", answer: "Only under Restricted rules with legitimacy proof; scam cards Prohibited." },
  ],
  relatedPolicies: RELATED,
};

export const ADULT_CATEGORY: ProductCategoryManual = {
  id: "adult",
  title: "Adult products and sexual content",
  overview: "Some adult toys may be Restricted. Pornographic media, escort services, and sexual services are Prohibited.",
  marketplaceRule: "No escorts, no explicit pornographic media listings, no sexual services. Adult toys may be Restricted with discreet shipping expectations.",
  ukLegal: "Obscene publications and prostitution offences may apply to Prohibited categories.",
  allowedExamples: [],
  restrictedExamples: ["Sealed adult toys sold discreetly as products"],
  prohibitedExamples: ["Escort services", "Pornographic media", "Sexual services", "Explicit sexual content listings"],
  specialConditions: "If Restricted adult products are allowed after review, photos must remain non-explicit and non-pornographic.",
  buyerRisks: "Scams related to services; inappropriate content exposure.",
  sellerResponsibilities: "Never offer services. Keep any Allowed/Restricted product imagery non-explicit.",
  moderationRules: "Automatic blocks for escort and porn keywords; image NSFW scoring.",
  aiDetection: "Keyword and image NSFW classifiers; service-offer language detection.",
  commonMistakes: "Escort ads in descriptions; explicit photo sets; “massage” service covers.",
  products: [
    product({ id: "adult-products", name: "Adult Products", classification: "restricted", why: "Physical adult toys may be sold discreetly in some cases.", rule: "Restricted. Sealed products; non-explicit photos. Services Prohibited." }),
    product({ id: "explicit-material", name: "Explicit Material", classification: "prohibited", why: "Explicit pornographic material is Prohibited on ROVEXO.", rule: "Prohibited." }),
    product({ id: "pornographic-material", name: "Pornographic Material", classification: "prohibited", why: "Pornographic media listings are Prohibited.", rule: "Prohibited." }),
    product({ id: "sexual-services", name: "Sexual Services", classification: "prohibited", why: "Services are not marketplace goods and are Prohibited.", rule: "Prohibited." }),
    product({ id: "escort-services", name: "Escort Services", classification: "prohibited", why: "Escort and related services are Prohibited.", rule: "Prohibited." }),
    product({ id: "adult-toys", name: "Adult Toys", classification: "restricted", why: "Physical products only, under Restricted review.", rule: "Restricted with discreet non-explicit presentation." }),
  ],
  faqs: [
    { question: "Can I offer escort services?", answer: "No. Prohibited." },
    { question: "Can I sell adult toys?", answer: "Possibly under Restricted rules with non-explicit photos; services remain Prohibited." },
  ],
  relatedPolicies: RELATED,
};

export const ILLEGAL_CATEGORY: ProductCategoryManual = {
  id: "illegal-fraud",
  title: "Illegal content, fraud, and cybercrime tools",
  overview: "Anything that facilitates crime is Prohibited. This includes counterfeits, fake IDs, malware, and scam services.",
  marketplaceRule: "Zero tolerance. Listings and chat that facilitate crime are removed and may be reported.",
  ukLegal: "Fraud Act, identity document offences, computer misuse, and IP crime apply.",
  allowedExamples: [],
  restrictedExamples: [],
  prohibitedExamples: ["Counterfeits", "Fake IDs", "Malware", "Hacking tools", "Pirated software", "Money mule offers"],
  specialConditions: "Appeals will not succeed for clear criminal facilitation.",
  buyerRisks: "Criminal liability and financial loss.",
  sellerResponsibilities: "Do not list. Report suspicious buyer requests via Reports.",
  moderationRules: "Immediate removal; account suspension; possible authority referral.",
  aiDetection: "Counterfeit brand detection; ID document cues; malware keywords; scam pattern chat signals.",
  commonMistakes: "Using replica as code for counterfeit; friends-and-family payment requests; fake certificates.",
  products: [
    product({ id: "counterfeit-products", name: "Counterfeit Products", classification: "prohibited", why: "Fake branded goods are illegal and unsafe.", rule: "Prohibited." }),
    product({ id: "pirated-software", name: "Pirated Software", classification: "prohibited", why: "Copyright infringement.", rule: "Prohibited." }),
    product({ id: "fake-documents", name: "Fake Documents", classification: "prohibited", why: "Forgery.", rule: "Prohibited." }),
    product({ id: "forged-certificates", name: "Forged Certificates", classification: "prohibited", why: "Forgery and fraud.", rule: "Prohibited." }),
    product({ id: "fake-ids", name: "Fake IDs", classification: "prohibited", why: "Identity document offences.", rule: "Prohibited." }),
    product({ id: "money-laundering", name: "Money Laundering", classification: "prohibited", why: "Financial crime facilitation.", rule: "Prohibited. No mule or layering offers." }),
    product({ id: "scams", name: "Scams", classification: "prohibited", why: "Fraudulent schemes.", rule: "Prohibited." }),
    product({ id: "fraud", name: "Fraud", classification: "prohibited", why: "Fraudulent listings and payments.", rule: "Prohibited." }),
    product({ id: "identity-theft", name: "Identity Theft", classification: "prohibited", why: "Identity crime tools/data.", rule: "Prohibited." }),
    product({ id: "hacking-tools", name: "Hacking Tools", classification: "prohibited", why: "Computer misuse.", rule: "Prohibited." }),
    product({ id: "malware", name: "Malware", classification: "prohibited", why: "Malicious software.", rule: "Prohibited." }),
  ],
  faqs: [
    { question: "Can I sell replicas?", answer: "If “replica” means counterfeit branded goods — No, Prohibited." },
    { question: "Can I sell fake IDs as novelty?", answer: "No. Prohibited." },
  ],
  relatedPolicies: RELATED,
};

export const SAFETY_CATEGORY: ProductCategoryManual = {
  id: "safety-risks",
  title: "Product safety, recalls, and high-risk goods",
  overview: "Safety is mandatory. Recalled products and goods with clear fire, chemical, or child safety failures are Prohibited. Helmets and toys must meet expected safety honesty.",
  marketplaceRule: "Do not sell recalled goods. Disclose damage. Child products must not be dangerous.",
  ukLegal: "UK product safety frameworks and recall obligations apply.",
  allowedExamples: ["Safe toys with honest age guidance", "Undamaged helmets meeting stated standards when accurately described"],
  restrictedExamples: ["Used child equipment requiring careful inspection", "Chemicals in sealed retail consumer packs"],
  prohibitedExamples: ["Recalled products", "Fireworks", "Known fire-risk damaged batteries", "Counterfeit safety equipment"],
  specialConditions: "When a recall is announced, remove matching listings immediately.",
  buyerRisks: "Injury, fire, poisoning, child harm.",
  sellerResponsibilities: "Check recalls before listing. Package chemicals lawfully.",
  moderationRules: "Recall keyword matching; battery swelling image cues; firework blocks.",
  aiDetection: "Recall lists, fire-risk language, chemical names, child product damage cues.",
  commonMistakes: "Selling recalled chargers; cracked helmets; fireworks.",
  products: [
    product({ id: "recalled-products", name: "Recalled Products", classification: "prohibited", why: "Recalls exist because products are unsafe.", rule: "Prohibited." }),
    product({ id: "fire-risk", name: "Fire Risk", classification: "prohibited", why: "Items with known uncontrolled fire risk.", rule: "Prohibited when the listing is for a known fire-risk product (e.g. recalled heater, damaged lithium)." }),
    product({ id: "electrical-risk", name: "Electrical Risk", classification: "restricted", why: "Faulty electrics injure.", rule: "Restricted. Unsafe exposed electrics sold as working are Prohibited." }),
    product({ id: "chemical-risk", name: "Chemical Risk", classification: "restricted", why: "Hazardous chemicals need lawful retail packaging.", rule: "Restricted for sealed consumer chemicals; industrial/unknown chemicals Prohibited." }),
    product({ id: "child-safety", name: "Child Safety", classification: "restricted", why: "Children’s products need honesty about standards and condition.", rule: "Restricted. Dangerous damaged child products Prohibited." }),
    product({ id: "battery-safety", name: "Battery Safety", classification: "restricted", why: "See Electronics lithium rules.", rule: "Damaged/loose lithium Prohibited; installed cells Restricted by shipping rules." }),
    product({ id: "toy-safety", name: "Toy Safety", classification: "restricted", why: "Toys must be suitable and honestly described.", rule: "Restricted. Counterfeit or recalled toys Prohibited." }),
    product({ id: "helmet-safety", name: "Helmet Safety", classification: "restricted", why: "Crashed helmets can fail.", rule: "Restricted. Disclose impacts; unsafe cracked helmets Prohibited for use claims." }),
    product({ id: "vehicle-safety", name: "Vehicle Safety", classification: "restricted", why: "See Vehicle parts safety-critical rules.", rule: "Airbags/seatbelts Restricted with provenance; fakes Prohibited." }),
    product({ id: "fireworks", name: "Fireworks", classification: "prohibited", why: "Explosives / fireworks are Prohibited.", rule: "Prohibited.", faq: [{ question: "Can I sell fireworks?", answer: "No. Prohibited." }] }),
  ],
  faqs: [
    { question: "Can I sell fireworks?", answer: "No." },
    { question: "Can I sell a recalled product?", answer: "No." },
    { question: "Can I sell a cracked helmet?", answer: "Not as safe protective equipment — Prohibited for use claims." },
  ],
  relatedPolicies: RELATED,
};
