import type { ProductCategoryManual } from "@/lib/documentation/documentation-engine-v1";
import { product } from "@/lib/documentation/product-seed-v1";

const RELATED = [
  { title: "Acceptable Use Policy", href: "/legal/acceptable-use-policy" },
  { title: "Seller Terms", href: "/legal/seller-terms" },
  { title: "Community Guidelines", href: "/legal/community-guidelines" },
  { title: "Account Suspension Policy", href: "/legal/account-suspension-policy" },
  { title: "Help — Safety", href: "/help/category/safety" },
];

export const WEAPONS_CATEGORY: ProductCategoryManual = {
  id: "weapons-blades-defence",
  title: "Weapons, blades, archery, air weapons, and defence sprays",
  overview:
    "ROVEXO is a consumer marketplace for everyday goods. Items designed to kill, injure, or function as offensive weapons are tightly controlled. Many are Prohibited. Some kitchen and outdoor tools are Allowed only when sold as tools with honest descriptions. There is no fourth state: every item is Allowed, Restricted, or Prohibited.",
  marketplaceRule:
    "If an item is primarily a weapon, replica firearm that could cause alarm, illegal blade, or prohibited defence spray — do not list it. Tool knives and archery sports equipment may be Allowed or Restricted only where UK law and this policy expressly allow them.",
  ukLegal:
    "UK law restricts firearms, offensive weapons, certain knives (including zombie knives and flick knives), pepper spray/CS spray for public sale, and many imitation firearms. Possession and sale rules differ by item. ROVEXO applies the stricter marketplace rule: if UK law forbids general public sale, the item is Prohibited on ROVEXO.",
  allowedExamples: [
    "Standard kitchen chef knives sold as cooking tools with clear photos of the kitchen context",
    "Sealed utility knives / box cutters sold as tools",
    "Recurve or compound bows sold as sports equipment without illegal modifications (Restricted review may still apply)",
  ],
  restrictedExamples: [
    "Hunting knives and survival knives marketed as outdoor tools (manual review; age and shipping limits may apply)",
    "Airsoft and paintball markers that comply with UK markings and are not realistic prohibited imitations (manual review)",
    "Decorative ceremonial blades that are blunt / wall display only (must be clearly non-functional; may still be removed if alarm risk is high)",
  ],
  prohibitedExamples: [
    "Firearms, ammunition, magazines, suppressors, and most firearm parts",
    "Zombie knives, switchblades, butterfly knives, throwing knives marketed as weapons",
    "Pepper spray, CS spray, tasers, stun guns, brass knuckles, batons designed as weapons",
    "3D-printed weapon files or physical 3D-printed weapons",
  ],
  specialConditions:
    "Sellers must never use code words, emoji, or partial photos to hide weapons. Buyers must not request weapons in chat. Shipping carriers may refuse weapons and blades — Restricted Allowed tools still need compliant packaging and carrier rules.",
  buyerRisks:
    "Illegal weapons purchases can lead to criminal investigation. Paying outside ROVEXO removes Buyer Protection.",
  sellerResponsibilities:
    "Classify honestly. If the primary purpose is a weapon, do not list. Keep kitchen knives in kitchen context. Never ship Prohibited items.",
  moderationRules:
    "Automatic block for high-risk weapon keywords and images. Manual review for borderline blades and sports air weapons. Appeals via Contact Support with evidence the item is a lawful tool.",
  aiDetection:
    "Title/description keyword detection (gun, ammo, taser, zombie knife, flick knife, etc.), image analysis for firearms and blades, brand/model detection, risk scoring, duplicate listing detection, automatic blocking for Prohibited classes, and manual review queues for Restricted classes.",
  commonMistakes:
    "Listing a kitchen knife with weapon marketing language; selling airsoft as a real firearm replica without UK compliance; claiming pepper spray is for “self defence keyring” to bypass rules.",
  products: [
    product({
      id: "firearms",
      name: "Firearms",
      classification: "prohibited",
      why: "Live firearms of any calibre are not permitted on ROVEXO.",
      rule: "Prohibited. Do not list, photograph, or negotiate firearm sales.",
      aliases: ["guns", "rifle firearm", "shotgun firearm"],
      faq: [{ question: "Can I sell a deactivated firearm?", answer: "No. Firearms and deactivated firearms are Prohibited on ROVEXO regardless of certificate claims in listing text." }],
    }),
    product({
      id: "handguns",
      name: "Handguns",
      classification: "prohibited",
      why: "Handguns are firearms and are not sold on ROVEXO.",
      rule: "Prohibited in all forms, including frames and major components offered as handgun parts.",
    }),
    product({
      id: "shotguns",
      name: "Shotguns",
      classification: "prohibited",
      why: "Shotguns are firearms and are Prohibited.",
      rule: "Prohibited, including sawn-off or antique marketing language used to sell a real shotgun.",
    }),
    product({
      id: "rifles",
      name: "Rifles",
      classification: "prohibited",
      why: "Rifles are firearms and are Prohibited.",
      rule: "Prohibited. Do not list hunting rifles or “farm rifle” offers.",
    }),
    product({
      id: "air-rifles",
      name: "Air Rifles",
      classification: "prohibited",
      why: "Air rifles present serious safety and legal control issues for a general marketplace.",
      rule: "Prohibited on ROVEXO. Do not list air rifles, even if described as low power.",
      aliases: ["airgun rifle", "pellet rifle"],
      faq: [{ question: "Can I sell a low-power air rifle?", answer: "No. Air rifles are Prohibited on ROVEXO." }],
    }),
    product({
      id: "air-pistols",
      name: "Air Pistols",
      classification: "prohibited",
      why: "Air pistols are treated as Prohibited weapons on ROVEXO.",
      rule: "Prohibited.",
    }),
    product({
      id: "airsoft",
      name: "Airsoft",
      classification: "restricted",
      why: "Airsoft markers can look like real firearms and may be restricted under UK imitation firearm rules.",
      rule: "Restricted. Only clearly marked UK-compliant sports airsoft equipment may be considered after manual review. Realistic prohibited imitations are Prohibited.",
      special: "Must state UK status, markings, and that it is a sports airsoft item. Photos must show markings. High-risk realistic replicas may still be removed.",
      faq: [{ question: "Can I sell an airsoft gun?", answer: "Only if it is clearly a UK-compliant sports airsoft marker and passes Restricted review. Realistic prohibited imitations are not Allowed." }],
    }),
    product({
      id: "paintball",
      name: "Paintball",
      classification: "restricted",
      why: "Paintball markers are sports equipment but can be misused or misdescribed.",
      rule: "Restricted. Sell as paintball sports equipment with clear photos. Do not market as a firearm.",
    }),
    product({
      id: "crossbows",
      name: "Crossbows",
      classification: "prohibited",
      why: "Crossbows are high-risk weapons unsuitable for open marketplace sale on ROVEXO.",
      rule: "Prohibited.",
    }),
    product({
      id: "compound-bows",
      name: "Compound Bows",
      classification: "restricted",
      why: "Compound bows are sports/archery equipment when sold honestly.",
      rule: "Restricted. Must be sold as archery sports equipment. Hunting marketing that implies unlawful use may lead to removal.",
    }),
    product({
      id: "arrows",
      name: "Arrows",
      classification: "restricted",
      why: "Arrows are archery consumables but can be dangerous.",
      rule: "Restricted. Sell as archery sports accessories. Broadhead hunting points marketed as weapons may be removed.",
    }),
    product({
      id: "ammunition",
      name: "Ammunition",
      classification: "prohibited",
      why: "Live ammunition and cartridges are Prohibited.",
      rule: "Prohibited, including blanks marketed for real firearms.",
      aliases: ["ammo", "cartridges", "bullets"],
    }),
    product({
      id: "magazines",
      name: "Magazines",
      classification: "prohibited",
      why: "Firearm magazines are weapon components.",
      rule: "Prohibited for firearms. Airsoft magazines only under Restricted airsoft rules when clearly sports-only.",
    }),
    product({
      id: "suppressors",
      name: "Suppressors",
      classification: "prohibited",
      why: "Firearm suppressors / silencers are Prohibited.",
      rule: "Prohibited.",
      aliases: ["silencer", "sound moderator firearm"],
    }),
    product({
      id: "scopes",
      name: "Scopes",
      classification: "restricted",
      why: "Optical scopes can be used for sports optics or firearms.",
      rule: "Restricted. Optical scopes sold as camera/spotting/airsoft optics may be Allowed after review. Listings clearly for firearm zeroing with prohibited context may be removed.",
    }),
    product({
      id: "firearm-parts",
      name: "Firearm Parts",
      classification: "prohibited",
      why: "Parts that complete or repair firearms are Prohibited.",
      rule: "Prohibited. Do not list barrels, receivers, triggers, or conversion kits for firearms.",
    }),
    product({
      id: "3d-printed-weapons",
      name: "3D Printed Weapons",
      classification: "prohibited",
      why: "3D-printed weapons and weapon print files enable illegal manufacture.",
      rule: "Prohibited, including STL/file sales for weapons.",
    }),
    product({
      id: "replica-weapons",
      name: "Replica Weapons",
      classification: "prohibited",
      why: "Realistic replica firearms and weapon replicas that could cause public alarm are Prohibited.",
      rule: "Prohibited when realistic. Clearly toy-like non-realistic props may be Restricted only if they cannot be mistaken for a real weapon.",
    }),
    product({
      id: "decorative-weapons",
      name: "Decorative Weapons",
      classification: "restricted",
      why: "Wall display swords and ceremonial pieces may be decorative, but many are still high risk.",
      rule: "Restricted. Must be blunt/display-only and honestly described. Sharp “decorative” weapons may be treated as Prohibited.",
    }),
    product({
      id: "kitchen-knives",
      name: "Kitchen Knives",
      classification: "allowed",
      why: "Ordinary kitchen knives are tools for food preparation.",
      rule: "Allowed when sold as kitchen tools with accurate photos and no weapon marketing.",
      faq: [{ question: "Can I sell a kitchen knife?", answer: "Yes, as a cooking tool with clear kitchen-context photos and honest condition. Do not market it as a weapon." }],
    }),
    product({
      id: "chef-knives",
      name: "Chef Knives",
      classification: "allowed",
      why: "Chef knives are standard cookware tools.",
      rule: "Allowed as kitchen tools. State brand, length, and condition.",
    }),
    product({
      id: "pocket-knives",
      name: "Pocket Knives",
      classification: "restricted",
      why: "UK knife carriage and lock-knife rules make many pocket knives sensitive.",
      rule: "Restricted. Non-locking small tools may pass review; lock knives and combat marketing are commonly removed or Prohibited.",
    }),
    product({
      id: "utility-knives",
      name: "Utility Knives",
      classification: "allowed",
      why: "Box cutters and utility knives are workplace tools.",
      rule: "Allowed as tools. Do not market for self-defence.",
    }),
    product({
      id: "survival-knives",
      name: "Survival Knives",
      classification: "restricted",
      why: "Survival knives sit between tools and weapons depending on design and marketing.",
      rule: "Restricted. Outdoor tool context required. Tactical/combat marketing may lead to Prohibited treatment.",
    }),
    product({
      id: "hunting-knives",
      name: "Hunting Knives",
      classification: "restricted",
      why: "Hunting knives are specialised blades with elevated risk.",
      rule: "Restricted. Clear outdoor/processing tool context required. May be refused by carriers.",
    }),
    product({
      id: "zombie-knives",
      name: "Zombie Knives",
      classification: "prohibited",
      why: "Zombie knives are prohibited offensive weapons under UK controls.",
      rule: "Prohibited.",
      faq: [{ question: "Can I sell a zombie knife as a collector item?", answer: "No. Zombie knives are Prohibited on ROVEXO." }],
    }),
    product({
      id: "switchblades",
      name: "Switchblades",
      classification: "prohibited",
      why: "Automatic opening knives (flick knives / switchblades) are prohibited weapons.",
      rule: "Prohibited.",
      aliases: ["flick knife", "automatic knife"],
    }),
    product({
      id: "butterfly-knives",
      name: "Butterfly Knives",
      classification: "prohibited",
      why: "Butterfly / balisong knives are prohibited offensive weapons.",
      rule: "Prohibited.",
      aliases: ["balisong"],
    }),
    product({
      id: "throwing-knives",
      name: "Throwing Knives",
      classification: "prohibited",
      why: "Throwing knives are designed as weapons.",
      rule: "Prohibited.",
    }),
    product({
      id: "axes",
      name: "Axes",
      classification: "restricted",
      why: "Axes can be tools or weapons depending on type and marketing.",
      rule: "Restricted. Wood-splitting and camping axes as tools may pass review. Tactical/throwing axes marketed as weapons are Prohibited.",
    }),
    product({
      id: "machetes",
      name: "Machetes",
      classification: "restricted",
      why: "Machetes are agricultural tools but frequently misused.",
      rule: "Restricted. Clear gardening/agricultural tool context required. Combat marketing is Prohibited.",
    }),
    product({
      id: "batons",
      name: "Batons",
      classification: "prohibited",
      why: "Expandable and police-style batons are offensive weapons for marketplace purposes.",
      rule: "Prohibited.",
    }),
    product({
      id: "brass-knuckles",
      name: "Brass Knuckles",
      classification: "prohibited",
      why: "Knuckle-dusters are offensive weapons.",
      rule: "Prohibited, including “paperweight” or novelty claims.",
      aliases: ["knuckle duster"],
    }),
    product({
      id: "pepper-spray",
      name: "Pepper Spray",
      classification: "prohibited",
      why: "Pepper spray is not for general public sale on ROVEXO.",
      rule: "Prohibited.",
      faq: [{ question: "Can I sell pepper spray for self-defence?", answer: "No. Pepper spray is Prohibited on ROVEXO." }],
    }),
    product({
      id: "cs-spray",
      name: "CS Spray",
      classification: "prohibited",
      why: "CS spray is a prohibited defence irritant for marketplace sale.",
      rule: "Prohibited.",
    }),
    product({
      id: "tasers",
      name: "Tasers",
      classification: "prohibited",
      why: "Conducted energy devices are Prohibited.",
      rule: "Prohibited.",
    }),
    product({
      id: "stun-guns",
      name: "Stun Guns",
      classification: "prohibited",
      why: "Stun guns are Prohibited weapons on ROVEXO.",
      rule: "Prohibited, including disguised stun devices.",
    }),
  ],
  faqs: [
    { question: "Can I sell a kitchen knife?", answer: "Yes — as a cooking tool with honest photos and description. Weapon-style marketing is not Allowed." },
    { question: "Can I sell an airsoft gun?", answer: "Only UK-compliant sports airsoft under Restricted review. Realistic prohibited imitations are Prohibited." },
    { question: "Can I sell fireworks?", answer: "No. Consumer fireworks and explosives are Prohibited on ROVEXO (see Safety / Illegal content rules)." },
    { question: "Can I sell a decorative sword?", answer: "Only if clearly display-only and it passes Restricted review. Sharp combat swords are commonly Prohibited." },
    { question: "What happens if I list a prohibited weapon?", answer: "The listing is removed or blocked, your account may be suspended, and serious cases may be reported." },
  ],
  relatedPolicies: RELATED,
};
